#ifndef CODE_H
#define CODE_H
#include <stdint.h>
#include <stdio.h>
#include "JIT.h"
#include "RECIPE.h"

enum
{
	MODE_INFER = 0,
	MODE_TRAIN = 1,
	MODE_UPDATE = 2,
	MODE_EVALUATE = 3
};

enum
{
	KIND_ENTRY = 1,
	KIND_EXIT,
	KIND_UPDATE_START,
	KIND_INFERENCE_GATE,
	KIND_LOSS,
	KIND_EMBEDDING,
	KIND_NORMALIZATION,
	KIND_FEED_FORWARD,
	KIND_ATTENTION_HEAD,
	KIND_WORD,
	KIND_GROW,
	KIND_EVALUATION_GATE,
	KIND_COPY,
	KIND_ORGAN,
	KIND_ADAM,
	KIND_RECIPE,
	KIND_TREE
};

#define ORGAN_RECIPE_BASE 1000
#define ORGAN_ROTARY_HEAD 900
#define ORGAN_TREE_BASE 800
#define TREE_LEAK_SLOPE (float)0.1

enum
{
	ROLE_FORWARD = 0,
	ROLE_BACKWARD = 1,
	ROLE_UPDATE = 2
};

enum
{
	WHY_SEED = 0,
	WHY_GROWTH = 1,
	WHY_NEW_WORD = 2,
	WHY_CONTROL = 3,
	WHY_PERSONAL = 4
};

enum
{
	SERVICE_READ = 0,
	SERVICE_WRITE,
	SERVICE_CREATE,
	SERVICE_CONNECT,
	SERVICE_TRACE,
	SERVICE_COUNT
};

enum
{
	CONSTANT_CLAMP_LOW,
	CONSTANT_CLAMP_HIGH,
	CONSTANT_LOG2_OF_E,
	CONSTANT_POLYNOMIAL_1,
	CONSTANT_POLYNOMIAL_2,
	CONSTANT_POLYNOMIAL_3,
	CONSTANT_POLYNOMIAL_4,
	CONSTANT_POLYNOMIAL_5,
	CONSTANT_POLYNOMIAL_6,
	CONSTANT_ONE,
	CONSTANT_NEGATIVE_INFINITY,
	CONSTANT_ZERO,
	CONSTANT_GELU_CUBIC,
	CONSTANT_GELU_SCALE,
	CONSTANT_COUNT
};

#define PARAMETER_PLANE ((int64_t)1 << 28)
#define WORD_PLANE_OFFSET (PARAMETER_PLANE / 2)
#define ACTIVATION_PLANE ((int64_t)1 << 30)
#define TRAINING_REGION_OFFSET (ACTIVATION_PLANE / 4)
#define ACTIVATION_PLANE_VERSION2 ((int64_t)1 << 28)
#define TRAINING_REGION_VERSION2 (ACTIVATION_PLANE_VERSION2 / 4)
#define ACTIVATION_PLANE_VERSION4 ((int64_t)1 << 29)
#define TRAINING_REGION_VERSION4 (ACTIVATION_PLANE_VERSION4 / 4)
#define LOGITS_OFFSET (ACTIVATION_PLANE / 2)
#define LAST_LOGITS_OFFSET (ACTIVATION_PLANE / 2 + ACTIVATION_PLANE / 4)
#define CODE_RESERVE_BYTES ((int64_t)1 << 28)
#define CODE_SEGMENT_BYTES 65536
#define KERNEL_VERSION 5

typedef struct
{
	float	CONSTANTS[CONSTANT_COUNT][8];
	int64_t	SEQUENCE_LENGTH;
	int64_t	START_POSITION;
	int64_t	MODE;
	int64_t	WORD_COUNT;
	int64_t	MAXIMUM_LENGTH;
	int64_t	DIMENSION;
	int64_t	STEP;
	int64_t	FIRE_COUNT;
	float	LEARNING_RATE;
	float	FIRST_MOMENT_DECAY;
	float	SECOND_MOMENT_DECAY;
	float	EPSILON;
	float	WEIGHT_DECAY;
	float	FIRST_BIAS_CORRECTION;
	float	SECOND_BIAS_CORRECTION;
	float	GRADIENT_SCALE;
	float	FIRST_MOMENT_RATE;
	float	SECOND_MOMENT_RATE;
	float	NORM_EPSILON;
	float	ATTENTION_SCALE;
	float	INVERSE_DIMENSION;
	float	ZERO;
	float	ONE;
	float	PADDING;
	float	SCRATCH[16];
	uint8_t	*ACTIVATIONS;
	float	*PARAMETERS;
	void	**SERVICE_TABLE;
	void	*OWNER;
	int64_t	REQUEST_AREA;
	int64_t	REQUEST_KIND;
	int64_t	REQUEST_ARGUMENT;
	int64_t	REQUEST_RESULT;
	int64_t	NEURON_ACTIVATION_OFFSET;
	int64_t	INFERENCE_LOGIT_OFFSET;
	int64_t	PARAMETER_BYTES_USED;
	int64_t	WORD_BYTES_USED;
	float	GRADIENT_SKIP_THRESHOLD;
	float	SECOND_PADDING;
	float	*ROTARY_TABLE;
	float	LEAK_SLOPE[8];
} KERNEL_CONTEXT;

typedef struct
{
	int32_t	ID;
	int32_t	KIND;
	int32_t	AREA_INDEX;
	int32_t	BIRTH_REASON;
	int32_t	BIRTH_STEP;
	int32_t	KIND_DETAIL;
	float	BIRTH_ERROR;
	int64_t	PARAMETER_OFFSET;
	int64_t	PARAMETER_COUNT;
	int64_t	ACTIVATION_OFFSET;
	int64_t	ACTIVATION_BYTES;
	int32_t	PIECE_IDS[3];
	int32_t	ALIVE;
} NEURON;

typedef struct
{
	int32_t	ID;
	int32_t	OFFSET;
	int32_t	LENGTH;
	int32_t	TAIL_POSITION;
	int32_t	NEXT_ID;
	int32_t	RELOCATION_COUNT;
	int32_t	SEGMENT_INDEX;
	int32_t	*RELOCATION_POSITIONS;
	int32_t	*RELOCATION_TARGETS;
	int32_t	INLINE_POSITIONS[2];
	int32_t	INLINE_TARGETS[2];
} CODE_PIECE;

typedef struct
{
	int32_t	GROUP;
	int32_t	OFFSET;
	int32_t	BYTE_SIZE;
	int32_t	BYTES_USED;
} SEGMENT;

typedef struct
{
	int32_t	SEGMENT_INDEX;
	int32_t	OFFSET;
	int32_t	LENGTH;
} HOLE;

typedef struct
{
	int32_t	KIND;
	int32_t	INDEX;
	int32_t	MEMBER_COUNT;
	int32_t	MEMBER_CAPACITY;
	int32_t	NORM_NEURON;
	int32_t	*MEMBERS;
	float	ERROR_LEVEL;
	float	ERROR_SLOW;
	float	ERROR_BEST;
	int32_t	LAST_GROWTH;
	int32_t	GROWN_COUNT;
} AREA;

typedef struct
{
	int	DIMENSION;
	int	LAYER_COUNT;
	int	HEAD_DIMENSION;
	int	MAXIMUM_LENGTH;
	int	MAXIMUM_WORDS;
	int	INITIAL_HEADS;
	int	INITIAL_FEED_FORWARD;
} CONFIG;

typedef struct
{
	float	LOSS_MOVING_AVERAGE;
	float	LOSS_AT_CHECK;
	float	PLATEAU;
	int32_t	ENABLED;
	int32_t	CHECK_INTERVAL;
	int32_t	COOLDOWN;
	int32_t	GROW_FEED_FORWARD;
	int32_t	MAXIMUM_HEADS;
	int32_t	STATISTICS_INTERVAL;
	int32_t	GROWTH_COUNT;
	int64_t	LAST_CHECK;
	int64_t	LAST_GROWTH;
	int64_t	MAXIMUM_PARAMETERS;
} GROWTH;

typedef struct
{
	uint8_t	*BASE;
	int64_t	RESERVED_BYTES;
	int64_t	COMMITTED_BYTES[16];
} SPACE;

typedef struct WEB
{
	CONFIG			CONFIGURATION;
	KERNEL_CONTEXT	*KERNEL_STATE;
	void			*KERNEL_STATE_MEMORY;
	uint8_t			*EXECUTABLE;
	int64_t			EXECUTABLE_USED;
	SEGMENT			*SEGMENTS;
	int32_t			SEGMENT_COUNT;
	int32_t			SEGMENT_CAPACITY;
	HOLE			*HOLES;
	int32_t			HOLE_COUNT;
	int32_t			HOLE_CAPACITY;
	int				CODE_WRITABLE;
	CODE_PIECE		*PIECES;
	int32_t			PIECE_COUNT;
	int32_t			PIECE_CAPACITY;
	int32_t			*PIECE_MAP;
	int32_t			PIECE_MAP_CAPACITY;
	NEURON			*NEURONS;
	int32_t			NEURON_COUNT;
	int32_t			NEURON_CAPACITY;
	AREA			*AREAS;
	int32_t			AREA_COUNT;
	SPACE			PARAMETER_SPACE;
	SPACE			ACTIVATION_SPACE;
	float			*PARAMETERS;
	int64_t			PARAMETER_BYTES_USED;
	uint8_t			*ACTIVATIONS;
	int64_t			ACTIVATION_BYTES_USED;
	int64_t			TRAINING_BYTES_USED;
	int				TRAINING_ENABLED;
	int				OPTIMIZER_ENABLED;
	int64_t			OPTIMIZER_START_STEP;
	int64_t			TOKENS_OFFSET;
	int64_t			TARGETS_OFFSET;
	int64_t			LOSS_WEIGHTS_OFFSET;
	int64_t			RESIDUAL_OFFSET;
	int64_t			RESIDUAL_GRADIENT_OFFSET;
	int64_t			NORMALIZED_OFFSET;
	int64_t			NORMALIZED_GRADIENT_OFFSET;
	int64_t			INVERSE_NORM_OFFSET;
	int64_t			SOFTMAX_STATISTICS_OFFSET;
	int64_t			TARGET_LOGIT_OFFSET;
	int64_t			WORD_STRIDE;
	int32_t			WORD_COUNT;
	int32_t			ENTRY_ID;
	int32_t			EXIT_ID;
	int32_t			UPDATE_START_ID;
	int32_t			INFERENCE_GATE_ID;
	int32_t			LOSS_ID;
	int32_t			EMBEDDING_ID;
	int32_t			GROW_ID;
	int32_t			EVALUATION_GATE_ID;
	int32_t			COPY_ID;
	int32_t			ADAM_ID;
	int32_t			*NORM_IDS;
	int32_t			*WORD_NEURONS;
	uint64_t		RANDOM_STATE;
	int64_t			STEP;
	void			*SERVICE_TABLE[SERVICE_COUNT];
	GROWTH			GROWTH_STATE;
	float			GRADIENT_MULTIPLIER;
	float			GRADIENT_NORM;
	int				OPTIMIZER_LOADED;
	int32_t			WORD_LIMIT;
	int				HALF_PRECISION;
	RECIPE			*RECIPES;
	int				RECIPE_COUNT;
	int				RECIPE_CAPACITY;
	int				GROWTH_RECIPE;
	int				GROWTH_ROTARY;
	int				FROZEN;
	int64_t			FREEZE_STEP;
	int32_t			FREEZE_WORD_COUNT;
	float			*ROTARY_TABLE;
} WEB;

typedef struct
{
	KERNEL_CONTEXT	*KERNEL_STATE;
	void			*KERNEL_STATE_MEMORY;
	SPACE			PARAMETER_SPACE;
	SPACE			ACTIVATION_SPACE;
	uint8_t			*ACTIVATIONS;
	float			*PARAMETERS;
} REPLICA;

REPLICA	*REPLICA_NEW(WEB *NEURAL_WEB);
void	REPLICA_FREE(REPLICA *REPLICA_STATE);
void	REPLICA_SYNCHRONIZE(WEB *NEURAL_WEB, REPLICA *REPLICA_STATE);
void	REPLICA_PREPARE(WEB *NEURAL_WEB, REPLICA *REPLICA_STATE);
void	REPLICA_REDUCE_RANGE(
	WEB *NEURAL_WEB, REPLICA **REPLICAS, int REPLICA_COUNT, int PART_INDEX,
	int PART_COUNT
);
void	REPLICA_SYNCHRONIZE_RANGE(
	WEB *NEURAL_WEB, REPLICA **REPLICAS, int REPLICA_COUNT, int PART_INDEX,
	int PART_COUNT
);

typedef void (*WEB_FUNCTION)(
	KERNEL_CONTEXT *, KERNEL_CONTEXT *, KERNEL_CONTEXT *, KERNEL_CONTEXT *
);

WEB		*WEB_NEW(CONFIG WEB_CONFIG, uint64_t RANDOM_SEED);
WEB		*WEB_NEW_EMPTY(CONFIG WEB_CONFIG, uint64_t RANDOM_SEED);
void	WEB_FREE(WEB *NEURAL_WEB);
int		WEB_RUN(WEB *NEURAL_WEB, int RUN_MODE);
void	WEB_PREPARE(WEB *NEURAL_WEB, int RUN_MODE);
void	WEB_RUN_KERNEL_STATE(WEB *NEURAL_WEB, KERNEL_CONTEXT *KERNEL_STATE);
int32_t	WEB_ADD_NEURON(
	WEB *NEURAL_WEB, int NEURON_KIND, int AREA_INDEX, int GROWTH_REASON,
	int KIND_VARIANT
);
void	WEB_RELINK(WEB *NEURAL_WEB);
int		WEB_SAVE(WEB *NEURAL_WEB, const char *PATH, int WITH_OPTIMIZER);
int		WEB_LOAD_OPTIMIZER(WEB *NEURAL_WEB, const char *PATH);
void	WEB_ROUND_TO_HALF(WEB *NEURAL_WEB);
int32_t	WEB_ORGAN(WEB *NEURAL_WEB, int ORGAN_KIND, int AREA_INDEX);
int		ORGAN_KEY(int NEURON_KIND, int KIND_VARIANT);
WEB		*WEB_LOAD(const char *PATH);
WEB		*WEB_LOAD_PLAY(const char *PATH);
float	WEB_WEIGHT(WEB *NEURAL_WEB, int32_t NEURON_ID, int64_t WEIGHT_INDEX);
float	*WEB_COPY_ATTENTION_ROW(
	WEB *NEURAL_WEB, uint8_t *ACTIVATIONS, int POSITION
);
int32_t	*PIECE_POSITIONS(CODE_PIECE *PIECE_RECORD);
int32_t	*PIECE_TARGETS(CODE_PIECE *PIECE_RECORD);
int		WEB_ADD_WORD(WEB *NEURAL_WEB);
int		WEB_RECIPE_ADD(
	WEB *NEURAL_WEB, const char *RECIPE_SOURCE, char *ERROR_MESSAGE,
	int ERROR_MESSAGE_SIZE
);
int		WEB_RECIPE_FIND(WEB *NEURAL_WEB, const char *RECIPE_NAME);
int32_t	WEB_ADD_COPY(WEB *NEURAL_WEB);
WEB		*WEB_RESHAPE(
	WEB *OLD_WEB, int MAX_POSITIONS, int MAX_WORDS, int ADD_FEED_FORWARD,
	int ADD_HEADS
);

typedef struct
{
	int	MAXIMUM_LENGTH;
	int	MAXIMUM_WORDS;
	int	ADD_FEED_FORWARD;
	int	ADD_HEADS;
	int	ADD_LAYERS;
	int	DIMENSION;
	int	LAYER_FEED_FORWARD;
	int	LAYER_HEADS;
	int	ROTARY;
} SHAPE;

WEB			*WEB_RESHAPE_SHAPE(WEB *OLD_WEB, SHAPE SHAPE_REQUEST);
void		WEB_SET_TRAINING(WEB *NEURAL_WEB, int ENABLE_TRAINING);
void		WEB_SET_OPTIMIZER(WEB *NEURAL_WEB, int ENABLE_OPTIMIZER);
int			WEB_PRUNE_WORDS(
	WEB *NEURAL_WEB, const uint8_t *KEEP_FLAGS, int32_t *NEW_INDEX
);
void		WEB_RECOMPILE(WEB *NEURAL_WEB);
void		COPY_HEAD_OFFSETS(WEB *NEURAL_WEB, int64_t *OFFSETS);
float		WEB_LOSS_AT(WEB *NEURAL_WEB, uint8_t *ACTIVATIONS, int POSITION);
float		*WEB_LAST_LOGITS(WEB *NEURAL_WEB);
float		WEB_RANDOM(WEB *NEURAL_WEB);
uint64_t	RANDOM_NEXT(uint64_t *SEED_STATE);
float		WEB_GAUSSIAN(WEB *NEURAL_WEB);
float		*NEURON_PARAMETERS(WEB *NEURAL_WEB, int32_t NEURON_ID);
float		*NEURON_GRADIENTS(WEB *NEURAL_WEB, int32_t NEURON_ID);
float		*NEURON_MOMENTS(
	WEB *NEURAL_WEB, int32_t NEURON_ID, int MOMENT_INDEX
);
int64_t		LAYER_RESIDUAL(WEB *NEURAL_WEB, int LAYER_INDEX);
int64_t		LAYER_RESIDUAL_GRADIENT(WEB *NEURAL_WEB, int LAYER_INDEX);
int64_t		LAYER_NORMALIZED(WEB *NEURAL_WEB, int LAYER_INDEX);
int64_t		LAYER_NORMALIZED_GRADIENT(WEB *NEURAL_WEB, int LAYER_INDEX);
int64_t		WEB_CODE_BYTES(WEB *NEURAL_WEB);
uint16_t	FLOAT_TO_HALF(float SINGLE_VALUE);
float		HALF_TO_FLOAT(uint16_t HALF_BITS);

double	LEARN_WINDOW(
	WEB *NEURAL_WEB, const int32_t *SEQUENCE, int SEQUENCE_LENGTH,
	const float *TOKEN_WEIGHTS, double *WEIGHT_SUM
);
void	LEARN_UPDATE(WEB *NEURAL_WEB);
void	LEARN_RECORD_LOSS(WEB *NEURAL_WEB, float BATCH_LOSS);
int		LEARN_AVOID_WEIGHTS(
	WEB *NEURAL_WEB, KERNEL_CONTEXT *KERNEL_STATE, uint8_t *ACTIVATIONS,
	int STEP_COUNT
);
void	LEARN_FREEZE(WEB *NEURAL_WEB, int ENABLE);
int		LEARN_PERSONAL(WEB *NEURAL_WEB, int PER_AREA, int RESET_EXISTING);
int64_t	WEB_PARAMETER_COUNT(WEB *NEURAL_WEB);
int		WEB_COUNT_NEURONS(WEB *NEURAL_WEB, int NEURON_KIND, int AREA_INDEX);
int		GENERATE_PIECE(
	WEB *NEURAL_WEB, ASSEMBLER *ASSEMBLY, NEURON *CURRENT_NEURON, int PASS_ROLE
);
void	REFERENCE_FORWARD(WEB *NEURAL_WEB, int IS_TRAINING);
void	REFERENCE_BACKWARD(WEB *NEURAL_WEB);
void	REFERENCE_UPDATE(WEB *NEURAL_WEB);

#endif
