#ifndef DATA_H
#define DATA_H
#include "BRAIN.h"

enum
{
	TOKEN_CLASS_MEMORY = 0,
	TOKEN_CLASS_USER,
	TOKEN_CLASS_CODE,
	TOKEN_CLASS_TEXT,
	TOKEN_CLASS_NONE,
	TOKEN_CLASS_BAD
};

extern const float	TOKEN_CLASS_WEIGHTS[6];

typedef struct
{
	int64_t	START;
	int64_t	FIRST_TURN;
	int32_t	MEMORY_LENGTH;
	int32_t	TURN_COUNT;
	int32_t	IS_PLAIN_TEXT;
	int32_t	LENGTH;
} CONVERSATION;

typedef struct
{
	int32_t	CONVERSATION_INDEX;
	int32_t	START;
	int32_t	END;
} WINDOW;

typedef struct
{
	int32_t			*TOKENS;
	uint8_t			*CLASSES;
	int64_t			TOKEN_COUNT;
	int64_t			TOKEN_CAPACITY;
	CONVERSATION	*CONVERSATIONS;
	int64_t			CONVERSATION_COUNT;
	int64_t			CONVERSATION_CAPACITY;
	int64_t			*TURN_STARTS;
	int64_t			TURN_COUNT;
	int64_t			TURN_CAPACITY;
	int32_t			FIRST_PERSON_TOKENS[8];
	int				FIRST_PERSON_COUNT;
} DATASET;

char	*READ_WHOLE_FILE(const char *PATH, long *FILE_LENGTH);
int		LINE_MARKER_KIND(const char *LINE);
void	COUNT_FILE_WORDS(LANGUAGE *LEXICON, const char *PATH);
void	LOAD_TRAINING_FILE(
	LANGUAGE *LEXICON, DATASET *TRAINING_DATA, const char *PATH,
	int MAX_SEQUENCE_LENGTH
);
WINDOW	*MAKE_WINDOWS(
	DATASET *TRAINING_DATA, int MAX_SEQUENCE_LENGTH, int64_t *OUTPUT_COUNT
);
int		BUILD_SEQUENCE(
	DATASET *TRAINING_DATA, WINDOW *TRAINING_WINDOW, int MAX_SEQUENCE_LENGTH,
	int32_t *SEQUENCE, float *WEIGHTS
);
void	DATASET_FREE(DATASET *TRAINING_DATA);
void	DATASET_SET_FIRST_PERSON(DATASET *TRAINING_DATA, LANGUAGE *LEXICON);
int		LIST_TEXT_FILES(const char *PATH, char **OUTPUT, int OUTPUT_SIZE);

#endif
