#include "DATA.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <dirent.h>
#include <sys/stat.h>
#endif

const float	TOKEN_CLASS_WEIGHTS[6] = {
	(float)0.1, (float)0.5, (float)1.0, (float)1.0, (float)0.0, -(float)1.0
};

void
	DATASET_PUSH_TOKEN(
		DATASET *TRAINING_DATA, int32_t TOKEN, uint8_t TOKEN_CLASS
	)
{
	if (TRAINING_DATA->TOKEN_COUNT >= TRAINING_DATA->TOKEN_CAPACITY)
	{
		if (TRAINING_DATA->TOKEN_CAPACITY)
			TRAINING_DATA->TOKEN_CAPACITY = TRAINING_DATA->TOKEN_CAPACITY * 2;
		else
			TRAINING_DATA->TOKEN_CAPACITY = 1 << 20;

		TRAINING_DATA->TOKENS =
			realloc(TRAINING_DATA->TOKENS, TRAINING_DATA->TOKEN_CAPACITY * 4);
		TRAINING_DATA->CLASSES =
			realloc(TRAINING_DATA->CLASSES, TRAINING_DATA->TOKEN_CAPACITY);
	}

	TRAINING_DATA->TOKENS[TRAINING_DATA->TOKEN_COUNT] = TOKEN;
	TRAINING_DATA->CLASSES[TRAINING_DATA->TOKEN_COUNT] = TOKEN_CLASS;
	TRAINING_DATA->TOKEN_COUNT++;
}

void
	DATASET_PUSH_TURN(DATASET *TRAINING_DATA, int64_t TURN_POSITION)
{
	if (TRAINING_DATA->TURN_COUNT >= TRAINING_DATA->TURN_CAPACITY)
	{
		if (TRAINING_DATA->TURN_CAPACITY)
			TRAINING_DATA->TURN_CAPACITY = TRAINING_DATA->TURN_CAPACITY * 2;
		else
			TRAINING_DATA->TURN_CAPACITY = 1 << 16;

		TRAINING_DATA->TURN_STARTS = realloc(
			TRAINING_DATA->TURN_STARTS, TRAINING_DATA->TURN_CAPACITY * 8
		);
	}

	TRAINING_DATA->TURN_STARTS[TRAINING_DATA->TURN_COUNT++] = TURN_POSITION;
}

CONVERSATION
	*DATASET_NEW_CONVERSATION(DATASET *TRAINING_DATA)
{
	if (
		TRAINING_DATA->CONVERSATION_COUNT >=
			TRAINING_DATA->CONVERSATION_CAPACITY
	)
	{
		if (TRAINING_DATA->CONVERSATION_CAPACITY)
			TRAINING_DATA->CONVERSATION_CAPACITY =
				TRAINING_DATA->CONVERSATION_CAPACITY * 2;
		else
			TRAINING_DATA->CONVERSATION_CAPACITY = 1 << 14;

		TRAINING_DATA->CONVERSATIONS = realloc(
			TRAINING_DATA->CONVERSATIONS,
			TRAINING_DATA->CONVERSATION_CAPACITY * sizeof(CONVERSATION)
		);
	}

	CONVERSATION	*NEW_CONVERSATION =
		&TRAINING_DATA->CONVERSATIONS[TRAINING_DATA->CONVERSATION_COUNT++];

	memset(NEW_CONVERSATION, 0, sizeof *NEW_CONVERSATION);
	NEW_CONVERSATION->START = TRAINING_DATA->TOKEN_COUNT;
	NEW_CONVERSATION->FIRST_TURN = TRAINING_DATA->TURN_COUNT;

	return (NEW_CONVERSATION);
}

char
	*READ_WHOLE_FILE(const char *PATH, long *FILE_LENGTH)
{
	FILE	*STREAM = fopen(PATH, "rb");

	if (!STREAM)
		return (NULL);

	fseek(STREAM, 0, SEEK_END);

	long	BYTE_COUNT = ftell(STREAM);

	fseek(STREAM, 0, SEEK_SET);

	char	*CONTENTS = malloc(BYTE_COUNT + 1);

	if (fread(CONTENTS, 1, BYTE_COUNT, STREAM) != (size_t)BYTE_COUNT)
	{
		fclose(STREAM);
		free(CONTENTS);
		return (NULL);
	}

	CONTENTS[BYTE_COUNT] = 0;
	fclose(STREAM);

	if (FILE_LENGTH)
		*FILE_LENGTH = BYTE_COUNT;

	return (CONTENTS);
}

int
	LINE_MARKER_KIND(const char *LINE)
{
	if (
		(
			LINE[0] == '#' ||
			LINE[0] == '@' ||
			LINE[0] == '>' ||
			LINE[0] == '<' ||
			LINE[0] == '!' ||
			LINE[0] == '=' ||
			LINE[0] == '%' ||
			LINE[0] == '~' ||
			LINE[0] == '+' ||
			LINE[0] == '-'
		) &&
		(LINE[1] == ' ' || LINE[1] == '\t' || LINE[1] == 0)
	)
		return (LINE[0]);

	return (0);
}

void
	COUNT_FILE_WORDS(LANGUAGE *LEXICON, const char *PATH)
{
	long	FILE_LENGTH;
	char	*CONTENTS = READ_WHOLE_FILE(PATH, &FILE_LENGTH);

	if (!CONTENTS)
	{
		fprintf(stderr, "cannot read %s\n", PATH);
		return ;
	}

	SPLIT_WORD	*LINE_WORDS = malloc(4096 * sizeof(SPLIT_WORD));
	char		*LINE_START = CONTENTS;

	while (*LINE_START)
	{
		char	*LINE_END = strchr(LINE_START, '\n');

		if (LINE_END)
			*LINE_END = 0;

		const char	*LINE_BODY =
			LINE_MARKER_KIND(LINE_START) ? LINE_START + 2 : LINE_START;
		int			WORD_COUNT;

		if (LINE_MARKER_KIND(LINE_START) == '%')
			WORD_COUNT = 0;
		else
			WORD_COUNT = SPLIT_WORDS(LINE_BODY, LINE_WORDS, 4096);

		int	WORD_INDEX;

		for (WORD_INDEX = 0; WORD_INDEX < WORD_COUNT; WORD_INDEX++)
			LANGUAGE_ADD(
				LEXICON, LINE_WORDS[WORD_INDEX].WORD_TEXT,
				LINE_WORDS[WORD_INDEX].IS_CAPITALIZED
			);

		if (!LINE_END)
			break ;

		LINE_START = LINE_END + 1;
	}

	free(LINE_WORDS);
	free(CONTENTS);
}

void
	LOAD_TRAINING_FILE(
		LANGUAGE *LEXICON, DATASET *TRAINING_DATA, const char *PATH,
		int MAX_SEQUENCE_LENGTH
	)
{
	long	FILE_LENGTH;
	char	*CONTENTS = READ_WHOLE_FILE(PATH, &FILE_LENGTH);

	if (!CONTENTS)
		return ;

	int32_t			*LINE_TOKENS = malloc(8192 * 4);
	int32_t			DO_TOKEN = LANGUAGE_TOKEN(LEXICON, SPECIAL_DO);
	int32_t			RESULT_TOKEN = LANGUAGE_TOKEN(LEXICON, SPECIAL_RESULT);
	int32_t			MORE_TOKEN = LANGUAGE_TOKEN(LEXICON, SPECIAL_MORE);
	CONVERSATION	*DIALOGUE = NULL;
	int				LAST_WAS_CODE = 0;
	char			*LINE_START = CONTENTS;

	for (;;)
	{
		char	*LINE_END = strchr(LINE_START, '\n');

		if (LINE_END)
			*LINE_END = 0;

		size_t	LINE_LENGTH = strlen(LINE_START);

		while (
			LINE_LENGTH &&
			(
				LINE_START[LINE_LENGTH - 1] == '\r' ||
				LINE_START[LINE_LENGTH - 1] == ' '
			)
		)
			LINE_START[--LINE_LENGTH] = 0;

		if (!LINE_LENGTH)
		{
			DIALOGUE = NULL;
			LAST_WAS_CODE = 0;
		}
		else
		{
			int	LINE_MARKER = LINE_MARKER_KIND(LINE_START);

			if (LINE_MARKER == '%')
			{
				if (LINE_END)
				{
					LINE_START = LINE_END + 1;
					continue ;
				}

				break ;
			}

			if (
				(LINE_MARKER == '!' || LINE_MARKER == '=') &&
				(
					!DIALOGUE ||
					DIALOGUE->IS_PLAIN_TEXT ||
					DIALOGUE->TURN_COUNT == 0 ||
					DO_TOKEN < 0 ||
					RESULT_TOKEN < 0
				)
			)
				LINE_MARKER = 0;

			if (
				(LINE_MARKER == '~' || LINE_MARKER == '-') &&
				(!DIALOGUE || DIALOGUE->IS_PLAIN_TEXT)
			)
				LINE_MARKER = 0;

			if (LINE_MARKER == '+' && MORE_TOKEN < 0)
				LINE_MARKER = '>';

			if (LINE_MARKER == '+' && DIALOGUE && DIALOGUE->IS_PLAIN_TEXT)
				LINE_MARKER = 0;

			const char	*LINE_BODY = LINE_MARKER ? LINE_START + 2 : LINE_START;
			int			TOKEN_COUNT =
				ENCODE_TEXT(LEXICON, LINE_BODY, LINE_TOKENS, 8192, 0);

			if (!DIALOGUE)
			{
				DIALOGUE = DATASET_NEW_CONVERSATION(TRAINING_DATA);
				DIALOGUE->IS_PLAIN_TEXT = LINE_MARKER == 0;

				if (DIALOGUE->IS_PLAIN_TEXT)
					DATASET_PUSH_TOKEN(
						TRAINING_DATA, TOKEN_TEXT, TOKEN_CLASS_NONE
					);
			}

			if (DIALOGUE->IS_PLAIN_TEXT)
			{
				int	TOKEN_INDEX;

				for (TOKEN_INDEX = 0; TOKEN_INDEX < TOKEN_COUNT; TOKEN_INDEX++)
					DATASET_PUSH_TOKEN(
						TRAINING_DATA, LINE_TOKENS[TOKEN_INDEX],
						TOKEN_CLASS_TEXT
					);
			}
			else if (LINE_MARKER == '#' || LINE_MARKER == '@')
			{
				if (DIALOGUE->TURN_COUNT == 0)
				{
					DATASET_PUSH_TOKEN(
						TRAINING_DATA,
						LINE_MARKER == '#' ? TOKEN_MEMORY : TOKEN_YOU,
						TOKEN_CLASS_NONE
					);

					int	TOKEN_INDEX;

					for (
						TOKEN_INDEX = 0;
						TOKEN_INDEX < TOKEN_COUNT;
						TOKEN_INDEX++
					)
						DATASET_PUSH_TOKEN(
							TRAINING_DATA, LINE_TOKENS[TOKEN_INDEX],
							TOKEN_CLASS_MEMORY
						);

					DIALOGUE->MEMORY_LENGTH =
						(int32_t)(TRAINING_DATA->TOKEN_COUNT - DIALOGUE->START);
				}
			}
			else if (LINE_MARKER == '!')
			{
				DATASET_PUSH_TURN(TRAINING_DATA, TRAINING_DATA->TOKEN_COUNT);
				DIALOGUE->TURN_COUNT++;
				DATASET_PUSH_TOKEN(TRAINING_DATA, DO_TOKEN, TOKEN_CLASS_USER);

				int	TOKEN_INDEX;

				for (TOKEN_INDEX = 0; TOKEN_INDEX < TOKEN_COUNT; TOKEN_INDEX++)
					DATASET_PUSH_TOKEN(
						TRAINING_DATA, LINE_TOKENS[TOKEN_INDEX],
						TOKEN_CLASS_CODE
					);

				LAST_WAS_CODE = 0;
			}
			else if (LINE_MARKER == '=')
			{
				DATASET_PUSH_TOKEN(
					TRAINING_DATA, RESULT_TOKEN, TOKEN_CLASS_CODE
				);

				int	TOKEN_INDEX;

				for (TOKEN_INDEX = 0; TOKEN_INDEX < TOKEN_COUNT; TOKEN_INDEX++)
					DATASET_PUSH_TOKEN(
						TRAINING_DATA, LINE_TOKENS[TOKEN_INDEX],
						TOKEN_CLASS_NONE
					);

				LAST_WAS_CODE = 0;
			}
			else if (LINE_MARKER == '-')
			{
				DATASET_PUSH_TURN(TRAINING_DATA, TRAINING_DATA->TOKEN_COUNT);
				DIALOGUE->TURN_COUNT++;
				DATASET_PUSH_TOKEN(
					TRAINING_DATA, TOKEN_CODE_TURN, TOKEN_CLASS_USER
				);

				int	TOKEN_INDEX;

				for (TOKEN_INDEX = 0; TOKEN_INDEX < TOKEN_COUNT; TOKEN_INDEX++)
					DATASET_PUSH_TOKEN(
						TRAINING_DATA, LINE_TOKENS[TOKEN_INDEX], TOKEN_CLASS_BAD
					);

				LAST_WAS_CODE = 1;
			}
			else if (LINE_MARKER == '~')
			{
				DATASET_PUSH_TURN(TRAINING_DATA, TRAINING_DATA->TOKEN_COUNT);
				DIALOGUE->TURN_COUNT++;
				DATASET_PUSH_TOKEN(
					TRAINING_DATA, TOKEN_CODE_TURN, TOKEN_CLASS_USER
				);

				int	TOKEN_INDEX;

				for (TOKEN_INDEX = 0; TOKEN_INDEX < TOKEN_COUNT; TOKEN_INDEX++)
					DATASET_PUSH_TOKEN(
						TRAINING_DATA, LINE_TOKENS[TOKEN_INDEX],
						TOKEN_CLASS_NONE
					);

				LAST_WAS_CODE = 0;
			}
			else if (LINE_MARKER == '+')
			{
				DATASET_PUSH_TURN(TRAINING_DATA, TRAINING_DATA->TOKEN_COUNT);
				DIALOGUE->TURN_COUNT++;
				DATASET_PUSH_TOKEN(
					TRAINING_DATA, TOKEN_USER_TURN,
					LAST_WAS_CODE ? TOKEN_CLASS_CODE : TOKEN_CLASS_USER
				);

				int	TOKEN_INDEX;

				for (TOKEN_INDEX = 0; TOKEN_INDEX < TOKEN_COUNT; TOKEN_INDEX++)
					DATASET_PUSH_TOKEN(
						TRAINING_DATA, LINE_TOKENS[TOKEN_INDEX],
						TOKEN_CLASS_USER
					);

				DATASET_PUSH_TOKEN(TRAINING_DATA, MORE_TOKEN, TOKEN_CLASS_USER);
				LAST_WAS_CODE = 0;
			}
			else if (LINE_MARKER == '>' || LINE_MARKER == '<')
			{
				DATASET_PUSH_TURN(TRAINING_DATA, TRAINING_DATA->TOKEN_COUNT);
				DIALOGUE->TURN_COUNT++;

				if (LINE_MARKER == '>')
				{
					DATASET_PUSH_TOKEN(
						TRAINING_DATA, TOKEN_USER_TURN,
						LAST_WAS_CODE ? TOKEN_CLASS_CODE : TOKEN_CLASS_USER
					);

					int	TOKEN_INDEX;

					for (
						TOKEN_INDEX = 0;
						TOKEN_INDEX < TOKEN_COUNT;
						TOKEN_INDEX++
					)
						DATASET_PUSH_TOKEN(
							TRAINING_DATA, LINE_TOKENS[TOKEN_INDEX],
							TOKEN_CLASS_USER
						);

					LAST_WAS_CODE = 0;
				}
				else
				{
					DATASET_PUSH_TOKEN(
						TRAINING_DATA, TOKEN_CODE_TURN, TOKEN_CLASS_USER
					);

					int	TOKEN_INDEX;

					for (
						TOKEN_INDEX = 0;
						TOKEN_INDEX < TOKEN_COUNT;
						TOKEN_INDEX++
					)
						DATASET_PUSH_TOKEN(
							TRAINING_DATA, LINE_TOKENS[TOKEN_INDEX],
							TOKEN_CLASS_CODE
						);

					LAST_WAS_CODE = 1;
				}
			}
			else
			{
				uint8_t	TOKEN_CLASS;

				if (LAST_WAS_CODE)
					TOKEN_CLASS = TOKEN_CLASS_CODE;
				else
					TOKEN_CLASS = TOKEN_CLASS_USER;

				int	TOKEN_INDEX;

				for (TOKEN_INDEX = 0; TOKEN_INDEX < TOKEN_COUNT; TOKEN_INDEX++)
					DATASET_PUSH_TOKEN(
						TRAINING_DATA, LINE_TOKENS[TOKEN_INDEX], TOKEN_CLASS
					);
			}

			DIALOGUE->LENGTH =
				(int32_t)(TRAINING_DATA->TOKEN_COUNT - DIALOGUE->START);

			if (DIALOGUE->MEMORY_LENGTH > MAX_SEQUENCE_LENGTH / 2)
				DIALOGUE->MEMORY_LENGTH = MAX_SEQUENCE_LENGTH / 2;
		}

		if (!LINE_END)
			break ;

		LINE_START = LINE_END + 1;
	}

	free(LINE_TOKENS);
	free(CONTENTS);
}

int64_t
	TURN_END(DATASET *TRAINING_DATA, CONVERSATION *DIALOGUE, int TURN_INDEX)
{
	if (TURN_INDEX + 1 < DIALOGUE->TURN_COUNT)
		return (
			TRAINING_DATA->TURN_STARTS[DIALOGUE->FIRST_TURN + TURN_INDEX + 1]
		);

	return (DIALOGUE->START + DIALOGUE->LENGTH);
}

WINDOW
	*MAKE_WINDOWS(
		DATASET *TRAINING_DATA, int MAX_SEQUENCE_LENGTH, int64_t *OUTPUT_COUNT
	)
{
	int64_t	WINDOW_CAPACITY = 1 << 16;
	int64_t	WINDOW_COUNT = 0;
	WINDOW	*WINDOWS = malloc(WINDOW_CAPACITY * sizeof(WINDOW));
	int		TOKEN_LIMIT = MAX_SEQUENCE_LENGTH + 1;
	int64_t	DIALOGUE_INDEX;

	for (
		DIALOGUE_INDEX = 0;
		DIALOGUE_INDEX < TRAINING_DATA->CONVERSATION_COUNT;
		DIALOGUE_INDEX++
	)
	{
		CONVERSATION	*DIALOGUE =
			&TRAINING_DATA->CONVERSATIONS[DIALOGUE_INDEX];

		if (WINDOW_COUNT + 64 >= WINDOW_CAPACITY)
		{
			WINDOW_CAPACITY *= 2;
			WINDOWS = realloc(WINDOWS, WINDOW_CAPACITY * sizeof(WINDOW));
		}

		if (DIALOGUE->IS_PLAIN_TEXT || DIALOGUE->TURN_COUNT == 0)
		{
			int32_t	TOKEN_OFFSET;

			for (
				TOKEN_OFFSET = 0;
				TOKEN_OFFSET < DIALOGUE->LENGTH - 1;
				TOKEN_OFFSET += MAX_SEQUENCE_LENGTH
			)
			{
				if (WINDOW_COUNT + 2 >= WINDOW_CAPACITY)
				{
					WINDOW_CAPACITY *= 2;
					WINDOWS =
						realloc(WINDOWS, WINDOW_CAPACITY * sizeof(WINDOW));
				}

				WINDOWS[WINDOW_COUNT].CONVERSATION_INDEX =
					(int32_t)DIALOGUE_INDEX;
				WINDOWS[WINDOW_COUNT].START = TOKEN_OFFSET;
				WINDOWS[WINDOW_COUNT].END = -1;
				WINDOW_COUNT++;
			}

			continue ;
		}

		int	FIRST_TURN = 0;

		while (FIRST_TURN < DIALOGUE->TURN_COUNT)
		{
			int64_t	USED_TOKENS = DIALOGUE->MEMORY_LENGTH;
			int		END_TURN = FIRST_TURN;

			while (END_TURN < DIALOGUE->TURN_COUNT)
			{
				int64_t	TURN_LENGTH =
					TURN_END(TRAINING_DATA, DIALOGUE, END_TURN) -
					TRAINING_DATA->TURN_STARTS[DIALOGUE->FIRST_TURN + END_TURN];

				if (
					USED_TOKENS + TURN_LENGTH > TOKEN_LIMIT &&
					END_TURN > FIRST_TURN
				)
					break ;

				USED_TOKENS += TURN_LENGTH;
				END_TURN++;
			}

			if (WINDOW_COUNT + 2 >= WINDOW_CAPACITY)
			{
				WINDOW_CAPACITY *= 2;
				WINDOWS = realloc(WINDOWS, WINDOW_CAPACITY * sizeof(WINDOW));
			}

			WINDOWS[WINDOW_COUNT].CONVERSATION_INDEX = (int32_t)DIALOGUE_INDEX;
			WINDOWS[WINDOW_COUNT].START = FIRST_TURN;
			WINDOWS[WINDOW_COUNT].END = END_TURN;
			WINDOW_COUNT++;

			if (END_TURN >= DIALOGUE->TURN_COUNT)
				break ;

			int	ADVANCE = (END_TURN - FIRST_TURN) / 2;

			if (ADVANCE > 0)
				FIRST_TURN += ADVANCE;
			else
				FIRST_TURN += 1;
		}
	}

	*OUTPUT_COUNT = WINDOW_COUNT;

	return (WINDOWS);
}

static int
	IS_FIRST_PERSON_TURN(
		DATASET *TRAINING_DATA, int64_t TURN_START, int64_t TURN_FINISH
	)
{
	if (
		TURN_FINISH - TURN_START < 5 ||
		TURN_FINISH - TURN_START > 40 ||
		TRAINING_DATA->TOKENS[TURN_START] != TOKEN_USER_TURN
	)
		return (0);

	int	PRONOUN_INDEX;

	for (
		PRONOUN_INDEX = 0;
		PRONOUN_INDEX < TRAINING_DATA->FIRST_PERSON_COUNT;
		PRONOUN_INDEX++
	)
		if (
			TRAINING_DATA->TOKENS[TURN_START + 1] ==
				TRAINING_DATA->FIRST_PERSON_TOKENS[PRONOUN_INDEX]
		)
			return (1);

	return (0);
}

int
	BUILD_SEQUENCE(
		DATASET *TRAINING_DATA, WINDOW *TRAINING_WINDOW,
		int MAX_SEQUENCE_LENGTH, int32_t *SEQUENCE, float *WEIGHTS
	)
{
	CONVERSATION	*DIALOGUE =
		&TRAINING_DATA->CONVERSATIONS[TRAINING_WINDOW->CONVERSATION_INDEX];
	int				TOKEN_LIMIT = MAX_SEQUENCE_LENGTH + 1;
	int				SEQUENCE_LENGTH = 0;

	if (TRAINING_WINDOW->END < 0)
	{
		int64_t	TURN_START = DIALOGUE->START + TRAINING_WINDOW->START;

		if (TRAINING_WINDOW->START > 0)
		{
			SEQUENCE[SEQUENCE_LENGTH] = TOKEN_TEXT;
			WEIGHTS[SEQUENCE_LENGTH++] = 0;
		}

		int64_t	TOKEN_POSITION;

		for (
			TOKEN_POSITION = TURN_START;
			TOKEN_POSITION <
				DIALOGUE->START + DIALOGUE->LENGTH &&SEQUENCE_LENGTH <
				TOKEN_LIMIT;
			TOKEN_POSITION++
		)
		{
			SEQUENCE[SEQUENCE_LENGTH] = TRAINING_DATA->TOKENS[TOKEN_POSITION];
			WEIGHTS[SEQUENCE_LENGTH++] =
				TOKEN_CLASS_WEIGHTS[TRAINING_DATA->CLASSES[TOKEN_POSITION]];
		}

		return (SEQUENCE_LENGTH);
	}

	int64_t	TOKEN_POSITION;

	for (
		TOKEN_POSITION = DIALOGUE->START;
		TOKEN_POSITION <
			DIALOGUE->START + DIALOGUE->MEMORY_LENGTH &&SEQUENCE_LENGTH <
			TOKEN_LIMIT;
		TOKEN_POSITION++
	)
	{
		SEQUENCE[SEQUENCE_LENGTH] = TRAINING_DATA->TOKENS[TOKEN_POSITION];
		WEIGHTS[SEQUENCE_LENGTH++] =
			TOKEN_CLASS_WEIGHTS[TRAINING_DATA->CLASSES[TOKEN_POSITION]];
	}

	int	PICKED_COUNT = 0;
	int	TURN_INDEX;

	for (
		TURN_INDEX = TRAINING_WINDOW->START - 1;
		TURN_INDEX >= 0 && PICKED_COUNT < 3 &&
			SEQUENCE_LENGTH < TOKEN_LIMIT / 3;
		TURN_INDEX--
	)
	{
		int64_t	TURN_START =
			TRAINING_DATA->TURN_STARTS[DIALOGUE->FIRST_TURN + TURN_INDEX];
		int64_t	TURN_FINISH = TURN_END(TRAINING_DATA, DIALOGUE, TURN_INDEX);

		if (!IS_FIRST_PERSON_TURN(TRAINING_DATA, TURN_START, TURN_FINISH))
			continue ;

		SEQUENCE[SEQUENCE_LENGTH] = TOKEN_YOU;
		WEIGHTS[SEQUENCE_LENGTH++] = 0;

		int64_t	TOKEN_POSITION;

		for (
			TOKEN_POSITION = TURN_START + 1;
			TOKEN_POSITION < TURN_FINISH && SEQUENCE_LENGTH < TOKEN_LIMIT;
			TOKEN_POSITION++
		)
		{
			SEQUENCE[SEQUENCE_LENGTH] = TRAINING_DATA->TOKENS[TOKEN_POSITION];
			WEIGHTS[SEQUENCE_LENGTH++] =
				TOKEN_CLASS_WEIGHTS[TOKEN_CLASS_MEMORY];
		}

		PICKED_COUNT++;
	}

	for (
		TURN_INDEX = TRAINING_WINDOW->START;
		TURN_INDEX < TRAINING_WINDOW->END && SEQUENCE_LENGTH < TOKEN_LIMIT;
		TURN_INDEX++
	)
	{
		int64_t	TURN_START =
			TRAINING_DATA->TURN_STARTS[DIALOGUE->FIRST_TURN + TURN_INDEX];
		int64_t	TURN_FINISH = TURN_END(TRAINING_DATA, DIALOGUE, TURN_INDEX);
		int64_t	TOKEN_POSITION;

		for (
			TOKEN_POSITION = TURN_START;
			TOKEN_POSITION < TURN_FINISH && SEQUENCE_LENGTH < TOKEN_LIMIT;
			TOKEN_POSITION++
		)
		{
			SEQUENCE[SEQUENCE_LENGTH] = TRAINING_DATA->TOKENS[TOKEN_POSITION];
			WEIGHTS[SEQUENCE_LENGTH++] =
				TOKEN_CLASS_WEIGHTS[TRAINING_DATA->CLASSES[TOKEN_POSITION]];
		}
	}

	return (SEQUENCE_LENGTH);
}

void
	DATASET_SET_FIRST_PERSON(DATASET *TRAINING_DATA, LANGUAGE *LEXICON)
{
	const char	*PRONOUNS[6] = { "i", "my", "i'm", "i've", "i'll", "im" };

	TRAINING_DATA->FIRST_PERSON_COUNT = 0;

	int	PRONOUN_INDEX;

	for (PRONOUN_INDEX = 0; PRONOUN_INDEX < 6; PRONOUN_INDEX++)
	{
		int32_t	LEXEME_ID = LANGUAGE_FIND(LEXICON, PRONOUNS[PRONOUN_INDEX]);

		if (LEXEME_ID >= 0 && LEXICON->LEXEME_TO_TOKEN[LEXEME_ID] >= 0)
			TRAINING_DATA
				->FIRST_PERSON_TOKENS[TRAINING_DATA->FIRST_PERSON_COUNT++] =
				LEXICON->LEXEME_TO_TOKEN[LEXEME_ID];
	}
}

void
	DATASET_FREE(DATASET *TRAINING_DATA)
{
	free(TRAINING_DATA->TOKENS);
	free(TRAINING_DATA->CLASSES);
	free(TRAINING_DATA->CONVERSATIONS);
	free(TRAINING_DATA->TURN_STARTS);
	memset(TRAINING_DATA, 0, sizeof *TRAINING_DATA);
}

static int
	IS_TEXT_FILE_NAME(const char *FILE_NAME)
{
	size_t	NAME_LENGTH = strlen(FILE_NAME);

	return (
		NAME_LENGTH > 4 &&
		(
			!strcmp(FILE_NAME + NAME_LENGTH - 4, ".txt") ||
			!strcmp(FILE_NAME + NAME_LENGTH - 4, ".TXT")
		)
	);
}

int
	LIST_TEXT_FILES(const char *PATH, char **OUTPUT, int OUTPUT_SIZE)
{
	int	PATH_COUNT = 0;
#ifdef _WIN32
	char	SEARCH_PATTERN[1024];

	snprintf(SEARCH_PATTERN, sizeof SEARCH_PATTERN, "%s\\*.txt", PATH);

	WIN32_FIND_DATAA	FIND_DATA;
	HANDLE				FIND_HANDLE =
		FindFirstFileA(SEARCH_PATTERN, &FIND_DATA);

	if (FIND_HANDLE == INVALID_HANDLE_VALUE)
	{
		if (IS_TEXT_FILE_NAME(PATH) && PATH_COUNT < OUTPUT_SIZE)
		{
			OUTPUT[PATH_COUNT] = malloc(strlen(PATH) + 1);
			strcpy(OUTPUT[PATH_COUNT++], PATH);
		}

		return (PATH_COUNT);
	}

	do
	{
		if (
			!(FIND_DATA.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) &&
			PATH_COUNT < OUTPUT_SIZE
		)
		{
			OUTPUT[PATH_COUNT] =
				malloc(strlen(PATH) + strlen(FIND_DATA.cFileName) + 2);
			sprintf(OUTPUT[PATH_COUNT++], "%s\\%s", PATH, FIND_DATA.cFileName);
		}
	} while (FindNextFileA(FIND_HANDLE, &FIND_DATA));

	FindClose(FIND_HANDLE);
#else
	struct stat	FILE_STATUS;

	if (stat(PATH, &FILE_STATUS) == 0 && S_ISDIR(FILE_STATUS.st_mode))
	{
		DIR				*DIRECTORY = opendir(PATH);
		struct dirent	*DIRECTORY_ENTRY;

		while (
			DIRECTORY &&
			(DIRECTORY_ENTRY = readdir(DIRECTORY)) &&
			PATH_COUNT < OUTPUT_SIZE
		)
			if (IS_TEXT_FILE_NAME(DIRECTORY_ENTRY->d_name))
			{
				OUTPUT[PATH_COUNT] =
					malloc(strlen(PATH) + strlen(DIRECTORY_ENTRY->d_name) + 2);
				sprintf(
					OUTPUT[PATH_COUNT++], "%s/%s", PATH, DIRECTORY_ENTRY->d_name
				);
			}

		if (DIRECTORY)
			closedir(DIRECTORY);
	}
	else if (PATH_COUNT < OUTPUT_SIZE)
	{
		OUTPUT[PATH_COUNT] = malloc(strlen(PATH) + 1);
		strcpy(OUTPUT[PATH_COUNT++], PATH);
	}
#endif
	int	OUTER_INDEX;

	for (OUTER_INDEX = 0; OUTER_INDEX < PATH_COUNT; OUTER_INDEX++)
	{
		int	INNER_INDEX;

		for (
			INNER_INDEX = OUTER_INDEX + 1;
			INNER_INDEX < PATH_COUNT;
			INNER_INDEX++
		)
			if (strcmp(OUTPUT[OUTER_INDEX], OUTPUT[INNER_INDEX]) > 0)
			{
				char	*SWAP_PATH = OUTPUT[OUTER_INDEX];

				OUTPUT[OUTER_INDEX] = OUTPUT[INNER_INDEX];
				OUTPUT[INNER_INDEX] = SWAP_PATH;
			}
	}

	return (PATH_COUNT);
}
