#ifndef GPU_H
#define GPU_H
#include <stdint.h>
#include <stddef.h>

typedef struct
{
	uint32_t	*WORDS;
	int			COUNT;
	int			CAPACITY;
} SPIRV_SECTION;

typedef struct
{
	SPIRV_SECTION	SECTIONS[5];
	uint32_t		ID_BOUND;
	uint32_t		TYPE_VOID;
	uint32_t		TYPE_FUNCTION;
	uint32_t		TYPE_BOOLEAN;
	uint32_t		TYPE_UNSIGNED;
	uint32_t		TYPE_SIGNED;
	uint32_t		TYPE_FLOAT;
	uint32_t		TYPE_UNSIGNED_VECTOR3;
	uint32_t		POINTER_INPUT_VECTOR3;
	uint32_t		POINTER_INPUT_UNSIGNED;
	uint32_t		TYPE_RUNTIME_ARRAY;
	uint32_t		TYPE_STORAGE_BUFFER;
	uint32_t		POINTER_UNIFORM_BLOCK;
	uint32_t		POINTER_UNIFORM_FLOAT;
	uint32_t		TYPE_PUSH_CONSTANTS;
	uint32_t		POINTER_PUSH_CONSTANTS;
	uint32_t		POINTER_PUSH_UNSIGNED;
	uint32_t		POINTER_LOCAL_UNSIGNED;
	uint32_t		POINTER_LOCAL_FLOAT;
	uint32_t		GLOBAL_ID;
	uint32_t		LOCAL_ID;
	uint32_t		WORKGROUP_ID;
	uint32_t		PUSH_CONSTANT_VARIABLE;
	uint32_t		BUFFER_VARIABLES[16];
	uint32_t		MAIN_FUNCTION;
	int				BUFFER_COUNT;
	int				PUSH_CONSTANT_COUNT;
	uint32_t		UNSIGNED_CONSTANT_IDS[64];
	uint32_t		UNSIGNED_CONSTANT_VALUES[64];
	int				UNSIGNED_CONSTANT_COUNT;
	uint32_t		POINTER_WORKGROUP_FLOAT;
	uint32_t		BARRIER_CONSTANTS[3];
	uint32_t		FLOAT_CONSTANT_IDS[32];
	float			FLOAT_CONSTANT_VALUES[32];
	int				FLOAT_CONSTANT_COUNT;
} KERNEL_BUILDER;

void		KERNEL_BEGIN(
	KERNEL_BUILDER *BUILDER, int BUFFER_COUNT, int PUSH_CONSTANT_COUNT,
	int LOCAL_SIZE_X, int LOCAL_SIZE_Y, int LOCAL_SIZE_Z
);
uint32_t	*KERNEL_END(KERNEL_BUILDER *BUILDER, int *OUTPUT_WORD_COUNT);
uint32_t	KERNEL_NEW_ID(KERNEL_BUILDER *BUILDER);
void		KERNEL_OPERATION(
	KERNEL_BUILDER *BUILDER, int SECTION_INDEX, int OPCODE, int OPERAND_COUNT,
	const uint32_t *OPERANDS
);
uint32_t	KERNEL_CONSTANT_UNSIGNED(
	KERNEL_BUILDER *BUILDER, uint32_t CONSTANT_VALUE
);
uint32_t	KERNEL_CONSTANT_FLOAT(
	KERNEL_BUILDER *BUILDER, float CONSTANT_VALUE
);
uint32_t	KERNEL_PUSH_CONSTANT(KERNEL_BUILDER *BUILDER, int CONSTANT_INDEX);
uint32_t	KERNEL_GLOBAL_ID(KERNEL_BUILDER *BUILDER, int AXIS);
uint32_t	KERNEL_LOCAL_ID(KERNEL_BUILDER *BUILDER, int AXIS);
uint32_t	KERNEL_WORKGROUP_ID(KERNEL_BUILDER *BUILDER, int AXIS);
uint32_t	KERNEL_LOAD_BUFFER(
	KERNEL_BUILDER *BUILDER, int BUFFER_INDEX, uint32_t ELEMENT_INDEX
);
void		KERNEL_STORE_BUFFER(
	KERNEL_BUILDER *BUILDER, int BUFFER_INDEX, uint32_t ELEMENT_INDEX,
	uint32_t STORED_VALUE
);
uint32_t	KERNEL_BINARY(
	KERNEL_BUILDER *BUILDER, int OPCODE, uint32_t RESULT_TYPE,
	uint32_t LEFT_OPERAND, uint32_t RIGHT_OPERAND
);
uint32_t	KERNEL_VARIABLE_UNSIGNED(KERNEL_BUILDER *BUILDER);
uint32_t	KERNEL_VARIABLE_FLOAT(KERNEL_BUILDER *BUILDER);
uint32_t	KERNEL_LOAD(
	KERNEL_BUILDER *BUILDER, uint32_t RESULT_TYPE, uint32_t VARIABLE_POINTER
);
void		KERNEL_STORE(
	KERNEL_BUILDER *BUILDER, uint32_t VARIABLE_POINTER, uint32_t STORED_VALUE
);
uint32_t	KERNEL_NEW_LABEL(KERNEL_BUILDER *BUILDER);
void		KERNEL_BIND_LABEL(KERNEL_BUILDER *BUILDER, uint32_t LABEL_ID);
void		KERNEL_BRANCH(KERNEL_BUILDER *BUILDER, uint32_t TARGET_LABEL);
void		KERNEL_IF(
	KERNEL_BUILDER *BUILDER, uint32_t CONDITION, uint32_t *MERGE_LABEL
);
void		KERNEL_END_IF(KERNEL_BUILDER *BUILDER, uint32_t MERGE_LABEL);

typedef struct
{
	uint32_t	VARIABLE;
	uint32_t	HEADER_LABEL;
	uint32_t	MERGE_LABEL;
	uint32_t	CONTINUE_LABEL;
	uint32_t	BODY_LABEL;
} KERNEL_LOOP;

KERNEL_LOOP	KERNEL_FOR(
	KERNEL_BUILDER *BUILDER, uint32_t START_VALUE, uint32_t END_VALUE
);
void		KERNEL_FOR_END(
	KERNEL_BUILDER *BUILDER, KERNEL_LOOP *LOOP_STATE, uint32_t STEP_VALUE
);
uint32_t	KERNEL_FOR_VARIABLE(
	KERNEL_BUILDER *BUILDER, KERNEL_LOOP *LOOP_STATE
);
uint32_t	KERNEL_SHARED_ARRAY(KERNEL_BUILDER *BUILDER, int ELEMENT_COUNT);
uint32_t	KERNEL_SHARED_POINTER(
	KERNEL_BUILDER *BUILDER, uint32_t SHARED_ARRAY, uint32_t ELEMENT_INDEX
);
void		KERNEL_BARRIER(KERNEL_BUILDER *BUILDER);

enum
{
	SPIRV_INTEGER_ADD = 128,
	SPIRV_FLOAT_ADD = 129,
	SPIRV_INTEGER_SUBTRACT = 130,
	SPIRV_FLOAT_SUBTRACT = 131,
	SPIRV_INTEGER_MULTIPLY = 132,
	SPIRV_FLOAT_MULTIPLY = 133,
	SPIRV_UNSIGNED_DIVIDE = 134,
	SPIRV_FLOAT_DIVIDE = 136,
	SPIRV_UNSIGNED_MODULO = 137,
	SPIRV_UNSIGNED_LESS_THAN = 176,
	SPIRV_UNSIGNED_AT_LEAST = 174,
	SPIRV_FLOAT_LESS_THAN = 184,
	SPIRV_FLOAT_GREATER_THAN = 186,
	SPIRV_BITWISE_AND = 199,
	SPIRV_SHIFT_LEFT = 196,
	SPIRV_SHIFT_RIGHT = 194
};

typedef struct GPU GPU;
typedef struct GPU_BUFFER GPU_BUFFER;
typedef struct GPU_PIPELINE GPU_PIPELINE;

GPU				*GPU_OPEN(int VERBOSE);
void			GPU_CLOSE(GPU *GPU_STATE);
const char		*GPU_NAME(GPU *GPU_STATE);
int				GPU_IS_DISCRETE(GPU *GPU_STATE);
uint64_t		GPU_VIDEO_MEMORY(GPU *GPU_STATE);
GPU_BUFFER		*GPU_NEW_BUFFER(GPU *GPU_STATE, uint64_t BYTE_COUNT);
void			GPU_FREE_BUFFER(GPU *GPU_STATE, GPU_BUFFER *DEVICE_BUFFER);
int				GPU_UPLOAD(
	GPU *GPU_STATE, GPU_BUFFER *DEVICE_BUFFER, const void *SOURCE,
	uint64_t BYTE_COUNT, uint64_t OFFSET
);
int				GPU_DOWNLOAD(
	GPU *GPU_STATE, GPU_BUFFER *DEVICE_BUFFER, void *DESTINATION,
	uint64_t BYTE_COUNT, uint64_t OFFSET
);
GPU_PIPELINE	*GPU_NEW_PIPELINE(
	GPU *GPU_STATE, const uint32_t *SPIRV_WORDS, int WORD_COUNT,
	int BUFFER_COUNT, int PUSH_CONSTANT_COUNT
);
void			GPU_BEGIN(GPU *GPU_STATE);
void			GPU_RUN(
	GPU *GPU_STATE, GPU_PIPELINE *PIPELINE_STATE, GPU_BUFFER **BUFFERS,
	const uint32_t *PUSH_CONSTANTS, uint32_t GROUP_COUNT_X,
	uint32_t GROUP_COUNT_Y, uint32_t GROUP_COUNT_Z
);
int				GPU_END(GPU *GPU_STATE);
void			GPU_PRINT_INFORMATION(GPU *GPU_STATE);

#endif
