#include "GPU.h"
#include "VULKAN.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <dlfcn.h>
#endif

static void
	SECTION_APPEND_WORD(SPIRV_SECTION *SECTION, uint32_t WORD_VALUE)
{
	if (SECTION->COUNT >= SECTION->CAPACITY)
	{
		if (SECTION->CAPACITY)
			SECTION->CAPACITY = SECTION->CAPACITY * 2;
		else
			SECTION->CAPACITY = 256;

		SECTION->WORDS = realloc(SECTION->WORDS, SECTION->CAPACITY * 4);
	}

	SECTION->WORDS[SECTION->COUNT++] = WORD_VALUE;
}

uint32_t
	KERNEL_NEW_ID(KERNEL_BUILDER *BUILDER)
{
	return (BUILDER->ID_BOUND++);
}

void
	KERNEL_OPERATION(
		KERNEL_BUILDER *BUILDER, int SECTION_INDEX, int OPCODE,
		int OPERAND_COUNT, const uint32_t *OPERANDS
	)
{
	SECTION_APPEND_WORD(
		&BUILDER->SECTIONS[SECTION_INDEX],
		(uint32_t)((OPERAND_COUNT + 1) << 16 | OPCODE)
	);

	int	OPERAND_INDEX;

	for (OPERAND_INDEX = 0; OPERAND_INDEX < OPERAND_COUNT; OPERAND_INDEX++)
		SECTION_APPEND_WORD(
			&BUILDER->SECTIONS[SECTION_INDEX], OPERANDS[OPERAND_INDEX]
		);
}

#define EMIT_OPERATION(SECTION, OPERATION_CODE, ...) \
	do \
	{ \
		uint32_t OPERAND_WORDS[] = { __VA_ARGS__ }; \
		KERNEL_OPERATION( \
			BUILDER, SECTION, OPERATION_CODE, (int)(sizeof OPERAND_WORDS / 4), \
			OPERAND_WORDS \
		); \
	} while (0)
#define EMIT_OPERATION_ALONE(SECTION, OPERATION_CODE) \
	KERNEL_OPERATION(BUILDER, SECTION, OPERATION_CODE, 0, NULL)

static uint32_t
	KERNEL_RESULT_OPERATION(
		KERNEL_BUILDER *BUILDER, int SECTION_INDEX, int OPCODE,
		uint32_t RESULT_TYPE, int OPERAND_COUNT, const uint32_t *OPERANDS
	)
{
	uint32_t	RESULT_ID = KERNEL_NEW_ID(BUILDER);
	uint32_t	INSTRUCTION_WORDS[16];
	int			WORD_COUNT = 0;

	if (RESULT_TYPE)
		INSTRUCTION_WORDS[WORD_COUNT++] = RESULT_TYPE;

	INSTRUCTION_WORDS[WORD_COUNT++] = RESULT_ID;

	int	OPERAND_INDEX;

	for (OPERAND_INDEX = 0; OPERAND_INDEX < OPERAND_COUNT; OPERAND_INDEX++)
		INSTRUCTION_WORDS[WORD_COUNT++] = OPERANDS[OPERAND_INDEX];

	KERNEL_OPERATION(
		BUILDER, SECTION_INDEX, OPCODE, WORD_COUNT, INSTRUCTION_WORDS
	);

	return (RESULT_ID);
}

uint32_t
	KERNEL_CONSTANT_UNSIGNED(KERNEL_BUILDER *BUILDER, uint32_t CONSTANT_VALUE)
{
	int	CACHE_INDEX;

	for (
		CACHE_INDEX = 0;
		CACHE_INDEX < BUILDER->UNSIGNED_CONSTANT_COUNT;
		CACHE_INDEX++
	)
		if (BUILDER->UNSIGNED_CONSTANT_VALUES[CACHE_INDEX] == CONSTANT_VALUE)
			return (BUILDER->UNSIGNED_CONSTANT_IDS[CACHE_INDEX]);

	uint32_t	CONSTANT_ID = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 43, BUILDER->TYPE_UNSIGNED, 1, &CONSTANT_VALUE
	);

	if (BUILDER->UNSIGNED_CONSTANT_COUNT < 64)
	{
		BUILDER->UNSIGNED_CONSTANT_VALUES[BUILDER->UNSIGNED_CONSTANT_COUNT] =
			CONSTANT_VALUE;
		BUILDER->UNSIGNED_CONSTANT_IDS[BUILDER->UNSIGNED_CONSTANT_COUNT++] =
			CONSTANT_ID;
	}

	return (CONSTANT_ID);
}

uint32_t
	KERNEL_CONSTANT_FLOAT(KERNEL_BUILDER *BUILDER, float CONSTANT_VALUE)
{
	int	CACHE_INDEX;

	for (
		CACHE_INDEX = 0;
		CACHE_INDEX < BUILDER->FLOAT_CONSTANT_COUNT;
		CACHE_INDEX++
	)
		if (
			!memcmp(
				&BUILDER->FLOAT_CONSTANT_VALUES[CACHE_INDEX], &CONSTANT_VALUE, 4
			)
		)
			return (BUILDER->FLOAT_CONSTANT_IDS[CACHE_INDEX]);

	uint32_t	VALUE_BITS;

	memcpy(&VALUE_BITS, &CONSTANT_VALUE, 4);

	uint32_t	CONSTANT_ID = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 43, BUILDER->TYPE_FLOAT, 1, &VALUE_BITS
	);

	if (BUILDER->FLOAT_CONSTANT_COUNT < 32)
	{
		BUILDER->FLOAT_CONSTANT_VALUES[BUILDER->FLOAT_CONSTANT_COUNT] =
			CONSTANT_VALUE;
		BUILDER->FLOAT_CONSTANT_IDS[BUILDER->FLOAT_CONSTANT_COUNT++] =
			CONSTANT_ID;
	}

	return (CONSTANT_ID);
}

static uint32_t
	KERNEL_SIGNED_ZERO(KERNEL_BUILDER *BUILDER)
{
	static const uint32_t	ZERO_VALUE = 0;
	int						CACHE_INDEX;

	for (
		CACHE_INDEX = 0;
		CACHE_INDEX < BUILDER->UNSIGNED_CONSTANT_COUNT;
		CACHE_INDEX++
	)
		if (
			BUILDER->UNSIGNED_CONSTANT_VALUES[CACHE_INDEX] ==
				(unsigned int)0XFFFFFFFF &&
			BUILDER->UNSIGNED_CONSTANT_IDS[CACHE_INDEX]
		)
			return (BUILDER->UNSIGNED_CONSTANT_IDS[CACHE_INDEX]);

	uint32_t	CONSTANT_ID = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 43, BUILDER->TYPE_SIGNED, 1, &ZERO_VALUE
	);

	if (BUILDER->UNSIGNED_CONSTANT_COUNT < 64)
	{
		BUILDER->UNSIGNED_CONSTANT_VALUES[BUILDER->UNSIGNED_CONSTANT_COUNT] =
			(unsigned int)0XFFFFFFFF;
		BUILDER->UNSIGNED_CONSTANT_IDS[BUILDER->UNSIGNED_CONSTANT_COUNT++] =
			CONSTANT_ID;
	}

	return (CONSTANT_ID);
}

void
	KERNEL_BEGIN(
		KERNEL_BUILDER *BUILDER, int BUFFER_COUNT, int PUSH_CONSTANT_COUNT,
		int LOCAL_SIZE_X, int LOCAL_SIZE_Y, int LOCAL_SIZE_Z
	)
{
	memset(BUILDER, 0, sizeof *BUILDER);
	BUILDER->ID_BOUND = 1;
	BUILDER->BUFFER_COUNT = BUFFER_COUNT;
	BUILDER->PUSH_CONSTANT_COUNT = PUSH_CONSTANT_COUNT;
	EMIT_OPERATION(0, 17, 1);
	EMIT_OPERATION(0, 14, 0, 1);
	BUILDER->TYPE_VOID = KERNEL_RESULT_OPERATION(BUILDER, 2, 19, 0, 0, NULL);
	BUILDER->TYPE_FUNCTION =
		KERNEL_RESULT_OPERATION(BUILDER, 2, 33, 0, 1, &BUILDER->TYPE_VOID);
	BUILDER->TYPE_BOOLEAN = KERNEL_RESULT_OPERATION(BUILDER, 2, 20, 0, 0, NULL);
	BUILDER->TYPE_UNSIGNED =
		KERNEL_RESULT_OPERATION(BUILDER, 2, 21, 0, 2, (uint32_t[2]){ 32, 0 });
	BUILDER->TYPE_SIGNED =
		KERNEL_RESULT_OPERATION(BUILDER, 2, 21, 0, 2, (uint32_t[2]){ 32, 1 });
	BUILDER->TYPE_FLOAT =
		KERNEL_RESULT_OPERATION(BUILDER, 2, 22, 0, 1, (uint32_t[1]){ 32 });
	BUILDER->TYPE_UNSIGNED_VECTOR3 = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 23, 0, 2, (uint32_t[2]){ BUILDER->TYPE_UNSIGNED, 3 }
	);
	BUILDER->POINTER_INPUT_VECTOR3 = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 32, 0, 2, (uint32_t[2]){ 1, BUILDER->TYPE_UNSIGNED_VECTOR3 }
	);
	BUILDER->TYPE_RUNTIME_ARRAY =
		KERNEL_RESULT_OPERATION(BUILDER, 2, 29, 0, 1, &BUILDER->TYPE_FLOAT);
	EMIT_OPERATION(1, 71, BUILDER->TYPE_RUNTIME_ARRAY, 6, 4);
	BUILDER->TYPE_STORAGE_BUFFER = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 30, 0, 1, &BUILDER->TYPE_RUNTIME_ARRAY
	);
	EMIT_OPERATION(1, 72, BUILDER->TYPE_STORAGE_BUFFER, 0, 35, 0);
	EMIT_OPERATION(1, 71, BUILDER->TYPE_STORAGE_BUFFER, 3);
	BUILDER->POINTER_UNIFORM_BLOCK = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 32, 0, 2, (uint32_t[2]){ 2, BUILDER->TYPE_STORAGE_BUFFER }
	);
	BUILDER->POINTER_UNIFORM_FLOAT = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 32, 0, 2, (uint32_t[2]){ 2, BUILDER->TYPE_FLOAT }
	);
	BUILDER->POINTER_LOCAL_UNSIGNED = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 32, 0, 2, (uint32_t[2]){ 7, BUILDER->TYPE_UNSIGNED }
	);
	BUILDER->POINTER_LOCAL_FLOAT = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 32, 0, 2, (uint32_t[2]){ 7, BUILDER->TYPE_FLOAT }
	);

	uint32_t	BUILTIN_KINDS[3] = { 28, 27, 26 };
	uint32_t	*BUILTIN_VARIABLES[3] = {
		&BUILDER->GLOBAL_ID, &BUILDER->LOCAL_ID, &BUILDER->WORKGROUP_ID
	};
	int			INDEX;

	for (INDEX = 0; INDEX < 3; INDEX++)
	{
		*BUILTIN_VARIABLES[INDEX] = KERNEL_RESULT_OPERATION(
			BUILDER, 2, 59, BUILDER->POINTER_INPUT_VECTOR3, 1,
			(uint32_t[1]){ 1 }
		);
		EMIT_OPERATION(
			1, 71, *BUILTIN_VARIABLES[INDEX], 11, BUILTIN_KINDS[INDEX]
		);
	}

	for (INDEX = 0; INDEX < BUFFER_COUNT; INDEX++)
	{
		BUILDER->BUFFER_VARIABLES[INDEX] = KERNEL_RESULT_OPERATION(
			BUILDER, 2, 59, BUILDER->POINTER_UNIFORM_BLOCK, 1,
			(uint32_t[1]){ 2 }
		);
		EMIT_OPERATION(1, 71, BUILDER->BUFFER_VARIABLES[INDEX], 34, 0);
		EMIT_OPERATION(
			1, 71, BUILDER->BUFFER_VARIABLES[INDEX], 33, (uint32_t)INDEX
		);
	}

	if (PUSH_CONSTANT_COUNT)
	{
		uint32_t	MEMBER_TYPES[32];
		int			INDEX;

		for (INDEX = 0; INDEX < PUSH_CONSTANT_COUNT; INDEX++)
			MEMBER_TYPES[INDEX] = BUILDER->TYPE_UNSIGNED;

		BUILDER->TYPE_PUSH_CONSTANTS = KERNEL_RESULT_OPERATION(
			BUILDER, 2, 30, 0, PUSH_CONSTANT_COUNT, MEMBER_TYPES
		);

		for (INDEX = 0; INDEX < PUSH_CONSTANT_COUNT; INDEX++)
			EMIT_OPERATION(
				1, 72, BUILDER->TYPE_PUSH_CONSTANTS, (uint32_t)INDEX, 35,
				(uint32_t)(4 * INDEX)
			);
		EMIT_OPERATION(1, 71, BUILDER->TYPE_PUSH_CONSTANTS, 2);
		BUILDER->POINTER_PUSH_CONSTANTS = KERNEL_RESULT_OPERATION(
			BUILDER, 2, 32, 0, 2,
			(uint32_t[2]){ 9, BUILDER->TYPE_PUSH_CONSTANTS }
		);
		BUILDER->POINTER_PUSH_UNSIGNED = KERNEL_RESULT_OPERATION(
			BUILDER, 2, 32, 0, 2, (uint32_t[2]){ 9, BUILDER->TYPE_UNSIGNED }
		);
		BUILDER->PUSH_CONSTANT_VARIABLE = KERNEL_RESULT_OPERATION(
			BUILDER, 2, 59, BUILDER->POINTER_PUSH_CONSTANTS, 1,
			(uint32_t[1]){ 9 }
		);
	}

	BUILDER->MAIN_FUNCTION = KERNEL_NEW_ID(BUILDER);
	EMIT_OPERATION(
		3, 54, BUILDER->TYPE_VOID, BUILDER->MAIN_FUNCTION, 0,
		BUILDER->TYPE_FUNCTION
	);
	uint32_t	ENTRY_LABEL = KERNEL_NEW_ID(BUILDER);
	EMIT_OPERATION(3, 248, ENTRY_LABEL);
	uint32_t	ENTRY_POINT[8] = {
		5, BUILDER->MAIN_FUNCTION, 0X6E69616D, 0, BUILDER->GLOBAL_ID,
		BUILDER->LOCAL_ID, BUILDER->WORKGROUP_ID
	};

	KERNEL_OPERATION(BUILDER, 0, 15, 7, ENTRY_POINT);
	EMIT_OPERATION(
		0, 16, BUILDER->MAIN_FUNCTION, 17, (uint32_t)LOCAL_SIZE_X,
		(uint32_t)LOCAL_SIZE_Y, (uint32_t)LOCAL_SIZE_Z
	);
}

uint32_t
	*KERNEL_END(KERNEL_BUILDER *BUILDER, int *OUTPUT_WORD_COUNT)
{
	EMIT_OPERATION_ALONE(4, 253);
	EMIT_OPERATION_ALONE(4, 56);
	int	TOTAL_WORDS = 5;
	int	SECTION_INDEX;

	for (SECTION_INDEX = 0; SECTION_INDEX < 5; SECTION_INDEX++)
		TOTAL_WORDS += BUILDER->SECTIONS[SECTION_INDEX].COUNT;

	uint32_t	*MODULE_WORDS = malloc(TOTAL_WORDS * 4);

	MODULE_WORDS[0] = 0X07230203;
	MODULE_WORDS[1] = 0X00010000;
	MODULE_WORDS[2] = 0;
	MODULE_WORDS[3] = BUILDER->ID_BOUND;
	MODULE_WORDS[4] = 0;

	int	WRITTEN_WORDS = 5;

	for (SECTION_INDEX = 0; SECTION_INDEX < 5; SECTION_INDEX++)
	{
		memcpy(
			MODULE_WORDS + WRITTEN_WORDS,
			BUILDER->SECTIONS[SECTION_INDEX].WORDS,
			BUILDER->SECTIONS[SECTION_INDEX].COUNT * 4
		);
		WRITTEN_WORDS += BUILDER->SECTIONS[SECTION_INDEX].COUNT;
		free(BUILDER->SECTIONS[SECTION_INDEX].WORDS);
	}

	*OUTPUT_WORD_COUNT = WRITTEN_WORDS;

	return (MODULE_WORDS);
}

uint32_t
	KERNEL_PUSH_CONSTANT(KERNEL_BUILDER *BUILDER, int CONSTANT_INDEX)
{
	uint32_t	MEMBER_POINTER = KERNEL_RESULT_OPERATION(
		BUILDER, 4, 65, BUILDER->POINTER_PUSH_UNSIGNED, 2,
		(uint32_t[2]
		){ BUILDER->PUSH_CONSTANT_VARIABLE,
			KERNEL_CONSTANT_UNSIGNED(BUILDER, (uint32_t)CONSTANT_INDEX) }
	);

	return (
		KERNEL_RESULT_OPERATION(
			BUILDER, 4, 61, BUILDER->TYPE_UNSIGNED, 1, &MEMBER_POINTER
		)
	);
}

static uint32_t
	KERNEL_BUILTIN_COMPONENT(
		KERNEL_BUILDER *BUILDER, uint32_t BUILTIN_VARIABLE, int AXIS
	)
{
	uint32_t	VECTOR_ID = KERNEL_RESULT_OPERATION(
		BUILDER, 4, 61, BUILDER->TYPE_UNSIGNED_VECTOR3, 1, &BUILTIN_VARIABLE
	);

	return (
		KERNEL_RESULT_OPERATION(
			BUILDER, 4, 81, BUILDER->TYPE_UNSIGNED, 2,
			(uint32_t[2]){ VECTOR_ID, (uint32_t)AXIS }
		)
	);
}

uint32_t
	KERNEL_GLOBAL_ID(KERNEL_BUILDER *BUILDER, int AXIS)
{
	return (KERNEL_BUILTIN_COMPONENT(BUILDER, BUILDER->GLOBAL_ID, AXIS));
}

uint32_t
	KERNEL_LOCAL_ID(KERNEL_BUILDER *BUILDER, int AXIS)
{
	return (KERNEL_BUILTIN_COMPONENT(BUILDER, BUILDER->LOCAL_ID, AXIS));
}

uint32_t
	KERNEL_WORKGROUP_ID(KERNEL_BUILDER *BUILDER, int AXIS)
{
	return (KERNEL_BUILTIN_COMPONENT(BUILDER, BUILDER->WORKGROUP_ID, AXIS));
}

uint32_t
	KERNEL_LOAD_BUFFER(
		KERNEL_BUILDER *BUILDER, int BUFFER_INDEX, uint32_t ELEMENT_INDEX
	)
{
	uint32_t	ELEMENT_POINTER = KERNEL_RESULT_OPERATION(
		BUILDER, 4, 65, BUILDER->POINTER_UNIFORM_FLOAT, 3,
		(uint32_t[3]){ BUILDER->BUFFER_VARIABLES[BUFFER_INDEX],
			KERNEL_SIGNED_ZERO(BUILDER), ELEMENT_INDEX }
	);

	return (
		KERNEL_RESULT_OPERATION(
			BUILDER, 4, 61, BUILDER->TYPE_FLOAT, 1, &ELEMENT_POINTER
		)
	);
}

void
	KERNEL_STORE_BUFFER(
		KERNEL_BUILDER *BUILDER, int BUFFER_INDEX, uint32_t ELEMENT_INDEX,
		uint32_t STORED_VALUE
	)
{
	uint32_t	ELEMENT_POINTER = KERNEL_RESULT_OPERATION(
		BUILDER, 4, 65, BUILDER->POINTER_UNIFORM_FLOAT, 3,
		(uint32_t[3]){ BUILDER->BUFFER_VARIABLES[BUFFER_INDEX],
			KERNEL_SIGNED_ZERO(BUILDER), ELEMENT_INDEX }
	);
	EMIT_OPERATION(4, 62, ELEMENT_POINTER, STORED_VALUE);
}

uint32_t
	KERNEL_BINARY(
		KERNEL_BUILDER *BUILDER, int OPCODE, uint32_t RESULT_TYPE,
		uint32_t LEFT_OPERAND, uint32_t RIGHT_OPERAND
	)
{
	return (
		KERNEL_RESULT_OPERATION(
			BUILDER, 4, OPCODE, RESULT_TYPE, 2,
			(uint32_t[2]){ LEFT_OPERAND, RIGHT_OPERAND }
		)
	);
}

uint32_t
	KERNEL_VARIABLE_UNSIGNED(KERNEL_BUILDER *BUILDER)
{
	return (
		KERNEL_RESULT_OPERATION(
			BUILDER, 3, 59, BUILDER->POINTER_LOCAL_UNSIGNED, 1,
			(uint32_t[1]){ 7 }
		)
	);
}

uint32_t
	KERNEL_VARIABLE_FLOAT(KERNEL_BUILDER *BUILDER)
{
	return (
		KERNEL_RESULT_OPERATION(
			BUILDER, 3, 59, BUILDER->POINTER_LOCAL_FLOAT, 1, (uint32_t[1]){ 7 }
		)
	);
}

uint32_t
	KERNEL_LOAD(
		KERNEL_BUILDER *BUILDER, uint32_t RESULT_TYPE, uint32_t VARIABLE_POINTER
	)
{
	return (
		KERNEL_RESULT_OPERATION(
			BUILDER, 4, 61, RESULT_TYPE, 1, &VARIABLE_POINTER
		)
	);
}

void
	KERNEL_STORE(
		KERNEL_BUILDER *BUILDER, uint32_t VARIABLE_POINTER,
		uint32_t STORED_VALUE
	)
{
	EMIT_OPERATION(4, 62, VARIABLE_POINTER, STORED_VALUE);
}

uint32_t
	KERNEL_NEW_LABEL(KERNEL_BUILDER *BUILDER)
{
	return (KERNEL_NEW_ID(BUILDER));
}

void
	KERNEL_BIND_LABEL(KERNEL_BUILDER *BUILDER, uint32_t LABEL_ID)
{
	EMIT_OPERATION(4, 248, LABEL_ID);
}

void
	KERNEL_BRANCH(KERNEL_BUILDER *BUILDER, uint32_t TARGET_LABEL)
{
	EMIT_OPERATION(4, 249, TARGET_LABEL);
}

void
	KERNEL_IF(
		KERNEL_BUILDER *BUILDER, uint32_t CONDITION, uint32_t *MERGE_LABEL
	)
{
	uint32_t	BODY_LABEL = KERNEL_NEW_LABEL(BUILDER);

	*MERGE_LABEL = KERNEL_NEW_LABEL(BUILDER);
	EMIT_OPERATION(4, 247, *MERGE_LABEL, 0);
	EMIT_OPERATION(4, 250, CONDITION, BODY_LABEL, *MERGE_LABEL);
	KERNEL_BIND_LABEL(BUILDER, BODY_LABEL);
}

void
	KERNEL_END_IF(KERNEL_BUILDER *BUILDER, uint32_t MERGE_LABEL)
{
	KERNEL_BRANCH(BUILDER, MERGE_LABEL);
	KERNEL_BIND_LABEL(BUILDER, MERGE_LABEL);
}

KERNEL_LOOP
	KERNEL_FOR(
		KERNEL_BUILDER *BUILDER, uint32_t START_VALUE, uint32_t END_VALUE
	)
{
	KERNEL_LOOP	LOOP_STATE;

	LOOP_STATE.VARIABLE = KERNEL_VARIABLE_UNSIGNED(BUILDER);
	KERNEL_STORE(BUILDER, LOOP_STATE.VARIABLE, START_VALUE);
	LOOP_STATE.HEADER_LABEL = KERNEL_NEW_LABEL(BUILDER);
	LOOP_STATE.MERGE_LABEL = KERNEL_NEW_LABEL(BUILDER);
	LOOP_STATE.CONTINUE_LABEL = KERNEL_NEW_LABEL(BUILDER);
	LOOP_STATE.BODY_LABEL = KERNEL_NEW_LABEL(BUILDER);

	uint32_t	CHECK_LABEL = KERNEL_NEW_LABEL(BUILDER);

	KERNEL_BRANCH(BUILDER, LOOP_STATE.HEADER_LABEL);
	KERNEL_BIND_LABEL(BUILDER, LOOP_STATE.HEADER_LABEL);
	EMIT_OPERATION(
		4, 246, LOOP_STATE.MERGE_LABEL, LOOP_STATE.CONTINUE_LABEL, 0
	);
	KERNEL_BRANCH(BUILDER, CHECK_LABEL);
	KERNEL_BIND_LABEL(BUILDER, CHECK_LABEL);

	uint32_t	COUNTER_VALUE =
		KERNEL_LOAD(BUILDER, BUILDER->TYPE_UNSIGNED, LOOP_STATE.VARIABLE);
	uint32_t	LOOP_CONDITION = KERNEL_BINARY(
		BUILDER, SPIRV_UNSIGNED_LESS_THAN, BUILDER->TYPE_BOOLEAN, COUNTER_VALUE,
		END_VALUE
	);
	EMIT_OPERATION(
		4, 250, LOOP_CONDITION, LOOP_STATE.BODY_LABEL, LOOP_STATE.MERGE_LABEL
	);
	KERNEL_BIND_LABEL(BUILDER, LOOP_STATE.BODY_LABEL);

	return (LOOP_STATE);
}

uint32_t
	KERNEL_FOR_VARIABLE(KERNEL_BUILDER *BUILDER, KERNEL_LOOP *LOOP_STATE)
{
	return (KERNEL_LOAD(BUILDER, BUILDER->TYPE_UNSIGNED, LOOP_STATE->VARIABLE));
}

void
	KERNEL_FOR_END(
		KERNEL_BUILDER *BUILDER, KERNEL_LOOP *LOOP_STATE, uint32_t STEP_VALUE
	)
{
	KERNEL_BRANCH(BUILDER, LOOP_STATE->CONTINUE_LABEL);
	KERNEL_BIND_LABEL(BUILDER, LOOP_STATE->CONTINUE_LABEL);

	uint32_t	COUNTER_VALUE =
		KERNEL_LOAD(BUILDER, BUILDER->TYPE_UNSIGNED, LOOP_STATE->VARIABLE);

	KERNEL_STORE(
		BUILDER, LOOP_STATE->VARIABLE,
		KERNEL_BINARY(
			BUILDER, SPIRV_INTEGER_ADD, BUILDER->TYPE_UNSIGNED, COUNTER_VALUE,
			STEP_VALUE
		)
	);
	KERNEL_BRANCH(BUILDER, LOOP_STATE->HEADER_LABEL);
	KERNEL_BIND_LABEL(BUILDER, LOOP_STATE->MERGE_LABEL);
}

uint32_t
	KERNEL_SHARED_ARRAY(KERNEL_BUILDER *BUILDER, int ELEMENT_COUNT)
{
	uint32_t	LENGTH_CONSTANT =
		KERNEL_CONSTANT_UNSIGNED(BUILDER, (uint32_t)ELEMENT_COUNT);
	uint32_t	ARRAY_TYPE = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 28, 0, 2,
		(uint32_t[2]){ BUILDER->TYPE_FLOAT, LENGTH_CONSTANT }
	);
	uint32_t	POINTER_TYPE = KERNEL_RESULT_OPERATION(
		BUILDER, 2, 32, 0, 2, (uint32_t[2]){ 4, ARRAY_TYPE }
	);

	if (!BUILDER->POINTER_WORKGROUP_FLOAT)
		BUILDER->POINTER_WORKGROUP_FLOAT = KERNEL_RESULT_OPERATION(
			BUILDER, 2, 32, 0, 2, (uint32_t[2]){ 4, BUILDER->TYPE_FLOAT }
		);

	return (
		KERNEL_RESULT_OPERATION(
			BUILDER, 2, 59, POINTER_TYPE, 1, (uint32_t[1]){ 4 }
		)
	);
}

uint32_t
	KERNEL_SHARED_POINTER(
		KERNEL_BUILDER *BUILDER, uint32_t SHARED_ARRAY, uint32_t ELEMENT_INDEX
	)
{
	return (
		KERNEL_RESULT_OPERATION(
			BUILDER, 4, 65, BUILDER->POINTER_WORKGROUP_FLOAT, 2,
			(uint32_t[2]){ SHARED_ARRAY, ELEMENT_INDEX }
		)
	);
}

void
	KERNEL_BARRIER(KERNEL_BUILDER *BUILDER)
{
	EMIT_OPERATION(
		4, 224, KERNEL_CONSTANT_UNSIGNED(BUILDER, 2),
		KERNEL_CONSTANT_UNSIGNED(BUILDER, 2),
		KERNEL_CONSTANT_UNSIGNED(BUILDER, 0X108)
	);
}

typedef void *(*GET_INSTANCE_PROC_ADDRESS)(VkInstance, const char *);

struct GPU
{
	void								*LIBRARY;
	GET_INSTANCE_PROC_ADDRESS			GET_PROCEDURE_ADDRESS;
	VkInstance							INSTANCE;
	VkPhysicalDevice					PHYSICAL_DEVICE;
	VkDevice							LOGICAL_DEVICE;
	VkQueue								QUEUE;
	uint32_t							QUEUE_FAMILY;
	VkCommandPool						COMMAND_POOL;
	VkCommandBuffer						COMMAND_BUFFER;
	VkDescriptorPool					DESCRIPTOR_POOL;
	VkPhysicalDevicePropertiesX			PROPERTIES;
	VkPhysicalDeviceMemoryProperties	MEMORY_PROPERTIES;
	GPU_BUFFER							*STAGING_BUFFER;
	int									RECORDING;
};

struct GPU_BUFFER
{
	VkBuffer		BUFFER;
	VkDeviceMemory	MEMORY;
	uint64_t		BYTE_SIZE;
	void			*MAPPED_MEMORY;
};

struct GPU_PIPELINE
{
	VkShaderModule			SHADER_MODULE;
	VkDescriptorSetLayout	DESCRIPTOR_SET_LAYOUT;
	VkPipelineLayout		PIPELINE_LAYOUT;
	VkPipeline				PIPELINE;
	int						BUFFER_COUNT;
	int						PUSH_CONSTANT_COUNT;
};

#define VULKAN_FUNCTION(FUNCTION_NAME) \
	((PFN_##FUNCTION_NAME \
	)GPU_STATE->GET_PROCEDURE_ADDRESS(GPU_STATE->INSTANCE, #FUNCTION_NAME))

typedef VkResult (*PFN_vkCreateInstance)(
	const VkInstanceCreateInfo *, const void *, VkInstance *
);
typedef VkResult (*PFN_vkEnumeratePhysicalDevices)(
	VkInstance, uint32_t *, VkPhysicalDevice *
);
typedef void (*PFN_vkGetPhysicalDeviceProperties)(
	VkPhysicalDevice, VkPhysicalDevicePropertiesX *
);
typedef void (*PFN_vkGetPhysicalDeviceMemoryProperties)(
	VkPhysicalDevice, VkPhysicalDeviceMemoryProperties *
);
typedef void (*PFN_vkGetPhysicalDeviceQueueFamilyProperties)(
	VkPhysicalDevice, uint32_t *, VkQueueFamilyProperties *
);
typedef VkResult (*PFN_vkCreateDevice)(
	VkPhysicalDevice, const VkDeviceCreateInfo *, const void *, VkDevice *
);
typedef void (*PFN_vkGetDeviceQueue)(VkDevice, uint32_t, uint32_t, VkQueue *);
typedef VkResult (*PFN_vkCreateBuffer)(
	VkDevice, const VkBufferCreateInfo *, const void *, VkBuffer *
);
typedef void (*PFN_vkGetBufferMemoryRequirements)(
	VkDevice, VkBuffer, VkMemoryRequirements *
);
typedef VkResult (*PFN_vkAllocateMemory)(
	VkDevice, const VkMemoryAllocateInfo *, const void *, VkDeviceMemory *
);
typedef VkResult (*PFN_vkBindBufferMemory)(
	VkDevice, VkBuffer, VkDeviceMemory, VkDeviceSize
);
typedef VkResult (*PFN_vkMapMemory)(
	VkDevice, VkDeviceMemory, VkDeviceSize, VkDeviceSize, VkFlags, void **
);
typedef void (*PFN_vkDestroyBuffer)(VkDevice, VkBuffer, const void *);
typedef void (*PFN_vkFreeMemory)(VkDevice, VkDeviceMemory, const void *);
typedef VkResult (*PFN_vkCreateShaderModule)(
	VkDevice, const VkShaderModuleCreateInfo *, const void *, VkShaderModule *
);
typedef VkResult (*PFN_vkCreateDescriptorSetLayout)(
	VkDevice, const VkDescriptorSetLayoutCreateInfo *, const void *,
	VkDescriptorSetLayout *
);
typedef VkResult (*PFN_vkCreatePipelineLayout)(
	VkDevice, const VkPipelineLayoutCreateInfo *, const void *,
	VkPipelineLayout *
);
typedef VkResult (*PFN_vkCreateComputePipelines)(
	VkDevice, VkPipelineCache, uint32_t, const VkComputePipelineCreateInfo *,
	const void *, VkPipeline *
);
typedef VkResult (*PFN_vkCreateDescriptorPool)(
	VkDevice, const VkDescriptorPoolCreateInfo *, const void *,
	VkDescriptorPool *
);
typedef VkResult (*PFN_vkResetDescriptorPool)(
	VkDevice, VkDescriptorPool, VkFlags
);
typedef VkResult (*PFN_vkAllocateDescriptorSets)(
	VkDevice, const VkDescriptorSetAllocateInfo *, VkDescriptorSet *
);
typedef void (*PFN_vkUpdateDescriptorSets)(
	VkDevice, uint32_t, const VkWriteDescriptorSet *, uint32_t, const void *
);
typedef VkResult (*PFN_vkCreateCommandPool)(
	VkDevice, const VkCommandPoolCreateInfo *, const void *, VkCommandPool *
);
typedef VkResult (*PFN_vkAllocateCommandBuffers)(
	VkDevice, const VkCommandBufferAllocateInfo *, VkCommandBuffer *
);
typedef VkResult (*PFN_vkBeginCommandBuffer)(
	VkCommandBuffer, const VkCommandBufferBeginInfo *
);
typedef VkResult (*PFN_vkEndCommandBuffer)(VkCommandBuffer);
typedef VkResult (*PFN_vkResetCommandBuffer)(VkCommandBuffer, VkFlags);
typedef void (*PFN_vkCmdBindPipeline)(VkCommandBuffer, int32_t, VkPipeline);
typedef void (*PFN_vkCmdBindDescriptorSets)(
	VkCommandBuffer, int32_t, VkPipelineLayout, uint32_t, uint32_t,
	const VkDescriptorSet *, uint32_t, const uint32_t *
);
typedef void (*PFN_vkCmdPushConstants)(
	VkCommandBuffer, VkPipelineLayout, VkFlags, uint32_t, uint32_t, const void *
);
typedef void (*PFN_vkCmdDispatch)(
	VkCommandBuffer, uint32_t, uint32_t, uint32_t
);
typedef void (*PFN_vkCmdPipelineBarrier)(
	VkCommandBuffer, VkFlags, VkFlags, VkFlags, uint32_t,
	const VkMemoryBarrier *, uint32_t, const void *, uint32_t, const void *
);
typedef void (*PFN_vkCmdCopyBuffer)(
	VkCommandBuffer, VkBuffer, VkBuffer, uint32_t, const VkBufferCopy *
);
typedef VkResult (*PFN_vkQueueSubmit)(
	VkQueue, uint32_t, const VkSubmitInfo *, VkFence
);
typedef VkResult (*PFN_vkQueueWaitIdle)(VkQueue);
typedef VkResult (*PFN_vkDeviceWaitIdle)(VkDevice);
typedef void (*PFN_vkDestroyDevice)(VkDevice, const void *);
typedef void (*PFN_vkDestroyInstance)(VkInstance, const void *);

static void
	*OPEN_VULKAN_LIBRARY(void)
{
#ifdef _WIN32
	return ((void *)LoadLibraryA("vulkan-1.dll"));
#else
	void	*LIBRARY_HANDLE = dlopen("libvulkan.so.1", RTLD_NOW);

	if (LIBRARY_HANDLE)
		return (LIBRARY_HANDLE);

	return (dlopen("libvulkan.so", RTLD_NOW));
#endif
}

static void
	*LIBRARY_SYMBOL(void *LIBRARY_HANDLE, const char *SYMBOL_NAME)
{
#ifdef _WIN32
	return ((void *)GetProcAddress((HMODULE)LIBRARY_HANDLE, SYMBOL_NAME));
#else
	return (dlsym(LIBRARY_HANDLE, SYMBOL_NAME));
#endif
}

static int
	FIND_MEMORY_TYPE(
		GPU *GPU_STATE, uint32_t ALLOWED_TYPE_BITS, VkFlags REQUIRED_FLAGS
	)
{
	uint32_t	TYPE_INDEX;

	for (
		TYPE_INDEX = 0;
		TYPE_INDEX < GPU_STATE->MEMORY_PROPERTIES.memoryTypeCount;
		TYPE_INDEX++
	)
		if (
			(ALLOWED_TYPE_BITS & ((unsigned int)1 << TYPE_INDEX)) &&
			(GPU_STATE->MEMORY_PROPERTIES.memoryTypes[TYPE_INDEX]
				.propertyFlags &
				REQUIRED_FLAGS) == REQUIRED_FLAGS
		)
			return ((int)TYPE_INDEX);

	return (-1);
}

static GPU_BUFFER
	*NEW_GPU_BUFFER(GPU *GPU_STATE, uint64_t BYTE_COUNT, int HOST_VISIBLE)
{
	GPU_BUFFER			*NEW_BUFFER = calloc(1, sizeof *NEW_BUFFER);
	VkBufferCreateInfo	BUFFER_INFO = {
		VKS_BUFFER_CREATE_INFO, NULL, 0, BYTE_COUNT,
		VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT |
			VK_BUFFER_USAGE_TRANSFER_DST_BIT,
		0, 0, NULL
	};

	if (
		VULKAN_FUNCTION(vkCreateBuffer)
		(GPU_STATE->LOGICAL_DEVICE, &BUFFER_INFO, NULL, &NEW_BUFFER->BUFFER)
	)
	{
		free(NEW_BUFFER);
		return (NULL);
	}

	VkMemoryRequirements	REQUIREMENTS;

	VULKAN_FUNCTION(vkGetBufferMemoryRequirements)
	(GPU_STATE->LOGICAL_DEVICE, NEW_BUFFER->BUFFER, &REQUIREMENTS);

	int	MEMORY_TYPE_INDEX;

	if (HOST_VISIBLE)
		MEMORY_TYPE_INDEX = FIND_MEMORY_TYPE(
			GPU_STATE, REQUIREMENTS.memoryTypeBits,
			VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
				VK_MEMORY_PROPERTY_HOST_COHERENT_BIT |
				VK_MEMORY_PROPERTY_HOST_CACHED_BIT
		);
	else
		MEMORY_TYPE_INDEX = FIND_MEMORY_TYPE(
			GPU_STATE, REQUIREMENTS.memoryTypeBits,
			VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT
		);

	if (MEMORY_TYPE_INDEX < 0 && HOST_VISIBLE)
		MEMORY_TYPE_INDEX = FIND_MEMORY_TYPE(
			GPU_STATE, REQUIREMENTS.memoryTypeBits,
			VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
				VK_MEMORY_PROPERTY_HOST_COHERENT_BIT
		);

	if (MEMORY_TYPE_INDEX < 0)
		MEMORY_TYPE_INDEX =
			FIND_MEMORY_TYPE(GPU_STATE, REQUIREMENTS.memoryTypeBits, 0);

	VkMemoryAllocateInfo	ALLOCATE_INFO = {
		VKS_MEMORY_ALLOCATE_INFO, NULL, REQUIREMENTS.size,
		(uint32_t)MEMORY_TYPE_INDEX
	};

	if (
		MEMORY_TYPE_INDEX < 0 ||
		VULKAN_FUNCTION(vkAllocateMemory)
		(GPU_STATE->LOGICAL_DEVICE, &ALLOCATE_INFO, NULL, &NEW_BUFFER->MEMORY)
	)
	{
		VULKAN_FUNCTION(vkDestroyBuffer)
		(GPU_STATE->LOGICAL_DEVICE, NEW_BUFFER->BUFFER, NULL);
		free(NEW_BUFFER);
		return (NULL);
	}

	VULKAN_FUNCTION(vkBindBufferMemory)
	(GPU_STATE->LOGICAL_DEVICE, NEW_BUFFER->BUFFER, NEW_BUFFER->MEMORY, 0);
	NEW_BUFFER->BYTE_SIZE = BYTE_COUNT;

	if (HOST_VISIBLE)
		VULKAN_FUNCTION(vkMapMemory)
		(GPU_STATE->LOGICAL_DEVICE, NEW_BUFFER->MEMORY, 0, BYTE_COUNT, 0,
			&NEW_BUFFER->MAPPED_MEMORY);

	return (NEW_BUFFER);
}

GPU
	*GPU_OPEN(int VERBOSE)
{
	GPU	*GPU_STATE = calloc(1, sizeof *GPU_STATE);

	GPU_STATE->LIBRARY = OPEN_VULKAN_LIBRARY();

	if (!GPU_STATE->LIBRARY)
	{
		if (VERBOSE)
			printf(
				"gpu: no Vulkan driver found (vulkan-1.dll / libvulkan.so.1)\n"
			);

		free(GPU_STATE);
		return (NULL);
	}

	GPU_STATE->GET_PROCEDURE_ADDRESS = (GET_INSTANCE_PROC_ADDRESS
	)LIBRARY_SYMBOL(GPU_STATE->LIBRARY, "vkGetInstanceProcAddr");

	if (!GPU_STATE->GET_PROCEDURE_ADDRESS)
	{
		free(GPU_STATE);
		return (NULL);
	}

	VkApplicationInfo		APPLICATION_INFO = {
		VKS_APPLICATION_INFO, NULL, "Code", 1, "Code", 1,
		((unsigned int)1 << 22) | ((unsigned int)1 << 12)
	};
	VkInstanceCreateInfo	INSTANCE_INFO = {
		VKS_INSTANCE_CREATE_INFO, NULL, 0, &APPLICATION_INFO, 0, NULL, 0, NULL
	};
	PFN_vkCreateInstance	CREATE_INSTANCE = (PFN_vkCreateInstance
	)GPU_STATE->GET_PROCEDURE_ADDRESS(NULL, "vkCreateInstance");
	VkResult				RESULT;

	if (CREATE_INSTANCE)
		RESULT = CREATE_INSTANCE(&INSTANCE_INFO, NULL, &GPU_STATE->INSTANCE);
	else
		RESULT = -99;

	if (RESULT)
	{
		if (VERBOSE)
			printf("gpu: Vulkan instance failed (code %d)\n", (int)RESULT);

		free(GPU_STATE);
		return (NULL);
	}

	uint32_t	DEVICE_COUNT = 0;

	VULKAN_FUNCTION(vkEnumeratePhysicalDevices)
	(GPU_STATE->INSTANCE, &DEVICE_COUNT, NULL);

	if (!DEVICE_COUNT)
	{
		if (VERBOSE)
			printf("gpu: no Vulkan devices\n");

		free(GPU_STATE);
		return (NULL);
	}

	VkPhysicalDevice	PHYSICAL_DEVICES[16];

	if (DEVICE_COUNT > 16)
		DEVICE_COUNT = 16;

	VULKAN_FUNCTION(vkEnumeratePhysicalDevices)
	(GPU_STATE->INSTANCE, &DEVICE_COUNT, PHYSICAL_DEVICES);

	int			BEST_DEVICE = -1;
	int			BEST_SCORE = -1;
	const char	*REQUESTED_DEVICE = getenv("CODE_GPU");
	uint32_t	INDEX;

	for (INDEX = 0; INDEX < DEVICE_COUNT; INDEX++)
	{
		VkPhysicalDevicePropertiesX	DEVICE_PROPERTIES;

		VULKAN_FUNCTION(vkGetPhysicalDeviceProperties)
		(PHYSICAL_DEVICES[INDEX], &DEVICE_PROPERTIES);

		static const char	*TYPE_NAMES[5] = {
			"other", "integrated", "discrete", "virtual", "cpu"
		};

		if (VERBOSE)
			printf(
				"gpu %u: %s (%s)\n", INDEX, DEVICE_PROPERTIES.deviceName,
				DEVICE_PROPERTIES.deviceType >= 0 &&
						DEVICE_PROPERTIES.deviceType <= 4
					? TYPE_NAMES[DEVICE_PROPERTIES.deviceType]
					: "?"
			);

		int	DEVICE_SCORE;

		if (DEVICE_PROPERTIES.deviceType == 2)
			DEVICE_SCORE = 4;
		else if (DEVICE_PROPERTIES.deviceType == 1)
			DEVICE_SCORE = 3;
		else if (DEVICE_PROPERTIES.deviceType == 3)
			DEVICE_SCORE = 2;
		else
			DEVICE_SCORE = 1;

		if (REQUESTED_DEVICE && atoi(REQUESTED_DEVICE) == (int)INDEX)
			DEVICE_SCORE = 100;

		if (DEVICE_SCORE > BEST_SCORE)
		{
			BEST_SCORE = DEVICE_SCORE;
			BEST_DEVICE = (int)INDEX;
		}
	}

	GPU_STATE->PHYSICAL_DEVICE = PHYSICAL_DEVICES[BEST_DEVICE];
	VULKAN_FUNCTION(vkGetPhysicalDeviceProperties)
	(GPU_STATE->PHYSICAL_DEVICE, &GPU_STATE->PROPERTIES);
	VULKAN_FUNCTION(vkGetPhysicalDeviceMemoryProperties)
	(GPU_STATE->PHYSICAL_DEVICE, &GPU_STATE->MEMORY_PROPERTIES);

	VkQueueFamilyProperties	QUEUE_FAMILIES[32];
	uint32_t				QUEUE_FAMILY_COUNT = 32;

	VULKAN_FUNCTION(vkGetPhysicalDeviceQueueFamilyProperties)
	(GPU_STATE->PHYSICAL_DEVICE, &QUEUE_FAMILY_COUNT, QUEUE_FAMILIES);
	GPU_STATE->QUEUE_FAMILY = (unsigned int)0XFFFFFFFF;

	for (INDEX = 0; INDEX < QUEUE_FAMILY_COUNT; INDEX++)
		if (QUEUE_FAMILIES[INDEX].queueFlags & VK_QUEUE_COMPUTE_BIT)
		{
			GPU_STATE->QUEUE_FAMILY = INDEX;
			break ;
		}

	if (GPU_STATE->QUEUE_FAMILY == (unsigned int)0XFFFFFFFF)
	{
		free(GPU_STATE);
		return (NULL);
	}

	float					QUEUE_PRIORITY = (float)1.0;
	VkDeviceQueueCreateInfo	QUEUE_INFO = {
		VKS_DEVICE_QUEUE_CREATE_INFO, NULL, 0, GPU_STATE->QUEUE_FAMILY, 1,
		&QUEUE_PRIORITY
	};
	VkDeviceCreateInfo		DEVICE_INFO = {
		VKS_DEVICE_CREATE_INFO, NULL, 0, 1, &QUEUE_INFO, 0, NULL, 0, NULL, NULL
	};

	RESULT = VULKAN_FUNCTION(vkCreateDevice)(
		GPU_STATE->PHYSICAL_DEVICE, &DEVICE_INFO, NULL,
		&GPU_STATE->LOGICAL_DEVICE
	);

	if (RESULT)
	{
		if (VERBOSE)
			printf("gpu: device failed (code %d)\n", (int)RESULT);

		free(GPU_STATE);
		return (NULL);
	}

	VULKAN_FUNCTION(vkGetDeviceQueue)
	(GPU_STATE->LOGICAL_DEVICE, GPU_STATE->QUEUE_FAMILY, 0, &GPU_STATE->QUEUE);

	VkCommandPoolCreateInfo	POOL_INFO = {
		VKS_COMMAND_POOL_CREATE_INFO, NULL,
		VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT, GPU_STATE->QUEUE_FAMILY
	};

	VULKAN_FUNCTION(vkCreateCommandPool)
	(GPU_STATE->LOGICAL_DEVICE, &POOL_INFO, NULL, &GPU_STATE->COMMAND_POOL);

	VkCommandBufferAllocateInfo	COMMAND_ALLOCATE_INFO = {
		VKS_COMMAND_BUFFER_ALLOCATE_INFO, NULL, GPU_STATE->COMMAND_POOL, 0, 1
	};

	VULKAN_FUNCTION(vkAllocateCommandBuffers)
	(GPU_STATE->LOGICAL_DEVICE, &COMMAND_ALLOCATE_INFO,
		&GPU_STATE->COMMAND_BUFFER);

	VkDescriptorPoolSize		POOL_SIZE = {
		VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 65536
	};
	VkDescriptorPoolCreateInfo	DESCRIPTOR_POOL_INFO = {
		VKS_DESCRIPTOR_POOL_CREATE_INFO, NULL, 0, 8192, 1, &POOL_SIZE
	};

	VULKAN_FUNCTION(vkCreateDescriptorPool)
	(GPU_STATE->LOGICAL_DEVICE, &DESCRIPTOR_POOL_INFO, NULL,
		&GPU_STATE->DESCRIPTOR_POOL);
	GPU_STATE->STAGING_BUFFER =
		NEW_GPU_BUFFER(GPU_STATE, (unsigned int)64 << 20, 1);

	if (!GPU_STATE->STAGING_BUFFER)
	{
		if (VERBOSE)
			printf("gpu: staging buffer failed\n");

		free(GPU_STATE);
		return (NULL);
	}

	return (GPU_STATE);
}

const char
	*GPU_NAME(GPU *GPU_STATE)
{
	return (GPU_STATE->PROPERTIES.deviceName);
}

int
	GPU_IS_DISCRETE(GPU *GPU_STATE)
{
	return (GPU_STATE->PROPERTIES.deviceType == 2);
}

uint64_t
	GPU_VIDEO_MEMORY(GPU *GPU_STATE)
{
	uint64_t	TOTAL_BYTES = 0;
	uint32_t	HEAP_INDEX;

	for (
		HEAP_INDEX = 0;
		HEAP_INDEX < GPU_STATE->MEMORY_PROPERTIES.memoryHeapCount;
		HEAP_INDEX++
	)
		if (GPU_STATE->MEMORY_PROPERTIES.memoryHeaps[HEAP_INDEX].flags & 1)
			TOTAL_BYTES +=
				GPU_STATE->MEMORY_PROPERTIES.memoryHeaps[HEAP_INDEX].size;

	return (TOTAL_BYTES);
}

GPU_BUFFER
	*GPU_NEW_BUFFER(GPU *GPU_STATE, uint64_t BYTE_COUNT)
{
	return (NEW_GPU_BUFFER(GPU_STATE, BYTE_COUNT, 0));
}

void
	GPU_FREE_BUFFER(GPU *GPU_STATE, GPU_BUFFER *DEVICE_BUFFER)
{
	if (!DEVICE_BUFFER)
		return ;

	VULKAN_FUNCTION(vkDestroyBuffer)
	(GPU_STATE->LOGICAL_DEVICE, DEVICE_BUFFER->BUFFER, NULL);
	VULKAN_FUNCTION(vkFreeMemory)
	(GPU_STATE->LOGICAL_DEVICE, DEVICE_BUFFER->MEMORY, NULL);
	free(DEVICE_BUFFER);
}

static void
	BEGIN_COMMAND_BUFFER(GPU *GPU_STATE)
{
	VULKAN_FUNCTION(vkResetCommandBuffer)(GPU_STATE->COMMAND_BUFFER, 0);

	VkCommandBufferBeginInfo	BEGIN_INFO = {
		VKS_COMMAND_BUFFER_BEGIN_INFO, NULL,
		VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT, NULL
	};

	VULKAN_FUNCTION(vkBeginCommandBuffer)
	(GPU_STATE->COMMAND_BUFFER, &BEGIN_INFO);
}

static int
	SUBMIT_AND_WAIT(GPU *GPU_STATE)
{
	VULKAN_FUNCTION(vkEndCommandBuffer)(GPU_STATE->COMMAND_BUFFER);

	VkSubmitInfo	SUBMIT_INFO = {
		VKS_SUBMIT_INFO, NULL, 0, NULL, NULL, 1, &GPU_STATE->COMMAND_BUFFER, 0,
		NULL
	};

	if (VULKAN_FUNCTION(vkQueueSubmit)(GPU_STATE->QUEUE, 1, &SUBMIT_INFO, 0))
		return (-1);

	if (VULKAN_FUNCTION(vkQueueWaitIdle)(GPU_STATE->QUEUE))
		return (-1);

	return (0);
}

static void
	RECORD_MEMORY_BARRIER(GPU *GPU_STATE)
{
	VkMemoryBarrier	BARRIER_INFO = {
		VKS_MEMORY_BARRIER, NULL,
		VK_ACCESS_SHADER_WRITE_BIT | VK_ACCESS_TRANSFER_WRITE_BIT,
		VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT |
			VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT
	};

	VULKAN_FUNCTION(vkCmdPipelineBarrier)
	(GPU_STATE->COMMAND_BUFFER,
		VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_TRANSFER_BIT,
	VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_TRANSFER_BIT, 0,
		1, &BARRIER_INFO, 0, NULL, 0, NULL);
}

int
	GPU_UPLOAD(
		GPU *GPU_STATE, GPU_BUFFER *DEVICE_BUFFER, const void *SOURCE,
		uint64_t BYTE_COUNT, uint64_t OFFSET
	)
{
	uint64_t	COPIED_BYTES = 0;

	while (COPIED_BYTES < BYTE_COUNT)
	{
		uint64_t	CHUNK_BYTES;

		if (BYTE_COUNT - COPIED_BYTES < GPU_STATE->STAGING_BUFFER->BYTE_SIZE)
			CHUNK_BYTES = BYTE_COUNT - COPIED_BYTES;
		else
			CHUNK_BYTES = GPU_STATE->STAGING_BUFFER->BYTE_SIZE;

		memcpy(
			GPU_STATE->STAGING_BUFFER->MAPPED_MEMORY,
			(const uint8_t *)SOURCE + COPIED_BYTES, CHUNK_BYTES
		);
		BEGIN_COMMAND_BUFFER(GPU_STATE);

		VkBufferCopy	COPY_REGION = { 0, OFFSET + COPIED_BYTES, CHUNK_BYTES };

		VULKAN_FUNCTION(vkCmdCopyBuffer)
		(GPU_STATE->COMMAND_BUFFER, GPU_STATE->STAGING_BUFFER->BUFFER,
			DEVICE_BUFFER->BUFFER, 1, &COPY_REGION);

		if (SUBMIT_AND_WAIT(GPU_STATE))
			return (-1);

		COPIED_BYTES += CHUNK_BYTES;
	}

	return (0);
}

int
	GPU_DOWNLOAD(
		GPU *GPU_STATE, GPU_BUFFER *DEVICE_BUFFER, void *DESTINATION,
		uint64_t BYTE_COUNT, uint64_t OFFSET
	)
{
	uint64_t	COPIED_BYTES = 0;

	while (COPIED_BYTES < BYTE_COUNT)
	{
		uint64_t	CHUNK_BYTES;

		if (BYTE_COUNT - COPIED_BYTES < GPU_STATE->STAGING_BUFFER->BYTE_SIZE)
			CHUNK_BYTES = BYTE_COUNT - COPIED_BYTES;
		else
			CHUNK_BYTES = GPU_STATE->STAGING_BUFFER->BYTE_SIZE;

		BEGIN_COMMAND_BUFFER(GPU_STATE);

		VkBufferCopy	COPY_REGION = { OFFSET + COPIED_BYTES, 0, CHUNK_BYTES };

		VULKAN_FUNCTION(vkCmdCopyBuffer)
		(GPU_STATE->COMMAND_BUFFER, DEVICE_BUFFER->BUFFER,
			GPU_STATE->STAGING_BUFFER->BUFFER, 1, &COPY_REGION);

		if (SUBMIT_AND_WAIT(GPU_STATE))
			return (-1);

		memcpy(
			(uint8_t *)DESTINATION + COPIED_BYTES,
			GPU_STATE->STAGING_BUFFER->MAPPED_MEMORY, CHUNK_BYTES
		);
		COPIED_BYTES += CHUNK_BYTES;
	}

	return (0);
}

GPU_PIPELINE
	*GPU_NEW_PIPELINE(
		GPU *GPU_STATE, const uint32_t *SPIRV_WORDS, int WORD_COUNT,
		int BUFFER_COUNT, int PUSH_CONSTANT_COUNT
	)
{
	GPU_PIPELINE	*PIPELINE_STATE = calloc(1, sizeof *PIPELINE_STATE);

	PIPELINE_STATE->BUFFER_COUNT = BUFFER_COUNT;
	PIPELINE_STATE->PUSH_CONSTANT_COUNT = PUSH_CONSTANT_COUNT;

	VkShaderModuleCreateInfo	SHADER_INFO = {
		VKS_SHADER_MODULE_CREATE_INFO, NULL, 0, (size_t)WORD_COUNT * 4,
		SPIRV_WORDS
	};

	if (
		VULKAN_FUNCTION(vkCreateShaderModule)
		(GPU_STATE->LOGICAL_DEVICE, &SHADER_INFO, NULL,
			&PIPELINE_STATE->SHADER_MODULE)
	)
	{
		free(PIPELINE_STATE);
		return (NULL);
	}

	VkDescriptorSetLayoutBinding	BINDINGS[16];
	int								BINDING_INDEX;

	for (BINDING_INDEX = 0; BINDING_INDEX < BUFFER_COUNT; BINDING_INDEX++)
	{
		BINDINGS[BINDING_INDEX].binding = (uint32_t)BINDING_INDEX;
		BINDINGS[BINDING_INDEX].descriptorType =
			VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
		BINDINGS[BINDING_INDEX].descriptorCount = 1;
		BINDINGS[BINDING_INDEX].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
		BINDINGS[BINDING_INDEX].pImmutableSamplers = NULL;
	}

	VkDescriptorSetLayoutCreateInfo	SET_LAYOUT_INFO = {
		VKS_DESCRIPTOR_SET_LAYOUT_CREATE_INFO, NULL, 0, (uint32_t)BUFFER_COUNT,
		BINDINGS
	};

	VULKAN_FUNCTION(vkCreateDescriptorSetLayout)
	(GPU_STATE->LOGICAL_DEVICE, &SET_LAYOUT_INFO, NULL,
		&PIPELINE_STATE->DESCRIPTOR_SET_LAYOUT);

	VkPushConstantRange			PUSH_RANGE = {
		VK_SHADER_STAGE_COMPUTE_BIT, 0, (uint32_t)(PUSH_CONSTANT_COUNT * 4)
	};
	VkPipelineLayoutCreateInfo	PIPELINE_LAYOUT_INFO = {
		VKS_PIPELINE_LAYOUT_CREATE_INFO, NULL, 0, 1,
		&PIPELINE_STATE->DESCRIPTOR_SET_LAYOUT,
		PUSH_CONSTANT_COUNT ? (unsigned int)1 : (unsigned int)0,
		PUSH_CONSTANT_COUNT ? &PUSH_RANGE : NULL
	};

	VULKAN_FUNCTION(vkCreatePipelineLayout)
	(GPU_STATE->LOGICAL_DEVICE, &PIPELINE_LAYOUT_INFO, NULL,
		&PIPELINE_STATE->PIPELINE_LAYOUT);

	VkComputePipelineCreateInfo	PIPELINE_INFO = {
		VKS_COMPUTE_PIPELINE_CREATE_INFO, NULL, 0,
		{
			VKS_PIPELINE_SHADER_STAGE_CREATE_INFO, NULL, 0,
			VK_SHADER_STAGE_COMPUTE_BIT, PIPELINE_STATE->SHADER_MODULE, "main",
			NULL
		},
		PIPELINE_STATE->PIPELINE_LAYOUT, 0, -1
	};

	if (
		VULKAN_FUNCTION(vkCreateComputePipelines)
		(GPU_STATE->LOGICAL_DEVICE, 0, 1, &PIPELINE_INFO, NULL,
			&PIPELINE_STATE->PIPELINE)
	)
	{
		free(PIPELINE_STATE);
		return (NULL);
	}

	return (PIPELINE_STATE);
}

void
	GPU_BEGIN(GPU *GPU_STATE)
{
	VULKAN_FUNCTION(vkResetDescriptorPool)
	(GPU_STATE->LOGICAL_DEVICE, GPU_STATE->DESCRIPTOR_POOL, 0);
	BEGIN_COMMAND_BUFFER(GPU_STATE);
	GPU_STATE->RECORDING = 1;
}

void
	GPU_RUN(
		GPU *GPU_STATE, GPU_PIPELINE *PIPELINE_STATE, GPU_BUFFER **BUFFERS,
		const uint32_t *PUSH_CONSTANTS, uint32_t GROUP_COUNT_X,
		uint32_t GROUP_COUNT_Y, uint32_t GROUP_COUNT_Z
	)
{
	VkDescriptorSet				DESCRIPTOR_SET;
	VkDescriptorSetAllocateInfo	SET_ALLOCATE_INFO = {
		VKS_DESCRIPTOR_SET_ALLOCATE_INFO, NULL, GPU_STATE->DESCRIPTOR_POOL, 1,
		&PIPELINE_STATE->DESCRIPTOR_SET_LAYOUT
	};

	VULKAN_FUNCTION(vkAllocateDescriptorSets)
	(GPU_STATE->LOGICAL_DEVICE, &SET_ALLOCATE_INFO, &DESCRIPTOR_SET);

	VkDescriptorBufferInfo	BUFFER_INFOS[16];
	VkWriteDescriptorSet	DESCRIPTOR_WRITES[16];
	int						BINDING_INDEX;

	for (
		BINDING_INDEX = 0;
		BINDING_INDEX < PIPELINE_STATE->BUFFER_COUNT;
		BINDING_INDEX++
	)
	{
		BUFFER_INFOS[BINDING_INDEX].buffer = BUFFERS[BINDING_INDEX]->BUFFER;
		BUFFER_INFOS[BINDING_INDEX].offset = 0;
		BUFFER_INFOS[BINDING_INDEX].range = ~(unsigned long long)0;

		VkWriteDescriptorSet	DESCRIPTOR_WRITE = {
			VKS_WRITE_DESCRIPTOR_SET, NULL, DESCRIPTOR_SET,
			(uint32_t)BINDING_INDEX, 0, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
			NULL, &BUFFER_INFOS[BINDING_INDEX], NULL
		};

		DESCRIPTOR_WRITES[BINDING_INDEX] = DESCRIPTOR_WRITE;
	}

	VULKAN_FUNCTION(vkUpdateDescriptorSets)
	(GPU_STATE->LOGICAL_DEVICE, (uint32_t)PIPELINE_STATE->BUFFER_COUNT,
		DESCRIPTOR_WRITES, 0, NULL);
	VULKAN_FUNCTION(vkCmdBindPipeline)
	(GPU_STATE->COMMAND_BUFFER, VK_PIPELINE_BIND_POINT_COMPUTE,
		PIPELINE_STATE->PIPELINE);
	VULKAN_FUNCTION(vkCmdBindDescriptorSets)
	(GPU_STATE->COMMAND_BUFFER, VK_PIPELINE_BIND_POINT_COMPUTE,
		PIPELINE_STATE->PIPELINE_LAYOUT, 0, 1, &DESCRIPTOR_SET, 0, NULL);

	if (PIPELINE_STATE->PUSH_CONSTANT_COUNT)
		VULKAN_FUNCTION(vkCmdPushConstants)
		(GPU_STATE->COMMAND_BUFFER, PIPELINE_STATE->PIPELINE_LAYOUT,
			VK_SHADER_STAGE_COMPUTE_BIT, 0,
		(uint32_t)(PIPELINE_STATE->PUSH_CONSTANT_COUNT * 4), PUSH_CONSTANTS);

	VULKAN_FUNCTION(vkCmdDispatch)
	(GPU_STATE->COMMAND_BUFFER, GROUP_COUNT_X, GROUP_COUNT_Y, GROUP_COUNT_Z);
	RECORD_MEMORY_BARRIER(GPU_STATE);
}

int
	GPU_END(GPU *GPU_STATE)
{
	GPU_STATE->RECORDING = 0;

	return (SUBMIT_AND_WAIT(GPU_STATE));
}

void
	GPU_CLOSE(GPU *GPU_STATE)
{
	if (!GPU_STATE)
		return ;

	VULKAN_FUNCTION(vkDeviceWaitIdle)(GPU_STATE->LOGICAL_DEVICE);
	VULKAN_FUNCTION(vkDestroyDevice)(GPU_STATE->LOGICAL_DEVICE, NULL);
	VULKAN_FUNCTION(vkDestroyInstance)(GPU_STATE->INSTANCE, NULL);
	free(GPU_STATE);
}

void
	GPU_PRINT_INFORMATION(GPU *GPU_STATE)
{
	const uint8_t	*LIMITS = (const uint8_t *)&GPU_STATE->PROPERTIES + 296;
	uint32_t		SHARED_MEMORY_SIZE;
	uint32_t		MAX_INVOCATIONS;
	uint32_t		STORAGE_RANGE;
	uint32_t		PUSH_CONSTANT_SIZE;
	uint32_t		GROUP_COUNT_LIMITS[3];
	uint32_t		GROUP_SIZE_LIMITS[3];

	memcpy(&SHARED_MEMORY_SIZE, LIMITS + 216, 4);
	memcpy(&MAX_INVOCATIONS, LIMITS + 232, 4);
	memcpy(&STORAGE_RANGE, LIMITS + 28, 4);
	memcpy(&PUSH_CONSTANT_SIZE, LIMITS + 32, 4);
	memcpy(GROUP_COUNT_LIMITS, LIMITS + 220, 12);
	memcpy(GROUP_SIZE_LIMITS, LIMITS + 236, 12);
	printf(
		"  using: %s (%s), Vulkan %u.%u, device memory %.1f GB\n",
		GPU_STATE->PROPERTIES.deviceName,
		GPU_IS_DISCRETE(GPU_STATE) ? "discrete" : "not discrete",
		GPU_STATE->PROPERTIES.apiVersion >> 22,
		(GPU_STATE->PROPERTIES.apiVersion >> 12) & 1023,
		GPU_VIDEO_MEMORY(GPU_STATE) / 1073741824.0
	);
	printf(
		"  limits: shared memory %u KB, %u threads per group (max %u x %u x "
		"%u), storage buffer %u MB, push constants %u bytes\n",
		SHARED_MEMORY_SIZE / 1024, MAX_INVOCATIONS, GROUP_SIZE_LIMITS[0],
		GROUP_SIZE_LIMITS[1], GROUP_SIZE_LIMITS[2], STORAGE_RANGE >> 20,
		PUSH_CONSTANT_SIZE
	);
}
