#include "GPU.h"
#include "THREAD.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

static uint32_t
	*BUILD_ADD_KERNEL(int *OUTPUT_WORD_COUNT)
{
	KERNEL_BUILDER	BUILDER;

	KERNEL_BEGIN(&BUILDER, 3, 1, 64, 1, 1);

	uint32_t	THREAD_INDEX = KERNEL_GLOBAL_ID(&BUILDER, 0);
	uint32_t	ELEMENT_COUNT = KERNEL_PUSH_CONSTANT(&BUILDER, 0);
	uint32_t	MERGE_LABEL;

	KERNEL_IF(
		&BUILDER,
		KERNEL_BINARY(
			&BUILDER, SPIRV_UNSIGNED_LESS_THAN, BUILDER.TYPE_BOOLEAN,
			THREAD_INDEX, ELEMENT_COUNT
		),
		&MERGE_LABEL
	);
	KERNEL_STORE_BUFFER(
		&BUILDER, 2, THREAD_INDEX,
		KERNEL_BINARY(
			&BUILDER, SPIRV_FLOAT_ADD, BUILDER.TYPE_FLOAT,
			KERNEL_LOAD_BUFFER(&BUILDER, 0, THREAD_INDEX),
			KERNEL_LOAD_BUFFER(&BUILDER, 1, THREAD_INDEX)
		)
	);
	KERNEL_END_IF(&BUILDER, MERGE_LABEL);

	return (KERNEL_END(&BUILDER, OUTPUT_WORD_COUNT));
}

static uint32_t
	*BUILD_NAIVE_MATRIX_KERNEL(int *OUTPUT_WORD_COUNT)
{
	KERNEL_BUILDER	BUILDER;

	KERNEL_BEGIN(&BUILDER, 3, 3, 16, 16, 1);

	uint32_t	COLUMN = KERNEL_GLOBAL_ID(&BUILDER, 0);
	uint32_t	ROW = KERNEL_GLOBAL_ID(&BUILDER, 1);
	uint32_t	ROW_COUNT = KERNEL_PUSH_CONSTANT(&BUILDER, 0);
	uint32_t	COLUMN_COUNT = KERNEL_PUSH_CONSTANT(&BUILDER, 1);
	uint32_t	INNER_COUNT = KERNEL_PUSH_CONSTANT(&BUILDER, 2);
	uint32_t	MERGE_LABEL;
	uint32_t	ACCUMULATOR = KERNEL_VARIABLE_FLOAT(&BUILDER);

	KERNEL_STORE(&BUILDER, ACCUMULATOR, KERNEL_CONSTANT_FLOAT(&BUILDER, 0));

	uint32_t	IN_BOUNDS = KERNEL_BINARY(
		&BUILDER, 167, BUILDER.TYPE_BOOLEAN,
		KERNEL_BINARY(
			&BUILDER, SPIRV_UNSIGNED_LESS_THAN, BUILDER.TYPE_BOOLEAN, ROW,
			ROW_COUNT
		),
		KERNEL_BINARY(
			&BUILDER, SPIRV_UNSIGNED_LESS_THAN, BUILDER.TYPE_BOOLEAN, COLUMN,
			COLUMN_COUNT
		)
	);

	KERNEL_IF(&BUILDER, IN_BOUNDS, &MERGE_LABEL);

	KERNEL_LOOP	INNER_LOOP = KERNEL_FOR(
		&BUILDER, KERNEL_CONSTANT_UNSIGNED(&BUILDER, 0), INNER_COUNT
	);
	uint32_t	INNER_INDEX = KERNEL_FOR_VARIABLE(&BUILDER, &INNER_LOOP);
	uint32_t	LEFT_VALUE = KERNEL_LOAD_BUFFER(
		&BUILDER, 0,
		KERNEL_BINARY(
			&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED,
			KERNEL_BINARY(
				&BUILDER, SPIRV_INTEGER_MULTIPLY, BUILDER.TYPE_UNSIGNED, ROW,
				INNER_COUNT
			),
			INNER_INDEX
		)
	);
	uint32_t	RIGHT_VALUE = KERNEL_LOAD_BUFFER(
		&BUILDER, 1,
		KERNEL_BINARY(
			&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED,
			KERNEL_BINARY(
				&BUILDER, SPIRV_INTEGER_MULTIPLY, BUILDER.TYPE_UNSIGNED,
				INNER_INDEX, COLUMN_COUNT
			),
			COLUMN
		)
	);

	KERNEL_STORE(
		&BUILDER, ACCUMULATOR,
		KERNEL_BINARY(
			&BUILDER, SPIRV_FLOAT_ADD, BUILDER.TYPE_FLOAT,
			KERNEL_LOAD(&BUILDER, BUILDER.TYPE_FLOAT, ACCUMULATOR),
			KERNEL_BINARY(
				&BUILDER, SPIRV_FLOAT_MULTIPLY, BUILDER.TYPE_FLOAT, LEFT_VALUE,
				RIGHT_VALUE
			)
		)
	);
	KERNEL_FOR_END(
		&BUILDER, &INNER_LOOP, KERNEL_CONSTANT_UNSIGNED(&BUILDER, 1)
	);
	KERNEL_STORE_BUFFER(
		&BUILDER, 2,
		KERNEL_BINARY(
			&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED,
			KERNEL_BINARY(
				&BUILDER, SPIRV_INTEGER_MULTIPLY, BUILDER.TYPE_UNSIGNED, ROW,
				COLUMN_COUNT
			),
			COLUMN
		),
		KERNEL_LOAD(&BUILDER, BUILDER.TYPE_FLOAT, ACCUMULATOR)
	);
	KERNEL_END_IF(&BUILDER, MERGE_LABEL);

	return (KERNEL_END(&BUILDER, OUTPUT_WORD_COUNT));
}

static uint32_t
	*BUILD_TILED_MATRIX_KERNEL(int *OUTPUT_WORD_COUNT)
{
	KERNEL_BUILDER	BUILDER;

	KERNEL_BEGIN(&BUILDER, 3, 3, 16, 16, 1);

	uint32_t	LOCAL_COLUMN = KERNEL_LOCAL_ID(&BUILDER, 0);
	uint32_t	LOCAL_ROW = KERNEL_LOCAL_ID(&BUILDER, 1);
	uint32_t	COLUMN = KERNEL_GLOBAL_ID(&BUILDER, 0);
	uint32_t	ROW = KERNEL_GLOBAL_ID(&BUILDER, 1);
	uint32_t	COLUMN_COUNT = KERNEL_PUSH_CONSTANT(&BUILDER, 1);
	uint32_t	INNER_COUNT = KERNEL_PUSH_CONSTANT(&BUILDER, 2);
	uint32_t	LEFT_TILE = KERNEL_SHARED_ARRAY(&BUILDER, 256);
	uint32_t	RIGHT_TILE = KERNEL_SHARED_ARRAY(&BUILDER, 256);
	uint32_t	TILE_WIDTH = KERNEL_CONSTANT_UNSIGNED(&BUILDER, 16);
	uint32_t	ACCUMULATOR = KERNEL_VARIABLE_FLOAT(&BUILDER);

	KERNEL_STORE(&BUILDER, ACCUMULATOR, KERNEL_CONSTANT_FLOAT(&BUILDER, 0));

	uint32_t	TILE_SLOT = KERNEL_BINARY(
		&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED,
		KERNEL_BINARY(
			&BUILDER, SPIRV_INTEGER_MULTIPLY, BUILDER.TYPE_UNSIGNED, LOCAL_ROW,
			TILE_WIDTH
		),
		LOCAL_COLUMN
	);
	KERNEL_LOOP	TILE_LOOP = KERNEL_FOR(
		&BUILDER, KERNEL_CONSTANT_UNSIGNED(&BUILDER, 0), INNER_COUNT
	);
	uint32_t	TILE_OFFSET = KERNEL_FOR_VARIABLE(&BUILDER, &TILE_LOOP);
	uint32_t	LEFT_ELEMENT = KERNEL_LOAD_BUFFER(
		&BUILDER, 0,
		KERNEL_BINARY(
			&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED,
			KERNEL_BINARY(
				&BUILDER, SPIRV_INTEGER_MULTIPLY, BUILDER.TYPE_UNSIGNED, ROW,
				INNER_COUNT
			),
			KERNEL_BINARY(
				&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED, TILE_OFFSET,
				LOCAL_COLUMN
			)
		)
	);
	uint32_t	RIGHT_ELEMENT = KERNEL_LOAD_BUFFER(
		&BUILDER, 1,
		KERNEL_BINARY(
			&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED,
			KERNEL_BINARY(
				&BUILDER, SPIRV_INTEGER_MULTIPLY, BUILDER.TYPE_UNSIGNED,
				KERNEL_BINARY(
					&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED,
					TILE_OFFSET, LOCAL_ROW
				),
				COLUMN_COUNT
			),
			COLUMN
		)
	);

	KERNEL_STORE(
		&BUILDER, KERNEL_SHARED_POINTER(&BUILDER, LEFT_TILE, TILE_SLOT),
		LEFT_ELEMENT
	);
	KERNEL_STORE(
		&BUILDER, KERNEL_SHARED_POINTER(&BUILDER, RIGHT_TILE, TILE_SLOT),
		RIGHT_ELEMENT
	);
	KERNEL_BARRIER(&BUILDER);

	KERNEL_LOOP	INNER_LOOP =
		KERNEL_FOR(&BUILDER, KERNEL_CONSTANT_UNSIGNED(&BUILDER, 0), TILE_WIDTH);
	uint32_t	INNER_INDEX = KERNEL_FOR_VARIABLE(&BUILDER, &INNER_LOOP);
	uint32_t	LEFT_VALUE = KERNEL_LOAD(
		&BUILDER, BUILDER.TYPE_FLOAT,
		KERNEL_SHARED_POINTER(
			&BUILDER, LEFT_TILE,
			KERNEL_BINARY(
				&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED,
				KERNEL_BINARY(
					&BUILDER, SPIRV_INTEGER_MULTIPLY, BUILDER.TYPE_UNSIGNED,
					LOCAL_ROW, TILE_WIDTH
				),
				INNER_INDEX
			)
		)
	);
	uint32_t	RIGHT_VALUE = KERNEL_LOAD(
		&BUILDER, BUILDER.TYPE_FLOAT,
		KERNEL_SHARED_POINTER(
			&BUILDER, RIGHT_TILE,
			KERNEL_BINARY(
				&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED,
				KERNEL_BINARY(
					&BUILDER, SPIRV_INTEGER_MULTIPLY, BUILDER.TYPE_UNSIGNED,
					INNER_INDEX, TILE_WIDTH
				),
				LOCAL_COLUMN
			)
		)
	);

	KERNEL_STORE(
		&BUILDER, ACCUMULATOR,
		KERNEL_BINARY(
			&BUILDER, SPIRV_FLOAT_ADD, BUILDER.TYPE_FLOAT,
			KERNEL_LOAD(&BUILDER, BUILDER.TYPE_FLOAT, ACCUMULATOR),
			KERNEL_BINARY(
				&BUILDER, SPIRV_FLOAT_MULTIPLY, BUILDER.TYPE_FLOAT, LEFT_VALUE,
				RIGHT_VALUE
			)
		)
	);
	KERNEL_FOR_END(
		&BUILDER, &INNER_LOOP, KERNEL_CONSTANT_UNSIGNED(&BUILDER, 1)
	);
	KERNEL_BARRIER(&BUILDER);
	KERNEL_FOR_END(&BUILDER, &TILE_LOOP, TILE_WIDTH);
	KERNEL_STORE_BUFFER(
		&BUILDER, 2,
		KERNEL_BINARY(
			&BUILDER, SPIRV_INTEGER_ADD, BUILDER.TYPE_UNSIGNED,
			KERNEL_BINARY(
				&BUILDER, SPIRV_INTEGER_MULTIPLY, BUILDER.TYPE_UNSIGNED, ROW,
				COLUMN_COUNT
			),
			COLUMN
		),
		KERNEL_LOAD(&BUILDER, BUILDER.TYPE_FLOAT, ACCUMULATOR)
	);

	return (KERNEL_END(&BUILDER, OUTPUT_WORD_COUNT));
}

static void
	SAVE_SPIRV_DUMP(
		const char *KERNEL_NAME, uint32_t *MODULE_WORDS, int WORD_COUNT
	)
{
	const char	*DUMP_DIRECTORY = getenv("SPV_DUMP");

	if (!DUMP_DIRECTORY)
		return ;

	char	DUMP_PATH[512];

	snprintf(
		DUMP_PATH, sizeof DUMP_PATH, "%s/%s.spv", DUMP_DIRECTORY, KERNEL_NAME
	);

	FILE	*STREAM = fopen(DUMP_PATH, "wb");

	if (STREAM)
	{
		fwrite(MODULE_WORDS, 4, WORD_COUNT, STREAM);
		fclose(STREAM);
	}
}

int
	main(int ARGUMENT_COUNT, char **ARGUMENTS)
{
	int	MATRIX_SIZE;

	if (ARGUMENT_COUNT > 1)
		MATRIX_SIZE = atoi(ARGUMENTS[1]);
	else
		MATRIX_SIZE = 1024;

	printf("Code GPU probe\n");

	GPU	*GPU_STATE = GPU_OPEN(1);

	if (!GPU_STATE)
	{
		printf("RESULT: no usable GPU, Code will use the CPU.\n");
		return (0);
	}

	GPU_PRINT_INFORMATION(GPU_STATE);

	int	FAIL_COUNT = 0;

	{
		int			SPIRV_WORD_COUNT;
		int			COUNT = 1 << 20;
		uint32_t	*SPIRV_CODE = BUILD_ADD_KERNEL(&SPIRV_WORD_COUNT);

		SAVE_SPIRV_DUMP("add", SPIRV_CODE, SPIRV_WORD_COUNT);

		GPU_PIPELINE	*PIPELINE =
			GPU_NEW_PIPELINE(GPU_STATE, SPIRV_CODE, SPIRV_WORD_COUNT, 3, 1);
		float			*FIRST_INPUT = malloc(COUNT * 4);
		float			*SECOND_INPUT = malloc(COUNT * 4);
		float			*HOST_OUTPUT = malloc(COUNT * 4);
		int				INDEX;

		for (INDEX = 0; INDEX < COUNT; INDEX++)
		{
			FIRST_INPUT[INDEX] = (float)INDEX;
			SECOND_INPUT[INDEX] = (float)0.5 * INDEX;
		}

		GPU_BUFFER	*FIRST_BUFFER =
			GPU_NEW_BUFFER(GPU_STATE, COUNT * (unsigned long long)4);
		GPU_BUFFER	*SECOND_BUFFER =
			GPU_NEW_BUFFER(GPU_STATE, COUNT * (unsigned long long)4);
		GPU_BUFFER	*OUTPUT_BUFFER =
			GPU_NEW_BUFFER(GPU_STATE, COUNT * (unsigned long long)4);

		GPU_UPLOAD(
			GPU_STATE, FIRST_BUFFER, FIRST_INPUT, COUNT * (unsigned long long)4,
			0
		);
		GPU_UPLOAD(
			GPU_STATE, SECOND_BUFFER, SECOND_INPUT,
			COUNT * (unsigned long long)4, 0
		);

		GPU_BUFFER	*BUFFER_LIST[3] = {
			FIRST_BUFFER, SECOND_BUFFER, OUTPUT_BUFFER
		};
		uint32_t	PUSH_CONSTANT = (uint32_t)COUNT;

		GPU_BEGIN(GPU_STATE);
		GPU_RUN(
			GPU_STATE, PIPELINE, BUFFER_LIST, &PUSH_CONSTANT, (COUNT + 63) / 64,
			1, 1
		);
		GPU_END(GPU_STATE);
		GPU_DOWNLOAD(
			GPU_STATE, OUTPUT_BUFFER, HOST_OUTPUT,
			COUNT * (unsigned long long)4, 0
		);

		int	WRONG_COUNT = 0;

		for (INDEX = 0; INDEX < COUNT; INDEX++)
			if (HOST_OUTPUT[INDEX] != FIRST_INPUT[INDEX] + SECOND_INPUT[INDEX])
				WRONG_COUNT++;

		printf(
			"  test 1, add 1M numbers: %s\n", WRONG_COUNT ? "FAILED" : "correct"
		);
		FAIL_COUNT += WRONG_COUNT != 0;
		free(FIRST_INPUT);
		free(SECOND_INPUT);
		free(HOST_OUTPUT);
		free(SPIRV_CODE);
	}

	int	KIND_NUMBER;

	for (KIND_NUMBER = 0; KIND_NUMBER < 2; KIND_NUMBER++)
	{
		int			ROW_COUNT = MATRIX_SIZE;
		int			COLUMN_COUNT = MATRIX_SIZE;
		int			INNER_SIZE = MATRIX_SIZE;
		int			SPIRV_WORD_COUNT;
		uint32_t	*SPIRV_CODE;

		if (KIND_NUMBER)
			SPIRV_CODE = BUILD_TILED_MATRIX_KERNEL(&SPIRV_WORD_COUNT);
		else
			SPIRV_CODE = BUILD_NAIVE_MATRIX_KERNEL(&SPIRV_WORD_COUNT);

		SAVE_SPIRV_DUMP(
			KIND_NUMBER ? "mm_tiled" : "mm_naive", SPIRV_CODE, SPIRV_WORD_COUNT
		);

		GPU_PIPELINE	*PIPELINE =
			GPU_NEW_PIPELINE(GPU_STATE, SPIRV_CODE, SPIRV_WORD_COUNT, 3, 3);

		if (!PIPELINE)
		{
			printf("  pipeline failed\n");
			FAIL_COUNT++;
			continue ;
		}

		float		*FIRST_INPUT = malloc((size_t)ROW_COUNT * INNER_SIZE * 4);
		float		*SECOND_INPUT =
			malloc((size_t)INNER_SIZE * COLUMN_COUNT * 4);
		float		*HOST_OUTPUT = malloc((size_t)ROW_COUNT * COLUMN_COUNT * 4);
		uint64_t	RANDOM_STATE = 5;
		size_t		INDEX;

		for (INDEX = 0; INDEX < (size_t)ROW_COUNT * INNER_SIZE; INDEX++)
		{
			RANDOM_STATE =
				RANDOM_STATE * (unsigned long long)6364136223846793005 + 1;
			FIRST_INPUT[INDEX] =
				(float)((RANDOM_STATE >> 40) % 1000) / (float)1000.0 -
				(float)0.5;
		}

		for (INDEX = 0; INDEX < (size_t)INNER_SIZE * COLUMN_COUNT; INDEX++)
		{
			RANDOM_STATE =
				RANDOM_STATE * (unsigned long long)6364136223846793005 + 1;
			SECOND_INPUT[INDEX] =
				(float)((RANDOM_STATE >> 40) % 1000) / (float)1000.0 -
				(float)0.5;
		}

		GPU_BUFFER	*FIRST_BUFFER =
			GPU_NEW_BUFFER(GPU_STATE, (uint64_t)ROW_COUNT * INNER_SIZE * 4);
		GPU_BUFFER	*SECOND_BUFFER =
			GPU_NEW_BUFFER(GPU_STATE, (uint64_t)INNER_SIZE * COLUMN_COUNT * 4);
		GPU_BUFFER	*OUTPUT_BUFFER =
			GPU_NEW_BUFFER(GPU_STATE, (uint64_t)ROW_COUNT * COLUMN_COUNT * 4);

		GPU_UPLOAD(
			GPU_STATE, FIRST_BUFFER, FIRST_INPUT,
			(uint64_t)ROW_COUNT * INNER_SIZE * 4, 0
		);
		GPU_UPLOAD(
			GPU_STATE, SECOND_BUFFER, SECOND_INPUT,
			(uint64_t)INNER_SIZE * COLUMN_COUNT * 4, 0
		);

		GPU_BUFFER	*BUFFER_LIST[3] = {
			FIRST_BUFFER, SECOND_BUFFER, OUTPUT_BUFFER
		};
		uint32_t	PUSH_CONSTANTS[3] = {
			(uint32_t)ROW_COUNT, (uint32_t)COLUMN_COUNT, (uint32_t)INNER_SIZE
		};

		GPU_BEGIN(GPU_STATE);
		GPU_RUN(
			GPU_STATE, PIPELINE, BUFFER_LIST, PUSH_CONSTANTS, COLUMN_COUNT / 16,
			ROW_COUNT / 16, 1
		);
		GPU_END(GPU_STATE);

		int		REPEAT_COUNT = 5;
		double	START_TIME = THREAD_NOW_SECONDS();

		GPU_BEGIN(GPU_STATE);

		{
			int	INDEX;

			for (INDEX = 0; INDEX < REPEAT_COUNT; INDEX++)
				GPU_RUN(
					GPU_STATE, PIPELINE, BUFFER_LIST, PUSH_CONSTANTS,
					COLUMN_COUNT / 16, ROW_COUNT / 16, 1
				);
		}

		GPU_END(GPU_STATE);

		double	ELAPSED_TIME =
			(THREAD_NOW_SECONDS() - START_TIME) / REPEAT_COUNT;

		GPU_DOWNLOAD(
			GPU_STATE, OUTPUT_BUFFER, HOST_OUTPUT,
			(uint64_t)ROW_COUNT * COLUMN_COUNT * 4, 0
		);

		double	MAXIMUM_ERROR = 0;
		int		SAMPLE_INDEX;

		for (SAMPLE_INDEX = 0; SAMPLE_INDEX < 64; SAMPLE_INDEX++)
		{
			int		INDEX = (SAMPLE_INDEX * 7919) % ROW_COUNT;
			int		SECOND_INDEX = (SAMPLE_INDEX * 104729) % COLUMN_COUNT;
			double	REFERENCE_SUM = 0;
			int		INNER_INDEX;

			for (INNER_INDEX = 0; INNER_INDEX < INNER_SIZE; INNER_INDEX++)
				REFERENCE_SUM +=
					(double
					)FIRST_INPUT[(size_t)INDEX * INNER_SIZE + INNER_INDEX] *
					SECOND_INPUT
						[(size_t)INNER_INDEX * COLUMN_COUNT + SECOND_INDEX];

			double	ABSOLUTE_ERROR = fabs(
				REFERENCE_SUM -
				HOST_OUTPUT[(size_t)INDEX * COLUMN_COUNT + SECOND_INDEX]
			);

			if (ABSOLUTE_ERROR > MAXIMUM_ERROR)
				MAXIMUM_ERROR = ABSOLUTE_ERROR;
		}

		printf(
			"  test %d, %s matrix multiply %dx%d: %s (max error %.2g), %.1f ms "
			"= %.0f GFLOP/s\n",
			2 + KIND_NUMBER, KIND_NUMBER ? "tiled" : "simple", ROW_COUNT,
			COLUMN_COUNT, MAXIMUM_ERROR < 1e-2 ? "correct" : "FAILED",
			MAXIMUM_ERROR, ELAPSED_TIME * 1000,
			2.0 * ROW_COUNT * COLUMN_COUNT * INNER_SIZE / ELAPSED_TIME / 1e9
		);
		FAIL_COUNT += MAXIMUM_ERROR >= 1e-2;
		free(FIRST_INPUT);
		free(SECOND_INPUT);
		free(HOST_OUTPUT);
		free(SPIRV_CODE);
		GPU_FREE_BUFFER(GPU_STATE, FIRST_BUFFER);
		GPU_FREE_BUFFER(GPU_STATE, SECOND_BUFFER);
		GPU_FREE_BUFFER(GPU_STATE, OUTPUT_BUFFER);
	}

	printf(
		"RESULT: %s\n",
		FAIL_COUNT ? "GPU found, but some tests FAILED - send me this output"
		: "GPU works with Code's own GPU programs"
	);
	GPU_CLOSE(GPU_STATE);

	return (0);
}
