#include "BRAIN.h"
#include "DATA.h"
#include "THREAD.h"
#include <stdio.h>
#include <stdlib.h>

int
	main(int ARGUMENT_COUNT, char **ARGUMENTS)
{
	BRAIN	LOADED_BRAIN;

	if (ARGUMENT_COUNT < 3 || BRAIN_OPEN(&LOADED_BRAIN, 1, 0))
		return (1);

	WEB		*NEURAL_WEB = LOADED_BRAIN.NEURAL_WEB;
	DATASET	TRAINING_DATA = { 0 };

	LOAD_TRAINING_FILE(
		LOADED_BRAIN.LEXICON, &TRAINING_DATA, ARGUMENTS[1],
		NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH
	);
	DATASET_SET_FIRST_PERSON(&TRAINING_DATA, LOADED_BRAIN.LEXICON);

	int64_t	WINDOW_COUNT;
	WINDOW	*WINDOWS = MAKE_WINDOWS(
		&TRAINING_DATA, NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH, &WINDOW_COUNT
	);
	int		MAX_POSITIONS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;
	int		COUNT = atoi(ARGUMENTS[2]);
	int32_t	*SEQUENCE = malloc((MAX_POSITIONS + 2) * 4);
	float	*TOKEN_WEIGHTS = malloc((MAX_POSITIONS + 2) * 4);
	int		INNER_INDEX;

	for (INNER_INDEX = 3; INNER_INDEX < ARGUMENT_COUNT; INNER_INDEX++)
	{
		NEURAL_WEB->KERNEL_STATE->GRADIENT_SKIP_THRESHOLD =
			(float)atof(ARGUMENTS[INNER_INDEX]);

		double	START_TIME = THREAD_NOW_SECONDS();
		double	TOKEN_TOTAL = 0;
		double	LOSS_TOTAL = 0;
		double	WEIGHT_SUM = 0;
		int		OUTER_INDEX;

		for (OUTER_INDEX = 0; OUTER_INDEX < COUNT; OUTER_INDEX++)
		{
			int		SEQUENCE_LENGTH = BUILD_SEQUENCE(
				&TRAINING_DATA, &WINDOWS[(OUTER_INDEX * 7919) % WINDOW_COUNT],
				MAX_POSITIONS, SEQUENCE, TOKEN_WEIGHTS
			);
			double	WINDOW_WEIGHT = 0;
			int		POSITION;

			for (POSITION = 1; POSITION < SEQUENCE_LENGTH; POSITION++)
				WINDOW_WEIGHT += TOKEN_WEIGHTS[POSITION];

			if (WINDOW_WEIGHT > 0)
				NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE =
					(float)(1.0 / WINDOW_WEIGHT);
			else
				NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE = 0;

			LOSS_TOTAL += LEARN_WINDOW(
				NEURAL_WEB, SEQUENCE, SEQUENCE_LENGTH, TOKEN_WEIGHTS,
				&WEIGHT_SUM
			);
			TOKEN_TOTAL += SEQUENCE_LENGTH - 1;
		}

		double	ELAPSED_TIME = THREAD_NOW_SECONDS() - START_TIME;

		printf(
			"grad-skip %g: %.0f tok/s on real windows (avg %.0f tokens)\n",
			NEURAL_WEB->KERNEL_STATE->GRADIENT_SKIP_THRESHOLD,
			TOKEN_TOTAL / ELAPSED_TIME, TOKEN_TOTAL / COUNT
		);
	}

	return (0);
}
