#ifndef JIT_H
#define JIT_H
#include <stdint.h>
#include <stddef.h>

enum
{
	RAX,
	RCX,
	RDX,
	RBX,
	RSP,
	RBP,
	RSI,
	RDI,
	R8,
	R9,
	R10,
	R11,
	R12,
	R13,
	R14,
	R15
};

enum
{
	CC_O = 0,
	CC_B = 2,
	CC_AE = 3,
	CC_E = 4,
	CC_NE = 5,
	CC_BE = 6,
	CC_A = 7,
	CC_S = 8,
	CC_L = 12,
	CC_GE = 13,
	CC_LE = 14,
	CC_G = 15
};

typedef struct
{
	int		BASE;
	int		INDEX;
	int		SCALE;
	int32_t	DISPLACEMENT;
} MEMORY_OPERAND;

typedef struct
{
	int32_t	POSITION;
	int32_t	TARGET_LABEL;
} JUMP_FIXUP;

typedef struct
{
	uint8_t		*BYTES;
	int32_t		BYTE_COUNT;
	int32_t		BYTE_CAPACITY;
	int32_t		*LABELS;
	int			LABEL_COUNT;
	int			LABEL_CAPACITY;
	JUMP_FIXUP	*FIXUPS;
	int			FIXUP_COUNT;
	int			FIXUP_CAPACITY;
	int32_t		*EXTERNAL_TARGETS;
	int32_t		*EXTERNAL_POSITIONS;
	int			EXTERNAL_COUNT;
	int			EXTERNAL_CAPACITY;
} ASSEMBLER;

MEMORY_OPERAND	MEMORY_AT(int BASE_REGISTER, int32_t DISPLACEMENT);
MEMORY_OPERAND	MEMORY_INDEXED(
	int BASE_REGISTER, int INDEX_REGISTER, int SCALE, int32_t DISPLACEMENT
);

void	ASSEMBLER_INITIALIZE(ASSEMBLER *ASSEMBLY);
void	ASSEMBLER_FREE(ASSEMBLER *ASSEMBLY);
void	ASSEMBLER_RESET(ASSEMBLER *ASSEMBLY);
void	ASSEMBLER_EMIT_BYTE(ASSEMBLER *ASSEMBLY, int BYTE_VALUE);
void	ASSEMBLER_EMIT_INTEGER32(ASSEMBLER *ASSEMBLY, int32_t VALUE);
int		ASSEMBLER_NEW_LABEL(ASSEMBLER *ASSEMBLY);
void	ASSEMBLER_BIND_LABEL(ASSEMBLER *ASSEMBLY, int LABEL);
int		ASSEMBLER_FINISH(ASSEMBLER *ASSEMBLY);

void	MOVE_FROM_MEMORY(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
);
void	MOVE_TO_MEMORY(
	ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND, int REGISTER_NUMBER
);
void	MOVE32_FROM_MEMORY(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
);
void	MOVE32_TO_MEMORY(
	ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND, int REGISTER_NUMBER
);
void	MOVE_SIGN_EXTENDED(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
);
void	MOVE_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE);
void	MOVE_IMMEDIATE(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, int32_t IMMEDIATE
);
void	STORE_IMMEDIATE32(
	ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND, int32_t IMMEDIATE
);
void	LOAD_ADDRESS(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
);
void	ADD_IMMEDIATE(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, int32_t IMMEDIATE
);
void	SUBTRACT_IMMEDIATE(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, int32_t IMMEDIATE
);
void	COMPARE_IMMEDIATE(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, int32_t IMMEDIATE
);
void	ADD_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE);
void	SUBTRACT_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE);
void	COMPARE_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE);
void	COMPARE_MEMORY(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
);
void	MULTIPLY_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE);
void	MULTIPLY_IMMEDIATE(
	ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE, int32_t IMMEDIATE
);
void	SHIFT_LEFT_IMMEDIATE(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, int SHIFT_COUNT
);
void	TEST_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE);
void	PUSH_REGISTER(ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER);
void	POP_REGISTER(ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER);
void	RETURN_INSTRUCTION(ASSEMBLER *ASSEMBLY);
void	CALL_MEMORY(ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND);
void	JUMP_TO_MEMORY(ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND);
void	BRANCH_TO_LABEL(ASSEMBLER *ASSEMBLY, int CONDITION, int LABEL);
void	JUMP_TO_LABEL(ASSEMBLER *ASSEMBLY, int LABEL);
void	JUMP_TO_PIECE(ASSEMBLER *ASSEMBLY, int32_t TARGET_ID);

void	VECTOR_LOAD(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int VECTOR_REGISTER,
	MEMORY_OPERAND OPERAND
);
void	VECTOR_STORE(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, MEMORY_OPERAND OPERAND,
	int VECTOR_REGISTER
);
void	VECTOR_MOVE(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE
);
void	SCALAR_LOAD(
	ASSEMBLER *ASSEMBLY, int VECTOR_REGISTER, MEMORY_OPERAND OPERAND
);
void	SCALAR_STORE(
	ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND, int VECTOR_REGISTER
);
void	BROADCAST_MEMORY(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int VECTOR_REGISTER,
	MEMORY_OPERAND OPERAND
);
void	BROADCAST_REGISTER(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE
);
void	VECTOR_MATH(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int OPCODE, int DESTINATION,
	int FIRST_SOURCE, int SECOND_SOURCE
);
void	VECTOR_MATH_MEMORY(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int OPCODE, int DESTINATION,
	int FIRST_SOURCE, MEMORY_OPERAND OPERAND
);
void	SCALAR_MATH(
	ASSEMBLER *ASSEMBLY, int OPCODE, int DESTINATION, int FIRST_SOURCE,
	int SECOND_SOURCE
);
void	SCALAR_MATH_MEMORY(
	ASSEMBLER *ASSEMBLY, int OPCODE, int DESTINATION, int FIRST_SOURCE,
	MEMORY_OPERAND OPERAND
);
void	MULTIPLY_ADD(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int FIRST_SOURCE,
	int SECOND_SOURCE
);
void	MULTIPLY_ADD_MEMORY(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int FIRST_SOURCE,
	MEMORY_OPERAND OPERAND
);
void	SCALAR_MULTIPLY_ADD(
	ASSEMBLER *ASSEMBLY, int DESTINATION, int FIRST_SOURCE, int SECOND_SOURCE
);
void	SCALAR_MULTIPLY_ADD_MEMORY(
	ASSEMBLER *ASSEMBLY, int DESTINATION, int FIRST_SOURCE,
	MEMORY_OPERAND OPERAND
);
void	MULTIPLY_THEN_ADD_MEMORY(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int FIRST_SOURCE,
	MEMORY_OPERAND OPERAND
);
void	SCALAR_COMPARE(
	ASSEMBLER *ASSEMBLY, int LEFT_REGISTER, int RIGHT_REGISTER
);
void	SCALAR_COMPARE_MEMORY(
	ASSEMBLER *ASSEMBLY, int LEFT_REGISTER, MEMORY_OPERAND OPERAND
);
void	BRANCH_TO_PIECE(ASSEMBLER *ASSEMBLY, int CONDITION, int32_t TARGET_ID);
void	VECTOR_COMPARE_MASK(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int FIRST_SOURCE,
	int SECOND_SOURCE, int PREDICATE
);
void	SCALAR_COMPARE_MASK(
	ASSEMBLER *ASSEMBLY, int DESTINATION, int FIRST_SOURCE, int SECOND_SOURCE,
	int PREDICATE
);
void	EXTRACT_HIGH_HALF(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE);
void	HORIZONTAL_ADD(
	ASSEMBLER *ASSEMBLY, int DESTINATION, int FIRST_SOURCE, int SECOND_SOURCE
);
void	VECTOR_FLOAT_TO_INTEGER(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE
);
void	VECTOR_INTEGER_TO_FLOAT(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE
);
void	VECTOR_INTEGER_ADD(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int FIRST_SOURCE,
	int SECOND_SOURCE
);
void	VECTOR_SHIFT_LEFT(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE,
	int SHIFT_COUNT
);
void	VECTOR_ROUND(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE,
	int ROUNDING_MODE
);
void	SCALAR_FROM_INTEGER(
	ASSEMBLER *ASSEMBLY, int DESTINATION, int FIRST_SOURCE, int INTEGER_REGISTER
);
void	CLEAR_UPPER_HALVES(ASSEMBLER *ASSEMBLY);
void	VECTOR_PERMUTE(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE,
	int SHUFFLE_CONTROL
);

enum
{
	OPCODE_ADD = 0X58,
	OPCODE_MULTIPLY = 0X59,
	OPCODE_SUBTRACT = 0X5C,
	OPCODE_MINIMUM = 0X5D,
	OPCODE_DIVIDE = 0X5E,
	OPCODE_MAXIMUM = 0X5F,
	OPCODE_AND = 0X54,
	OPCODE_EXCLUSIVE_OR = 0X57,
	OPCODE_SQUARE_ROOT = 0X51
};

void	*EXECUTABLE_ALLOCATE(size_t BYTE_COUNT);
void	EXECUTABLE_FREE(void *ADDRESS, size_t BYTE_COUNT);
void	*VIRTUAL_RESERVE(size_t BYTE_COUNT);
int		VIRTUAL_COMMIT(void *ADDRESS, size_t BYTE_COUNT, int EXECUTABLE);
int		VIRTUAL_PROTECT(void *ADDRESS, size_t BYTE_COUNT, int WRITABLE);
void	VIRTUAL_RELEASE(void *ADDRESS, size_t BYTE_COUNT);
void	LOAD_RELATIVE_ADDRESS(ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER);
void	JUMP_TO_REGISTER(ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER);
void	STORE_IMMEDIATE64(
	ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND, int32_t IMMEDIATE
);
void	MOVE_IMMEDIATE64(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, uint64_t IMMEDIATE
);
void	ADD_FROM_MEMORY(
	ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
);
void	LOAD_HALF_FLOATS(
	ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int VECTOR_REGISTER,
	MEMORY_OPERAND OPERAND
);
int		CPU_SUPPORTED(void);

#endif
