#include "JIT.h"
#include <stdlib.h>
#include <string.h>
#include <cpuid.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <sys/mman.h>
#endif

MEMORY_OPERAND
	MEMORY_AT(int BASE_REGISTER, int32_t DISPLACEMENT)
{
	MEMORY_OPERAND	OPERAND = { BASE_REGISTER, -1, 1, DISPLACEMENT };

	return (OPERAND);
}

MEMORY_OPERAND
	MEMORY_INDEXED(
		int BASE_REGISTER, int INDEX_REGISTER, int SCALE, int32_t DISPLACEMENT
	)
{
	MEMORY_OPERAND	OPERAND = {
		BASE_REGISTER, INDEX_REGISTER, SCALE, DISPLACEMENT
	};

	return (OPERAND);
}

void
	ASSEMBLER_INITIALIZE(ASSEMBLER *ASSEMBLY)
{
	memset(ASSEMBLY, 0, sizeof *ASSEMBLY);
}

void
	ASSEMBLER_FREE(ASSEMBLER *ASSEMBLY)
{
	free(ASSEMBLY->BYTES);
	free(ASSEMBLY->LABELS);
	free(ASSEMBLY->FIXUPS);
	free(ASSEMBLY->EXTERNAL_TARGETS);
	free(ASSEMBLY->EXTERNAL_POSITIONS);
	memset(ASSEMBLY, 0, sizeof *ASSEMBLY);
}

void
	ASSEMBLER_RESET(ASSEMBLER *ASSEMBLY)
{
	ASSEMBLY->BYTE_COUNT = 0;
	ASSEMBLY->LABEL_COUNT = 0;
	ASSEMBLY->FIXUP_COUNT = 0;
	ASSEMBLY->EXTERNAL_COUNT = 0;
}

void
	ASSEMBLER_EMIT_BYTE(ASSEMBLER *ASSEMBLY, int BYTE_VALUE)
{
	if (ASSEMBLY->BYTE_COUNT >= ASSEMBLY->BYTE_CAPACITY)
	{
		if (ASSEMBLY->BYTE_CAPACITY)
			ASSEMBLY->BYTE_CAPACITY = ASSEMBLY->BYTE_CAPACITY * 2;
		else
			ASSEMBLY->BYTE_CAPACITY = 4096;

		ASSEMBLY->BYTES = realloc(ASSEMBLY->BYTES, ASSEMBLY->BYTE_CAPACITY);
	}

	ASSEMBLY->BYTES[ASSEMBLY->BYTE_COUNT++] = (uint8_t)BYTE_VALUE;
}

void
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLER *ASSEMBLY, int32_t VALUE)
{
	int	BYTE_INDEX;

	for (BYTE_INDEX = 0; BYTE_INDEX < 4; BYTE_INDEX++)
		ASSEMBLER_EMIT_BYTE(ASSEMBLY, (VALUE >> (8 * BYTE_INDEX)) & 255);
}

static void
	WRITE_INTEGER32(uint8_t *DESTINATION, int32_t VALUE)
{
	int	BYTE_INDEX;

	for (BYTE_INDEX = 0; BYTE_INDEX < 4; BYTE_INDEX++)
		DESTINATION[BYTE_INDEX] = (uint8_t)((VALUE >> (8 * BYTE_INDEX)) & 255);
}

int
	ASSEMBLER_NEW_LABEL(ASSEMBLER *ASSEMBLY)
{
	if (ASSEMBLY->LABEL_COUNT >= ASSEMBLY->LABEL_CAPACITY)
	{
		if (ASSEMBLY->LABEL_CAPACITY)
			ASSEMBLY->LABEL_CAPACITY = ASSEMBLY->LABEL_CAPACITY * 2;
		else
			ASSEMBLY->LABEL_CAPACITY = 64;

		ASSEMBLY->LABELS = realloc(
			ASSEMBLY->LABELS, ASSEMBLY->LABEL_CAPACITY * sizeof(int32_t)
		);
	}

	ASSEMBLY->LABELS[ASSEMBLY->LABEL_COUNT] = -1;

	return (ASSEMBLY->LABEL_COUNT++);
}

void
	ASSEMBLER_BIND_LABEL(ASSEMBLER *ASSEMBLY, int LABEL)
{
	ASSEMBLY->LABELS[LABEL] = ASSEMBLY->BYTE_COUNT;
}

static void
	ADD_JUMP_FIXUP(ASSEMBLER *ASSEMBLY, int LABEL)
{
	if (ASSEMBLY->FIXUP_COUNT >= ASSEMBLY->FIXUP_CAPACITY)
	{
		if (ASSEMBLY->FIXUP_CAPACITY)
			ASSEMBLY->FIXUP_CAPACITY = ASSEMBLY->FIXUP_CAPACITY * 2;
		else
			ASSEMBLY->FIXUP_CAPACITY = 64;

		ASSEMBLY->FIXUPS = realloc(
			ASSEMBLY->FIXUPS, ASSEMBLY->FIXUP_CAPACITY * sizeof(JUMP_FIXUP)
		);
	}

	ASSEMBLY->FIXUPS[ASSEMBLY->FIXUP_COUNT].POSITION = ASSEMBLY->BYTE_COUNT;
	ASSEMBLY->FIXUPS[ASSEMBLY->FIXUP_COUNT].TARGET_LABEL = LABEL;
	ASSEMBLY->FIXUP_COUNT++;
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, 0);
}

int
	ASSEMBLER_FINISH(ASSEMBLER *ASSEMBLY)
{
	int	FIXUP_INDEX;

	for (FIXUP_INDEX = 0; FIXUP_INDEX < ASSEMBLY->FIXUP_COUNT; FIXUP_INDEX++)
	{
		int32_t	TARGET_OFFSET =
			ASSEMBLY->LABELS[ASSEMBLY->FIXUPS[FIXUP_INDEX].TARGET_LABEL];

		if (TARGET_OFFSET < 0)
			return (-1);

		WRITE_INTEGER32(
			ASSEMBLY->BYTES + ASSEMBLY->FIXUPS[FIXUP_INDEX].POSITION,
			TARGET_OFFSET - (ASSEMBLY->FIXUPS[FIXUP_INDEX].POSITION + 4)
		);
	}

	return (0);
}

static void
	ENCODE_MEMORY_OPERAND(
		ASSEMBLER *ASSEMBLY, int REGISTER_FIELD, MEMORY_OPERAND OPERAND
	)
{
	int	USES_SIB = (OPERAND.BASE & 7) == 4 || OPERAND.INDEX >= 0;

	ASSEMBLER_EMIT_BYTE(
		ASSEMBLY,
		0X80 | ((REGISTER_FIELD & 7) << 3) | (USES_SIB ? 4 : (OPERAND.BASE & 7))
	);

	if (USES_SIB)
	{
		int	SCALE_BITS;

		if (OPERAND.SCALE == 8)
			SCALE_BITS = 3;
		else if (OPERAND.SCALE == 4)
			SCALE_BITS = 2;
		else if (OPERAND.SCALE == 2)
			SCALE_BITS = 1;
		else
			SCALE_BITS = 0;

		int	INDEX_BITS;

		if (OPERAND.INDEX >= 0)
			INDEX_BITS = (OPERAND.INDEX & 7);
		else
			INDEX_BITS = 4;

		ASSEMBLER_EMIT_BYTE(
			ASSEMBLY, (SCALE_BITS << 6) | (INDEX_BITS << 3) | (OPERAND.BASE & 7)
		);
	}

	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, OPERAND.DISPLACEMENT);
}

static void
	REGISTER_EXTENSION_PREFIX(
		ASSEMBLER *ASSEMBLY, int WIDE, int REGISTER_FIELD, int INDEX_REGISTER,
		int BASE_REGISTER, int FORCE_PREFIX
	)
{
	int	PREFIX_BYTE = 0X40 | (WIDE << 3) | ((REGISTER_FIELD >> 3) << 2) |
		((INDEX_REGISTER >> 3) << 1) | (BASE_REGISTER >> 3);

	if (PREFIX_BYTE != 0X40 || FORCE_PREFIX)
		ASSEMBLER_EMIT_BYTE(ASSEMBLY, PREFIX_BYTE);
}

static void
	GENERAL_MEMORY_FORM(
		ASSEMBLER *ASSEMBLY, int WIDE, const uint8_t *OPCODE_BYTES,
		int OPCODE_COUNT, int REGISTER_FIELD, MEMORY_OPERAND OPERAND
	)
{
	REGISTER_EXTENSION_PREFIX(
		ASSEMBLY, WIDE, REGISTER_FIELD & 8,
		OPERAND.INDEX >= 0 ? (OPERAND.INDEX & 8) : 0, OPERAND.BASE & 8, 0
	);

	int	BYTE_INDEX;

	for (BYTE_INDEX = 0; BYTE_INDEX < OPCODE_COUNT; BYTE_INDEX++)
		ASSEMBLER_EMIT_BYTE(ASSEMBLY, OPCODE_BYTES[BYTE_INDEX]);

	ENCODE_MEMORY_OPERAND(ASSEMBLY, REGISTER_FIELD, OPERAND);
}

static void
	GENERAL_REGISTER_FORM(
		ASSEMBLER *ASSEMBLY, int WIDE, const uint8_t *OPCODE_BYTES,
		int OPCODE_COUNT, int REGISTER_FIELD, int RM_REGISTER
	)
{
	REGISTER_EXTENSION_PREFIX(
		ASSEMBLY, WIDE, REGISTER_FIELD & 8, 0, RM_REGISTER & 8, 0
	);

	int	BYTE_INDEX;

	for (BYTE_INDEX = 0; BYTE_INDEX < OPCODE_COUNT; BYTE_INDEX++)
		ASSEMBLER_EMIT_BYTE(ASSEMBLY, OPCODE_BYTES[BYTE_INDEX]);

	ASSEMBLER_EMIT_BYTE(
		ASSEMBLY, 0XC0 | ((REGISTER_FIELD & 7) << 3) | (RM_REGISTER & 7)
	);
}

void
	MOVE_FROM_MEMORY(
		ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
	)
{
	uint8_t	OPCODE[1] = { 0X8B };

	GENERAL_MEMORY_FORM(ASSEMBLY, 1, OPCODE, 1, REGISTER_NUMBER, OPERAND);
}

void
	MOVE_TO_MEMORY(
		ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND, int REGISTER_NUMBER
	)
{
	uint8_t	OPCODE[1] = { 0X89 };

	GENERAL_MEMORY_FORM(ASSEMBLY, 1, OPCODE, 1, REGISTER_NUMBER, OPERAND);
}

void
	MOVE32_FROM_MEMORY(
		ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
	)
{
	uint8_t	OPCODE[1] = { 0X8B };

	GENERAL_MEMORY_FORM(ASSEMBLY, 0, OPCODE, 1, REGISTER_NUMBER, OPERAND);
}

void
	MOVE32_TO_MEMORY(
		ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND, int REGISTER_NUMBER
	)
{
	uint8_t	OPCODE[1] = { 0X89 };

	GENERAL_MEMORY_FORM(ASSEMBLY, 0, OPCODE, 1, REGISTER_NUMBER, OPERAND);
}

void
	MOVE_SIGN_EXTENDED(
		ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
	)
{
	uint8_t	OPCODE[1] = { 0X63 };

	GENERAL_MEMORY_FORM(ASSEMBLY, 1, OPCODE, 1, REGISTER_NUMBER, OPERAND);
}

void
	MOVE_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE)
{
	uint8_t	OPCODE[1] = { 0X89 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, SOURCE, DESTINATION);
}

void
	MOVE_IMMEDIATE(ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, int32_t IMMEDIATE)
{
	uint8_t	OPCODE[1] = { 0XC7 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, 0, REGISTER_NUMBER);
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, IMMEDIATE);
}

void
	MOVE_IMMEDIATE64(
		ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, uint64_t IMMEDIATE
	)
{
	REGISTER_EXTENSION_PREFIX(ASSEMBLY, 1, 0, 0, REGISTER_NUMBER & 8, 0);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0XB8 | (REGISTER_NUMBER & 7));

	int	BYTE_INDEX;

	for (BYTE_INDEX = 0; BYTE_INDEX < 8; BYTE_INDEX++)
		ASSEMBLER_EMIT_BYTE(
			ASSEMBLY, (int)((IMMEDIATE >> (8 * BYTE_INDEX)) & 0XFF)
		);
}

void
	STORE_IMMEDIATE64(
		ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND, int32_t IMMEDIATE
	)
{
	uint8_t	OPCODE[1] = { 0XC7 };

	GENERAL_MEMORY_FORM(ASSEMBLY, 1, OPCODE, 1, 0, OPERAND);
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, IMMEDIATE);
}

void
	ADD_FROM_MEMORY(
		ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
	)
{
	uint8_t	OPCODE[1] = { 0X03 };

	GENERAL_MEMORY_FORM(ASSEMBLY, 1, OPCODE, 1, REGISTER_NUMBER, OPERAND);
}

void
	LOAD_RELATIVE_ADDRESS(ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER)
{
	REGISTER_EXTENSION_PREFIX(ASSEMBLY, 1, REGISTER_NUMBER & 8, 0, 0, 0);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X8D);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X05 | ((REGISTER_NUMBER & 7) << 3));
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, 0);
}

void
	JUMP_TO_REGISTER(ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER)
{
	if (REGISTER_NUMBER & 8)
		ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X41);

	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0XFF);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0XE0 | (REGISTER_NUMBER & 7));
}

void
	STORE_IMMEDIATE32(
		ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND, int32_t IMMEDIATE
	)
{
	uint8_t	OPCODE[1] = { 0XC7 };

	GENERAL_MEMORY_FORM(ASSEMBLY, 0, OPCODE, 1, 0, OPERAND);
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, IMMEDIATE);
}

void
	LOAD_ADDRESS(
		ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
	)
{
	uint8_t	OPCODE[1] = { 0X8D };

	GENERAL_MEMORY_FORM(ASSEMBLY, 1, OPCODE, 1, REGISTER_NUMBER, OPERAND);
}

void
	ADD_IMMEDIATE(ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, int32_t IMMEDIATE)
{
	uint8_t	OPCODE[1] = { 0X81 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, 0, REGISTER_NUMBER);
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, IMMEDIATE);
}

void
	SUBTRACT_IMMEDIATE(
		ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, int32_t IMMEDIATE
	)
{
	uint8_t	OPCODE[1] = { 0X81 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, 5, REGISTER_NUMBER);
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, IMMEDIATE);
}

void
	COMPARE_IMMEDIATE(
		ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, int32_t IMMEDIATE
	)
{
	uint8_t	OPCODE[1] = { 0X81 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, 7, REGISTER_NUMBER);
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, IMMEDIATE);
}

void
	ADD_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE)
{
	uint8_t	OPCODE[1] = { 0X01 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, SOURCE, DESTINATION);
}

void
	SUBTRACT_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE)
{
	uint8_t	OPCODE[1] = { 0X29 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, SOURCE, DESTINATION);
}

void
	COMPARE_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE)
{
	uint8_t	OPCODE[1] = { 0X39 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, SOURCE, DESTINATION);
}

void
	COMPARE_MEMORY(
		ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, MEMORY_OPERAND OPERAND
	)
{
	uint8_t	OPCODE[1] = { 0X3B };

	GENERAL_MEMORY_FORM(ASSEMBLY, 1, OPCODE, 1, REGISTER_NUMBER, OPERAND);
}

void
	MULTIPLY_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE)
{
	uint8_t	OPCODE[2] = { 0X0F, 0XAF };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 2, DESTINATION, SOURCE);
}

void
	MULTIPLY_IMMEDIATE(
		ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE, int32_t IMMEDIATE
	)
{
	uint8_t	OPCODE[1] = { 0X69 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, DESTINATION, SOURCE);
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, IMMEDIATE);
}

void
	SHIFT_LEFT_IMMEDIATE(
		ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER, int SHIFT_COUNT
	)
{
	uint8_t	OPCODE[1] = { 0XC1 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, 4, REGISTER_NUMBER);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, SHIFT_COUNT);
}

void
	TEST_REGISTER(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE)
{
	uint8_t	OPCODE[1] = { 0X85 };

	GENERAL_REGISTER_FORM(ASSEMBLY, 1, OPCODE, 1, SOURCE, DESTINATION);
}

void
	PUSH_REGISTER(ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER)
{
	if (REGISTER_NUMBER & 8)
		ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X41);

	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X50 + (REGISTER_NUMBER & 7));
}

void
	POP_REGISTER(ASSEMBLER *ASSEMBLY, int REGISTER_NUMBER)
{
	if (REGISTER_NUMBER & 8)
		ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X41);

	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X58 + (REGISTER_NUMBER & 7));
}

void
	RETURN_INSTRUCTION(ASSEMBLER *ASSEMBLY)
{
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0XC3);
}

void
	CALL_MEMORY(ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND)
{
	uint8_t	OPCODE[1] = { 0XFF };

	GENERAL_MEMORY_FORM(ASSEMBLY, 0, OPCODE, 1, 2, OPERAND);
}

void
	JUMP_TO_MEMORY(ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND)
{
	uint8_t	OPCODE[1] = { 0XFF };

	GENERAL_MEMORY_FORM(ASSEMBLY, 0, OPCODE, 1, 4, OPERAND);
}

void
	BRANCH_TO_LABEL(ASSEMBLER *ASSEMBLY, int CONDITION, int LABEL)
{
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X0F);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X80 + CONDITION);
	ADD_JUMP_FIXUP(ASSEMBLY, LABEL);
}

void
	JUMP_TO_LABEL(ASSEMBLER *ASSEMBLY, int LABEL)
{
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0XE9);
	ADD_JUMP_FIXUP(ASSEMBLY, LABEL);
}

static void
	RECORD_EXTERNAL_TARGET(ASSEMBLER *ASSEMBLY, int32_t TARGET_ID)
{
	if (ASSEMBLY->EXTERNAL_COUNT >= ASSEMBLY->EXTERNAL_CAPACITY)
	{
		if (ASSEMBLY->EXTERNAL_CAPACITY)
			ASSEMBLY->EXTERNAL_CAPACITY = ASSEMBLY->EXTERNAL_CAPACITY * 2;
		else
			ASSEMBLY->EXTERNAL_CAPACITY = 16;

		ASSEMBLY->EXTERNAL_TARGETS = realloc(
			ASSEMBLY->EXTERNAL_TARGETS,
			ASSEMBLY->EXTERNAL_CAPACITY * sizeof(int32_t)
		);
		ASSEMBLY->EXTERNAL_POSITIONS = realloc(
			ASSEMBLY->EXTERNAL_POSITIONS,
			ASSEMBLY->EXTERNAL_CAPACITY * sizeof(int32_t)
		);
	}

	ASSEMBLY->EXTERNAL_TARGETS[ASSEMBLY->EXTERNAL_COUNT] = TARGET_ID;
	ASSEMBLY->EXTERNAL_POSITIONS[ASSEMBLY->EXTERNAL_COUNT] =
		ASSEMBLY->BYTE_COUNT;
	ASSEMBLY->EXTERNAL_COUNT++;
	ASSEMBLER_EMIT_INTEGER32(ASSEMBLY, 0);
}

void
	JUMP_TO_PIECE(ASSEMBLER *ASSEMBLY, int32_t TARGET_ID)
{
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0XE9);
	RECORD_EXTERNAL_TARGET(ASSEMBLY, TARGET_ID);
}

void
	BRANCH_TO_PIECE(ASSEMBLER *ASSEMBLY, int CONDITION, int32_t TARGET_ID)
{
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X0F);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X80 + CONDITION);
	RECORD_EXTERNAL_TARGET(ASSEMBLY, TARGET_ID);
}

static void
	VECTOR_EXTENSION_PREFIX(
		ASSEMBLER *ASSEMBLY, int EXTEND_REGISTER, int EXTEND_INDEX,
		int EXTEND_BASE, int OPCODE_MAP, int WIDE, int EXTRA_SOURCE,
		int VECTOR_LENGTH, int PREFIX_CODE
	)
{
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0XC4);
	ASSEMBLER_EMIT_BYTE(
		ASSEMBLY,
		((~EXTEND_REGISTER & 1) << 7) | ((~EXTEND_INDEX & 1) << 6) |
			((~EXTEND_BASE & 1) << 5) | OPCODE_MAP
	);
	ASSEMBLER_EMIT_BYTE(
		ASSEMBLY,
		(WIDE << 7) | ((~EXTRA_SOURCE & 15) << 3) | (VECTOR_LENGTH << 2) |
			PREFIX_CODE
	);
}

static void
	VECTOR_MEMORY_FORM(
		ASSEMBLER *ASSEMBLY, int PREFIX_CODE, int OPCODE_MAP, int WIDE,
		int VECTOR_LENGTH, int OPCODE, int REGISTER_FIELD, int EXTRA_SOURCE,
		MEMORY_OPERAND OPERAND
	)
{
	VECTOR_EXTENSION_PREFIX(
		ASSEMBLY, REGISTER_FIELD >> 3,
		OPERAND.INDEX >= 0 ? OPERAND.INDEX >> 3 : 0, OPERAND.BASE >> 3,
		OPCODE_MAP, WIDE, EXTRA_SOURCE, VECTOR_LENGTH, PREFIX_CODE
	);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, OPCODE);
	ENCODE_MEMORY_OPERAND(ASSEMBLY, REGISTER_FIELD, OPERAND);
}

static void
	VECTOR_REGISTER_FORM(
		ASSEMBLER *ASSEMBLY, int PREFIX_CODE, int OPCODE_MAP, int WIDE,
		int VECTOR_LENGTH, int OPCODE, int REGISTER_FIELD, int EXTRA_SOURCE,
		int RM_REGISTER
	)
{
	VECTOR_EXTENSION_PREFIX(
		ASSEMBLY, REGISTER_FIELD >> 3, 0, RM_REGISTER >> 3, OPCODE_MAP, WIDE,
		EXTRA_SOURCE, VECTOR_LENGTH, PREFIX_CODE
	);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, OPCODE);
	ASSEMBLER_EMIT_BYTE(
		ASSEMBLY, 0XC0 | ((REGISTER_FIELD & 7) << 3) | (RM_REGISTER & 7)
	);
}

void
	VECTOR_LOAD(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int VECTOR_REGISTER,
		MEMORY_OPERAND OPERAND
	)
{
	VECTOR_MEMORY_FORM(
		ASSEMBLY, 0, 1, 0, VECTOR_LENGTH, 0X10, VECTOR_REGISTER, 0, OPERAND
	);
}

void
	VECTOR_STORE(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, MEMORY_OPERAND OPERAND,
		int VECTOR_REGISTER
	)
{
	VECTOR_MEMORY_FORM(
		ASSEMBLY, 0, 1, 0, VECTOR_LENGTH, 0X11, VECTOR_REGISTER, 0, OPERAND
	);
}

void
	VECTOR_MOVE(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 0, 1, 0, VECTOR_LENGTH, 0X10, DESTINATION, 0, SOURCE
	);
}

void
	SCALAR_LOAD(
		ASSEMBLER *ASSEMBLY, int VECTOR_REGISTER, MEMORY_OPERAND OPERAND
	)
{
	VECTOR_MEMORY_FORM(ASSEMBLY, 2, 1, 0, 0, 0X10, VECTOR_REGISTER, 0, OPERAND);
}

void
	SCALAR_STORE(
		ASSEMBLER *ASSEMBLY, MEMORY_OPERAND OPERAND, int VECTOR_REGISTER
	)
{
	VECTOR_MEMORY_FORM(ASSEMBLY, 2, 1, 0, 0, 0X11, VECTOR_REGISTER, 0, OPERAND);
}

void
	BROADCAST_MEMORY(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int VECTOR_REGISTER,
		MEMORY_OPERAND OPERAND
	)
{
	VECTOR_MEMORY_FORM(
		ASSEMBLY, 1, 2, 0, VECTOR_LENGTH, 0X18, VECTOR_REGISTER, 0, OPERAND
	);
}

void
	BROADCAST_REGISTER(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 1, 2, 0, VECTOR_LENGTH, 0X18, DESTINATION, 0, SOURCE
	);
}

void
	VECTOR_MATH(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int OPCODE, int DESTINATION,
		int FIRST_SOURCE, int SECOND_SOURCE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 0, 1, 0, VECTOR_LENGTH, OPCODE, DESTINATION, FIRST_SOURCE,
		SECOND_SOURCE
	);
}

void
	VECTOR_MATH_MEMORY(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int OPCODE, int DESTINATION,
		int FIRST_SOURCE, MEMORY_OPERAND OPERAND
	)
{
	VECTOR_MEMORY_FORM(
		ASSEMBLY, 0, 1, 0, VECTOR_LENGTH, OPCODE, DESTINATION, FIRST_SOURCE,
		OPERAND
	);
}

void
	SCALAR_MATH(
		ASSEMBLER *ASSEMBLY, int OPCODE, int DESTINATION, int FIRST_SOURCE,
		int SECOND_SOURCE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 2, 1, 0, 0, OPCODE, DESTINATION, FIRST_SOURCE, SECOND_SOURCE
	);
}

void
	SCALAR_MATH_MEMORY(
		ASSEMBLER *ASSEMBLY, int OPCODE, int DESTINATION, int FIRST_SOURCE,
		MEMORY_OPERAND OPERAND
	)
{
	VECTOR_MEMORY_FORM(
		ASSEMBLY, 2, 1, 0, 0, OPCODE, DESTINATION, FIRST_SOURCE, OPERAND
	);
}

void
	MULTIPLY_ADD(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION,
		int FIRST_SOURCE, int SECOND_SOURCE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 1, 2, 0, VECTOR_LENGTH, 0XB8, DESTINATION, FIRST_SOURCE,
		SECOND_SOURCE
	);
}

void
	MULTIPLY_ADD_MEMORY(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION,
		int FIRST_SOURCE, MEMORY_OPERAND OPERAND
	)
{
	VECTOR_MEMORY_FORM(
		ASSEMBLY, 1, 2, 0, VECTOR_LENGTH, 0XB8, DESTINATION, FIRST_SOURCE,
		OPERAND
	);
}

void
	SCALAR_MULTIPLY_ADD(
		ASSEMBLER *ASSEMBLY, int DESTINATION, int FIRST_SOURCE,
		int SECOND_SOURCE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 1, 2, 0, 0, 0XB9, DESTINATION, FIRST_SOURCE, SECOND_SOURCE
	);
}

void
	SCALAR_MULTIPLY_ADD_MEMORY(
		ASSEMBLER *ASSEMBLY, int DESTINATION, int FIRST_SOURCE,
		MEMORY_OPERAND OPERAND
	)
{
	VECTOR_MEMORY_FORM(
		ASSEMBLY, 1, 2, 0, 0, 0XB9, DESTINATION, FIRST_SOURCE, OPERAND
	);
}

void
	MULTIPLY_THEN_ADD_MEMORY(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION,
		int FIRST_SOURCE, MEMORY_OPERAND OPERAND
	)
{
	VECTOR_MEMORY_FORM(
		ASSEMBLY, 1, 2, 0, VECTOR_LENGTH, 0XA8, DESTINATION, FIRST_SOURCE,
		OPERAND
	);
}

void
	SCALAR_COMPARE(ASSEMBLER *ASSEMBLY, int LEFT_REGISTER, int RIGHT_REGISTER)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 0, 1, 0, 0, 0X2E, LEFT_REGISTER, 0, RIGHT_REGISTER
	);
}

void
	SCALAR_COMPARE_MEMORY(
		ASSEMBLER *ASSEMBLY, int LEFT_REGISTER, MEMORY_OPERAND OPERAND
	)
{
	VECTOR_MEMORY_FORM(ASSEMBLY, 0, 1, 0, 0, 0X2E, LEFT_REGISTER, 0, OPERAND);
}

void
	VECTOR_COMPARE_MASK(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION,
		int FIRST_SOURCE, int SECOND_SOURCE, int PREDICATE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 0, 1, 0, VECTOR_LENGTH, 0XC2, DESTINATION, FIRST_SOURCE,
		SECOND_SOURCE
	);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, PREDICATE);
}

void
	SCALAR_COMPARE_MASK(
		ASSEMBLER *ASSEMBLY, int DESTINATION, int FIRST_SOURCE,
		int SECOND_SOURCE, int PREDICATE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 2, 1, 0, 0, 0XC2, DESTINATION, FIRST_SOURCE, SECOND_SOURCE
	);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, PREDICATE);
}

void
	EXTRACT_HIGH_HALF(ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE)
{
	VECTOR_REGISTER_FORM(ASSEMBLY, 1, 3, 0, 1, 0X19, SOURCE, 0, DESTINATION);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 1);
}

void
	HORIZONTAL_ADD(
		ASSEMBLER *ASSEMBLY, int DESTINATION, int FIRST_SOURCE,
		int SECOND_SOURCE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 3, 1, 0, 0, 0X7C, DESTINATION, FIRST_SOURCE, SECOND_SOURCE
	);
}

void
	VECTOR_FLOAT_TO_INTEGER(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 1, 1, 0, VECTOR_LENGTH, 0X5B, DESTINATION, 0, SOURCE
	);
}

void
	VECTOR_INTEGER_TO_FLOAT(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 0, 1, 0, VECTOR_LENGTH, 0X5B, DESTINATION, 0, SOURCE
	);
}

void
	VECTOR_INTEGER_ADD(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION,
		int FIRST_SOURCE, int SECOND_SOURCE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 1, 1, 0, VECTOR_LENGTH, 0XFE, DESTINATION, FIRST_SOURCE,
		SECOND_SOURCE
	);
}

void
	VECTOR_SHIFT_LEFT(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE,
		int SHIFT_COUNT
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 1, 1, 0, VECTOR_LENGTH, 0X72, 6, DESTINATION, SOURCE
	);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, SHIFT_COUNT);
}

void
	VECTOR_ROUND(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE,
		int ROUNDING_MODE
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 1, 3, 0, VECTOR_LENGTH, 0X08, DESTINATION, 0, SOURCE
	);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, ROUNDING_MODE);
}

void
	SCALAR_FROM_INTEGER(
		ASSEMBLER *ASSEMBLY, int DESTINATION, int FIRST_SOURCE,
		int INTEGER_REGISTER
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 2, 1, 1, 0, 0X2A, DESTINATION, FIRST_SOURCE, INTEGER_REGISTER
	);
}

void
	LOAD_HALF_FLOATS(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int VECTOR_REGISTER,
		MEMORY_OPERAND OPERAND
	)
{
	VECTOR_MEMORY_FORM(
		ASSEMBLY, 1, 2, 0, VECTOR_LENGTH, 0X13, VECTOR_REGISTER, 0, OPERAND
	);
}

void
	VECTOR_PERMUTE(
		ASSEMBLER *ASSEMBLY, int VECTOR_LENGTH, int DESTINATION, int SOURCE,
		int SHUFFLE_CONTROL
	)
{
	VECTOR_REGISTER_FORM(
		ASSEMBLY, 1, 3, 0, VECTOR_LENGTH, 0X04, DESTINATION, 0, SOURCE
	);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, SHUFFLE_CONTROL);
}

void
	CLEAR_UPPER_HALVES(ASSEMBLER *ASSEMBLY)
{
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0XC5);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0XF8);
	ASSEMBLER_EMIT_BYTE(ASSEMBLY, 0X77);
}

void
	*EXECUTABLE_ALLOCATE(size_t BYTE_COUNT)
{
#ifdef _WIN32
	return (
		VirtualAlloc(
			NULL, BYTE_COUNT, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE
		)
	);
#else
	void	*ADDRESS = mmap(
		NULL, BYTE_COUNT, PROT_READ | PROT_WRITE | PROT_EXEC,
		MAP_PRIVATE | MAP_ANONYMOUS, -1, 0
	);

	if (ADDRESS == MAP_FAILED)
		return (NULL);

	return (ADDRESS);
#endif
}

void
	EXECUTABLE_FREE(void *ADDRESS, size_t BYTE_COUNT)
{
	if (!ADDRESS)
		return ;
#ifdef _WIN32
	(void)BYTE_COUNT;
	VirtualFree(ADDRESS, 0, MEM_RELEASE);
#else
	munmap(ADDRESS, BYTE_COUNT);
#endif
}

void
	*VIRTUAL_RESERVE(size_t BYTE_COUNT)
{
#ifdef _WIN32
	return (VirtualAlloc(NULL, BYTE_COUNT, MEM_RESERVE, PAGE_NOACCESS));
#else
	void	*ADDRESS = mmap(
		NULL, BYTE_COUNT, PROT_NONE,
		MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0
	);

	if (ADDRESS == MAP_FAILED)
		return (NULL);

	return (ADDRESS);
#endif
}

int
	VIRTUAL_COMMIT(void *ADDRESS, size_t BYTE_COUNT, int EXECUTABLE)
{
#ifdef _WIN32
	if (
		VirtualAlloc(
			ADDRESS, BYTE_COUNT, MEM_COMMIT,
			EXECUTABLE ? PAGE_EXECUTE_READWRITE : PAGE_READWRITE
		)
	)
		return (0);

	return (-1);
#else
	return (
		mprotect(
			ADDRESS, BYTE_COUNT,
			PROT_READ | PROT_WRITE | (EXECUTABLE ? PROT_EXEC : 0)
		)
	);
#endif
}

int
	VIRTUAL_PROTECT(void *ADDRESS, size_t BYTE_COUNT, int WRITABLE)
{
#ifdef _WIN32
	DWORD	OLD_PROTECTION;

	if (
		VirtualProtect(
			ADDRESS, BYTE_COUNT,
			WRITABLE ? PAGE_EXECUTE_READWRITE : PAGE_EXECUTE_READ,
			&OLD_PROTECTION
		)
	)
		return (0);

	return (-1);
#else
	return (
		mprotect(
			ADDRESS, BYTE_COUNT,
			PROT_READ | PROT_EXEC | (WRITABLE ? PROT_WRITE : 0)
		)
	);
#endif
}

void
	VIRTUAL_RELEASE(void *ADDRESS, size_t BYTE_COUNT)
{
	if (!ADDRESS)
		return ;
#ifdef _WIN32
	(void)BYTE_COUNT;
	VirtualFree(ADDRESS, 0, MEM_RELEASE);
#else
	munmap(ADDRESS, BYTE_COUNT);
#endif
}

int
	CPU_SUPPORTED(void)
{
	unsigned	CPUID_EAX;
	unsigned	CPUID_EBX;
	unsigned	CPUID_ECX;
	unsigned	CPUID_EDX;

	if (!__get_cpuid(1, &CPUID_EAX, &CPUID_EBX, &CPUID_ECX, &CPUID_EDX))
		return (0);

	if (
		!(CPUID_ECX & ((unsigned int)1 << 12)) ||
		!(CPUID_ECX & ((unsigned int)1 << 27)) ||
		!(CPUID_ECX & ((unsigned int)1 << 28)) ||
		!(CPUID_ECX & ((unsigned int)1 << 29))
	)
		return (0);

	unsigned	STATE_MASK_LOW;
	unsigned	STATE_MASK_HIGH;

	__asm__ volatile("xgetbv"
		: "=a"(STATE_MASK_LOW), "=d"(STATE_MASK_HIGH)
		: "c"(0));

	if ((STATE_MASK_LOW & 6) != 6)
		return (0);

	if (
		!__get_cpuid_count(7, 0, &CPUID_EAX, &CPUID_EBX, &CPUID_ECX, &CPUID_EDX)
	)
		return (0);

	return ((CPUID_EBX & ((unsigned int)1 << 5)) != 0);
}
