#include "CODE.h"
#include <stddef.h>

#define STATE_FIELD(FIELD_NAME) \
	MEMORY_AT(R15, (int32_t)offsetof(KERNEL_CONTEXT, FIELD_NAME))
#define STATE_CONSTANT(CONSTANT_INDEX) \
	MEMORY_AT( \
		R15, \
		(int32_t)(offsetof(KERNEL_CONTEXT, CONSTANTS) + (CONSTANT_INDEX) * 32) \
	)

static MEMORY_OPERAND
	OPERAND_AT(int BASE_REGISTER, int INDEX_REGISTER, int32_t DISPLACEMENT)
{
	if (INDEX_REGISTER >= 0)
		return (MEMORY_INDEXED(BASE_REGISTER, INDEX_REGISTER, 1, DISPLACEMENT));

	return (MEMORY_AT(BASE_REGISTER, DISPLACEMENT));
}

static int	HALF_WEIGHTS;

static MEMORY_OPERAND
	WEIGHT_OPERAND(int BASE_REGISTER, int INDEX_REGISTER, int32_t DISPLACEMENT)
{
	return (
		OPERAND_AT(
			BASE_REGISTER, INDEX_REGISTER,
			HALF_WEIGHTS ? DISPLACEMENT / 2 : DISPLACEMENT
		)
	);
}

static void
	LOAD_WEIGHTS(
		ASSEMBLER *ASSEMBLY, int DESTINATION, MEMORY_OPERAND MEMORY_SOURCE
	)
{
	if (HALF_WEIGHTS)
		LOAD_HALF_FLOATS(ASSEMBLY, 1, DESTINATION, MEMORY_SOURCE);
	else
		VECTOR_LOAD(ASSEMBLY, 1, DESTINATION, MEMORY_SOURCE);
}

static void
	MULTIPLY_ADD_WEIGHTS(
		ASSEMBLER *ASSEMBLY, int ACCUMULATOR, int FACTOR_REGISTER,
		MEMORY_OPERAND MEMORY_SOURCE
	)
{
	if (HALF_WEIGHTS)
	{
		LOAD_HALF_FLOATS(ASSEMBLY, 1, 15, MEMORY_SOURCE);
		MULTIPLY_ADD(ASSEMBLY, 1, ACCUMULATOR, FACTOR_REGISTER, 15);
	}
	else
		MULTIPLY_ADD_MEMORY(
			ASSEMBLY, 1, ACCUMULATOR, FACTOR_REGISTER, MEMORY_SOURCE
		);
}

static int64_t
	KERNEL_LAYER_RESIDUAL(WEB *NEURAL_WEB, int AREA_INDEX)
{
	return (
		LAYER_RESIDUAL(NEURAL_WEB, HALF_WEIGHTS ? (AREA_INDEX & 1) : AREA_INDEX)
	);
}

static int64_t
	KERNEL_LAYER_NORMALIZED(WEB *NEURAL_WEB, int AREA_INDEX)
{
	return (
		LAYER_NORMALIZED(
			NEURAL_WEB, HALF_WEIGHTS ? (AREA_INDEX & 1) : AREA_INDEX
		)
	);
}

static void
	WEIGHT_MATH(
		ASSEMBLER *ASSEMBLY, int OPERATION, int DESTINATION, int SOURCE,
		MEMORY_OPERAND MEMORY_SOURCE
	)
{
	if (HALF_WEIGHTS)
	{
		LOAD_HALF_FLOATS(ASSEMBLY, 1, 15, MEMORY_SOURCE);
		VECTOR_MATH(ASSEMBLY, 1, OPERATION, DESTINATION, SOURCE, 15);
	}
	else
		VECTOR_MATH_MEMORY(
			ASSEMBLY, 1, OPERATION, DESTINATION, SOURCE, MEMORY_SOURCE
		);
}

static void
	ADD_SCALAR_WEIGHT(
		ASSEMBLER *ASSEMBLY, int DESTINATION, int SOURCE,
		MEMORY_OPERAND MEMORY_SOURCE
	)
{
	if (HALF_WEIGHTS)
	{
		LOAD_HALF_FLOATS(ASSEMBLY, 0, 15, MEMORY_SOURCE);
		SCALAR_MATH(ASSEMBLY, OPCODE_ADD, DESTINATION, SOURCE, 15);
	}
	else
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_ADD, DESTINATION, SOURCE, MEMORY_SOURCE
		);
}

static void
	ZERO_VECTOR(ASSEMBLER *ASSEMBLY, int VECTOR_REGISTER)
{
	VECTOR_MATH(
		ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, VECTOR_REGISTER, VECTOR_REGISTER,
		VECTOR_REGISTER
	);
}

static void
	HORIZONTAL_SUM(
		ASSEMBLER *ASSEMBLY, int VECTOR_REGISTER, int SCRATCH_REGISTER
	)
{
	EXTRACT_HIGH_HALF(ASSEMBLY, SCRATCH_REGISTER, VECTOR_REGISTER);
	VECTOR_MATH(
		ASSEMBLY, 0, OPCODE_ADD, VECTOR_REGISTER, VECTOR_REGISTER,
		SCRATCH_REGISTER
	);
	HORIZONTAL_ADD(ASSEMBLY, VECTOR_REGISTER, VECTOR_REGISTER, VECTOR_REGISTER);
	HORIZONTAL_ADD(ASSEMBLY, VECTOR_REGISTER, VECTOR_REGISTER, VECTOR_REGISTER);
}

typedef void (*CHUNK_BODY)(
	ASSEMBLER *ASSEMBLY, void *LAYOUT_DATA, int INDEX_REGISTER, int32_t OFFSET
);

static void
	FOR_EACH_CHUNK(
		ASSEMBLER *ASSEMBLY, int ELEMENT_COUNT, CHUNK_BODY BODY_FUNCTION,
		void *BODY_STATE
	)
{
	if (ELEMENT_COUNT <= 128 || HALF_WEIGHTS)
	{
		int	CHUNK_INDEX;

		for (CHUNK_INDEX = 0; CHUNK_INDEX < ELEMENT_COUNT / 8; CHUNK_INDEX++)
			BODY_FUNCTION(ASSEMBLY, BODY_STATE, -1, 32 * CHUNK_INDEX);

		return ;
	}

	int	CHUNK_COUNT = ELEMENT_COUNT / 8;
	int	PAIR_COUNT = CHUNK_COUNT / 2;

	MOVE_IMMEDIATE(ASSEMBLY, R11, 0);

	int	LOOP_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);

	ASSEMBLER_BIND_LABEL(ASSEMBLY, LOOP_TOP);
	BODY_FUNCTION(ASSEMBLY, BODY_STATE, R11, 0);
	BODY_FUNCTION(ASSEMBLY, BODY_STATE, R11, 32);
	ADD_IMMEDIATE(ASSEMBLY, R11, 64);
	COMPARE_IMMEDIATE(ASSEMBLY, R11, PAIR_COUNT * 64);
	BRANCH_TO_LABEL(ASSEMBLY, CC_L, LOOP_TOP);

	if (CHUNK_COUNT & 1)
		BODY_FUNCTION(ASSEMBLY, BODY_STATE, R11, 0);
}

typedef struct
{
	int		FIRST_ACCUMULATOR;
	int		SECOND_ACCUMULATOR;
	int		TEMPORARY;
	int		FIRST_BASE;
	int		SECOND_BASE;
	int32_t	FIRST_DISPLACEMENT;
	int32_t	SECOND_DISPLACEMENT;
	int		USE_SECOND;
} DOT_REGISTERS;

static void
	DOT_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	DOT_REGISTERS	*DOT_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, DOT_STATE->TEMPORARY,
		OPERAND_AT(
			DOT_STATE->FIRST_BASE, INDEX_REGISTER,
			DOT_STATE->FIRST_DISPLACEMENT + OFFSET
		)
	);
	MULTIPLY_ADD_MEMORY(
		ASSEMBLY, 1,
		DOT_STATE->USE_SECOND ? DOT_STATE->SECOND_ACCUMULATOR
		: DOT_STATE->FIRST_ACCUMULATOR,
		DOT_STATE->TEMPORARY,
		OPERAND_AT(
			DOT_STATE->SECOND_BASE, INDEX_REGISTER,
			DOT_STATE->SECOND_DISPLACEMENT + OFFSET
		)
	);
	DOT_STATE->USE_SECOND ^= 1;
}

static void
	DOT_WEIGHT_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	DOT_REGISTERS	*DOT_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, DOT_STATE->TEMPORARY,
		OPERAND_AT(
			DOT_STATE->FIRST_BASE, INDEX_REGISTER,
			DOT_STATE->FIRST_DISPLACEMENT + OFFSET
		)
	);
	MULTIPLY_ADD_WEIGHTS(
		ASSEMBLY,
		DOT_STATE->USE_SECOND ? DOT_STATE->SECOND_ACCUMULATOR
		: DOT_STATE->FIRST_ACCUMULATOR,
		DOT_STATE->TEMPORARY,
		WEIGHT_OPERAND(
			DOT_STATE->SECOND_BASE, INDEX_REGISTER,
			DOT_STATE->SECOND_DISPLACEMENT + OFFSET
		)
	);
	DOT_STATE->USE_SECOND ^= 1;
}

static void
	DOT_WITH_WEIGHTS(
		ASSEMBLER *ASSEMBLY, int RESULT_REGISTER, int SECOND_ACCUMULATOR,
		int TEMPORARY_REGISTER, int FIRST_BASE, int32_t FIRST_DISPLACEMENT,
		int SECOND_BASE, int32_t SECOND_DISPLACEMENT, int ELEMENT_COUNT
	)
{
	DOT_REGISTERS	DOT_STATE = {
		RESULT_REGISTER, SECOND_ACCUMULATOR, TEMPORARY_REGISTER, FIRST_BASE,
		SECOND_BASE, FIRST_DISPLACEMENT, SECOND_DISPLACEMENT, 0
	};

	ZERO_VECTOR(ASSEMBLY, RESULT_REGISTER);
	ZERO_VECTOR(ASSEMBLY, SECOND_ACCUMULATOR);
	FOR_EACH_CHUNK(ASSEMBLY, ELEMENT_COUNT, DOT_WEIGHT_CHUNK, &DOT_STATE);
	VECTOR_MATH(
		ASSEMBLY, 1, OPCODE_ADD, RESULT_REGISTER, RESULT_REGISTER,
		SECOND_ACCUMULATOR
	);
	HORIZONTAL_SUM(ASSEMBLY, RESULT_REGISTER, TEMPORARY_REGISTER);
}

static void
	DOT_PRODUCT(
		ASSEMBLER *ASSEMBLY, int RESULT_REGISTER, int SECOND_ACCUMULATOR,
		int TEMPORARY_REGISTER, int FIRST_BASE, int32_t FIRST_DISPLACEMENT,
		int SECOND_BASE, int32_t SECOND_DISPLACEMENT, int ELEMENT_COUNT
	)
{
	DOT_REGISTERS	DOT_STATE = {
		RESULT_REGISTER, SECOND_ACCUMULATOR, TEMPORARY_REGISTER, FIRST_BASE,
		SECOND_BASE, FIRST_DISPLACEMENT, SECOND_DISPLACEMENT, 0
	};

	ZERO_VECTOR(ASSEMBLY, RESULT_REGISTER);
	ZERO_VECTOR(ASSEMBLY, SECOND_ACCUMULATOR);
	FOR_EACH_CHUNK(ASSEMBLY, ELEMENT_COUNT, DOT_CHUNK, &DOT_STATE);
	VECTOR_MATH(
		ASSEMBLY, 1, OPCODE_ADD, RESULT_REGISTER, RESULT_REGISTER,
		SECOND_ACCUMULATOR
	);
	HORIZONTAL_SUM(ASSEMBLY, RESULT_REGISTER, TEMPORARY_REGISTER);
}

typedef struct
{
	int		SCALE_REGISTER;
	int		TEMPORARY;
	int		OUTPUT_BASE;
	int		INPUT_BASE;
	int32_t	OUTPUT_DISPLACEMENT;
	int32_t	INPUT_DISPLACEMENT;
} SCALED_ADD_REGISTERS;

static void
	SCALED_ADD_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	SCALED_ADD_REGISTERS	*SCALED_ADD_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, SCALED_ADD_STATE->TEMPORARY,
		OPERAND_AT(
			SCALED_ADD_STATE->OUTPUT_BASE, INDEX_REGISTER,
			SCALED_ADD_STATE->OUTPUT_DISPLACEMENT + OFFSET
		)
	);
	MULTIPLY_ADD_MEMORY(
		ASSEMBLY, 1, SCALED_ADD_STATE->TEMPORARY,
		SCALED_ADD_STATE->SCALE_REGISTER,
		OPERAND_AT(
			SCALED_ADD_STATE->INPUT_BASE, INDEX_REGISTER,
			SCALED_ADD_STATE->INPUT_DISPLACEMENT + OFFSET
		)
	);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			SCALED_ADD_STATE->OUTPUT_BASE, INDEX_REGISTER,
			SCALED_ADD_STATE->OUTPUT_DISPLACEMENT + OFFSET
		),
		SCALED_ADD_STATE->TEMPORARY
	);
}

static void
	SCALED_ADD_WEIGHT_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	SCALED_ADD_REGISTERS	*SCALED_ADD_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, SCALED_ADD_STATE->TEMPORARY,
		OPERAND_AT(
			SCALED_ADD_STATE->OUTPUT_BASE, INDEX_REGISTER,
			SCALED_ADD_STATE->OUTPUT_DISPLACEMENT + OFFSET
		)
	);
	MULTIPLY_ADD_WEIGHTS(
		ASSEMBLY, SCALED_ADD_STATE->TEMPORARY, SCALED_ADD_STATE->SCALE_REGISTER,
		WEIGHT_OPERAND(
			SCALED_ADD_STATE->INPUT_BASE, INDEX_REGISTER,
			SCALED_ADD_STATE->INPUT_DISPLACEMENT + OFFSET
		)
	);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			SCALED_ADD_STATE->OUTPUT_BASE, INDEX_REGISTER,
			SCALED_ADD_STATE->OUTPUT_DISPLACEMENT + OFFSET
		),
		SCALED_ADD_STATE->TEMPORARY
	);
}

static void
	SCALED_ADD_WEIGHTS(
		ASSEMBLER *ASSEMBLY, int SCALE_REGISTER, int TEMPORARY_REGISTER,
		int TARGET_BASE, int32_t TARGET_DISPLACEMENT, int SOURCE_BASE,
		int32_t SOURCE_DISPLACEMENT, int ELEMENT_COUNT
	)
{
	SCALED_ADD_REGISTERS	SCALED_ADD_STATE = {
		SCALE_REGISTER, TEMPORARY_REGISTER, TARGET_BASE, SOURCE_BASE,
		TARGET_DISPLACEMENT, SOURCE_DISPLACEMENT
	};

	FOR_EACH_CHUNK(
		ASSEMBLY, ELEMENT_COUNT, SCALED_ADD_WEIGHT_CHUNK, &SCALED_ADD_STATE
	);
}

static void
	SCALED_ADD(
		ASSEMBLER *ASSEMBLY, int SCALE_REGISTER, int TEMPORARY_REGISTER,
		int TARGET_BASE, int32_t TARGET_DISPLACEMENT, int SOURCE_BASE,
		int32_t SOURCE_DISPLACEMENT, int ELEMENT_COUNT
	)
{
	SCALED_ADD_REGISTERS	SCALED_ADD_STATE = {
		SCALE_REGISTER, TEMPORARY_REGISTER, TARGET_BASE, SOURCE_BASE,
		TARGET_DISPLACEMENT, SOURCE_DISPLACEMENT
	};

	FOR_EACH_CHUNK(
		ASSEMBLY, ELEMENT_COUNT, SCALED_ADD_CHUNK, &SCALED_ADD_STATE
	);
}

static void
	VECTOR_EXPONENTIAL(
		ASSEMBLER *ASSEMBLY, int IS_WIDE, int VECTOR_REGISTER,
		int ROUNDED_REGISTER, int POLYNOMIAL_REGISTER
	)
{
	VECTOR_MATH_MEMORY(
		ASSEMBLY, IS_WIDE, OPCODE_MAXIMUM, VECTOR_REGISTER, VECTOR_REGISTER,
		STATE_CONSTANT(CONSTANT_CLAMP_LOW)
	);
	VECTOR_MATH_MEMORY(
		ASSEMBLY, IS_WIDE, OPCODE_MINIMUM, VECTOR_REGISTER, VECTOR_REGISTER,
		STATE_CONSTANT(CONSTANT_CLAMP_HIGH)
	);
	VECTOR_MATH_MEMORY(
		ASSEMBLY, IS_WIDE, OPCODE_MULTIPLY, VECTOR_REGISTER, VECTOR_REGISTER,
		STATE_CONSTANT(CONSTANT_LOG2_OF_E)
	);
	VECTOR_ROUND(ASSEMBLY, IS_WIDE, ROUNDED_REGISTER, VECTOR_REGISTER, 0);
	VECTOR_MATH(
		ASSEMBLY, IS_WIDE, OPCODE_SUBTRACT, VECTOR_REGISTER, VECTOR_REGISTER,
		ROUNDED_REGISTER
	);
	VECTOR_LOAD(
		ASSEMBLY, IS_WIDE, POLYNOMIAL_REGISTER,
		STATE_CONSTANT(CONSTANT_POLYNOMIAL_6)
	);
	MULTIPLY_THEN_ADD_MEMORY(
		ASSEMBLY, IS_WIDE, POLYNOMIAL_REGISTER, VECTOR_REGISTER,
		STATE_CONSTANT(CONSTANT_POLYNOMIAL_5)
	);
	MULTIPLY_THEN_ADD_MEMORY(
		ASSEMBLY, IS_WIDE, POLYNOMIAL_REGISTER, VECTOR_REGISTER,
		STATE_CONSTANT(CONSTANT_POLYNOMIAL_4)
	);
	MULTIPLY_THEN_ADD_MEMORY(
		ASSEMBLY, IS_WIDE, POLYNOMIAL_REGISTER, VECTOR_REGISTER,
		STATE_CONSTANT(CONSTANT_POLYNOMIAL_3)
	);
	MULTIPLY_THEN_ADD_MEMORY(
		ASSEMBLY, IS_WIDE, POLYNOMIAL_REGISTER, VECTOR_REGISTER,
		STATE_CONSTANT(CONSTANT_POLYNOMIAL_2)
	);
	MULTIPLY_THEN_ADD_MEMORY(
		ASSEMBLY, IS_WIDE, POLYNOMIAL_REGISTER, VECTOR_REGISTER,
		STATE_CONSTANT(CONSTANT_POLYNOMIAL_1)
	);
	MULTIPLY_THEN_ADD_MEMORY(
		ASSEMBLY, IS_WIDE, POLYNOMIAL_REGISTER, VECTOR_REGISTER,
		STATE_CONSTANT(CONSTANT_ONE)
	);
	VECTOR_FLOAT_TO_INTEGER(
		ASSEMBLY, IS_WIDE, ROUNDED_REGISTER, ROUNDED_REGISTER
	);
	VECTOR_SHIFT_LEFT(
		ASSEMBLY, IS_WIDE, ROUNDED_REGISTER, ROUNDED_REGISTER, 23
	);
	VECTOR_INTEGER_ADD(
		ASSEMBLY, IS_WIDE, VECTOR_REGISTER, POLYNOMIAL_REGISTER,
		ROUNDED_REGISTER
	);
}

static void
	HORIZONTAL_MAXIMUM(ASSEMBLER *ASSEMBLY, int VECTOR_REGISTER)
{
	int32_t	SCRATCH_OFFSET = (int32_t)offsetof(KERNEL_CONTEXT, SCRATCH);

	VECTOR_STORE(ASSEMBLY, 1, MEMORY_AT(R15, SCRATCH_OFFSET), VECTOR_REGISTER);
	SCALAR_LOAD(ASSEMBLY, VECTOR_REGISTER, MEMORY_AT(R15, SCRATCH_OFFSET));

	int	LANE_INDEX;

	for (LANE_INDEX = 1; LANE_INDEX < 8; LANE_INDEX++)
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MAXIMUM, VECTOR_REGISTER, VECTOR_REGISTER,
			MEMORY_AT(R15, SCRATCH_OFFSET + 4 * LANE_INDEX)
		);
}

static void
	SOFTMAX_ROW(ASSEMBLER *ASSEMBLY, int ROW_REGISTER, int COUNT_REGISTER)
{
	int	MAX_VECTOR_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	MAX_VECTOR_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	MAX_SCALAR_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	MAX_SCALAR_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	EXP_VECTOR_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	EXP_VECTOR_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	EXP_SCALAR_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	EXP_SCALAR_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	SCALE_VECTOR_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	SCALE_VECTOR_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	SCALE_SCALAR_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	SCALE_SCALAR_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);

	VECTOR_LOAD(ASSEMBLY, 1, 0, STATE_CONSTANT(CONSTANT_NEGATIVE_INFINITY));
	MOVE_IMMEDIATE(ASSEMBLY, R9, 0);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, MAX_VECTOR_TOP);
	LOAD_ADDRESS(ASSEMBLY, R8, MEMORY_AT(R9, 8));
	COMPARE_REGISTER(ASSEMBLY, R8, COUNT_REGISTER);
	BRANCH_TO_LABEL(ASSEMBLY, CC_G, MAX_VECTOR_END);
	VECTOR_MATH_MEMORY(
		ASSEMBLY, 1, OPCODE_MAXIMUM, 0, 0,
		MEMORY_INDEXED(ROW_REGISTER, R9, 4, 0)
	);
	ADD_IMMEDIATE(ASSEMBLY, R9, 8);
	JUMP_TO_LABEL(ASSEMBLY, MAX_VECTOR_TOP);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, MAX_VECTOR_END);
	HORIZONTAL_MAXIMUM(ASSEMBLY, 0);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, MAX_SCALAR_TOP);
	COMPARE_REGISTER(ASSEMBLY, R9, COUNT_REGISTER);
	BRANCH_TO_LABEL(ASSEMBLY, CC_GE, MAX_SCALAR_END);
	SCALAR_MATH_MEMORY(
		ASSEMBLY, OPCODE_MAXIMUM, 0, 0, MEMORY_INDEXED(ROW_REGISTER, R9, 4, 0)
	);
	ADD_IMMEDIATE(ASSEMBLY, R9, 1);
	JUMP_TO_LABEL(ASSEMBLY, MAX_SCALAR_TOP);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, MAX_SCALAR_END);
	BROADCAST_REGISTER(ASSEMBLY, 1, 0, 0);
	ZERO_VECTOR(ASSEMBLY, 1);
	MOVE_IMMEDIATE(ASSEMBLY, R9, 0);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, EXP_VECTOR_TOP);
	LOAD_ADDRESS(ASSEMBLY, R8, MEMORY_AT(R9, 8));
	COMPARE_REGISTER(ASSEMBLY, R8, COUNT_REGISTER);
	BRANCH_TO_LABEL(ASSEMBLY, CC_G, EXP_VECTOR_END);
	VECTOR_LOAD(ASSEMBLY, 1, 2, MEMORY_INDEXED(ROW_REGISTER, R9, 4, 0));
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_SUBTRACT, 2, 2, 0);
	VECTOR_EXPONENTIAL(ASSEMBLY, 1, 2, 3, 4);
	VECTOR_STORE(ASSEMBLY, 1, MEMORY_INDEXED(ROW_REGISTER, R9, 4, 0), 2);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_ADD, 1, 1, 2);
	ADD_IMMEDIATE(ASSEMBLY, R9, 8);
	JUMP_TO_LABEL(ASSEMBLY, EXP_VECTOR_TOP);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, EXP_VECTOR_END);
	HORIZONTAL_SUM(ASSEMBLY, 1, 5);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, EXP_SCALAR_TOP);
	COMPARE_REGISTER(ASSEMBLY, R9, COUNT_REGISTER);
	BRANCH_TO_LABEL(ASSEMBLY, CC_GE, EXP_SCALAR_END);
	SCALAR_LOAD(ASSEMBLY, 2, MEMORY_INDEXED(ROW_REGISTER, R9, 4, 0));
	SCALAR_MATH(ASSEMBLY, OPCODE_SUBTRACT, 2, 2, 0);
	VECTOR_EXPONENTIAL(ASSEMBLY, 0, 2, 3, 4);
	SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(ROW_REGISTER, R9, 4, 0), 2);
	SCALAR_MATH(ASSEMBLY, OPCODE_ADD, 1, 1, 2);
	ADD_IMMEDIATE(ASSEMBLY, R9, 1);
	JUMP_TO_LABEL(ASSEMBLY, EXP_SCALAR_TOP);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, EXP_SCALAR_END);
	SCALAR_LOAD(ASSEMBLY, 3, STATE_FIELD(ONE));
	SCALAR_MATH(ASSEMBLY, OPCODE_DIVIDE, 3, 3, 1);
	BROADCAST_REGISTER(ASSEMBLY, 1, 3, 3);
	MOVE_IMMEDIATE(ASSEMBLY, R9, 0);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, SCALE_VECTOR_TOP);
	LOAD_ADDRESS(ASSEMBLY, R8, MEMORY_AT(R9, 8));
	COMPARE_REGISTER(ASSEMBLY, R8, COUNT_REGISTER);
	BRANCH_TO_LABEL(ASSEMBLY, CC_G, SCALE_VECTOR_END);
	VECTOR_MATH_MEMORY(
		ASSEMBLY, 1, OPCODE_MULTIPLY, 2, 3,
		MEMORY_INDEXED(ROW_REGISTER, R9, 4, 0)
	);
	VECTOR_STORE(ASSEMBLY, 1, MEMORY_INDEXED(ROW_REGISTER, R9, 4, 0), 2);
	ADD_IMMEDIATE(ASSEMBLY, R9, 8);
	JUMP_TO_LABEL(ASSEMBLY, SCALE_VECTOR_TOP);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, SCALE_VECTOR_END);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, SCALE_SCALAR_TOP);
	COMPARE_REGISTER(ASSEMBLY, R9, COUNT_REGISTER);
	BRANCH_TO_LABEL(ASSEMBLY, CC_GE, SCALE_SCALAR_END);
	SCALAR_MATH_MEMORY(
		ASSEMBLY, OPCODE_MULTIPLY, 2, 3, MEMORY_INDEXED(ROW_REGISTER, R9, 4, 0)
	);
	SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(ROW_REGISTER, R9, 4, 0), 2);
	ADD_IMMEDIATE(ASSEMBLY, R9, 1);
	JUMP_TO_LABEL(ASSEMBLY, SCALE_SCALAR_TOP);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, SCALE_SCALAR_END);
}

typedef struct
{
	int	TOP_LABEL;
	int	END_LABEL;
} TIME_LOOP;

static TIME_LOOP
	BEGIN_TIME_LOOP(ASSEMBLER *ASSEMBLY, int FROM_START_TIME)
{
	TIME_LOOP	STEP_LOOP = {
		ASSEMBLER_NEW_LABEL(ASSEMBLY), ASSEMBLER_NEW_LABEL(ASSEMBLY)
	};

	if (FROM_START_TIME)
		MOVE_FROM_MEMORY(ASSEMBLY, RAX, STATE_FIELD(START_POSITION));
	else
		MOVE_IMMEDIATE(ASSEMBLY, RAX, 0);

	ASSEMBLER_BIND_LABEL(ASSEMBLY, STEP_LOOP.TOP_LABEL);
	COMPARE_MEMORY(ASSEMBLY, RAX, STATE_FIELD(SEQUENCE_LENGTH));
	BRANCH_TO_LABEL(ASSEMBLY, CC_GE, STEP_LOOP.END_LABEL);

	return (STEP_LOOP);
}

static void
	END_TIME_LOOP(ASSEMBLER *ASSEMBLY, TIME_LOOP STEP_LOOP)
{
	ADD_IMMEDIATE(ASSEMBLY, RAX, 1);
	JUMP_TO_LABEL(ASSEMBLY, STEP_LOOP.TOP_LABEL);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, STEP_LOOP.END_LABEL);
}

static void
	ROW_POINTER(ASSEMBLER *ASSEMBLY, int ROW_REGISTER, int32_t ROW_STRIDE)
{
	MULTIPLY_IMMEDIATE(ASSEMBLY, ROW_REGISTER, RAX, ROW_STRIDE);
	ADD_REGISTER(ASSEMBLY, ROW_REGISTER, R14);
}

static void
	ADAM_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	(void)BODY_STATE;

	int32_t	PLANE_SIZE = (int32_t)PARAMETER_PLANE;

	VECTOR_LOAD(
		ASSEMBLY, 1, 0, OPERAND_AT(RSI, INDEX_REGISTER, OFFSET + PLANE_SIZE)
	);
	VECTOR_LOAD(
		ASSEMBLY, 1, 1, OPERAND_AT(RSI, INDEX_REGISTER, OFFSET + 2 * PLANE_SIZE)
	);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 1, 1, 8);
	MULTIPLY_ADD(ASSEMBLY, 1, 1, 0, 9);
	VECTOR_LOAD(
		ASSEMBLY, 1, 2, OPERAND_AT(RSI, INDEX_REGISTER, OFFSET + 3 * PLANE_SIZE)
	);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 2, 2, 10);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 3, 0, 0);
	MULTIPLY_ADD(ASSEMBLY, 1, 2, 3, 11);
	VECTOR_STORE(
		ASSEMBLY, 1, OPERAND_AT(RSI, INDEX_REGISTER, OFFSET + 2 * PLANE_SIZE), 1
	);
	VECTOR_STORE(
		ASSEMBLY, 1, OPERAND_AT(RSI, INDEX_REGISTER, OFFSET + 3 * PLANE_SIZE), 2
	);
	VECTOR_STORE(
		ASSEMBLY, 1, OPERAND_AT(RSI, INDEX_REGISTER, OFFSET + PLANE_SIZE), 6
	);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 3, 2, 13);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_SQUARE_ROOT, 3, 0, 3);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_ADD, 3, 3, 14);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 4, 1, 12);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_DIVIDE, 4, 4, 3);
	VECTOR_LOAD(ASSEMBLY, 1, 5, OPERAND_AT(RSI, INDEX_REGISTER, OFFSET));
	MULTIPLY_ADD(ASSEMBLY, 1, 4, 5, 7);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 4, 4, 15);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_SUBTRACT, 5, 5, 4);
	VECTOR_STORE(ASSEMBLY, 1, OPERAND_AT(RSI, INDEX_REGISTER, OFFSET), 5);
}

static void
	GENERATE_ADAM(ASSEMBLER *ASSEMBLY)
{
	BROADCAST_MEMORY(ASSEMBLY, 1, 8, STATE_FIELD(FIRST_MOMENT_DECAY));
	BROADCAST_MEMORY(ASSEMBLY, 1, 9, STATE_FIELD(FIRST_MOMENT_RATE));
	BROADCAST_MEMORY(ASSEMBLY, 1, 10, STATE_FIELD(SECOND_MOMENT_DECAY));
	BROADCAST_MEMORY(ASSEMBLY, 1, 11, STATE_FIELD(SECOND_MOMENT_RATE));
	BROADCAST_MEMORY(ASSEMBLY, 1, 12, STATE_FIELD(FIRST_BIAS_CORRECTION));
	BROADCAST_MEMORY(ASSEMBLY, 1, 13, STATE_FIELD(SECOND_BIAS_CORRECTION));
	BROADCAST_MEMORY(ASSEMBLY, 1, 14, STATE_FIELD(EPSILON));
	BROADCAST_MEMORY(ASSEMBLY, 1, 15, STATE_FIELD(LEARNING_RATE));
	BROADCAST_MEMORY(ASSEMBLY, 1, 7, STATE_FIELD(WEIGHT_DECAY));
	ZERO_VECTOR(ASSEMBLY, 6);

	int	PART_INDEX;

	for (PART_INDEX = 0; PART_INDEX < 2; PART_INDEX++)
	{
		int	LOOP_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int	LOOP_DONE = ASSEMBLER_NEW_LABEL(ASSEMBLY);

		if (PART_INDEX == 0)
			MOVE_REGISTER(ASSEMBLY, RSI, R13);
		else
			LOAD_ADDRESS(
				ASSEMBLY, RSI, MEMORY_AT(R13, (int32_t)WORD_PLANE_OFFSET)
			);

		MOVE_IMMEDIATE(ASSEMBLY, R11, 0);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, LOOP_TOP);
		COMPARE_MEMORY(
			ASSEMBLY, R11,
			PART_INDEX == 0 ? STATE_FIELD(PARAMETER_BYTES_USED)
							: STATE_FIELD(WORD_BYTES_USED)
		);
		BRANCH_TO_LABEL(ASSEMBLY, CC_GE, LOOP_DONE);
		ADAM_CHUNK(ASSEMBLY, NULL, R11, 0);
		ADD_IMMEDIATE(ASSEMBLY, R11, 32);
		JUMP_TO_LABEL(ASSEMBLY, LOOP_TOP);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, LOOP_DONE);
	}
}

static void
	GENERATE_ENTRY(ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB)
{
	int	SAVED_REGISTERS[8] = { RBX, RBP, RDI, RSI, R12, R13, R14, R15 };
	int	REGISTER_INDEX;

	for (REGISTER_INDEX = 0; REGISTER_INDEX < 8; REGISTER_INDEX++)
		PUSH_REGISTER(ASSEMBLY, SAVED_REGISTERS[REGISTER_INDEX]);

	SUBTRACT_IMMEDIATE(ASSEMBLY, RSP, 200);

	for (REGISTER_INDEX = 0; REGISTER_INDEX < 10; REGISTER_INDEX++)
		VECTOR_STORE(
			ASSEMBLY, 0, MEMORY_AT(RSP, 32 + 16 * REGISTER_INDEX),
			6 + REGISTER_INDEX
		);

	MOVE_REGISTER(ASSEMBLY, R15, RCX);
	MOVE_FROM_MEMORY(ASSEMBLY, R14, STATE_FIELD(ACTIVATIONS));
	MOVE_FROM_MEMORY(ASSEMBLY, R13, STATE_FIELD(PARAMETERS));
	MOVE_FROM_MEMORY(ASSEMBLY, RBX, STATE_FIELD(SERVICE_TABLE));
	MOVE_FROM_MEMORY(ASSEMBLY, RAX, STATE_FIELD(MODE));
	COMPARE_IMMEDIATE(ASSEMBLY, RAX, MODE_UPDATE);
	BRANCH_TO_PIECE(ASSEMBLY, CC_E, NEURAL_WEB->UPDATE_START_ID * 4);
}

static void
	GENERATE_EXIT(ASSEMBLER *ASSEMBLY)
{
	int	SAVED_REGISTERS[8] = { RBX, RBP, RDI, RSI, R12, R13, R14, R15 };

	CLEAR_UPPER_HALVES(ASSEMBLY);

	int	REGISTER_INDEX;

	for (REGISTER_INDEX = 0; REGISTER_INDEX < 10; REGISTER_INDEX++)
		VECTOR_LOAD(
			ASSEMBLY, 0, 6 + REGISTER_INDEX,
			MEMORY_AT(RSP, 32 + 16 * REGISTER_INDEX)
		);

	ADD_IMMEDIATE(ASSEMBLY, RSP, 200);

	for (REGISTER_INDEX = 7; REGISTER_INDEX >= 0; REGISTER_INDEX--)
		POP_REGISTER(ASSEMBLY, SAVED_REGISTERS[REGISTER_INDEX]);

	RETURN_INSTRUCTION(ASSEMBLY);
}

static void
	GENERATE_GROW(ASSEMBLER *ASSEMBLY)
{
	int	SKIP_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

	MOVE_FROM_MEMORY(ASSEMBLY, RAX, STATE_FIELD(REQUEST_AREA));
	TEST_REGISTER(ASSEMBLY, RAX, RAX);
	BRANCH_TO_LABEL(ASSEMBLY, CC_S, SKIP_LABEL);
	MOVE_REGISTER(ASSEMBLY, RCX, R15);
	MOVE_REGISTER(ASSEMBLY, RDI, R15);
	CALL_MEMORY(ASSEMBLY, MEMORY_AT(RBX, SERVICE_CREATE * 8));
	MOVE_FROM_MEMORY(ASSEMBLY, R14, STATE_FIELD(ACTIVATIONS));
	MOVE_FROM_MEMORY(ASSEMBLY, R13, STATE_FIELD(PARAMETERS));
	MOVE_FROM_MEMORY(ASSEMBLY, RBX, STATE_FIELD(SERVICE_TABLE));
	ASSEMBLER_BIND_LABEL(ASSEMBLY, SKIP_LABEL);
}

typedef struct
{
	int32_t	RESIDUAL_OFFSET;
	int32_t	POSITION_PARAMETERS;
	int32_t	FIRST_RESIDUAL_OFFSET;
	int64_t	WORD_BASE;
} EMBED_FORWARD_LAYOUT;

static void
	EMBED_FORWARD_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	EMBED_FORWARD_LAYOUT	*EMBED_STATE = BODY_STATE;

	LOAD_WEIGHTS(
		ASSEMBLY, 0,
		WEIGHT_OPERAND(
			RDX, INDEX_REGISTER, (int32_t)EMBED_STATE->WORD_BASE + OFFSET
		)
	);
	WEIGHT_MATH(
		ASSEMBLY, OPCODE_ADD, 0, 0,
		WEIGHT_OPERAND(
			RDI, INDEX_REGISTER, EMBED_STATE->POSITION_PARAMETERS + OFFSET
		)
	);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			RSI, INDEX_REGISTER, EMBED_STATE->FIRST_RESIDUAL_OFFSET + OFFSET
		),
		0
	);
}

typedef struct
{
	int32_t	RESIDUAL_GRADIENT_OFFSET;
	int32_t	POSITION_PARAMETERS;
	int32_t	WORD_GRADIENT_OFFSET;
	int32_t	POSITION_GRADIENT_OFFSET;
	int64_t	WORD_BASE;
} EMBED_BACKWARD_LAYOUT;

static void
	EMBED_BACKWARD_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	EMBED_BACKWARD_LAYOUT	*EMBED_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, 0,
		OPERAND_AT(
			RSI, INDEX_REGISTER, EMBED_STATE->RESIDUAL_GRADIENT_OFFSET + OFFSET
		)
	);
	VECTOR_MATH_MEMORY(
		ASSEMBLY, 1, OPCODE_ADD, 1, 0,
		OPERAND_AT(
			RDX, INDEX_REGISTER,
			(int32_t)EMBED_STATE->WORD_BASE +
				EMBED_STATE->WORD_GRADIENT_OFFSET + OFFSET
		)
	);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			RDX, INDEX_REGISTER,
			(int32_t)EMBED_STATE->WORD_BASE +
				EMBED_STATE->WORD_GRADIENT_OFFSET + OFFSET
		),
		1
	);
	VECTOR_MATH_MEMORY(
		ASSEMBLY, 1, OPCODE_ADD, 2, 0,
		OPERAND_AT(
			RDI, INDEX_REGISTER,
			EMBED_STATE->POSITION_PARAMETERS +
				EMBED_STATE->POSITION_GRADIENT_OFFSET + OFFSET
		)
	);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			RDI, INDEX_REGISTER,
			EMBED_STATE->POSITION_PARAMETERS +
				EMBED_STATE->POSITION_GRADIENT_OFFSET + OFFSET
		),
		2
	);
}

static void
	GENERATE_EMBED(
		ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB, NEURON *CURRENT_NEURON, int ROLE
	)
{
	int			DIMENSION = NEURAL_WEB->CONFIGURATION.DIMENSION;
	TIME_LOOP	STEP_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, ROLE == ROLE_FORWARD);

	MULTIPLY_IMMEDIATE(ASSEMBLY, RSI, RAX, DIMENSION * 4);
	MULTIPLY_IMMEDIATE(
		ASSEMBLY, RDI, RAX, HALF_WEIGHTS ? DIMENSION * 2 : DIMENSION * 4
	);
	ADD_REGISTER(ASSEMBLY, RDI, R13);
	ADD_REGISTER(ASSEMBLY, RSI, R14);
	MOVE_SIGN_EXTENDED(
		ASSEMBLY, RDX,
		MEMORY_INDEXED(R14, RAX, 4, (int32_t)NEURAL_WEB->TOKENS_OFFSET)
	);
	MULTIPLY_IMMEDIATE(
		ASSEMBLY, RDX, RDX,
		(int32_t)(HALF_WEIGHTS ? NEURAL_WEB->WORD_STRIDE / 2
			: NEURAL_WEB->WORD_STRIDE)
	);
	ADD_REGISTER(ASSEMBLY, RDX, R13);

	if (ROLE == ROLE_FORWARD)
	{
		EMBED_FORWARD_LAYOUT	EMBED_STATE = {
			0, (int32_t)CURRENT_NEURON->PARAMETER_OFFSET,
			(int32_t)KERNEL_LAYER_RESIDUAL(NEURAL_WEB, 0), WORD_PLANE_OFFSET
		};

		FOR_EACH_CHUNK(ASSEMBLY, DIMENSION, EMBED_FORWARD_CHUNK, &EMBED_STATE);
	}
	else
	{
		EMBED_BACKWARD_LAYOUT	EMBED_STATE = {
			(int32_t)LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, 0),
			(int32_t)CURRENT_NEURON->PARAMETER_OFFSET, (int32_t)PARAMETER_PLANE,
			(int32_t)PARAMETER_PLANE, WORD_PLANE_OFFSET
		};

		FOR_EACH_CHUNK(ASSEMBLY, DIMENSION, EMBED_BACKWARD_CHUNK, &EMBED_STATE);
	}

	END_TIME_LOOP(ASSEMBLY, STEP_LOOP);
}

typedef struct
{
	int32_t	RESIDUAL_OFFSET;
	int32_t	NEXT_RESIDUAL_OFFSET;
	int32_t	NORMALIZED_OFFSET;
	int32_t	NORMALIZED_GRADIENT_OFFSET;
	int32_t	RESIDUAL_GRADIENT_OFFSET;
	int32_t	NEXT_RESIDUAL_GRADIENT;
	int32_t	GRADIENT_PLANE;
	int		IS_LAST;
} NORM_LAYOUT;

static void
	NORM_FORWARD_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	NORM_LAYOUT	*NORM_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, 2,
		OPERAND_AT(RSI, INDEX_REGISTER, NORM_STATE->RESIDUAL_OFFSET + OFFSET)
	);

	if (!NORM_STATE->IS_LAST)
		VECTOR_STORE(
			ASSEMBLY, 1,
			OPERAND_AT(
				RSI, INDEX_REGISTER, NORM_STATE->NEXT_RESIDUAL_OFFSET + OFFSET
			),
			2
		);

	VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 2, 2, 1);
	WEIGHT_MATH(
		ASSEMBLY, OPCODE_MULTIPLY, 2, 2,
		WEIGHT_OPERAND(RDI, INDEX_REGISTER, OFFSET)
	);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(RSI, INDEX_REGISTER, NORM_STATE->NORMALIZED_OFFSET + OFFSET),
		2
	);
}

static void
	ZERO_GRADIENT_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	NORM_LAYOUT	*NORM_STATE = BODY_STATE;

	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			RSI, INDEX_REGISTER, NORM_STATE->NORMALIZED_GRADIENT_OFFSET + OFFSET
		),
		3
	);
}

typedef struct
{
	int32_t	RESIDUAL_OFFSET;
	int32_t	NORMALIZED_GRADIENT_OFFSET;
} NORM_DOT_LAYOUT;

static void
	NORM_DOT_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	NORM_DOT_LAYOUT	*NORM_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, 0,
		OPERAND_AT(
			RSI, INDEX_REGISTER, NORM_STATE->NORMALIZED_GRADIENT_OFFSET + OFFSET
		)
	);
	VECTOR_MATH_MEMORY(
		ASSEMBLY, 1, OPCODE_MULTIPLY, 0, 0,
		OPERAND_AT(RDI, INDEX_REGISTER, OFFSET)
	);
	MULTIPLY_ADD_MEMORY(
		ASSEMBLY, 1, 6, 0,
		OPERAND_AT(RSI, INDEX_REGISTER, NORM_STATE->RESIDUAL_OFFSET + OFFSET)
	);
}

static void
	NORM_BACKWARD_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	NORM_LAYOUT	*NORM_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, 0,
		OPERAND_AT(
			RSI, INDEX_REGISTER, NORM_STATE->NORMALIZED_GRADIENT_OFFSET + OFFSET
		)
	);
	VECTOR_LOAD(
		ASSEMBLY, 1, 1,
		OPERAND_AT(RSI, INDEX_REGISTER, NORM_STATE->RESIDUAL_OFFSET + OFFSET)
	);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 2, 0, 1);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 2, 2, 5);
	VECTOR_MATH_MEMORY(
		ASSEMBLY, 1, OPCODE_ADD, 2, 2,
		OPERAND_AT(RDI, INDEX_REGISTER, NORM_STATE->GRADIENT_PLANE + OFFSET)
	);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(RDI, INDEX_REGISTER, NORM_STATE->GRADIENT_PLANE + OFFSET), 2
	);
	VECTOR_MATH_MEMORY(
		ASSEMBLY, 1, OPCODE_MULTIPLY, 3, 0,
		OPERAND_AT(RDI, INDEX_REGISTER, OFFSET)
	);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 3, 3, 5);
	MULTIPLY_ADD(ASSEMBLY, 1, 3, 1, 9);

	if (!NORM_STATE->IS_LAST)
		VECTOR_MATH_MEMORY(
			ASSEMBLY, 1, OPCODE_ADD, 3, 3,
			OPERAND_AT(
				RSI, INDEX_REGISTER, NORM_STATE->NEXT_RESIDUAL_GRADIENT + OFFSET
			)
		);

	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			RSI, INDEX_REGISTER, NORM_STATE->RESIDUAL_GRADIENT_OFFSET + OFFSET
		),
		3
	);
}

static void
	GENERATE_NORM(
		ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB, NEURON *CURRENT_NEURON, int ROLE
	)
{
	int			DIMENSION = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int			AREA_INDEX = CURRENT_NEURON->AREA_INDEX;
	int			IS_LAST =
		AREA_INDEX == 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT;
	int32_t		INVERSE_RMS_OFFSET =
		(int32_t)(NEURAL_WEB->INVERSE_NORM_OFFSET +
			(int64_t)AREA_INDEX *
			NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH * 4);
	NORM_LAYOUT	NORM_STATE = {
		(int32_t)KERNEL_LAYER_RESIDUAL(NEURAL_WEB, AREA_INDEX),
		IS_LAST ? 0
				: (int32_t)KERNEL_LAYER_RESIDUAL(NEURAL_WEB, AREA_INDEX + 1),
		(int32_t)KERNEL_LAYER_NORMALIZED(NEURAL_WEB, AREA_INDEX),
		(int32_t)LAYER_NORMALIZED_GRADIENT(NEURAL_WEB, AREA_INDEX),
		(int32_t)LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, AREA_INDEX),
		IS_LAST ? 0
				: (int32_t)LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, AREA_INDEX + 1),
		(int32_t)PARAMETER_PLANE, IS_LAST
	};

	LOAD_ADDRESS(
		ASSEMBLY, RDI,
		WEIGHT_OPERAND(R13, -1, (int32_t)CURRENT_NEURON->PARAMETER_OFFSET)
	);

	TIME_LOOP	STEP_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, ROLE == ROLE_FORWARD);

	ROW_POINTER(ASSEMBLY, RSI, DIMENSION * 4);

	if (ROLE == ROLE_FORWARD)
	{
		DOT_PRODUCT(
			ASSEMBLY, 0, 1, 2, RSI, NORM_STATE.RESIDUAL_OFFSET, RSI,
			NORM_STATE.RESIDUAL_OFFSET, DIMENSION
		);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MULTIPLY, 0, 0, STATE_FIELD(INVERSE_DIMENSION)
		);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_ADD, 0, 0, STATE_FIELD(NORM_EPSILON)
		);
		SCALAR_MATH(ASSEMBLY, OPCODE_SQUARE_ROOT, 0, 0, 0);
		SCALAR_LOAD(ASSEMBLY, 1, STATE_FIELD(ONE));
		SCALAR_MATH(ASSEMBLY, OPCODE_DIVIDE, 1, 1, 0);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, INVERSE_RMS_OFFSET), 1
		);
		BROADCAST_REGISTER(ASSEMBLY, 1, 1, 1);
		FOR_EACH_CHUNK(ASSEMBLY, DIMENSION, NORM_FORWARD_CHUNK, &NORM_STATE);
	}
	else
	{
		BROADCAST_MEMORY(
			ASSEMBLY, 1, 5, MEMORY_INDEXED(R14, RAX, 4, INVERSE_RMS_OFFSET)
		);
		ZERO_VECTOR(ASSEMBLY, 6);

		NORM_DOT_LAYOUT	CORRECTION_STATE = {
			NORM_STATE.RESIDUAL_OFFSET, NORM_STATE.NORMALIZED_GRADIENT_OFFSET
		};

		FOR_EACH_CHUNK(ASSEMBLY, DIMENSION, NORM_DOT_CHUNK, &CORRECTION_STATE);
		HORIZONTAL_SUM(ASSEMBLY, 6, 7);
		SCALAR_LOAD(
			ASSEMBLY, 8, MEMORY_INDEXED(R14, RAX, 4, INVERSE_RMS_OFFSET)
		);
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 7, 8, 8);
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 7, 7, 8);
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 7, 7, 6);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MULTIPLY, 7, 7, STATE_FIELD(INVERSE_DIMENSION)
		);
		VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 10, 10, 10);
		SCALAR_MATH(ASSEMBLY, OPCODE_SUBTRACT, 9, 10, 7);
		BROADCAST_REGISTER(ASSEMBLY, 1, 9, 9);
		FOR_EACH_CHUNK(ASSEMBLY, DIMENSION, NORM_BACKWARD_CHUNK, &NORM_STATE);
	}

	END_TIME_LOOP(ASSEMBLY, STEP_LOOP);

	if (ROLE == ROLE_FORWARD)
	{
		int	SKIP_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

		MOVE_FROM_MEMORY(ASSEMBLY, RAX, STATE_FIELD(MODE));
		COMPARE_IMMEDIATE(ASSEMBLY, RAX, MODE_INFER);
		BRANCH_TO_LABEL(ASSEMBLY, CC_E, SKIP_LABEL);
		ZERO_VECTOR(ASSEMBLY, 3);

		TIME_LOOP	ZERO_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 1);

		ROW_POINTER(ASSEMBLY, RSI, DIMENSION * 4);
		FOR_EACH_CHUNK(ASSEMBLY, DIMENSION, ZERO_GRADIENT_CHUNK, &NORM_STATE);
		END_TIME_LOOP(ASSEMBLY, ZERO_LOOP);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, SKIP_LABEL);
	}
}

typedef struct
{
	int32_t	NEXT_RESIDUAL_OFFSET;
	int32_t	NORMALIZED_OFFSET;
	int32_t	NORMALIZED_GRADIENT_OFFSET;
	int32_t	NEXT_RESIDUAL_GRADIENT;
	int32_t	GRADIENT_PLANE;
	int32_t	ROW_BYTES;
} FEED_FORWARD_LAYOUT;

static void
	FEED_FORWARD_BACK_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	FEED_FORWARD_LAYOUT	*FEED_FORWARD_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, 0,
		OPERAND_AT(
			RSI, INDEX_REGISTER,
			FEED_FORWARD_STATE->NEXT_RESIDUAL_GRADIENT + OFFSET
		)
	);
	VECTOR_LOAD(
		ASSEMBLY, 1, 4,
		OPERAND_AT(
			RDI, INDEX_REGISTER,
			FEED_FORWARD_STATE->GRADIENT_PLANE + FEED_FORWARD_STATE->ROW_BYTES +
				OFFSET
		)
	);
	MULTIPLY_ADD(ASSEMBLY, 1, 4, 7, 0);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			RDI, INDEX_REGISTER,
			FEED_FORWARD_STATE->GRADIENT_PLANE + FEED_FORWARD_STATE->ROW_BYTES +
				OFFSET
		),
		4
	);
	VECTOR_LOAD(
		ASSEMBLY, 1, 1,
		OPERAND_AT(
			RSI, INDEX_REGISTER, FEED_FORWARD_STATE->NORMALIZED_OFFSET + OFFSET
		)
	);
	VECTOR_LOAD(
		ASSEMBLY, 1, 5,
		OPERAND_AT(
			RDI, INDEX_REGISTER, FEED_FORWARD_STATE->GRADIENT_PLANE + OFFSET
		)
	);
	MULTIPLY_ADD(ASSEMBLY, 1, 5, 8, 1);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			RDI, INDEX_REGISTER, FEED_FORWARD_STATE->GRADIENT_PLANE + OFFSET
		),
		5
	);
	VECTOR_LOAD(
		ASSEMBLY, 1, 2,
		OPERAND_AT(
			RSI, INDEX_REGISTER,
			FEED_FORWARD_STATE->NORMALIZED_GRADIENT_OFFSET + OFFSET
		)
	);
	MULTIPLY_ADD_MEMORY(
		ASSEMBLY, 1, 2, 8, OPERAND_AT(RDI, INDEX_REGISTER, OFFSET)
	);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			RSI, INDEX_REGISTER,
			FEED_FORWARD_STATE->NORMALIZED_GRADIENT_OFFSET + OFFSET
		),
		2
	);
}

static void
	FEED_FORWARD_INPUT_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	FEED_FORWARD_LAYOUT	*FEED_FORWARD_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, 2,
		OPERAND_AT(
			RSI, INDEX_REGISTER,
			FEED_FORWARD_STATE->NORMALIZED_GRADIENT_OFFSET + OFFSET
		)
	);
	MULTIPLY_ADD_MEMORY(
		ASSEMBLY, 1, 2, 8, OPERAND_AT(RDI, INDEX_REGISTER, OFFSET)
	);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			RSI, INDEX_REGISTER,
			FEED_FORWARD_STATE->NORMALIZED_GRADIENT_OFFSET + OFFSET
		),
		2
	);
}

static void
	FEED_FORWARD_BACKWARD(ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB, int AREA_INDEX)
{
	int					DIMENSION = NEURAL_WEB->CONFIGURATION.DIMENSION;
	FEED_FORWARD_LAYOUT	FEED_FORWARD_STATE = {
		(int32_t)KERNEL_LAYER_RESIDUAL(NEURAL_WEB, AREA_INDEX + 1),
		(int32_t)KERNEL_LAYER_NORMALIZED(NEURAL_WEB, AREA_INDEX),
		(int32_t)LAYER_NORMALIZED_GRADIENT(NEURAL_WEB, AREA_INDEX),
		(int32_t)LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, AREA_INDEX + 1),
		(int32_t)PARAMETER_PLANE, DIMENSION * 4
	};
	int32_t				ACTIVE_LIST_OFFSET = (int32_t)LAST_LOGITS_OFFSET;
	int32_t				ACTIVE_GRADIENT_OFFSET =
		(int32_t)(LAST_LOGITS_OFFSET +
			(int64_t)NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH * 8);

	MOVE_REGISTER(ASSEMBLY, RDI, R12);
	MOVE_FROM_MEMORY(ASSEMBLY, R10, STATE_FIELD(NEURON_ACTIVATION_OFFSET));
	ADD_REGISTER(ASSEMBLY, R10, R14);
	MOVE_IMMEDIATE(ASSEMBLY, RDX, 0);
	ZERO_VECTOR(ASSEMBLY, 9);

	TIME_LOOP	STEP_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);
	int			SKIP_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

	ROW_POINTER(ASSEMBLY, RSI, DIMENSION * 4);
	SCALAR_LOAD(ASSEMBLY, 6, MEMORY_INDEXED(R10, RAX, 4, 0));
	ZERO_VECTOR(ASSEMBLY, 1);
	SCALAR_COMPARE(ASSEMBLY, 6, 1);
	BRANCH_TO_LABEL(ASSEMBLY, CC_BE, SKIP_LABEL);
	DOT_PRODUCT(
		ASSEMBLY, 1, 2, 3, RSI, FEED_FORWARD_STATE.NEXT_RESIDUAL_GRADIENT, RDI,
		DIMENSION * 4, DIMENSION
	);
	SCALAR_MATH(ASSEMBLY, OPCODE_ADD, 9, 9, 1);
	BROADCAST_REGISTER(ASSEMBLY, 1, 8, 1);
	FOR_EACH_CHUNK(
		ASSEMBLY, DIMENSION, FEED_FORWARD_INPUT_CHUNK, &FEED_FORWARD_STATE
	);
	MOVE_TO_MEMORY(
		ASSEMBLY, MEMORY_INDEXED(R14, RDX, 8, ACTIVE_LIST_OFFSET), RAX
	);
	SCALAR_STORE(
		ASSEMBLY, MEMORY_INDEXED(R14, RDX, 4, ACTIVE_GRADIENT_OFFSET), 1
	);
	ADD_IMMEDIATE(ASSEMBLY, RDX, 1);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, SKIP_LABEL);
	END_TIME_LOOP(ASSEMBLY, STEP_LOOP);
	SCALAR_MATH_MEMORY(
		ASSEMBLY, OPCODE_ADD, 9, 9,
		MEMORY_AT(RDI, FEED_FORWARD_STATE.GRADIENT_PLANE + 2 * DIMENSION * 4)
	);
	SCALAR_STORE(
		ASSEMBLY,
		MEMORY_AT(RDI, FEED_FORWARD_STATE.GRADIENT_PLANE + 2 * DIMENSION * 4), 9
	);

	int	PART_INDEX;

	for (PART_INDEX = 0; PART_INDEX < 2; PART_INDEX++)
	{
		int32_t	SOURCE_OFFSET;

		if (PART_INDEX == 0)
			SOURCE_OFFSET = FEED_FORWARD_STATE.NEXT_RESIDUAL_GRADIENT;
		else
			SOURCE_OFFSET = FEED_FORWARD_STATE.NORMALIZED_OFFSET;

		int32_t	GRADIENT_OFFSET = FEED_FORWARD_STATE.GRADIENT_PLANE +
			(PART_INDEX == 0 ? DIMENSION * 4 : 0);
		int		GROUP_START;

		for (GROUP_START = 0; GROUP_START < DIMENSION / 8; GROUP_START += 12)
		{
			int	GROUP_COUNT;

			if (DIMENSION / 8 - GROUP_START < 12)
				GROUP_COUNT = DIMENSION / 8 - GROUP_START;
			else
				GROUP_COUNT = 12;

			int	LOOP_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
			int	LOOP_DONE = ASSEMBLER_NEW_LABEL(ASSEMBLY);
			int	REGISTER_INDEX;

			for (
				REGISTER_INDEX = 0;
				REGISTER_INDEX < GROUP_COUNT;
				REGISTER_INDEX++
			)
				ZERO_VECTOR(ASSEMBLY, REGISTER_INDEX);

			MOVE_IMMEDIATE(ASSEMBLY, RCX, 0);
			ASSEMBLER_BIND_LABEL(ASSEMBLY, LOOP_TOP);
			COMPARE_REGISTER(ASSEMBLY, RCX, RDX);
			BRANCH_TO_LABEL(ASSEMBLY, CC_GE, LOOP_DONE);
			MOVE_FROM_MEMORY(
				ASSEMBLY, RAX, MEMORY_INDEXED(R14, RCX, 8, ACTIVE_LIST_OFFSET)
			);
			ROW_POINTER(ASSEMBLY, RSI, DIMENSION * 4);

			if (PART_INDEX == 0)
				BROADCAST_MEMORY(
					ASSEMBLY, 1, 12, MEMORY_INDEXED(R10, RAX, 4, 0)
				);
			else
				BROADCAST_MEMORY(
					ASSEMBLY, 1, 12,
					MEMORY_INDEXED(R14, RCX, 4, ACTIVE_GRADIENT_OFFSET)
				);

			for (
				REGISTER_INDEX = 0;
				REGISTER_INDEX < GROUP_COUNT;
				REGISTER_INDEX++
			)
				MULTIPLY_ADD_MEMORY(
					ASSEMBLY, 1, REGISTER_INDEX, 12,
					MEMORY_AT(
						RSI, SOURCE_OFFSET + 32 * (GROUP_START + REGISTER_INDEX)
					)
				);

			ADD_IMMEDIATE(ASSEMBLY, RCX, 1);
			JUMP_TO_LABEL(ASSEMBLY, LOOP_TOP);
			ASSEMBLER_BIND_LABEL(ASSEMBLY, LOOP_DONE);

			for (
				REGISTER_INDEX = 0;
				REGISTER_INDEX < GROUP_COUNT;
				REGISTER_INDEX++
			)
			{
				VECTOR_MATH_MEMORY(
					ASSEMBLY, 1, OPCODE_ADD, REGISTER_INDEX, REGISTER_INDEX,
					MEMORY_AT(
						RDI,
						GRADIENT_OFFSET + 32 * (GROUP_START + REGISTER_INDEX)
					)
				);
				VECTOR_STORE(
					ASSEMBLY, 1,
					MEMORY_AT(
						RDI,
						GRADIENT_OFFSET + 32 * (GROUP_START + REGISTER_INDEX)
					),
					REGISTER_INDEX
				);
			}
		}
	}

	JUMP_TO_REGISTER(ASSEMBLY, RBP);
}

static void
	GENERATE_FEED_FORWARD(
		ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB, NEURON *CURRENT_NEURON, int ROLE
	)
{
	int	DIMENSION = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int	AREA_INDEX = CURRENT_NEURON->AREA_INDEX;

	if (ROLE != ROLE_FORWARD)
	{
		FEED_FORWARD_BACKWARD(ASSEMBLY, NEURAL_WEB, AREA_INDEX);
		return ;
	}

	FEED_FORWARD_LAYOUT	FEED_FORWARD_STATE = {
		(int32_t)KERNEL_LAYER_RESIDUAL(NEURAL_WEB, AREA_INDEX + 1),
		(int32_t)KERNEL_LAYER_NORMALIZED(NEURAL_WEB, AREA_INDEX),
		(int32_t)LAYER_NORMALIZED_GRADIENT(NEURAL_WEB, AREA_INDEX),
		(int32_t)LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, AREA_INDEX + 1),
		(int32_t)PARAMETER_PLANE, DIMENSION * 4
	};

	MOVE_REGISTER(ASSEMBLY, RDI, R12);
	MOVE_FROM_MEMORY(ASSEMBLY, R10, STATE_FIELD(NEURON_ACTIVATION_OFFSET));
	ADD_REGISTER(ASSEMBLY, R10, R14);

	TIME_LOOP	STEP_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, ROLE == ROLE_FORWARD);
	int			SKIP_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

	ROW_POINTER(ASSEMBLY, RSI, DIMENSION * 4);

	if (ROLE == ROLE_FORWARD)
	{
		DOT_WITH_WEIGHTS(
			ASSEMBLY, 0, 1, 2, RSI, FEED_FORWARD_STATE.NORMALIZED_OFFSET, RDI,
			0, DIMENSION
		);
		ADD_SCALAR_WEIGHT(
			ASSEMBLY, 0, 0, WEIGHT_OPERAND(RDI, -1, 2 * DIMENSION * 4)
		);

		if (!HALF_WEIGHTS)
			SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(R10, RAX, 4, 0), 0);

		VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 1, 1, 1);
		SCALAR_COMPARE(ASSEMBLY, 0, 1);
		BRANCH_TO_LABEL(ASSEMBLY, CC_BE, SKIP_LABEL);
		BROADCAST_REGISTER(ASSEMBLY, 1, 0, 0);
		SCALED_ADD_WEIGHTS(
			ASSEMBLY, 0, 3, RSI, FEED_FORWARD_STATE.NEXT_RESIDUAL_OFFSET, RDI,
			DIMENSION * 4, DIMENSION
		);
	}
	else
	{
		SCALAR_LOAD(ASSEMBLY, 6, MEMORY_INDEXED(R10, RAX, 4, 0));
		VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 1, 1, 1);
		SCALAR_COMPARE(ASSEMBLY, 6, 1);
		BRANCH_TO_LABEL(ASSEMBLY, CC_BE, SKIP_LABEL);
		DOT_PRODUCT(
			ASSEMBLY, 1, 2, 3, RSI, FEED_FORWARD_STATE.NEXT_RESIDUAL_GRADIENT,
			RDI, DIMENSION * 4, DIMENSION
		);
		BROADCAST_REGISTER(ASSEMBLY, 1, 7, 6);
		BROADCAST_REGISTER(ASSEMBLY, 1, 8, 1);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_ADD, 2, 1,
			MEMORY_AT(
				RDI, FEED_FORWARD_STATE.GRADIENT_PLANE + 2 * DIMENSION * 4
			)
		);
		SCALAR_STORE(
			ASSEMBLY,
			MEMORY_AT(
				RDI, FEED_FORWARD_STATE.GRADIENT_PLANE + 2 * DIMENSION * 4
			),
			2
		);
		FOR_EACH_CHUNK(
			ASSEMBLY, DIMENSION, FEED_FORWARD_BACK_CHUNK, &FEED_FORWARD_STATE
		);
	}

	ASSEMBLER_BIND_LABEL(ASSEMBLY, SKIP_LABEL);
	END_TIME_LOOP(ASSEMBLY, STEP_LOOP);
	JUMP_TO_REGISTER(ASSEMBLY, RBP);
}

typedef struct
{
	int32_t	FINAL_NORMALIZED_OFFSET;
	int32_t	ROW_BYTES;
} WORD_FORWARD_LAYOUT;

static void
	WORD_FOUR_ROWS_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	WORD_FORWARD_LAYOUT	*WORD_STATE = BODY_STATE;

	VECTOR_LOAD(ASSEMBLY, 1, 4, OPERAND_AT(RDI, INDEX_REGISTER, OFFSET));

	int	ROW_INDEX;

	for (ROW_INDEX = 0; ROW_INDEX < 4; ROW_INDEX++)
		MULTIPLY_ADD_MEMORY(
			ASSEMBLY, 1, ROW_INDEX, 4,
			OPERAND_AT(
				RSI, INDEX_REGISTER,
				WORD_STATE->FINAL_NORMALIZED_OFFSET +
					ROW_INDEX * WORD_STATE->ROW_BYTES + OFFSET
			)
		);
}

typedef struct
{
	int32_t	NORMALIZED_GRADIENT_OFFSET;
} WORD_BACKWARD_LAYOUT;

static void
	WORD_BACKWARD_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	WORD_BACKWARD_LAYOUT	*WORD_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, 1,
		OPERAND_AT(
			RSI, INDEX_REGISTER, WORD_STATE->NORMALIZED_GRADIENT_OFFSET + OFFSET
		)
	);
	MULTIPLY_ADD_MEMORY(
		ASSEMBLY, 1, 1, 0, OPERAND_AT(RDI, INDEX_REGISTER, OFFSET)
	);
	VECTOR_STORE(
		ASSEMBLY, 1,
		OPERAND_AT(
			RSI, INDEX_REGISTER, WORD_STATE->NORMALIZED_GRADIENT_OFFSET + OFFSET
		),
		1
	);
}

static void
	GENERATE_WORD(
		ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB, NEURON *CURRENT_NEURON, int ROLE
	)
{
	int		DIMENSION = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int		FINAL_AREA = 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT;
	int32_t	FINAL_NORM_OFFSET =
		(int32_t)KERNEL_LAYER_NORMALIZED(NEURAL_WEB, FINAL_AREA);
	int32_t	FINAL_GRADIENT_OFFSET =
		(int32_t)LAYER_NORMALIZED_GRADIENT(NEURAL_WEB, FINAL_AREA);
	int32_t	COLUMN_OFFSET = 0;
	int32_t	PLANE_SIZE = (int32_t)PARAMETER_PLANE;

	(void)CURRENT_NEURON;
	MOVE_REGISTER(ASSEMBLY, RDI, R12);
	MOVE_FROM_MEMORY(ASSEMBLY, R10, STATE_FIELD(NEURON_ACTIVATION_OFFSET));
	ADD_REGISTER(ASSEMBLY, R10, R14);

	if (ROLE == ROLE_FORWARD)
	{
		int	QUAD_LOOP_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int	SINGLE_LOOP_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int	END_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int	TRAIN_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

		MOVE_FROM_MEMORY(ASSEMBLY, RAX, STATE_FIELD(MODE));
		COMPARE_IMMEDIATE(ASSEMBLY, RAX, MODE_INFER);
		BRANCH_TO_LABEL(ASSEMBLY, CC_NE, TRAIN_LABEL);
		MOVE_FROM_MEMORY(ASSEMBLY, RAX, STATE_FIELD(SEQUENCE_LENGTH));
		SUBTRACT_IMMEDIATE(ASSEMBLY, RAX, 1);
		ROW_POINTER(ASSEMBLY, RSI, DIMENSION * 4);
		DOT_WITH_WEIGHTS(
			ASSEMBLY, 0, 1, 2, RSI, FINAL_NORM_OFFSET, RDI, 0, DIMENSION
		);
		ADD_SCALAR_WEIGHT(
			ASSEMBLY, 0, 0, WEIGHT_OPERAND(RDI, -1, DIMENSION * 4)
		);
		MOVE_FROM_MEMORY(ASSEMBLY, RCX, STATE_FIELD(INFERENCE_LOGIT_OFFSET));
		SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(R14, RCX, 1, 0), 0);
		JUMP_TO_LABEL(ASSEMBLY, END_LABEL);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, TRAIN_LABEL);

		if (HALF_WEIGHTS)
		{
			ASSEMBLER_BIND_LABEL(ASSEMBLY, QUAD_LOOP_TOP);
			ASSEMBLER_BIND_LABEL(ASSEMBLY, SINGLE_LOOP_TOP);
			ASSEMBLER_BIND_LABEL(ASSEMBLY, END_LABEL);
			JUMP_TO_REGISTER(ASSEMBLY, RBP);
			return ;
		}

		MOVE_FROM_MEMORY(ASSEMBLY, RAX, STATE_FIELD(START_POSITION));
		ASSEMBLER_BIND_LABEL(ASSEMBLY, QUAD_LOOP_TOP);
		LOAD_ADDRESS(ASSEMBLY, RCX, MEMORY_AT(RAX, 4));
		COMPARE_MEMORY(ASSEMBLY, RCX, STATE_FIELD(SEQUENCE_LENGTH));
		BRANCH_TO_LABEL(ASSEMBLY, CC_G, SINGLE_LOOP_TOP);
		ROW_POINTER(ASSEMBLY, RSI, DIMENSION * 4);

		int	ROW_INDEX;

		for (ROW_INDEX = 0; ROW_INDEX < 4; ROW_INDEX++)
			ZERO_VECTOR(ASSEMBLY, ROW_INDEX);

		WORD_FORWARD_LAYOUT	WORD_STATE = { FINAL_NORM_OFFSET, DIMENSION * 4 };

		FOR_EACH_CHUNK(ASSEMBLY, DIMENSION, WORD_FOUR_ROWS_CHUNK, &WORD_STATE);
		SCALAR_LOAD(ASSEMBLY, 5, MEMORY_AT(RDI, DIMENSION * 4));

		for (ROW_INDEX = 0; ROW_INDEX < 4; ROW_INDEX++)
		{
			HORIZONTAL_SUM(ASSEMBLY, ROW_INDEX, 6);
			SCALAR_MATH(ASSEMBLY, OPCODE_ADD, ROW_INDEX, ROW_INDEX, 5);
			SCALAR_STORE(
				ASSEMBLY,
				MEMORY_INDEXED(R10, RAX, 4, COLUMN_OFFSET + 4 * ROW_INDEX),
				ROW_INDEX
			);
		}

		ADD_IMMEDIATE(ASSEMBLY, RAX, 4);
		JUMP_TO_LABEL(ASSEMBLY, QUAD_LOOP_TOP);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, SINGLE_LOOP_TOP);
		COMPARE_MEMORY(ASSEMBLY, RAX, STATE_FIELD(SEQUENCE_LENGTH));
		BRANCH_TO_LABEL(ASSEMBLY, CC_GE, END_LABEL);
		ROW_POINTER(ASSEMBLY, RSI, DIMENSION * 4);
		DOT_PRODUCT(
			ASSEMBLY, 0, 1, 2, RSI, FINAL_NORM_OFFSET, RDI, 0, DIMENSION
		);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_ADD, 0, 0, MEMORY_AT(RDI, DIMENSION * 4)
		);
		SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(R10, RAX, 4, COLUMN_OFFSET), 0);
		ADD_IMMEDIATE(ASSEMBLY, RAX, 1);
		JUMP_TO_LABEL(ASSEMBLY, SINGLE_LOOP_TOP);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, END_LABEL);
		JUMP_TO_REGISTER(ASSEMBLY, RBP);
		return ;
	}

	int32_t	WEIGHT_OFFSET = (int32_t)NEURAL_WEB->LOSS_WEIGHTS_OFFSET;
	int32_t	ACTIVE_LIST_OFFSET = (int32_t)LAST_LOGITS_OFFSET;

	VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 7, 7, 7);
	MOVE_IMMEDIATE(ASSEMBLY, RDX, 0);

	TIME_LOOP	STEP_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);
	int			SKIP_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

	ROW_POINTER(ASSEMBLY, RSI, DIMENSION * 4);
	BROADCAST_MEMORY(
		ASSEMBLY, 1, 0, MEMORY_INDEXED(R10, RAX, 4, COLUMN_OFFSET)
	);
	SCALAR_MATH_MEMORY(
		ASSEMBLY, OPCODE_ADD, 7, 7, MEMORY_INDEXED(R10, RAX, 4, COLUMN_OFFSET)
	);
	SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 1, 0, 0);
	SCALAR_LOAD(ASSEMBLY, 2, MEMORY_INDEXED(R14, RAX, 4, WEIGHT_OFFSET));
	SCALAR_MATH_MEMORY(
		ASSEMBLY, OPCODE_MULTIPLY, 2, 2, STATE_FIELD(GRADIENT_SCALE)
	);
	SCALAR_MATH_MEMORY(
		ASSEMBLY, OPCODE_MULTIPLY, 2, 2, STATE_FIELD(GRADIENT_SKIP_THRESHOLD)
	);
	SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 2, 2, 2);
	SCALAR_COMPARE(ASSEMBLY, 1, 2);
	BRANCH_TO_LABEL(ASSEMBLY, CC_BE, SKIP_LABEL);

	WORD_BACKWARD_LAYOUT	WORD_STATE = { FINAL_GRADIENT_OFFSET };

	FOR_EACH_CHUNK(ASSEMBLY, DIMENSION, WORD_BACKWARD_CHUNK, &WORD_STATE);
	MOVE_TO_MEMORY(
		ASSEMBLY, MEMORY_INDEXED(R14, RDX, 8, ACTIVE_LIST_OFFSET), RAX
	);
	ADD_IMMEDIATE(ASSEMBLY, RDX, 1);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, SKIP_LABEL);
	END_TIME_LOOP(ASSEMBLY, STEP_LOOP);
	SCALAR_MATH_MEMORY(
		ASSEMBLY, OPCODE_ADD, 7, 7, MEMORY_AT(RDI, PLANE_SIZE + DIMENSION * 4)
	);
	SCALAR_STORE(ASSEMBLY, MEMORY_AT(RDI, PLANE_SIZE + DIMENSION * 4), 7);

	int	GROUP_START;

	for (GROUP_START = 0; GROUP_START < DIMENSION / 8; GROUP_START += 12)
	{
		int	GROUP_COUNT;

		if (DIMENSION / 8 - GROUP_START < 12)
			GROUP_COUNT = DIMENSION / 8 - GROUP_START;
		else
			GROUP_COUNT = 12;

		int	LOOP_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int	LOOP_DONE = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int	REGISTER_INDEX;

		for (REGISTER_INDEX = 0; REGISTER_INDEX < GROUP_COUNT; REGISTER_INDEX++)
			ZERO_VECTOR(ASSEMBLY, REGISTER_INDEX);

		MOVE_IMMEDIATE(ASSEMBLY, RCX, 0);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, LOOP_TOP);
		COMPARE_REGISTER(ASSEMBLY, RCX, RDX);
		BRANCH_TO_LABEL(ASSEMBLY, CC_GE, LOOP_DONE);
		MOVE_FROM_MEMORY(
			ASSEMBLY, RAX, MEMORY_INDEXED(R14, RCX, 8, ACTIVE_LIST_OFFSET)
		);
		ROW_POINTER(ASSEMBLY, RSI, DIMENSION * 4);
		BROADCAST_MEMORY(
			ASSEMBLY, 1, 12, MEMORY_INDEXED(R10, RAX, 4, COLUMN_OFFSET)
		);

		for (REGISTER_INDEX = 0; REGISTER_INDEX < GROUP_COUNT; REGISTER_INDEX++)
			MULTIPLY_ADD_MEMORY(
				ASSEMBLY, 1, REGISTER_INDEX, 12,
				MEMORY_AT(
					RSI, FINAL_NORM_OFFSET + 32 * (GROUP_START + REGISTER_INDEX)
				)
			);

		ADD_IMMEDIATE(ASSEMBLY, RCX, 1);
		JUMP_TO_LABEL(ASSEMBLY, LOOP_TOP);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, LOOP_DONE);

		for (REGISTER_INDEX = 0; REGISTER_INDEX < GROUP_COUNT; REGISTER_INDEX++)
		{
			VECTOR_MATH_MEMORY(
				ASSEMBLY, 1, OPCODE_ADD, REGISTER_INDEX, REGISTER_INDEX,
				MEMORY_AT(RDI, PLANE_SIZE + 32 * (GROUP_START + REGISTER_INDEX))
			);
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(
					RDI, PLANE_SIZE + 32 * (GROUP_START + REGISTER_INDEX)
				),
				REGISTER_INDEX
			);
		}
	}

	JUMP_TO_REGISTER(ASSEMBLY, RBP);
}

static void	KERNEL_COPY_OFFSETS(
	WEB *NEURAL_WEB, NEURON *COPIER_NEURON, int32_t *OFFSETS
);

static void
	GENERATE_LOSS(ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB)
{
	int32_t	ROW_BYTES = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH * 4;
	int32_t	LOGIT_PLANE_OFFSET = (int32_t)LOGITS_OFFSET;
	int32_t	LOG_SUM_OFFSET = (int32_t)NEURAL_WEB->SOFTMAX_STATISTICS_OFFSET;
	int32_t	TARGET_LOGIT_OFFSET = (int32_t)NEURAL_WEB->TARGET_LOGIT_OFFSET;
	int32_t	WEIGHT_OFFSET = (int32_t)NEURAL_WEB->LOSS_WEIGHTS_OFFSET;
	int32_t	TARGET_OFFSET = (int32_t)NEURAL_WEB->TARGETS_OFFSET;
	int32_t	TOKEN_OFFSET = (int32_t)NEURAL_WEB->TOKENS_OFFSET;
	int		HAS_COPY = NEURAL_WEB->COPY_ID >= 0;
	int32_t	COPY_OFFSETS[10] = { 0 };

	if (HAS_COPY)
		KERNEL_COPY_OFFSETS(
			NEURAL_WEB, &NEURAL_WEB->NEURONS[NEURAL_WEB->COPY_ID], COPY_OFFSETS
		);

	{
		TIME_LOOP	STEP_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);
		int			SKIP_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

		VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 0, 0, 0);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, TARGET_LOGIT_OFFSET), 0
		);
		MOVE_SIGN_EXTENDED(
			ASSEMBLY, RDX, MEMORY_INDEXED(R14, RAX, 4, TARGET_OFFSET)
		);
		TEST_REGISTER(ASSEMBLY, RDX, RDX);
		BRANCH_TO_LABEL(ASSEMBLY, CC_S, SKIP_LABEL);
		MULTIPLY_IMMEDIATE(ASSEMBLY, RDX, RDX, ROW_BYTES);
		LOAD_ADDRESS(ASSEMBLY, RDX, MEMORY_INDEXED(RDX, RAX, 4, 0));
		SCALAR_LOAD(
			ASSEMBLY, 0, MEMORY_INDEXED(R14, RDX, 1, LOGIT_PLANE_OFFSET)
		);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, TARGET_LOGIT_OFFSET), 0
		);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, SKIP_LABEL);
		END_TIME_LOOP(ASSEMBLY, STEP_LOOP);
	}

	int	GROUP_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	GROUP_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	MAX_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	MAX_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	SUM_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	SUM_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);

	MOVE_IMMEDIATE(ASSEMBLY, R8, 0);
	MOVE_FROM_MEMORY(ASSEMBLY, R9, STATE_FIELD(SEQUENCE_LENGTH));
	SHIFT_LEFT_IMMEDIATE(ASSEMBLY, R9, 2);
	MOVE_FROM_MEMORY(ASSEMBLY, RCX, STATE_FIELD(WORD_COUNT));
	MULTIPLY_IMMEDIATE(ASSEMBLY, RCX, RCX, ROW_BYTES);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, GROUP_TOP);
	COMPARE_REGISTER(ASSEMBLY, R8, R9);
	BRANCH_TO_LABEL(ASSEMBLY, CC_GE, GROUP_END);
	LOAD_ADDRESS(ASSEMBLY, RSI, MEMORY_INDEXED(R14, R8, 1, LOGIT_PLANE_OFFSET));
	VECTOR_LOAD(ASSEMBLY, 1, 0, STATE_CONSTANT(CONSTANT_NEGATIVE_INFINITY));
	MOVE_IMMEDIATE(ASSEMBLY, RDX, 0);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, MAX_TOP);
	COMPARE_REGISTER(ASSEMBLY, RDX, RCX);
	BRANCH_TO_LABEL(ASSEMBLY, CC_GE, MAX_END);
	VECTOR_MATH_MEMORY(
		ASSEMBLY, 1, OPCODE_MAXIMUM, 0, 0, MEMORY_INDEXED(RSI, RDX, 1, 0)
	);
	ADD_IMMEDIATE(ASSEMBLY, RDX, ROW_BYTES);
	JUMP_TO_LABEL(ASSEMBLY, MAX_TOP);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, MAX_END);
	ZERO_VECTOR(ASSEMBLY, 1);
	MOVE_IMMEDIATE(ASSEMBLY, RDX, 0);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, SUM_TOP);
	COMPARE_REGISTER(ASSEMBLY, RDX, RCX);
	BRANCH_TO_LABEL(ASSEMBLY, CC_GE, SUM_END);
	VECTOR_LOAD(ASSEMBLY, 1, 2, MEMORY_INDEXED(RSI, RDX, 1, 0));
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_SUBTRACT, 2, 2, 0);
	VECTOR_EXPONENTIAL(ASSEMBLY, 1, 2, 3, 4);
	VECTOR_STORE(ASSEMBLY, 1, MEMORY_INDEXED(RSI, RDX, 1, 0), 2);
	VECTOR_MATH(ASSEMBLY, 1, OPCODE_ADD, 1, 1, 2);
	ADD_IMMEDIATE(ASSEMBLY, RDX, ROW_BYTES);
	JUMP_TO_LABEL(ASSEMBLY, SUM_TOP);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, SUM_END);
	VECTOR_STORE(ASSEMBLY, 1, MEMORY_INDEXED(R14, R8, 1, LOG_SUM_OFFSET), 0);
	VECTOR_STORE(
		ASSEMBLY, 1, MEMORY_INDEXED(R14, R8, 1, LOG_SUM_OFFSET + ROW_BYTES), 1
	);
	ADD_IMMEDIATE(ASSEMBLY, R8, 32);
	JUMP_TO_LABEL(ASSEMBLY, GROUP_TOP);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, GROUP_END);

	if (HAS_COPY)
	{
		int32_t		ATTENTION_OFFSET = COPY_OFFSETS[2];
		int32_t		GATE_OFFSET = COPY_OFFSETS[3];
		int32_t		COPY_MASS_OFFSET = COPY_OFFSETS[4];
		int32_t		MIXED_PROB_OFFSET = COPY_OFFSETS[5];
		int32_t		LOGIT_SCALE_OFFSET = COPY_OFFSETS[6];
		int32_t		TARGET_SCALE_OFFSET = COPY_OFFSETS[7];
		int32_t		GATE_GRADIENT_OFFSET = COPY_OFFSETS[8];
		int32_t		COPY_GRADIENT_OFFSET = COPY_OFFSETS[9];
		TIME_LOOP	STEP_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);
		int			SKIP_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int			DONE_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int			SCAN_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int			SCAN_NEXT = ASSEMBLER_NEW_LABEL(ASSEMBLY);

		VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 0, 0, 0);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, LOGIT_SCALE_OFFSET), 0
		);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, TARGET_SCALE_OFFSET), 0
		);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, GATE_GRADIENT_OFFSET), 0
		);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, COPY_GRADIENT_OFFSET), 0
		);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, COPY_MASS_OFFSET), 0
		);
		SCALAR_LOAD(ASSEMBLY, 1, STATE_FIELD(ONE));
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, MIXED_PROB_OFFSET), 1
		);
		MOVE_SIGN_EXTENDED(
			ASSEMBLY, RDX, MEMORY_INDEXED(R14, RAX, 4, TARGET_OFFSET)
		);
		TEST_REGISTER(ASSEMBLY, RDX, RDX);
		BRANCH_TO_LABEL(ASSEMBLY, CC_S, SKIP_LABEL);
		SCALAR_LOAD(
			ASSEMBLY, 0, MEMORY_INDEXED(R14, RAX, 4, TARGET_LOGIT_OFFSET)
		);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_SUBTRACT, 0, 0,
			MEMORY_INDEXED(R14, RAX, 4, LOG_SUM_OFFSET)
		);
		VECTOR_EXPONENTIAL(ASSEMBLY, 0, 0, 3, 4);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_DIVIDE, 6, 0,
			MEMORY_INDEXED(R14, RAX, 4, LOG_SUM_OFFSET + ROW_BYTES)
		);
		VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 7, 7, 7);
		MULTIPLY_IMMEDIATE(ASSEMBLY, RSI, RAX, ROW_BYTES);
		ADD_REGISTER(ASSEMBLY, RSI, R14);
		MOVE_IMMEDIATE(ASSEMBLY, R9, 0);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, SCAN_TOP);
		MOVE_SIGN_EXTENDED(
			ASSEMBLY, R10, MEMORY_INDEXED(R14, R9, 4, TOKEN_OFFSET)
		);
		COMPARE_REGISTER(ASSEMBLY, R10, RDX);
		BRANCH_TO_LABEL(ASSEMBLY, CC_NE, SCAN_NEXT);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_ADD, 7, 7,
			MEMORY_INDEXED(RSI, R9, 4, ATTENTION_OFFSET)
		);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, SCAN_NEXT);
		ADD_IMMEDIATE(ASSEMBLY, R9, 1);
		COMPARE_REGISTER(ASSEMBLY, R9, RAX);
		BRANCH_TO_LABEL(ASSEMBLY, CC_LE, SCAN_TOP);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, COPY_MASS_OFFSET), 7
		);
		SCALAR_LOAD(ASSEMBLY, 8, MEMORY_INDEXED(R14, RAX, 4, GATE_OFFSET));
		SCALAR_LOAD(ASSEMBLY, 9, STATE_FIELD(ONE));
		SCALAR_MATH(ASSEMBLY, OPCODE_SUBTRACT, 9, 9, 8);
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 10, 9, 6);
		SCALAR_MULTIPLY_ADD(ASSEMBLY, 10, 8, 7);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MAXIMUM, 10, 10,
			MEMORY_AT(R15, (int32_t)(offsetof(KERNEL_CONTEXT, SCRATCH) + 48))
		);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, MIXED_PROB_OFFSET), 10
		);
		SCALAR_LOAD(ASSEMBLY, 11, MEMORY_INDEXED(R14, RAX, 4, WEIGHT_OFFSET));
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MULTIPLY, 11, 11, STATE_FIELD(GRADIENT_SCALE)
		);
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 12, 9, 6);
		SCALAR_MATH(ASSEMBLY, OPCODE_DIVIDE, 12, 12, 10);
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 12, 12, 11);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, TARGET_SCALE_OFFSET), 12
		);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_DIVIDE, 13, 12,
			MEMORY_INDEXED(R14, RAX, 4, LOG_SUM_OFFSET + ROW_BYTES)
		);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, LOGIT_SCALE_OFFSET), 13
		);
		SCALAR_MATH(ASSEMBLY, OPCODE_SUBTRACT, 13, 6, 7);
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 13, 13, 8);
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 13, 13, 9);
		SCALAR_MATH(ASSEMBLY, OPCODE_DIVIDE, 13, 13, 10);
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 13, 13, 11);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, GATE_GRADIENT_OFFSET), 13
		);
		SCALAR_MATH(ASSEMBLY, OPCODE_DIVIDE, 14, 8, 10);
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 14, 14, 11);
		VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 15, 15, 15);
		SCALAR_MATH(ASSEMBLY, OPCODE_SUBTRACT, 14, 15, 14);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, COPY_GRADIENT_OFFSET), 14
		);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, SKIP_LABEL);
		(void)DONE_LABEL;
		END_TIME_LOOP(ASSEMBLY, STEP_LOOP);
	}

	{
		int	SCALE_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int	SCALE_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int	VOCABULARY_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		int	VOCABULARY_END = ASSEMBLER_NEW_LABEL(ASSEMBLY);

		MOVE_IMMEDIATE(ASSEMBLY, R8, 0);
		MOVE_FROM_MEMORY(ASSEMBLY, R9, STATE_FIELD(SEQUENCE_LENGTH));
		SHIFT_LEFT_IMMEDIATE(ASSEMBLY, R9, 2);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, SCALE_TOP);
		COMPARE_REGISTER(ASSEMBLY, R8, R9);
		BRANCH_TO_LABEL(ASSEMBLY, CC_GE, SCALE_END);
		LOAD_ADDRESS(
			ASSEMBLY, RSI, MEMORY_INDEXED(R14, R8, 1, LOGIT_PLANE_OFFSET)
		);

		if (HAS_COPY)
			VECTOR_LOAD(
				ASSEMBLY, 1, 2, MEMORY_INDEXED(R14, R8, 1, COPY_OFFSETS[6])
			);
		else
		{
			VECTOR_LOAD(
				ASSEMBLY, 1, 2, MEMORY_INDEXED(R14, R8, 1, WEIGHT_OFFSET)
			);
			BROADCAST_MEMORY(ASSEMBLY, 1, 3, STATE_FIELD(GRADIENT_SCALE));
			VECTOR_MATH(ASSEMBLY, 1, OPCODE_MULTIPLY, 2, 2, 3);
			VECTOR_MATH_MEMORY(
				ASSEMBLY, 1, OPCODE_DIVIDE, 2, 2,
				MEMORY_INDEXED(R14, R8, 1, LOG_SUM_OFFSET + ROW_BYTES)
			);
		}

		MOVE_IMMEDIATE(ASSEMBLY, RDX, 0);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, VOCABULARY_TOP);
		COMPARE_REGISTER(ASSEMBLY, RDX, RCX);
		BRANCH_TO_LABEL(ASSEMBLY, CC_GE, VOCABULARY_END);
		VECTOR_MATH_MEMORY(
			ASSEMBLY, 1, OPCODE_MULTIPLY, 3, 2, MEMORY_INDEXED(RSI, RDX, 1, 0)
		);
		VECTOR_STORE(ASSEMBLY, 1, MEMORY_INDEXED(RSI, RDX, 1, 0), 3);
		ADD_IMMEDIATE(ASSEMBLY, RDX, ROW_BYTES);
		JUMP_TO_LABEL(ASSEMBLY, VOCABULARY_TOP);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, VOCABULARY_END);
		ADD_IMMEDIATE(ASSEMBLY, R8, 32);
		JUMP_TO_LABEL(ASSEMBLY, SCALE_TOP);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, SCALE_END);
	}

	{
		TIME_LOOP	STEP_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);
		int			SKIP_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

		MOVE_SIGN_EXTENDED(
			ASSEMBLY, RDX, MEMORY_INDEXED(R14, RAX, 4, TARGET_OFFSET)
		);
		TEST_REGISTER(ASSEMBLY, RDX, RDX);
		BRANCH_TO_LABEL(ASSEMBLY, CC_S, SKIP_LABEL);
		MULTIPLY_IMMEDIATE(ASSEMBLY, RDX, RDX, ROW_BYTES);
		LOAD_ADDRESS(ASSEMBLY, RDX, MEMORY_INDEXED(RDX, RAX, 4, 0));

		if (HAS_COPY)
			SCALAR_LOAD(
				ASSEMBLY, 0, MEMORY_INDEXED(R14, RAX, 4, COPY_OFFSETS[7])
			);
		else
		{
			SCALAR_LOAD(
				ASSEMBLY, 0, MEMORY_INDEXED(R14, RAX, 4, WEIGHT_OFFSET)
			);
			SCALAR_MATH_MEMORY(
				ASSEMBLY, OPCODE_MULTIPLY, 0, 0, STATE_FIELD(GRADIENT_SCALE)
			);
		}

		SCALAR_LOAD(
			ASSEMBLY, 1, MEMORY_INDEXED(R14, RDX, 1, LOGIT_PLANE_OFFSET)
		);
		SCALAR_MATH(ASSEMBLY, OPCODE_SUBTRACT, 1, 1, 0);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R14, RDX, 1, LOGIT_PLANE_OFFSET), 1
		);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, SKIP_LABEL);
		END_TIME_LOOP(ASSEMBLY, STEP_LOOP);
	}
}

typedef struct
{
	int32_t	GRADIENT_PLANE;
	int32_t	MATRIX_BYTES;
	int32_t	NORMALIZED_OFFSET;
} HEAD_GRADIENT_LAYOUT;

static void
	HEAD_GRADIENT_CHUNK(
		ASSEMBLER *ASSEMBLY, void *BODY_STATE, int INDEX_REGISTER,
		int32_t OFFSET
	)
{
	HEAD_GRADIENT_LAYOUT	*HEAD_STATE = BODY_STATE;

	VECTOR_LOAD(
		ASSEMBLY, 1, 0,
		OPERAND_AT(RSI, INDEX_REGISTER, HEAD_STATE->NORMALIZED_OFFSET + OFFSET)
	);

	int	PROJECTION_INDEX;

	for (PROJECTION_INDEX = 0; PROJECTION_INDEX < 3; PROJECTION_INDEX++)
	{
		VECTOR_LOAD(
			ASSEMBLY, 1, 4 + PROJECTION_INDEX,
			OPERAND_AT(
				R8, INDEX_REGISTER,
				HEAD_STATE->GRADIENT_PLANE +
					PROJECTION_INDEX * HEAD_STATE->MATRIX_BYTES + OFFSET
			)
		);
		MULTIPLY_ADD(
			ASSEMBLY, 1, 4 + PROJECTION_INDEX, 1 + PROJECTION_INDEX, 0
		);
		VECTOR_STORE(
			ASSEMBLY, 1,
			OPERAND_AT(
				R8, INDEX_REGISTER,
				HEAD_STATE->GRADIENT_PLANE +
					PROJECTION_INDEX * HEAD_STATE->MATRIX_BYTES + OFFSET
			),
			4 + PROJECTION_INDEX
		);
	}
}

static void
	BEGIN_WEIGHT_ROW_LOOP(ASSEMBLER *ASSEMBLY, int *LOOP_TOP)
{
	MOVE_REGISTER(ASSEMBLY, R8, R12);
	MOVE_IMMEDIATE(ASSEMBLY, RCX, 0);
	*LOOP_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, *LOOP_TOP);
}

static void
	END_WEIGHT_ROW_LOOP(
		ASSEMBLER *ASSEMBLY, int LOOP_TOP, int DIMENSION, int HEAD_DIMENSION
	)
{
	ADD_IMMEDIATE(ASSEMBLY, R8, HALF_WEIGHTS ? DIMENSION * 2 : DIMENSION * 4);
	ADD_IMMEDIATE(ASSEMBLY, RCX, 1);
	COMPARE_IMMEDIATE(ASSEMBLY, RCX, HEAD_DIMENSION);
	BRANCH_TO_LABEL(ASSEMBLY, CC_L, LOOP_TOP);
}

static void
	BEGIN_SOURCE_LOOP(
		ASSEMBLER *ASSEMBLY, int *LOOP_TOP, int HEAD_DIMENSION,
		int ADD_ACTIVATION_OFFSET
	)
{
	MOVE_IMMEDIATE(ASSEMBLY, R9, 0);
	*LOOP_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, *LOOP_TOP);
	MULTIPLY_IMMEDIATE(ASSEMBLY, R10, R9, HEAD_DIMENSION * 4);
	ADD_REGISTER(ASSEMBLY, R10, R14);

	if (ADD_ACTIVATION_OFFSET)
		ADD_FROM_MEMORY(ASSEMBLY, R10, STATE_FIELD(NEURON_ACTIVATION_OFFSET));
}

static void
	END_SOURCE_LOOP(ASSEMBLER *ASSEMBLY, int LOOP_TOP)
{
	ADD_IMMEDIATE(ASSEMBLY, R9, 1);
	COMPARE_REGISTER(ASSEMBLY, R9, RAX);
	BRANCH_TO_LABEL(ASSEMBLY, CC_LE, LOOP_TOP);
}

static int	OUTER_INPUT_FROM_NEURON;

static void
	OUTER_PRODUCT_BLOCKS(
		ASSEMBLER *ASSEMBLY, int START_ROW, int BLOCK_COUNT, int ROWS_PER_BLOCK,
		int COLUMN_COUNT, int32_t COEFFICIENT_OFFSET,
		int32_t COEFFICIENT_STRIDE, int COEFFICIENT_FROM_NEURON,
		int32_t INPUT_OFFSET, int32_t INPUT_STRIDE, int32_t GRADIENT_OFFSET,
		int32_t GRADIENT_STRIDE
	)
{
	int	ROW_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	COLUMN_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	TIME_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	TIME_DONE = ASSEMBLER_NEW_LABEL(ASSEMBLY);

	MOVE_IMMEDIATE(ASSEMBLY, R8, START_ROW * 4);
	MOVE_IMMEDIATE(ASSEMBLY, R10, START_ROW * GRADIENT_STRIDE);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, ROW_TOP);
	MOVE_IMMEDIATE(ASSEMBLY, R9, 0);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, COLUMN_TOP);

	int	ROW_INDEX;

	for (ROW_INDEX = 0; ROW_INDEX < ROWS_PER_BLOCK; ROW_INDEX++)
	{
		ZERO_VECTOR(ASSEMBLY, 2 * ROW_INDEX);
		ZERO_VECTOR(ASSEMBLY, 2 * ROW_INDEX + 1);
	}

	MOVE_REGISTER(ASSEMBLY, RSI, R14);

	if (OUTER_INPUT_FROM_NEURON)
		ADD_FROM_MEMORY(ASSEMBLY, RSI, STATE_FIELD(NEURON_ACTIVATION_OFFSET));

	MOVE_REGISTER(ASSEMBLY, RDI, R14);

	if (COEFFICIENT_FROM_NEURON)
		ADD_FROM_MEMORY(ASSEMBLY, RDI, STATE_FIELD(NEURON_ACTIVATION_OFFSET));

	MOVE_IMMEDIATE(ASSEMBLY, RAX, 0);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, TIME_TOP);
	COMPARE_MEMORY(ASSEMBLY, RAX, STATE_FIELD(SEQUENCE_LENGTH));
	BRANCH_TO_LABEL(ASSEMBLY, CC_GE, TIME_DONE);
	VECTOR_LOAD(ASSEMBLY, 1, 12, MEMORY_INDEXED(RSI, R9, 1, INPUT_OFFSET));
	VECTOR_LOAD(ASSEMBLY, 1, 13, MEMORY_INDEXED(RSI, R9, 1, INPUT_OFFSET + 32));

	for (ROW_INDEX = 0; ROW_INDEX < ROWS_PER_BLOCK; ROW_INDEX++)
	{
		BROADCAST_MEMORY(
			ASSEMBLY, 1, 14,
			MEMORY_INDEXED(RDI, R8, 1, COEFFICIENT_OFFSET + ROW_INDEX * 4)
		);
		MULTIPLY_ADD(ASSEMBLY, 1, 2 * ROW_INDEX, 14, 12);
		MULTIPLY_ADD(ASSEMBLY, 1, 2 * ROW_INDEX + 1, 14, 13);
	}

	ADD_IMMEDIATE(ASSEMBLY, RSI, INPUT_STRIDE);
	ADD_IMMEDIATE(ASSEMBLY, RDI, COEFFICIENT_STRIDE);
	ADD_IMMEDIATE(ASSEMBLY, RAX, 1);
	JUMP_TO_LABEL(ASSEMBLY, TIME_TOP);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, TIME_DONE);
	LOAD_ADDRESS(ASSEMBLY, R11, MEMORY_INDEXED(R12, R10, 1, 0));

	for (ROW_INDEX = 0; ROW_INDEX < ROWS_PER_BLOCK; ROW_INDEX++)
	{
		int	HALF_INDEX;

		for (HALF_INDEX = 0; HALF_INDEX < 2; HALF_INDEX++)
		{
			MEMORY_OPERAND	GRADIENT_OPERAND = MEMORY_INDEXED(
				R11, R9, 1,
				GRADIENT_OFFSET + ROW_INDEX * GRADIENT_STRIDE + 32 * HALF_INDEX
			);

			VECTOR_MATH_MEMORY(
				ASSEMBLY, 1, OPCODE_ADD, 2 * ROW_INDEX + HALF_INDEX,
				2 * ROW_INDEX + HALF_INDEX, GRADIENT_OPERAND
			);
			VECTOR_STORE(
				ASSEMBLY, 1, GRADIENT_OPERAND, 2 * ROW_INDEX + HALF_INDEX
			);
		}
	}

	ADD_IMMEDIATE(ASSEMBLY, R9, 64);
	COMPARE_IMMEDIATE(ASSEMBLY, R9, COLUMN_COUNT * 4);
	BRANCH_TO_LABEL(ASSEMBLY, CC_L, COLUMN_TOP);
	ADD_IMMEDIATE(ASSEMBLY, R8, ROWS_PER_BLOCK * 4);
	ADD_IMMEDIATE(ASSEMBLY, R10, ROWS_PER_BLOCK * GRADIENT_STRIDE);
	COMPARE_IMMEDIATE(
		ASSEMBLY, R8, (START_ROW + BLOCK_COUNT * ROWS_PER_BLOCK) * 4
	);
	BRANCH_TO_LABEL(ASSEMBLY, CC_L, ROW_TOP);
}

static void
	ACCUMULATE_OUTER_PRODUCT(
		ASSEMBLER *ASSEMBLY, int ROW_COUNT, int COLUMN_COUNT,
		int32_t COEFFICIENT_OFFSET, int32_t COEFFICIENT_STRIDE,
		int COEFFICIENT_IN_AREA, int32_t INPUT_OFFSET, int32_t INPUT_STRIDE,
		int32_t GRADIENT_OFFSET, int32_t GRADIENT_STRIDE
	)
{
	int	FULL_BLOCK_COUNT = ROW_COUNT / 6;
	int	REMAINING_ROWS = ROW_COUNT % 6;

	if (FULL_BLOCK_COUNT)
		OUTER_PRODUCT_BLOCKS(
			ASSEMBLY, 0, FULL_BLOCK_COUNT, 6, COLUMN_COUNT, COEFFICIENT_OFFSET,
			COEFFICIENT_STRIDE, COEFFICIENT_IN_AREA, INPUT_OFFSET, INPUT_STRIDE,
			GRADIENT_OFFSET, GRADIENT_STRIDE
		);

	if (REMAINING_ROWS)
		OUTER_PRODUCT_BLOCKS(
			ASSEMBLY, FULL_BLOCK_COUNT * 6, 1, REMAINING_ROWS, COLUMN_COUNT,
			COEFFICIENT_OFFSET, COEFFICIENT_STRIDE, COEFFICIENT_IN_AREA,
			INPUT_OFFSET, INPUT_STRIDE, GRADIENT_OFFSET, GRADIENT_STRIDE
		);
}

static int	USE_ROTARY;

static void
	ROTATE_ROWS(
		ASSEMBLER *ASSEMBLY, int HEAD_DIMENSION, int INVERSE,
		int FIRST_BASE_REGISTER, int32_t FIRST_OFFSET, int SECOND_BASE_REGISTER,
		int32_t SECOND_OFFSET
	)
{
	MOVE_FROM_MEMORY(ASSEMBLY, R11, STATE_FIELD(ROTARY_TABLE));
	MULTIPLY_IMMEDIATE(ASSEMBLY, R10, RAX, HEAD_DIMENSION * 8);
	ADD_REGISTER(ASSEMBLY, R10, R11);

	int	ROW_INDEX;

	for (ROW_INDEX = 0; ROW_INDEX < 2; ROW_INDEX++)
	{
		int	BASE_REGISTER;

		if (ROW_INDEX)
			BASE_REGISTER = SECOND_BASE_REGISTER;
		else
			BASE_REGISTER = FIRST_BASE_REGISTER;

		int32_t	ROW_OFFSET;

		if (ROW_INDEX)
			ROW_OFFSET = SECOND_OFFSET;
		else
			ROW_OFFSET = FIRST_OFFSET;

		int	CHUNK_INDEX;

		for (CHUNK_INDEX = 0; CHUNK_INDEX < HEAD_DIMENSION / 8; CHUNK_INDEX++)
		{
			VECTOR_LOAD(
				ASSEMBLY, 1, 0,
				MEMORY_AT(BASE_REGISTER, ROW_OFFSET + 32 * CHUNK_INDEX)
			);
			VECTOR_PERMUTE(ASSEMBLY, 1, 1, 0, 0XB1);
			VECTOR_MATH_MEMORY(
				ASSEMBLY, 1, OPCODE_MULTIPLY, 1, 1,
				MEMORY_AT(R10, HEAD_DIMENSION * 4 + 32 * CHUNK_INDEX)
			);
			VECTOR_MATH_MEMORY(
				ASSEMBLY, 1, OPCODE_MULTIPLY, 0, 0,
				MEMORY_AT(R10, 32 * CHUNK_INDEX)
			);
			VECTOR_MATH(
				ASSEMBLY, 1, INVERSE ? OPCODE_SUBTRACT : OPCODE_ADD, 0, 0, 1
			);
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(BASE_REGISTER, ROW_OFFSET + 32 * CHUNK_INDEX), 0
			);
		}
	}
}

static void
	GENERATE_HEAD(
		ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB, NEURON *HEAD_NEURON, int PASS_ROLE
	)
{
	int		MODEL_DIMENSION = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int		HEAD_DIMENSION = NEURAL_WEB->CONFIGURATION.HEAD_DIMENSION;
	int		AREA_INDEX = HEAD_NEURON->AREA_INDEX;
	int		CHUNK_COUNT = HEAD_DIMENSION / 8;
	int		MAX_TOKENS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;
	int32_t	MATRIX_BYTES = HEAD_DIMENSION * MODEL_DIMENSION * 4;
	int32_t	QUERY_OFFSET = 0;
	int32_t	KEY_OFFSET = QUERY_OFFSET + MAX_TOKENS * HEAD_DIMENSION * 4;
	int32_t	VALUE_OFFSET = KEY_OFFSET + MAX_TOKENS * HEAD_DIMENSION * 4;
	int32_t	MIXED_OFFSET = VALUE_OFFSET + MAX_TOKENS * HEAD_DIMENSION * 4;
	int32_t	PROBABILITY_OFFSET = MIXED_OFFSET + MAX_TOKENS * HEAD_DIMENSION * 4;
	int32_t	INPUT_OFFSET =
		(int32_t)KERNEL_LAYER_NORMALIZED(NEURAL_WEB, AREA_INDEX);
	int32_t	INPUT_GRADIENT_OFFSET =
		(int32_t)LAYER_NORMALIZED_GRADIENT(NEURAL_WEB, AREA_INDEX);
	int32_t	RESIDUAL_OFFSET =
		(int32_t)KERNEL_LAYER_RESIDUAL(NEURAL_WEB, AREA_INDEX + 1);
	int32_t	RESIDUAL_GRADIENT_OFFSET =
		(int32_t)LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, AREA_INDEX + 1);
	int32_t	GRADIENT_PLANE = (int32_t)PARAMETER_PLANE;
	int32_t	QUERY_GRADIENT_OFFSET = (int32_t)ACTIVATION_PLANE + QUERY_OFFSET;
	int32_t	KEY_GRADIENT_OFFSET = (int32_t)ACTIVATION_PLANE + KEY_OFFSET;
	int32_t	VALUE_GRADIENT_OFFSET = (int32_t)ACTIVATION_PLANE + VALUE_OFFSET;
	int32_t	MIXED_GRADIENT_OFFSET = (int32_t)ACTIVATION_PLANE + MIXED_OFFSET;
	int32_t	PROBABILITY_GRADIENT =
		(int32_t)ACTIVATION_PLANE + PROBABILITY_OFFSET;
	int		LOOP_TOP;
	int		SECOND_LOOP_TOP;

	if (PASS_ROLE == ROLE_FORWARD)
	{
		TIME_LOOP	TOKEN_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 1);

		ROW_POINTER(ASSEMBLY, RSI, MODEL_DIMENSION * 4);
		ROW_POINTER(ASSEMBLY, RDI, HEAD_DIMENSION * 4);
		ADD_FROM_MEMORY(ASSEMBLY, RDI, STATE_FIELD(NEURON_ACTIVATION_OFFSET));

		if (HALF_WEIGHTS)
		{
			MOVE_REGISTER(ASSEMBLY, RDX, R14);
			ADD_FROM_MEMORY(
				ASSEMBLY, RDX, STATE_FIELD(NEURON_ACTIVATION_OFFSET)
			);
		}

		int	QUERY_BASE_REGISTER;

		if (HALF_WEIGHTS)
			QUERY_BASE_REGISTER = RDX;
		else
			QUERY_BASE_REGISTER = RDI;

		BEGIN_WEIGHT_ROW_LOOP(ASSEMBLY, &LOOP_TOP);
		DOT_WITH_WEIGHTS(
			ASSEMBLY, 0, 1, 2, RSI, INPUT_OFFSET, R8, 0, MODEL_DIMENSION
		);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(QUERY_BASE_REGISTER, RCX, 4, QUERY_OFFSET),
			0
		);
		DOT_WITH_WEIGHTS(
			ASSEMBLY, 0, 1, 2, RSI, INPUT_OFFSET, R8, MATRIX_BYTES,
			MODEL_DIMENSION
		);
		SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(RDI, RCX, 4, KEY_OFFSET), 0);
		DOT_WITH_WEIGHTS(
			ASSEMBLY, 0, 1, 2, RSI, INPUT_OFFSET, R8, 2 * MATRIX_BYTES,
			MODEL_DIMENSION
		);
		SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(RDI, RCX, 4, VALUE_OFFSET), 0);
		END_WEIGHT_ROW_LOOP(
			ASSEMBLY, LOOP_TOP, MODEL_DIMENSION, HEAD_DIMENSION
		);

		if (USE_ROTARY)
			ROTATE_ROWS(
				ASSEMBLY, HEAD_DIMENSION, 0, QUERY_BASE_REGISTER, QUERY_OFFSET,
				RDI, KEY_OFFSET
			);

		if (!HALF_WEIGHTS)
		{
			ROW_POINTER(ASSEMBLY, RDX, MAX_TOKENS * 4);
			ADD_FROM_MEMORY(
				ASSEMBLY, RDX, STATE_FIELD(NEURON_ACTIVATION_OFFSET)
			);
		}

		int	CHUNK_INDEX;

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			VECTOR_LOAD(
				ASSEMBLY, 1, 8 + CHUNK_INDEX,
				MEMORY_AT(QUERY_BASE_REGISTER, QUERY_OFFSET + 32 * CHUNK_INDEX)
			);

		BEGIN_SOURCE_LOOP(ASSEMBLY, &LOOP_TOP, HEAD_DIMENSION, 1);
		ZERO_VECTOR(ASSEMBLY, 0);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			MULTIPLY_ADD_MEMORY(
				ASSEMBLY, 1, 0, 8 + CHUNK_INDEX,
				MEMORY_AT(R10, KEY_OFFSET + 32 * CHUNK_INDEX)
			);

		HORIZONTAL_SUM(ASSEMBLY, 0, 1);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MULTIPLY, 0, 0, STATE_FIELD(ATTENTION_SCALE)
		);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(RDX, R9, 4, PROBABILITY_OFFSET), 0
		);
		END_SOURCE_LOOP(ASSEMBLY, LOOP_TOP);
		LOAD_ADDRESS(ASSEMBLY, R10, MEMORY_AT(RDX, PROBABILITY_OFFSET));
		LOAD_ADDRESS(ASSEMBLY, RCX, MEMORY_AT(RAX, 1));
		SOFTMAX_ROW(ASSEMBLY, R10, RCX);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			ZERO_VECTOR(ASSEMBLY, 8 + CHUNK_INDEX);

		BEGIN_SOURCE_LOOP(ASSEMBLY, &LOOP_TOP, HEAD_DIMENSION, 1);
		BROADCAST_MEMORY(
			ASSEMBLY, 1, 0, MEMORY_INDEXED(RDX, R9, 4, PROBABILITY_OFFSET)
		);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			MULTIPLY_ADD_MEMORY(
				ASSEMBLY, 1, 8 + CHUNK_INDEX, 0,
				MEMORY_AT(R10, VALUE_OFFSET + 32 * CHUNK_INDEX)
			);

		END_SOURCE_LOOP(ASSEMBLY, LOOP_TOP);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(QUERY_BASE_REGISTER, MIXED_OFFSET + 32 * CHUNK_INDEX),
				8 + CHUNK_INDEX
			);

		int	GROUP_START;

		for (
			GROUP_START = 0;
			GROUP_START < MODEL_DIMENSION / 8;
			GROUP_START += 12
		)
		{
			int	GROUP_LENGTH;

			if (MODEL_DIMENSION / 8 - GROUP_START < 12)
				GROUP_LENGTH = MODEL_DIMENSION / 8 - GROUP_START;
			else
				GROUP_LENGTH = 12;

			int	VECTOR_INDEX;

			for (VECTOR_INDEX = 0; VECTOR_INDEX < GROUP_LENGTH; VECTOR_INDEX++)
				VECTOR_LOAD(
					ASSEMBLY, 1, VECTOR_INDEX,
					MEMORY_AT(
						RSI, RESIDUAL_OFFSET + 32 * (GROUP_START + VECTOR_INDEX)
					)
				);

			BEGIN_WEIGHT_ROW_LOOP(ASSEMBLY, &SECOND_LOOP_TOP);
			BROADCAST_MEMORY(
				ASSEMBLY, 1, 13,
				MEMORY_INDEXED(QUERY_BASE_REGISTER, RCX, 4, MIXED_OFFSET)
			);

			for (VECTOR_INDEX = 0; VECTOR_INDEX < GROUP_LENGTH; VECTOR_INDEX++)
				MULTIPLY_ADD_WEIGHTS(
					ASSEMBLY, VECTOR_INDEX, 13,
					WEIGHT_OPERAND(
						R8, -1,
						3 * MATRIX_BYTES + 32 * (GROUP_START + VECTOR_INDEX)
					)
				);

			END_WEIGHT_ROW_LOOP(
				ASSEMBLY, SECOND_LOOP_TOP, MODEL_DIMENSION, HEAD_DIMENSION
			);

			for (VECTOR_INDEX = 0; VECTOR_INDEX < GROUP_LENGTH; VECTOR_INDEX++)
				VECTOR_STORE(
					ASSEMBLY, 1,
					MEMORY_AT(
						RSI, RESIDUAL_OFFSET + 32 * (GROUP_START + VECTOR_INDEX)
					),
					VECTOR_INDEX
				);
		}

		END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);
		JUMP_TO_REGISTER(ASSEMBLY, RBP);
		return ;
	}

	{
		TIME_LOOP	TOKEN_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);

		ROW_POINTER(ASSEMBLY, RDI, HEAD_DIMENSION * 4);
		ADD_FROM_MEMORY(ASSEMBLY, RDI, STATE_FIELD(NEURON_ACTIVATION_OFFSET));
		ZERO_VECTOR(ASSEMBLY, 0);

		int	CHUNK_INDEX;

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
		{
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(RDI, KEY_GRADIENT_OFFSET + 32 * CHUNK_INDEX), 0
			);
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(RDI, VALUE_GRADIENT_OFFSET + 32 * CHUNK_INDEX), 0
			);
		}

		END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);
	}

	{
		TIME_LOOP	TOKEN_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);

		ROW_POINTER(ASSEMBLY, RSI, MODEL_DIMENSION * 4);
		ROW_POINTER(ASSEMBLY, RDI, HEAD_DIMENSION * 4);
		ADD_FROM_MEMORY(ASSEMBLY, RDI, STATE_FIELD(NEURON_ACTIVATION_OFFSET));
		BEGIN_WEIGHT_ROW_LOOP(ASSEMBLY, &LOOP_TOP);
		DOT_PRODUCT(
			ASSEMBLY, 0, 1, 2, RSI, RESIDUAL_GRADIENT_OFFSET, R8,
			3 * MATRIX_BYTES, MODEL_DIMENSION
		);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(RDI, RCX, 4, MIXED_GRADIENT_OFFSET), 0
		);
		END_WEIGHT_ROW_LOOP(
			ASSEMBLY, LOOP_TOP, MODEL_DIMENSION, HEAD_DIMENSION
		);
		END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);
		ACCUMULATE_OUTER_PRODUCT(
			ASSEMBLY, HEAD_DIMENSION, MODEL_DIMENSION, MIXED_OFFSET,
			HEAD_DIMENSION * 4, 1, RESIDUAL_GRADIENT_OFFSET,
			MODEL_DIMENSION * 4, GRADIENT_PLANE + 3 * MATRIX_BYTES,
			MODEL_DIMENSION * 4
		);
	}

	{
		MOVE_FROM_MEMORY(ASSEMBLY, R11, STATE_FIELD(NEURON_ACTIVATION_OFFSET));
		ADD_REGISTER(ASSEMBLY, R11, R14);

		TIME_LOOP	TOKEN_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);

		ROW_POINTER(ASSEMBLY, RDI, HEAD_DIMENSION * 4);
		ADD_FROM_MEMORY(ASSEMBLY, RDI, STATE_FIELD(NEURON_ACTIVATION_OFFSET));
		ROW_POINTER(ASSEMBLY, RDX, MAX_TOKENS * 4);
		ADD_FROM_MEMORY(ASSEMBLY, RDX, STATE_FIELD(NEURON_ACTIVATION_OFFSET));

		int	CHUNK_INDEX;

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			VECTOR_LOAD(
				ASSEMBLY, 1, 8 + CHUNK_INDEX,
				MEMORY_AT(RDI, MIXED_GRADIENT_OFFSET + 32 * CHUNK_INDEX)
			);

		BEGIN_SOURCE_LOOP(ASSEMBLY, &LOOP_TOP, HEAD_DIMENSION, 1);
		ZERO_VECTOR(ASSEMBLY, 0);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			MULTIPLY_ADD_MEMORY(
				ASSEMBLY, 1, 0, 8 + CHUNK_INDEX,
				MEMORY_AT(R10, VALUE_OFFSET + 32 * CHUNK_INDEX)
			);

		HORIZONTAL_SUM(ASSEMBLY, 0, 1);
		SCALAR_STORE(
			ASSEMBLY, MEMORY_INDEXED(R11, R9, 4, PROBABILITY_GRADIENT), 0
		);
		BROADCAST_MEMORY(
			ASSEMBLY, 1, 2, MEMORY_INDEXED(RDX, R9, 4, PROBABILITY_OFFSET)
		);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
		{
			VECTOR_LOAD(
				ASSEMBLY, 1, 3,
				MEMORY_AT(R10, VALUE_GRADIENT_OFFSET + 32 * CHUNK_INDEX)
			);
			MULTIPLY_ADD(ASSEMBLY, 1, 3, 2, 8 + CHUNK_INDEX);
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(R10, VALUE_GRADIENT_OFFSET + 32 * CHUNK_INDEX), 3
			);
		}

		END_SOURCE_LOOP(ASSEMBLY, LOOP_TOP);
		VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 7, 7, 7);
		MOVE_IMMEDIATE(ASSEMBLY, R9, 0);
		SECOND_LOOP_TOP = ASSEMBLER_NEW_LABEL(ASSEMBLY);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, SECOND_LOOP_TOP);
		SCALAR_LOAD(
			ASSEMBLY, 0, MEMORY_INDEXED(RDX, R9, 4, PROBABILITY_OFFSET)
		);
		SCALAR_MULTIPLY_ADD_MEMORY(
			ASSEMBLY, 7, 0, MEMORY_INDEXED(R11, R9, 4, PROBABILITY_GRADIENT)
		);
		ADD_IMMEDIATE(ASSEMBLY, R9, 1);
		COMPARE_REGISTER(ASSEMBLY, R9, RAX);
		BRANCH_TO_LABEL(ASSEMBLY, CC_LE, SECOND_LOOP_TOP);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
		{
			VECTOR_LOAD(
				ASSEMBLY, 1, 8 + CHUNK_INDEX,
				MEMORY_AT(RDI, QUERY_OFFSET + 32 * CHUNK_INDEX)
			);
			ZERO_VECTOR(ASSEMBLY, 12 + CHUNK_INDEX);
		}

		BEGIN_SOURCE_LOOP(ASSEMBLY, &LOOP_TOP, HEAD_DIMENSION, 1);
		SCALAR_LOAD(
			ASSEMBLY, 0, MEMORY_INDEXED(R11, R9, 4, PROBABILITY_GRADIENT)
		);
		SCALAR_MATH(ASSEMBLY, OPCODE_SUBTRACT, 0, 0, 7);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MULTIPLY, 0, 0,
			MEMORY_INDEXED(RDX, R9, 4, PROBABILITY_OFFSET)
		);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MULTIPLY, 0, 0, STATE_FIELD(ATTENTION_SCALE)
		);
		BROADCAST_REGISTER(ASSEMBLY, 1, 0, 0);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
		{
			MULTIPLY_ADD_MEMORY(
				ASSEMBLY, 1, 12 + CHUNK_INDEX, 0,
				MEMORY_AT(R10, KEY_OFFSET + 32 * CHUNK_INDEX)
			);
			VECTOR_LOAD(
				ASSEMBLY, 1, 1,
				MEMORY_AT(R10, KEY_GRADIENT_OFFSET + 32 * CHUNK_INDEX)
			);
			MULTIPLY_ADD(ASSEMBLY, 1, 1, 0, 8 + CHUNK_INDEX);
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(R10, KEY_GRADIENT_OFFSET + 32 * CHUNK_INDEX), 1
			);
		}

		END_SOURCE_LOOP(ASSEMBLY, LOOP_TOP);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(RDI, QUERY_GRADIENT_OFFSET + 32 * CHUNK_INDEX),
				12 + CHUNK_INDEX
			);

		END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);
	}

	if (USE_ROTARY)
	{
		TIME_LOOP	TOKEN_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);

		ROW_POINTER(ASSEMBLY, RDI, HEAD_DIMENSION * 4);
		ADD_FROM_MEMORY(ASSEMBLY, RDI, STATE_FIELD(NEURON_ACTIVATION_OFFSET));
		ROTATE_ROWS(
			ASSEMBLY, HEAD_DIMENSION, 1, RDI, QUERY_GRADIENT_OFFSET, RDI,
			KEY_GRADIENT_OFFSET
		);
		END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);
	}

	{
		TIME_LOOP	TOKEN_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);

		ROW_POINTER(ASSEMBLY, RSI, MODEL_DIMENSION * 4);
		ROW_POINTER(ASSEMBLY, RDI, HEAD_DIMENSION * 4);
		ADD_FROM_MEMORY(ASSEMBLY, RDI, STATE_FIELD(NEURON_ACTIVATION_OFFSET));

		int	GROUP_START;

		for (
			GROUP_START = 0;
			GROUP_START < MODEL_DIMENSION / 8;
			GROUP_START += 12
		)
		{
			int	GROUP_LENGTH;

			if (MODEL_DIMENSION / 8 - GROUP_START < 12)
				GROUP_LENGTH = MODEL_DIMENSION / 8 - GROUP_START;
			else
				GROUP_LENGTH = 12;

			int	VECTOR_INDEX;

			for (VECTOR_INDEX = 0; VECTOR_INDEX < GROUP_LENGTH; VECTOR_INDEX++)
				VECTOR_LOAD(
					ASSEMBLY, 1, VECTOR_INDEX,
					MEMORY_AT(
						RSI,
						INPUT_GRADIENT_OFFSET +
							32 * (GROUP_START + VECTOR_INDEX)
					)
				);

			BEGIN_WEIGHT_ROW_LOOP(ASSEMBLY, &SECOND_LOOP_TOP);
			BROADCAST_MEMORY(
				ASSEMBLY, 1, 12,
				MEMORY_INDEXED(RDI, RCX, 4, QUERY_GRADIENT_OFFSET)
			);
			BROADCAST_MEMORY(
				ASSEMBLY, 1, 13,
				MEMORY_INDEXED(RDI, RCX, 4, KEY_GRADIENT_OFFSET)
			);
			BROADCAST_MEMORY(
				ASSEMBLY, 1, 14,
				MEMORY_INDEXED(RDI, RCX, 4, VALUE_GRADIENT_OFFSET)
			);

			for (VECTOR_INDEX = 0; VECTOR_INDEX < GROUP_LENGTH; VECTOR_INDEX++)
			{
				MULTIPLY_ADD_MEMORY(
					ASSEMBLY, 1, VECTOR_INDEX, 12,
					MEMORY_AT(R8, 32 * (GROUP_START + VECTOR_INDEX))
				);
				MULTIPLY_ADD_MEMORY(
					ASSEMBLY, 1, VECTOR_INDEX, 13,
					MEMORY_AT(
						R8, MATRIX_BYTES + 32 * (GROUP_START + VECTOR_INDEX)
					)
				);
				MULTIPLY_ADD_MEMORY(
					ASSEMBLY, 1, VECTOR_INDEX, 14,
					MEMORY_AT(
						R8, 2 * MATRIX_BYTES + 32 * (GROUP_START + VECTOR_INDEX)
					)
				);
			}

			END_WEIGHT_ROW_LOOP(
				ASSEMBLY, SECOND_LOOP_TOP, MODEL_DIMENSION, HEAD_DIMENSION
			);

			for (VECTOR_INDEX = 0; VECTOR_INDEX < GROUP_LENGTH; VECTOR_INDEX++)
				VECTOR_STORE(
					ASSEMBLY, 1,
					MEMORY_AT(
						RSI,
						INPUT_GRADIENT_OFFSET +
							32 * (GROUP_START + VECTOR_INDEX)
					),
					VECTOR_INDEX
				);
		}

		END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);

		int	MATRIX_INDEX;

		for (MATRIX_INDEX = 0; MATRIX_INDEX < 3; MATRIX_INDEX++)
			ACCUMULATE_OUTER_PRODUCT(
				ASSEMBLY, HEAD_DIMENSION, MODEL_DIMENSION,
				MATRIX_INDEX == 0 ? QUERY_GRADIENT_OFFSET
					: MATRIX_INDEX == 1 ? KEY_GRADIENT_OFFSET
										: VALUE_GRADIENT_OFFSET,
				HEAD_DIMENSION * 4, 1, INPUT_OFFSET, MODEL_DIMENSION * 4,
				GRADIENT_PLANE + MATRIX_INDEX * MATRIX_BYTES,
				MODEL_DIMENSION * 4
			);
	}

	JUMP_TO_REGISTER(ASSEMBLY, RBP);
}

static void
	KERNEL_COPY_OFFSETS(
		WEB *NEURAL_WEB, NEURON *COPIER_NEURON, int32_t *OFFSETS
	)
{
	int32_t	MAX_TOKENS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;
	int32_t	HEAD_DIMENSION = NEURAL_WEB->CONFIGURATION.HEAD_DIMENSION;

	OFFSETS[0] = (int32_t)COPIER_NEURON->ACTIVATION_OFFSET;
	OFFSETS[1] = OFFSETS[0] + MAX_TOKENS * HEAD_DIMENSION * 4;
	OFFSETS[2] = OFFSETS[1] + MAX_TOKENS * HEAD_DIMENSION * 4;
	OFFSETS[3] = OFFSETS[2] + MAX_TOKENS * MAX_TOKENS * 4;

	int	SLOT_INDEX;

	for (SLOT_INDEX = 0; SLOT_INDEX < 6; SLOT_INDEX++)
		OFFSETS[4 + SLOT_INDEX] = (int32_t)ACTIVATION_PLANE + OFFSETS[0] +
			2 * MAX_TOKENS * HEAD_DIMENSION * 4 + SLOT_INDEX * MAX_TOKENS * 4;
}

typedef struct
{
	int32_t	GRADIENT_PLANE;
	int32_t	MATRIX_BYTES;
	int32_t	NORMALIZED_OFFSET;
} COPY_GRADIENT_LAYOUT;

static void
	COPY_GRADIENT_CHUNK(
		ASSEMBLER *ASSEMBLY, void *USER_DATA, int INDEX_REGISTER,
		int32_t CHUNK_OFFSET
	)
{
	COPY_GRADIENT_LAYOUT	*LAYOUT = USER_DATA;

	VECTOR_LOAD(
		ASSEMBLY, 1, 0,
		OPERAND_AT(
			RSI, INDEX_REGISTER, LAYOUT->NORMALIZED_OFFSET + CHUNK_OFFSET
		)
	);

	int	MATRIX_INDEX;

	for (MATRIX_INDEX = 0; MATRIX_INDEX < 2; MATRIX_INDEX++)
	{
		VECTOR_LOAD(
			ASSEMBLY, 1, 4 + MATRIX_INDEX,
			OPERAND_AT(
				R8, INDEX_REGISTER,
				LAYOUT->GRADIENT_PLANE + MATRIX_INDEX * LAYOUT->MATRIX_BYTES +
					CHUNK_OFFSET
			)
		);
		MULTIPLY_ADD(ASSEMBLY, 1, 4 + MATRIX_INDEX, 1 + MATRIX_INDEX, 0);
		VECTOR_STORE(
			ASSEMBLY, 1,
			OPERAND_AT(
				R8, INDEX_REGISTER,
				LAYOUT->GRADIENT_PLANE + MATRIX_INDEX * LAYOUT->MATRIX_BYTES +
					CHUNK_OFFSET
			),
			4 + MATRIX_INDEX
		);
	}
}

static void
	GENERATE_COPY(
		ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB, NEURON *COPIER_NEURON,
		int PASS_ROLE
	)
{
	int		MODEL_DIMENSION = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int		HEAD_DIMENSION = NEURAL_WEB->CONFIGURATION.HEAD_DIMENSION;
	int		CHUNK_COUNT = HEAD_DIMENSION / 8;
	int		MAX_TOKENS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;
	int		FINAL_AREA = 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT;
	int32_t	MATRIX_BYTES = HEAD_DIMENSION * MODEL_DIMENSION * 4;
	int32_t	GRADIENT_PLANE = (int32_t)PARAMETER_PLANE;
	int32_t	OFFSETS[10];

	KERNEL_COPY_OFFSETS(NEURAL_WEB, COPIER_NEURON, OFFSETS);

	int32_t	QUERY_OFFSET = OFFSETS[0];
	int32_t	KEY_OFFSET = OFFSETS[1];
	int32_t	ATTENTION_OFFSET = OFFSETS[2];
	int32_t	GATE_OFFSET = OFFSETS[3];
	int32_t	COPY_MASS_OFFSET = OFFSETS[4];
	int32_t	GATE_GRADIENT_OFFSET = OFFSETS[8];
	int32_t	KEY_FACTOR_OFFSET = OFFSETS[9];
	int32_t	INPUT_OFFSET =
		(int32_t)KERNEL_LAYER_NORMALIZED(NEURAL_WEB, FINAL_AREA);
	int32_t	INPUT_GRADIENT_OFFSET =
		(int32_t)LAYER_NORMALIZED_GRADIENT(NEURAL_WEB, FINAL_AREA);
	int32_t	TOKENS_OFFSET = (int32_t)NEURAL_WEB->TOKENS_OFFSET;
	int32_t	TARGETS_OFFSET = (int32_t)NEURAL_WEB->TARGETS_OFFSET;
	int32_t	QUERY_GRADIENT_OFFSET = (int32_t)ACTIVATION_PLANE + OFFSETS[0];
	int32_t	KEY_GRADIENT_OFFSET = (int32_t)ACTIVATION_PLANE + OFFSETS[1];
	int		LOOP_TOP;
	int		SECOND_LOOP_TOP;

	LOAD_ADDRESS(
		ASSEMBLY, R12,
		WEIGHT_OPERAND(R13, -1, (int32_t)COPIER_NEURON->PARAMETER_OFFSET)
	);

	if (PASS_ROLE == ROLE_FORWARD)
	{
		TIME_LOOP	TOKEN_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 1);

		ROW_POINTER(ASSEMBLY, RSI, MODEL_DIMENSION * 4);
		ROW_POINTER(ASSEMBLY, RDI, HEAD_DIMENSION * 4);
		BEGIN_WEIGHT_ROW_LOOP(ASSEMBLY, &LOOP_TOP);
		DOT_WITH_WEIGHTS(
			ASSEMBLY, 0, 1, 2, RSI, INPUT_OFFSET, R8, 0, MODEL_DIMENSION
		);
		SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(RDI, RCX, 4, QUERY_OFFSET), 0);
		DOT_WITH_WEIGHTS(
			ASSEMBLY, 0, 1, 2, RSI, INPUT_OFFSET, R8, MATRIX_BYTES,
			MODEL_DIMENSION
		);
		SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(RDI, RCX, 4, KEY_OFFSET), 0);
		END_WEIGHT_ROW_LOOP(
			ASSEMBLY, LOOP_TOP, MODEL_DIMENSION, HEAD_DIMENSION
		);

		if (HALF_WEIGHTS)
			MOVE_REGISTER(ASSEMBLY, RDX, R14);
		else
			ROW_POINTER(ASSEMBLY, RDX, MAX_TOKENS * 4);

		int	CHUNK_INDEX;

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			VECTOR_LOAD(
				ASSEMBLY, 1, 8 + CHUNK_INDEX,
				MEMORY_AT(RDI, QUERY_OFFSET + 32 * CHUNK_INDEX)
			);

		BEGIN_SOURCE_LOOP(ASSEMBLY, &LOOP_TOP, HEAD_DIMENSION, 0);
		ZERO_VECTOR(ASSEMBLY, 0);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			MULTIPLY_ADD_MEMORY(
				ASSEMBLY, 1, 0, 8 + CHUNK_INDEX,
				MEMORY_AT(R10, KEY_OFFSET + 32 * CHUNK_INDEX)
			);

		HORIZONTAL_SUM(ASSEMBLY, 0, 1);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MULTIPLY, 0, 0, STATE_FIELD(ATTENTION_SCALE)
		);
		SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(RDX, R9, 4, ATTENTION_OFFSET), 0);
		END_SOURCE_LOOP(ASSEMBLY, LOOP_TOP);
		LOAD_ADDRESS(ASSEMBLY, R10, MEMORY_AT(RDX, ATTENTION_OFFSET));
		LOAD_ADDRESS(ASSEMBLY, RCX, MEMORY_AT(RAX, 1));
		SOFTMAX_ROW(ASSEMBLY, R10, RCX);
		DOT_WITH_WEIGHTS(
			ASSEMBLY, 0, 1, 2, RSI, INPUT_OFFSET, R12, 2 * MATRIX_BYTES,
			MODEL_DIMENSION
		);
		ADD_SCALAR_WEIGHT(
			ASSEMBLY, 0, 0,
			WEIGHT_OPERAND(R12, -1, 2 * MATRIX_BYTES + MODEL_DIMENSION * 4)
		);
		VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 1, 1, 1);
		SCALAR_MATH(ASSEMBLY, OPCODE_SUBTRACT, 0, 1, 0);
		VECTOR_EXPONENTIAL(ASSEMBLY, 0, 0, 3, 4);
		SCALAR_MATH_MEMORY(ASSEMBLY, OPCODE_ADD, 0, 0, STATE_FIELD(ONE));
		SCALAR_LOAD(ASSEMBLY, 1, STATE_FIELD(ONE));
		SCALAR_MATH(ASSEMBLY, OPCODE_DIVIDE, 1, 1, 0);
		SCALAR_STORE(ASSEMBLY, MEMORY_INDEXED(R14, RAX, 4, GATE_OFFSET), 1);
		END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);
		return ;
	}

	{
		TIME_LOOP	TOKEN_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);

		ROW_POINTER(ASSEMBLY, RDI, HEAD_DIMENSION * 4);
		ZERO_VECTOR(ASSEMBLY, 0);

		int	CHUNK_INDEX;

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(RDI, KEY_GRADIENT_OFFSET + 32 * CHUNK_INDEX), 0
			);

		END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);
	}

	{
		TIME_LOOP	TOKEN_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);

		ROW_POINTER(ASSEMBLY, RDI, HEAD_DIMENSION * 4);
		ROW_POINTER(ASSEMBLY, RDX, MAX_TOKENS * 4);

		int	CHUNK_INDEX;

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
		{
			VECTOR_LOAD(
				ASSEMBLY, 1, 8 + CHUNK_INDEX,
				MEMORY_AT(RDI, QUERY_OFFSET + 32 * CHUNK_INDEX)
			);
			ZERO_VECTOR(ASSEMBLY, 12 + CHUNK_INDEX);
		}

		MOVE_SIGN_EXTENDED(
			ASSEMBLY, R11, MEMORY_INDEXED(R14, RAX, 4, TARGETS_OFFSET)
		);
		SCALAR_LOAD(
			ASSEMBLY, 6, MEMORY_INDEXED(R14, RAX, 4, KEY_FACTOR_OFFSET)
		);
		SCALAR_LOAD(ASSEMBLY, 7, MEMORY_INDEXED(R14, RAX, 4, COPY_MASS_OFFSET));
		SCALAR_MATH(ASSEMBLY, OPCODE_MULTIPLY, 7, 7, 6);
		BEGIN_SOURCE_LOOP(ASSEMBLY, &LOOP_TOP, HEAD_DIMENSION, 0);

		int	NO_MATCH_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

		VECTOR_MATH(ASSEMBLY, 1, OPCODE_EXCLUSIVE_OR, 0, 0, 0);
		MOVE_SIGN_EXTENDED(
			ASSEMBLY, RCX, MEMORY_INDEXED(R14, R9, 4, TOKENS_OFFSET)
		);
		COMPARE_REGISTER(ASSEMBLY, RCX, R11);
		BRANCH_TO_LABEL(ASSEMBLY, CC_NE, NO_MATCH_LABEL);
		VECTOR_MOVE(ASSEMBLY, 0, 0, 6);
		ASSEMBLER_BIND_LABEL(ASSEMBLY, NO_MATCH_LABEL);
		SCALAR_MATH(ASSEMBLY, OPCODE_SUBTRACT, 0, 0, 7);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MULTIPLY, 0, 0,
			MEMORY_INDEXED(RDX, R9, 4, ATTENTION_OFFSET)
		);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_MULTIPLY, 0, 0, STATE_FIELD(ATTENTION_SCALE)
		);
		BROADCAST_REGISTER(ASSEMBLY, 1, 0, 0);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
		{
			MULTIPLY_ADD_MEMORY(
				ASSEMBLY, 1, 12 + CHUNK_INDEX, 0,
				MEMORY_AT(R10, KEY_OFFSET + 32 * CHUNK_INDEX)
			);
			VECTOR_LOAD(
				ASSEMBLY, 1, 1,
				MEMORY_AT(R10, KEY_GRADIENT_OFFSET + 32 * CHUNK_INDEX)
			);
			MULTIPLY_ADD(ASSEMBLY, 1, 1, 0, 8 + CHUNK_INDEX);
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(R10, KEY_GRADIENT_OFFSET + 32 * CHUNK_INDEX), 1
			);
		}

		END_SOURCE_LOOP(ASSEMBLY, LOOP_TOP);

		for (CHUNK_INDEX = 0; CHUNK_INDEX < CHUNK_COUNT; CHUNK_INDEX++)
			VECTOR_STORE(
				ASSEMBLY, 1,
				MEMORY_AT(RDI, QUERY_GRADIENT_OFFSET + 32 * CHUNK_INDEX),
				12 + CHUNK_INDEX
			);

		END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);
	}

	{
		TIME_LOOP	TOKEN_LOOP = BEGIN_TIME_LOOP(ASSEMBLY, 0);

		ROW_POINTER(ASSEMBLY, RSI, MODEL_DIMENSION * 4);
		ROW_POINTER(ASSEMBLY, RDI, HEAD_DIMENSION * 4);
		BEGIN_WEIGHT_ROW_LOOP(ASSEMBLY, &LOOP_TOP);
		BROADCAST_MEMORY(
			ASSEMBLY, 1, 1, MEMORY_INDEXED(RDI, RCX, 4, QUERY_GRADIENT_OFFSET)
		);
		BROADCAST_MEMORY(
			ASSEMBLY, 1, 2, MEMORY_INDEXED(RDI, RCX, 4, KEY_GRADIENT_OFFSET)
		);

		COPY_GRADIENT_LAYOUT	LAYOUT = {
			GRADIENT_PLANE, MATRIX_BYTES, INPUT_OFFSET
		};

		FOR_EACH_CHUNK(ASSEMBLY, MODEL_DIMENSION, COPY_GRADIENT_CHUNK, &LAYOUT);
		END_WEIGHT_ROW_LOOP(
			ASSEMBLY, LOOP_TOP, MODEL_DIMENSION, HEAD_DIMENSION
		);
		BROADCAST_MEMORY(
			ASSEMBLY, 1, 3, MEMORY_INDEXED(R14, RAX, 4, GATE_GRADIENT_OFFSET)
		);
		SCALED_ADD(
			ASSEMBLY, 3, 4, R12, GRADIENT_PLANE + 2 * MATRIX_BYTES, RSI,
			INPUT_OFFSET, MODEL_DIMENSION
		);
		SCALAR_LOAD(
			ASSEMBLY, 5, MEMORY_INDEXED(R14, RAX, 4, GATE_GRADIENT_OFFSET)
		);
		SCALAR_MATH_MEMORY(
			ASSEMBLY, OPCODE_ADD, 5, 5,
			MEMORY_AT(
				R12, GRADIENT_PLANE + 2 * MATRIX_BYTES + MODEL_DIMENSION * 4
			)
		);
		SCALAR_STORE(
			ASSEMBLY,
			MEMORY_AT(
				R12, GRADIENT_PLANE + 2 * MATRIX_BYTES + MODEL_DIMENSION * 4
			),
			5
		);
		BROADCAST_MEMORY(
			ASSEMBLY, 1, 14, MEMORY_INDEXED(R14, RAX, 4, GATE_GRADIENT_OFFSET)
		);

		int	GROUP_START;

		for (
			GROUP_START = 0;
			GROUP_START < MODEL_DIMENSION / 8;
			GROUP_START += 12
		)
		{
			int	GROUP_LENGTH;

			if (MODEL_DIMENSION / 8 - GROUP_START < 12)
				GROUP_LENGTH = MODEL_DIMENSION / 8 - GROUP_START;
			else
				GROUP_LENGTH = 12;

			int	VECTOR_INDEX;

			for (VECTOR_INDEX = 0; VECTOR_INDEX < GROUP_LENGTH; VECTOR_INDEX++)
				VECTOR_LOAD(
					ASSEMBLY, 1, VECTOR_INDEX,
					MEMORY_AT(
						RSI,
						INPUT_GRADIENT_OFFSET +
							32 * (GROUP_START + VECTOR_INDEX)
					)
				);

			BEGIN_WEIGHT_ROW_LOOP(ASSEMBLY, &SECOND_LOOP_TOP);
			BROADCAST_MEMORY(
				ASSEMBLY, 1, 12,
				MEMORY_INDEXED(RDI, RCX, 4, QUERY_GRADIENT_OFFSET)
			);
			BROADCAST_MEMORY(
				ASSEMBLY, 1, 13,
				MEMORY_INDEXED(RDI, RCX, 4, KEY_GRADIENT_OFFSET)
			);

			for (VECTOR_INDEX = 0; VECTOR_INDEX < GROUP_LENGTH; VECTOR_INDEX++)
			{
				MULTIPLY_ADD_MEMORY(
					ASSEMBLY, 1, VECTOR_INDEX, 12,
					MEMORY_AT(R8, 32 * (GROUP_START + VECTOR_INDEX))
				);
				MULTIPLY_ADD_MEMORY(
					ASSEMBLY, 1, VECTOR_INDEX, 13,
					MEMORY_AT(
						R8, MATRIX_BYTES + 32 * (GROUP_START + VECTOR_INDEX)
					)
				);
			}

			END_WEIGHT_ROW_LOOP(
				ASSEMBLY, SECOND_LOOP_TOP, MODEL_DIMENSION, HEAD_DIMENSION
			);

			for (VECTOR_INDEX = 0; VECTOR_INDEX < GROUP_LENGTH; VECTOR_INDEX++)
				MULTIPLY_ADD_MEMORY(
					ASSEMBLY, 1, VECTOR_INDEX, 14,
					MEMORY_AT(
						R12,
						2 * MATRIX_BYTES + 32 * (GROUP_START + VECTOR_INDEX)
					)
				);

			for (VECTOR_INDEX = 0; VECTOR_INDEX < GROUP_LENGTH; VECTOR_INDEX++)
				VECTOR_STORE(
					ASSEMBLY, 1,
					MEMORY_AT(
						RSI,
						INPUT_GRADIENT_OFFSET +
							32 * (GROUP_START + VECTOR_INDEX)
					),
					VECTOR_INDEX
				);
		}

		END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);
	}
}

static void
	GENERATE_TREE(
		ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB, NEURON *TREE_NEURON, int PASS_ROLE
	)
{
	int		MODEL_DIMENSION = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int		AREA_INDEX = TREE_NEURON->AREA_INDEX;
	int		TREE_DEPTH = TREE_NEURON->KIND_DETAIL - ORGAN_TREE_BASE;
	int		LEVEL_COUNT = TREE_DEPTH + 1;
	int32_t	NODE_STRIDE;

	if (HALF_WEIGHTS)
		NODE_STRIDE = (2 * MODEL_DIMENSION + 8) * 2;
	else
		NODE_STRIDE = (2 * MODEL_DIMENSION + 8) * 4;

	int32_t	INPUT_OFFSET =
		(int32_t)KERNEL_LAYER_NORMALIZED(NEURAL_WEB, AREA_INDEX);
	int32_t	RESIDUAL_OFFSET =
		(int32_t)KERNEL_LAYER_RESIDUAL(NEURAL_WEB, AREA_INDEX + 1);
	int32_t	GRADIENT_PLANE = (int32_t)PARAMETER_PLANE;
	int32_t	SCORE_AREA_OFFSET =
		NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH * LEVEL_COUNT * 4;

	MOVE_REGISTER(ASSEMBLY, RDI, R12);
	MOVE_FROM_MEMORY(ASSEMBLY, R10, STATE_FIELD(NEURON_ACTIVATION_OFFSET));
	ADD_REGISTER(ASSEMBLY, R10, R14);

	TIME_LOOP	TOKEN_LOOP =
		BEGIN_TIME_LOOP(ASSEMBLY, PASS_ROLE == ROLE_FORWARD);

	ROW_POINTER(ASSEMBLY, RSI, MODEL_DIMENSION * 4);
	MULTIPLY_IMMEDIATE(ASSEMBLY, R9, RAX, LEVEL_COUNT * 4);
	ADD_REGISTER(ASSEMBLY, R9, R10);

	if (PASS_ROLE == ROLE_FORWARD)
	{
		MOVE_IMMEDIATE(ASSEMBLY, RCX, 0);

		int	LEVEL;

		for (LEVEL = 0; LEVEL < LEVEL_COUNT; LEVEL++)
		{
			MULTIPLY_IMMEDIATE(ASSEMBLY, RDX, RCX, NODE_STRIDE);
			ADD_REGISTER(ASSEMBLY, RDX, RDI);
			DOT_WITH_WEIGHTS(
				ASSEMBLY, 0, 1, 2, RSI, INPUT_OFFSET, RDX, 0, MODEL_DIMENSION
			);
			ADD_SCALAR_WEIGHT(
				ASSEMBLY, 0, 0, WEIGHT_OPERAND(RDX, -1, 2 * MODEL_DIMENSION * 4)
			);

			if (!HALF_WEIGHTS)
			{
				MOVE32_TO_MEMORY(ASSEMBLY, MEMORY_AT(R9, LEVEL * 4), RCX);
				SCALAR_STORE(
					ASSEMBLY, MEMORY_AT(R9, SCORE_AREA_OFFSET + LEVEL * 4), 0
				);
			}

			SCALAR_MATH_MEMORY(
				ASSEMBLY, OPCODE_MULTIPLY, 4, 0, STATE_FIELD(LEAK_SLOPE)
			);
			SCALAR_MATH(ASSEMBLY, OPCODE_MAXIMUM, 4, 0, 4);
			BROADCAST_REGISTER(ASSEMBLY, 1, 4, 4);
			SCALED_ADD_WEIGHTS(
				ASSEMBLY, 4, 3, RSI, RESIDUAL_OFFSET, RDX, MODEL_DIMENSION * 4,
				MODEL_DIMENSION
			);

			if (LEVEL < LEVEL_COUNT - 1)
			{
				int	LEFT_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

				ADD_REGISTER(ASSEMBLY, RCX, RCX);
				ADD_IMMEDIATE(ASSEMBLY, RCX, 1);
				ZERO_VECTOR(ASSEMBLY, 1);
				SCALAR_COMPARE(ASSEMBLY, 0, 1);
				BRANCH_TO_LABEL(ASSEMBLY, CC_BE, LEFT_LABEL);
				ADD_IMMEDIATE(ASSEMBLY, RCX, 1);
				ASSEMBLER_BIND_LABEL(ASSEMBLY, LEFT_LABEL);
			}
		}
	}
	else
	{
		int32_t	INPUT_GRADIENT_OFFSET =
			(int32_t)LAYER_NORMALIZED_GRADIENT(NEURAL_WEB, AREA_INDEX);
		int32_t	RESIDUAL_GRADIENT_OFFSET =
			(int32_t)LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, AREA_INDEX + 1);
		int		LEVEL;

		for (LEVEL = 0; LEVEL < LEVEL_COUNT; LEVEL++)
		{
			int	NEGATIVE_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

			MOVE_SIGN_EXTENDED(ASSEMBLY, RCX, MEMORY_AT(R9, LEVEL * 4));
			MULTIPLY_IMMEDIATE(ASSEMBLY, RDX, RCX, NODE_STRIDE);
			ADD_REGISTER(ASSEMBLY, RDX, RDI);
			SCALAR_LOAD(
				ASSEMBLY, 6, MEMORY_AT(R9, SCORE_AREA_OFFSET + LEVEL * 4)
			);
			DOT_PRODUCT(
				ASSEMBLY, 1, 2, 3, RSI, RESIDUAL_GRADIENT_OFFSET, RDX,
				MODEL_DIMENSION * 4, MODEL_DIMENSION
			);
			SCALAR_MATH_MEMORY(
				ASSEMBLY, OPCODE_MULTIPLY, 7, 6, STATE_FIELD(LEAK_SLOPE)
			);
			SCALAR_MATH(ASSEMBLY, OPCODE_MAXIMUM, 7, 6, 7);
			SCALAR_MATH_MEMORY(
				ASSEMBLY, OPCODE_MULTIPLY, 8, 1, STATE_FIELD(LEAK_SLOPE)
			);
			ZERO_VECTOR(ASSEMBLY, 2);
			SCALAR_COMPARE(ASSEMBLY, 6, 2);
			BRANCH_TO_LABEL(ASSEMBLY, CC_BE, NEGATIVE_LABEL);
			VECTOR_MATH(ASSEMBLY, 0, OPCODE_ADD, 8, 1, 2);
			ASSEMBLER_BIND_LABEL(ASSEMBLY, NEGATIVE_LABEL);
			SCALAR_MATH_MEMORY(
				ASSEMBLY, OPCODE_ADD, 2, 8,
				MEMORY_AT(RDX, GRADIENT_PLANE + 2 * MODEL_DIMENSION * 4)
			);
			SCALAR_STORE(
				ASSEMBLY,
				MEMORY_AT(RDX, GRADIENT_PLANE + 2 * MODEL_DIMENSION * 4), 2
			);
			BROADCAST_REGISTER(ASSEMBLY, 1, 7, 7);
			BROADCAST_REGISTER(ASSEMBLY, 1, 8, 8);
			SCALED_ADD(
				ASSEMBLY, 7, 4, RDX, GRADIENT_PLANE + MODEL_DIMENSION * 4, RSI,
				RESIDUAL_GRADIENT_OFFSET, MODEL_DIMENSION
			);
			SCALED_ADD(
				ASSEMBLY, 8, 4, RDX, GRADIENT_PLANE, RSI, INPUT_OFFSET,
				MODEL_DIMENSION
			);
			SCALED_ADD(
				ASSEMBLY, 8, 4, RSI, INPUT_GRADIENT_OFFSET, RDX, 0,
				MODEL_DIMENSION
			);
		}
	}

	END_TIME_LOOP(ASSEMBLY, TOKEN_LOOP);
	JUMP_TO_REGISTER(ASSEMBLY, RBP);
}

#include "RECIPE_KERNEL.inc"

static int
	GENERATE_STUB(
		ASSEMBLER *ASSEMBLY, WEB *NEURAL_WEB, NEURON *STUB_NEURON, int PASS_ROLE
	)
{
	int32_t	ORGAN_INDEX = WEB_ORGAN(
		NEURAL_WEB, ORGAN_KEY(STUB_NEURON->KIND, STUB_NEURON->KIND_DETAIL),
		STUB_NEURON->AREA_INDEX
	);
	int64_t	ACTIVATION_ADDRESS;

	if (STUB_NEURON->KIND == KIND_WORD)
		ACTIVATION_ADDRESS = LOGITS_OFFSET +
			(int64_t)STUB_NEURON->KIND_DETAIL *
				NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH * 4;
	else
		ACTIVATION_ADDRESS = STUB_NEURON->ACTIVATION_OFFSET;

	LOAD_ADDRESS(
		ASSEMBLY, R12,
		WEIGHT_OPERAND(R13, -1, (int32_t)STUB_NEURON->PARAMETER_OFFSET)
	);
	STORE_IMMEDIATE64(
		ASSEMBLY, STATE_FIELD(NEURON_ACTIVATION_OFFSET),
		(int32_t)ACTIVATION_ADDRESS
	);

	if (STUB_NEURON->KIND == KIND_WORD && PASS_ROLE == ROLE_FORWARD)
		STORE_IMMEDIATE64(
			ASSEMBLY, STATE_FIELD(INFERENCE_LOGIT_OFFSET),
			(int32_t)(LAST_LOGITS_OFFSET + (int64_t)STUB_NEURON->KIND_DETAIL * 4
			)
		);

	LOAD_RELATIVE_ADDRESS(ASSEMBLY, RBP);

	int	PATCH_POSITION = ASSEMBLY->BYTE_COUNT - 4;

	JUMP_TO_PIECE(ASSEMBLY, ORGAN_INDEX * 4 + PASS_ROLE);

	return (PATCH_POSITION);
}

int
	GENERATE_PIECE(
		WEB *NEURAL_WEB, ASSEMBLER *ASSEMBLY, NEURON *CURRENT_NEURON,
		int PASS_ROLE
	)
{
	HALF_WEIGHTS = NEURAL_WEB->HALF_PRECISION;

	switch (CURRENT_NEURON->KIND)
	{
		case KIND_ENTRY:
		{
			GENERATE_ENTRY(ASSEMBLY, NEURAL_WEB);
			return (-1);
		}
		case KIND_EXIT:
		{
			GENERATE_EXIT(ASSEMBLY);
			return (-2);
		}
		case KIND_UPDATE_START:
		{
			return (-1);
		}
		case KIND_INFERENCE_GATE:
		{
			MOVE_FROM_MEMORY(ASSEMBLY, RAX, STATE_FIELD(MODE));
			COMPARE_IMMEDIATE(ASSEMBLY, RAX, MODE_INFER);
			BRANCH_TO_PIECE(ASSEMBLY, CC_E, NEURAL_WEB->EXIT_ID * 4);
			return (-1);
		}
		case KIND_EVALUATION_GATE:
		{
			MOVE_FROM_MEMORY(ASSEMBLY, RAX, STATE_FIELD(MODE));
			COMPARE_IMMEDIATE(ASSEMBLY, RAX, MODE_EVALUATE);
			BRANCH_TO_PIECE(ASSEMBLY, CC_E, NEURAL_WEB->EXIT_ID * 4);
			return (-1);
		}
		case KIND_GROW:
		{
			GENERATE_GROW(ASSEMBLY);
			return (-1);
		}
		case KIND_ADAM:
		{
			GENERATE_ADAM(ASSEMBLY);
			return (-1);
		}
		case KIND_LOSS:
		{
			GENERATE_LOSS(ASSEMBLY, NEURAL_WEB);
			return (-1);
		}
		case KIND_EMBEDDING:
		{
			GENERATE_EMBED(ASSEMBLY, NEURAL_WEB, CURRENT_NEURON, PASS_ROLE);
			return (-1);
		}
		case KIND_NORMALIZATION:
		{
			GENERATE_NORM(ASSEMBLY, NEURAL_WEB, CURRENT_NEURON, PASS_ROLE);
			return (-1);
		}
		case KIND_COPY:
		{
			GENERATE_COPY(ASSEMBLY, NEURAL_WEB, CURRENT_NEURON, PASS_ROLE);
			return (-1);
		}
		case KIND_FEED_FORWARD:
		case KIND_ATTENTION_HEAD:
		case KIND_WORD:
		case KIND_RECIPE:
		case KIND_TREE:
		{
			return (
				GENERATE_STUB(ASSEMBLY, NEURAL_WEB, CURRENT_NEURON, PASS_ROLE)
			);
		}
		case KIND_ORGAN:
		{
			if (CURRENT_NEURON->KIND_DETAIL >= ORGAN_RECIPE_BASE)
				GENERATE_RECIPE(
					ASSEMBLY, NEURAL_WEB, CURRENT_NEURON, PASS_ROLE
				);
			else if (
				CURRENT_NEURON->KIND_DETAIL >= ORGAN_TREE_BASE &&
				CURRENT_NEURON->KIND_DETAIL < ORGAN_ROTARY_HEAD
			)
				GENERATE_TREE(ASSEMBLY, NEURAL_WEB, CURRENT_NEURON, PASS_ROLE);
			else if (CURRENT_NEURON->KIND_DETAIL == KIND_FEED_FORWARD)
				GENERATE_FEED_FORWARD(
					ASSEMBLY, NEURAL_WEB, CURRENT_NEURON, PASS_ROLE
				);
			else if (
				CURRENT_NEURON->KIND_DETAIL == KIND_ATTENTION_HEAD ||
				CURRENT_NEURON->KIND_DETAIL == ORGAN_ROTARY_HEAD
			)
			{
				USE_ROTARY = CURRENT_NEURON->KIND_DETAIL == ORGAN_ROTARY_HEAD;
				GENERATE_HEAD(ASSEMBLY, NEURAL_WEB, CURRENT_NEURON, PASS_ROLE);
				USE_ROTARY = 0;
			}
			else
				GENERATE_WORD(ASSEMBLY, NEURAL_WEB, CURRENT_NEURON, PASS_ROLE);

			return (-2);
		}
		default:
		{
			return (-1);
		}
	}
}
