#ifndef KNOWLEDGE_H
#define KNOWLEDGE_H

enum
{
	RELATION_IS_A,
	RELATION_IS,
	RELATION_HAS,
	RELATION_CAN,
	RELATION_DO
};

enum
{
	FACT_SOURCE_TOLD,
	FACT_SOURCE_READ,
	FACT_SOURCE_DERIVED,
	FACT_SOURCE_GUESS
};

enum
{
	HEAR_NONE,
	HEAR_SAVED,
	HEAR_KNEW,
	HEAR_CONFLICT,
	HEAR_ANSWER,
	HEAR_UNKNOWN
};

enum
{
	SYMBOL_THING = 1,
	SYMBOL_PROPERTY = 2,
	SYMBOL_VERB = 4
};

typedef struct
{
	int	SUBJECT;
	int	RELATION;
	int	VERB;
	int	OBJECT_NAME;
	int	COUNT;
	int	IS_NEGATED;
	int	SOURCE;
	int	TURN;
	int	IS_ALIVE;
} KNOWLEDGE_FACT;

typedef struct
{
	char			(*SYMBOLS)[40];
	int				*ASKED_COUNTS;
	unsigned char	*SYMBOL_KINDS;
	int				SYMBOL_COUNT;
	int				SYMBOL_CAPACITY;
	KNOWLEDGE_FACT	*FACTS;
	int				FACT_COUNT;
	int				FACT_CAPACITY;
	int				OPEN_QUESTIONS[64];
	int				OPEN_QUESTION_COUNT;
	int				TURN;
	int				IS_DIRTY;
	int				ABOUT_SYMBOL;
	char			LAST_REPLY[8192];
} KNOWLEDGE;

KNOWLEDGE	*KNOWLEDGE_NEW(void);
void		KNOWLEDGE_FREE(KNOWLEDGE *KNOWLEDGE_BASE);
void		KNOWLEDGE_RESET(KNOWLEDGE *KNOWLEDGE_BASE);
int			KNOWLEDGE_LOAD(KNOWLEDGE *KNOWLEDGE_BASE, const char *PATH);
int			KNOWLEDGE_SAVE(KNOWLEDGE *KNOWLEDGE_BASE, const char *PATH);
int			KNOWLEDGE_HEAR(
	KNOWLEDGE *KNOWLEDGE_BASE, const char *HEARD_TEXT, char *OUTPUT,
	int OUTPUT_SIZE
);
void		KNOWLEDGE_LIST(
	KNOWLEDGE *KNOWLEDGE_BASE, char *OUTPUT, int OUTPUT_SIZE
);
int			KNOWLEDGE_SCRIPT(
	const char *SCRIPT_TEXT, int SHOW_OUTPUT, int *CHECK_COUNT_OUT
);
int			KNOWLEDGE_SCRIPT_FILE(const char *PATH, int SHOW_OUTPUT);

#endif
