#ifndef LANGUAGE_H
#define LANGUAGE_H
#include <stdint.h>

enum
{
	TOKEN_TEXT = 0,
	TOKEN_USER_TURN,
	TOKEN_CODE_TURN,
	TOKEN_MEMORY,
	TOKEN_YOU,
	TOKEN_FIRST_CHARACTER
};

#define CHARACTER_COUNT 37
#define TOKEN_FIRST_WORD (TOKEN_FIRST_CHARACTER + 2 * CHARACTER_COUNT)

typedef struct
{
	char		**STRINGS;
	uint32_t	*USE_COUNTS;
	uint32_t	*CAPITAL_COUNTS;
	int32_t		COUNT;
	int32_t		CAPACITY;
	int32_t		*HASH_TABLE;
	int32_t		HASH_CAPACITY;
	int32_t		*LEXEME_TO_TOKEN;
	int32_t		*TOKEN_TO_LEXEME;
	int32_t		TOKEN_COUNT;
	int32_t		TOKEN_CAPACITY;
	int			IS_DIRTY;
	char		**BLOCKS;
	int			BLOCK_COUNT;
	int32_t		BLOCK_USED;
} LANGUAGE;

typedef struct
{
	char	WORD_TEXT[64];
	int		IS_CAPITALIZED;
} SPLIT_WORD;

LANGUAGE	*LANGUAGE_NEW(void);
void		LANGUAGE_FREE(LANGUAGE *LEXICON);
int32_t		LANGUAGE_FIND(LANGUAGE *LEXICON, const char *STRING);
int32_t		LANGUAGE_ADD(
	LANGUAGE *LEXICON, const char *STRING, int IS_CAPITALIZED
);
int			LANGUAGE_SAVE(LANGUAGE *LEXICON, const char *PATH);
LANGUAGE	*LANGUAGE_LOAD(const char *PATH);
int			LANGUAGE_SAVE_VOCABULARY(LANGUAGE *LEXICON, const char *PATH);
int			LANGUAGE_LOAD_VOCABULARY(LANGUAGE *LEXICON, const char *PATH);
int32_t		LANGUAGE_VOCABULARY_ADD(LANGUAGE *LEXICON, int32_t LEXEME);
int			SPLIT_WORDS(
	const char *INPUT_TEXT, SPLIT_WORD *WORDS, int MAXIMUM_WORDS
);
int			ENCODE_WORDS(
	LANGUAGE *LEXICON, SPLIT_WORD *WORDS, int WORD_COUNT, int32_t *OUTPUT,
	int OUTPUT_SIZE, int LEARN_NEW
);
int			ENCODE_TEXT(
	LANGUAGE *LEXICON, const char *INPUT_TEXT, int32_t *OUTPUT, int OUTPUT_SIZE,
	int LEARN_NEW
);
int			DECODE_TOKENS(
	LANGUAGE *LEXICON, const int32_t *TOKENS, int TOKEN_COUNT, char *OUTPUT,
	int OUTPUT_SIZE, const char **KNOWN_NAMES, int NAME_COUNT
);
const char	*TOKEN_NAME(LANGUAGE *LEXICON, int32_t TOKEN, char *BUFFER);
int			IS_PROPER_NOUN(LANGUAGE *LEXICON, int32_t LEXEME);
int32_t		LANGUAGE_TOKEN(LANGUAGE *LEXICON, const char *STRING);
int			IS_SPECIAL_WORD(LANGUAGE *LEXICON, int32_t LEXEME);
#define SPECIAL_DO "<do>"
#define SPECIAL_RESULT "<res>"
#define SPECIAL_MORE "<more>"

#endif
