#include "CODE.h"
#include <math.h>
#include <string.h>

int64_t
	WEB_PARAMETER_COUNT(WEB *NEURAL_WEB)
{
	int64_t	PARAMETER_TOTAL = 0;
	int32_t	NEURON_INDEX;

	for (
		NEURON_INDEX = 0;
		NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
		NEURON_INDEX++
	)
		if (NEURAL_WEB->NEURONS[NEURON_INDEX].ALIVE)
			PARAMETER_TOTAL +=
				NEURAL_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT;

	return (PARAMETER_TOTAL);
}

int
	WEB_COUNT_NEURONS(WEB *NEURAL_WEB, int NEURON_KIND, int AREA_INDEX)
{
	int		MATCH_COUNT = 0;
	int32_t	NEURON_INDEX;

	for (
		NEURON_INDEX = 0;
		NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
		NEURON_INDEX++
	)
		if (
			NEURAL_WEB->NEURONS[NEURON_INDEX].ALIVE &&
			(
				NEURON_KIND < 0 ||
				NEURAL_WEB->NEURONS[NEURON_INDEX].KIND == NEURON_KIND
			) &&
			(
				AREA_INDEX < 0 ||
				NEURAL_WEB->NEURONS[NEURON_INDEX].AREA_INDEX == AREA_INDEX
			)
		)
			MATCH_COUNT++;

	return (MATCH_COUNT);
}

double
	LEARN_WINDOW(
		WEB *NEURAL_WEB, const int32_t *SEQUENCE, int SEQUENCE_LENGTH,
		const float *TOKEN_WEIGHTS, double *WEIGHT_SUM
	)
{
	if (SEQUENCE_LENGTH < 2)
		return (0);

	if (SEQUENCE_LENGTH > NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH + 1)
		SEQUENCE_LENGTH = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH + 1;

	int	STEP_COUNT = SEQUENCE_LENGTH - 1;
	int	MAXIMUM_STEPS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;

	if (!NEURAL_WEB->TRAINING_ENABLED)
		WEB_SET_TRAINING(NEURAL_WEB, 1);

	int32_t	*INPUT_TOKENS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);
	int32_t	*TARGETS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TARGETS_OFFSET);
	float	*POSITION_WEIGHTS =
		(float *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
	int		POSITION;

	for (POSITION = 0; POSITION < STEP_COUNT; POSITION++)
	{
		INPUT_TOKENS[POSITION] = SEQUENCE[POSITION];
		TARGETS[POSITION] = SEQUENCE[POSITION + 1];

		if (TOKEN_WEIGHTS)
			POSITION_WEIGHTS[POSITION] = TOKEN_WEIGHTS[POSITION + 1];
		else
			POSITION_WEIGHTS[POSITION] = (float)1.0;

		if (POSITION_WEIGHTS[POSITION] <= 0)
			TARGETS[POSITION] = -1;
	}

	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = STEP_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_TRAIN);

	double	TOTAL_LOSS = 0;
	double	WEIGHT_TOTAL = 0;

	(void)MAXIMUM_STEPS;

	for (POSITION = 0; POSITION < STEP_COUNT; POSITION++)
	{
		if (TARGETS[POSITION] < 0)
			continue ;

		TOTAL_LOSS += POSITION_WEIGHTS[POSITION] *
			WEB_LOSS_AT(NEURAL_WEB, NEURAL_WEB->ACTIVATIONS, POSITION);
		WEIGHT_TOTAL += POSITION_WEIGHTS[POSITION];
	}

	if (WEIGHT_SUM)
		*WEIGHT_SUM += WEIGHT_TOTAL;

	return (TOTAL_LOSS);
}

static void
	UPDATE_AREA_STATISTICS(WEB *NEURAL_WEB)
{
	double	GRADIENT_SQUARES = 0;
	int32_t	NEURON_INDEX;

	for (
		NEURON_INDEX = 0;
		NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
		NEURON_INDEX++
	)
	{
		NEURON	*NEURON_ENTRY = &NEURAL_WEB->NEURONS[NEURON_INDEX];

		if (!NEURON_ENTRY->ALIVE || !NEURON_ENTRY->PARAMETER_COUNT)
			continue ;

		float	*GRADIENT = NEURON_GRADIENTS(NEURAL_WEB, NEURON_ENTRY->ID);
		int64_t	PARAMETER_INDEX;

		for (
			PARAMETER_INDEX = 0;
			PARAMETER_INDEX < NEURON_ENTRY->PARAMETER_COUNT;
			PARAMETER_INDEX++
		)
			GRADIENT_SQUARES +=
				(double)GRADIENT[PARAMETER_INDEX] * GRADIENT[PARAMETER_INDEX];
	}

	NEURAL_WEB->GRADIENT_NORM = (float)sqrt(GRADIENT_SQUARES);

	if (NEURAL_WEB->GRADIENT_NORM > (float)1.0)
		NEURAL_WEB->GRADIENT_MULTIPLIER =
			(float)1.0 / NEURAL_WEB->GRADIENT_NORM;
	else
		NEURAL_WEB->GRADIENT_MULTIPLIER = (float)1.0;

	if (
		!NEURAL_WEB->GROWTH_STATE.ENABLED ||
		NEURAL_WEB->GROWTH_STATE.STATISTICS_INTERVAL <= 0 ||
		NEURAL_WEB->STEP % NEURAL_WEB->GROWTH_STATE.STATISTICS_INTERVAL
	)
		return ;

	int	AREA_INDEX;

	for (
		AREA_INDEX = 0;
		AREA_INDEX < 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT;
		AREA_INDEX++
	)
	{
		AREA	*AREA_ENTRY = &NEURAL_WEB->AREAS[AREA_INDEX];
		double	AREA_SQUARES = 0;
		int64_t	PARAMETER_COUNT = 0;
		int		LIST_INDEX;

		for (
			LIST_INDEX = 0;
			LIST_INDEX < AREA_ENTRY->MEMBER_COUNT;
			LIST_INDEX++
		)
		{
			NEURON	*NEURON_ENTRY =
				&NEURAL_WEB->NEURONS[AREA_ENTRY->MEMBERS[LIST_INDEX]];

			if (!NEURON_ENTRY->ALIVE)
				continue ;

			float	*GRADIENT = NEURON_GRADIENTS(NEURAL_WEB, NEURON_ENTRY->ID);
			int64_t	PARAMETER_INDEX;

			for (
				PARAMETER_INDEX = 0;
				PARAMETER_INDEX < NEURON_ENTRY->PARAMETER_COUNT;
				PARAMETER_INDEX++
			)
				AREA_SQUARES += (double)GRADIENT[PARAMETER_INDEX] *
					GRADIENT[PARAMETER_INDEX];

			PARAMETER_COUNT += NEURON_ENTRY->PARAMETER_COUNT;
		}

		float	MEAN_SQUARE;

		if (PARAMETER_COUNT)
			MEAN_SQUARE = (float)(AREA_SQUARES / PARAMETER_COUNT);
		else
			MEAN_SQUARE = 0;

		if (AREA_ENTRY->ERROR_LEVEL == 0)
			AREA_ENTRY->ERROR_LEVEL = MEAN_SQUARE;
		else
			AREA_ENTRY->ERROR_LEVEL =
				(float)0.9 * AREA_ENTRY->ERROR_LEVEL + (float)0.1 * MEAN_SQUARE;
	}
}

static int
	PICK_GROWTH_AREA(WEB *NEURAL_WEB, int NEURON_KIND)
{
	int		BEST_AREA = -1;
	float	BEST_ERROR = -1;
	int		AREA_INDEX;

	for (
		AREA_INDEX = 0;
		AREA_INDEX < 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT;
		AREA_INDEX++
	)
	{
		if (NEURAL_WEB->AREAS[AREA_INDEX].KIND != NEURON_KIND)
			continue ;

		if (
			NEURON_KIND == KIND_ATTENTION_HEAD &&
			WEB_COUNT_NEURONS(NEURAL_WEB, KIND_ATTENTION_HEAD, AREA_INDEX) >=
				NEURAL_WEB->GROWTH_STATE.MAXIMUM_HEADS
		)
			continue ;

		if (NEURAL_WEB->AREAS[AREA_INDEX].ERROR_LEVEL > BEST_ERROR)
		{
			BEST_ERROR = NEURAL_WEB->AREAS[AREA_INDEX].ERROR_LEVEL;
			BEST_AREA = AREA_INDEX;
		}
	}

	return (BEST_AREA);
}

static int
	IS_TRAINABLE(WEB *NEURAL_WEB, NEURON *NEURON_ENTRY)
{
	if (!NEURAL_WEB->FROZEN)
		return (1);

	if (NEURON_ENTRY->BIRTH_REASON == WHY_PERSONAL)
		return (1);

	return (
		NEURON_ENTRY->KIND == KIND_WORD &&
		NEURON_ENTRY->KIND_DETAIL >= NEURAL_WEB->FREEZE_WORD_COUNT
	);
}

void
	LEARN_FREEZE(WEB *NEURAL_WEB, int ENABLE)
{
	NEURAL_WEB->FROZEN = ENABLE;

	if (!ENABLE)
		return ;

	NEURAL_WEB->FREEZE_STEP = NEURAL_WEB->STEP;
	NEURAL_WEB->FREEZE_WORD_COUNT = NEURAL_WEB->WORD_COUNT;
	NEURAL_WEB->KERNEL_STATE->WEIGHT_DECAY = 0;

	if (!NEURAL_WEB->OPTIMIZER_ENABLED)
		return ;

	int32_t	NEURON_INDEX;

	for (
		NEURON_INDEX = 0;
		NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
		NEURON_INDEX++
	)
	{
		NEURON	*NEURON_ENTRY = &NEURAL_WEB->NEURONS[NEURON_INDEX];

		if (
			!NEURON_ENTRY->ALIVE ||
			!NEURON_ENTRY->PARAMETER_COUNT ||
			IS_TRAINABLE(NEURAL_WEB, NEURON_ENTRY)
		)
			continue ;

		memset(
			NEURON_MOMENTS(NEURAL_WEB, NEURON_INDEX, 0), 0,
			NEURON_ENTRY->PARAMETER_COUNT * 4
		);
		memset(
			NEURON_MOMENTS(NEURAL_WEB, NEURON_INDEX, 1), 0,
			NEURON_ENTRY->PARAMETER_COUNT * 4
		);
	}
}

int
	LEARN_PERSONAL(WEB *NEURAL_WEB, int PER_AREA, int RESET_EXISTING)
{
	int		PERSONAL_COUNT = 0;
	int32_t	NEURON_INDEX;

	for (
		NEURON_INDEX = 0;
		NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
		NEURON_INDEX++
	)
		if (
			NEURAL_WEB->NEURONS[NEURON_INDEX].ALIVE &&
			NEURAL_WEB->NEURONS[NEURON_INDEX].BIRTH_REASON == WHY_PERSONAL
		)
			PERSONAL_COUNT++;

	if (RESET_EXISTING && PERSONAL_COUNT)
	{
		int32_t	NEURON_INDEX;

		for (
			NEURON_INDEX = 0;
			NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
			NEURON_INDEX++
		)
		{
			NEURON	*NEURON_ENTRY = &NEURAL_WEB->NEURONS[NEURON_INDEX];

			if (
				!NEURON_ENTRY->ALIVE ||
				NEURON_ENTRY->BIRTH_REASON != WHY_PERSONAL ||
				NEURON_ENTRY->KIND != KIND_FEED_FORWARD
			)
				continue ;

			float	*PARAMETERS = NEURON_PARAMETERS(NEURAL_WEB, NEURON_INDEX);
			int		MODEL_WIDTH = NEURAL_WEB->CONFIGURATION.DIMENSION;
			int		INNER_INDEX;

			for (INNER_INDEX = 0; INNER_INDEX < MODEL_WIDTH; INNER_INDEX++)
				PARAMETERS[INNER_INDEX] =
					(float)0.02 * WEB_GAUSSIAN(NEURAL_WEB);

			for (
				INNER_INDEX = MODEL_WIDTH;
				INNER_INDEX < NEURON_ENTRY->PARAMETER_COUNT;
				INNER_INDEX++
			)
				PARAMETERS[INNER_INDEX] = (float)0.0;

			if (NEURAL_WEB->OPTIMIZER_ENABLED)
			{
				memset(
					NEURON_MOMENTS(NEURAL_WEB, NEURON_INDEX, 0), 0,
					NEURON_ENTRY->PARAMETER_COUNT * 4
				);
				memset(
					NEURON_MOMENTS(NEURAL_WEB, NEURON_INDEX, 1), 0,
					NEURON_ENTRY->PARAMETER_COUNT * 4
				);
			}
		}

		return (PERSONAL_COUNT);
	}

	if (PERSONAL_COUNT)
		return (PERSONAL_COUNT);

	int	AREA_INDEX;

	for (
		AREA_INDEX = 1;
		AREA_INDEX < 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT;
		AREA_INDEX += 2
	)
	{
		int	INNER_INDEX;

		for (INNER_INDEX = 0; INNER_INDEX < PER_AREA; INNER_INDEX++)
		{
			WEB_ADD_NEURON(
				NEURAL_WEB, KIND_FEED_FORWARD, AREA_INDEX, WHY_PERSONAL, -1
			);
			PERSONAL_COUNT++;
		}
	}

	WEB_RELINK(NEURAL_WEB);

	return (PERSONAL_COUNT);
}

void
	LEARN_UPDATE(WEB *NEURAL_WEB)
{
	GROWTH	*GROWTH_STATE = &NEURAL_WEB->GROWTH_STATE;

	if (NEURAL_WEB->FROZEN)
	{
		int32_t	NEURON_INDEX;

		for (
			NEURON_INDEX = 0;
			NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
			NEURON_INDEX++
		)
		{
			NEURON	*NEURON_ENTRY = &NEURAL_WEB->NEURONS[NEURON_INDEX];

			if (
				NEURON_ENTRY->ALIVE &&
				NEURON_ENTRY->PARAMETER_COUNT &&
				!IS_TRAINABLE(NEURAL_WEB, NEURON_ENTRY)
			)
				memset(
					NEURON_GRADIENTS(NEURAL_WEB, NEURON_INDEX), 0,
					NEURON_ENTRY->PARAMETER_COUNT * 4
				);
		}
	}

	UPDATE_AREA_STATISTICS(NEURAL_WEB);

	if (
		GROWTH_STATE->ENABLED &&
		NEURAL_WEB->STEP - GROWTH_STATE->LAST_CHECK >=
			GROWTH_STATE->CHECK_INTERVAL
	)
	{
		float	RELATIVE_GAIN;

		if (GROWTH_STATE->LOSS_AT_CHECK > 0)
			RELATIVE_GAIN = (GROWTH_STATE->LOSS_AT_CHECK -
				GROWTH_STATE->LOSS_MOVING_AVERAGE) /
				GROWTH_STATE->LOSS_AT_CHECK;
		else
			RELATIVE_GAIN = (float)1.0;

		if (
			GROWTH_STATE->LOSS_AT_CHECK > 0 &&
			RELATIVE_GAIN < GROWTH_STATE->PLATEAU &&
			NEURAL_WEB->STEP - GROWTH_STATE->LAST_GROWTH >=
				GROWTH_STATE->COOLDOWN &&
			WEB_PARAMETER_COUNT(NEURAL_WEB) < GROWTH_STATE->MAXIMUM_PARAMETERS
		)
		{
			int	GROW_KIND;

			if (GROWTH_STATE->GROWTH_COUNT % 3 == 2)
				GROW_KIND = KIND_ATTENTION_HEAD;
			else
				GROW_KIND = KIND_FEED_FORWARD;

			int	AREA_INDEX = PICK_GROWTH_AREA(NEURAL_WEB, GROW_KIND);

			if (AREA_INDEX < 0)
			{
				GROW_KIND = KIND_FEED_FORWARD;
				AREA_INDEX = PICK_GROWTH_AREA(NEURAL_WEB, GROW_KIND);
			}

			if (AREA_INDEX >= 0)
			{
				NEURAL_WEB->KERNEL_STATE->REQUEST_AREA = AREA_INDEX;
				NEURAL_WEB->KERNEL_STATE->REQUEST_KIND = GROW_KIND;

				if (GROW_KIND == KIND_FEED_FORWARD)
					NEURAL_WEB->KERNEL_STATE->REQUEST_ARGUMENT =
						GROWTH_STATE->GROW_FEED_FORWARD;
				else
					NEURAL_WEB->KERNEL_STATE->REQUEST_ARGUMENT = 1;

				if (
					GROW_KIND == KIND_FEED_FORWARD &&
					NEURAL_WEB->GROWTH_RECIPE >= 0 &&
					NEURAL_WEB->GROWTH_RECIPE < NEURAL_WEB->RECIPE_COUNT
				)
				{
					NEURAL_WEB->KERNEL_STATE->REQUEST_KIND = KIND_RECIPE;

					int64_t	RECIPE_SIZE =
						NEURAL_WEB->RECIPES[NEURAL_WEB->GROWTH_RECIPE]
							.PARAMETER_TOTAL;
					int64_t	WANTED_PARAMETERS =
						(int64_t)GROWTH_STATE->GROW_FEED_FORWARD *
						(2 * NEURAL_WEB->CONFIGURATION.DIMENSION + 8);

					if (WANTED_PARAMETERS / RECIPE_SIZE > 1)
						NEURAL_WEB->KERNEL_STATE->REQUEST_ARGUMENT =
							WANTED_PARAMETERS / RECIPE_SIZE;
					else
						NEURAL_WEB->KERNEL_STATE->REQUEST_ARGUMENT = 1;
				}

				GROWTH_STATE->LAST_GROWTH = NEURAL_WEB->STEP;
				GROWTH_STATE->GROWTH_COUNT++;
				NEURAL_WEB->AREAS[AREA_INDEX].GROWN_COUNT++;
			}
		}

		GROWTH_STATE->LOSS_AT_CHECK = GROWTH_STATE->LOSS_MOVING_AVERAGE;
		GROWTH_STATE->LAST_CHECK = NEURAL_WEB->STEP;
	}

	WEB_RUN(NEURAL_WEB, MODE_UPDATE);

	if (
		NEURAL_WEB->KERNEL_STATE->REQUEST_AREA >= 0 &&
		NEURAL_WEB->KERNEL_STATE->REQUEST_RESULT == -2
	)
		NEURAL_WEB->KERNEL_STATE->REQUEST_RESULT = 0;
}

int
	LEARN_AVOID_WEIGHTS(
		WEB *NEURAL_WEB, KERNEL_CONTEXT *KERNEL_STATE, uint8_t *ACTIVATIONS,
		int STEP_COUNT
	)
{
	int32_t	*TARGETS = (int32_t *)(ACTIVATIONS + NEURAL_WEB->TARGETS_OFFSET);
	float	*POSITION_WEIGHTS =
		(float *)(ACTIVATIONS + NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
	int		HAS_AVOIDED = 0;
	int		POSITION;

	for (POSITION = 0; POSITION < STEP_COUNT; POSITION++)
		if (TARGETS[POSITION] >= 0 && POSITION_WEIGHTS[POSITION] < 0)
			HAS_AVOIDED = 1;

	if (!HAS_AVOIDED)
		return (0);

	KERNEL_STATE->SEQUENCE_LENGTH = STEP_COUNT;
	KERNEL_STATE->START_POSITION = 0;

	if (KERNEL_STATE == NEURAL_WEB->KERNEL_STATE)
		WEB_RUN(NEURAL_WEB, MODE_EVALUATE);
	else
	{
		KERNEL_STATE->MODE = MODE_EVALUATE;
		WEB_RUN_KERNEL_STATE(NEURAL_WEB, KERNEL_STATE);
	}

	for (POSITION = 0; POSITION < STEP_COUNT; POSITION++)
	{
		if (TARGETS[POSITION] < 0 || POSITION_WEIGHTS[POSITION] >= 0)
			continue ;

		double	PROBABILITY =
			exp(-(double)WEB_LOSS_AT(NEURAL_WEB, ACTIVATIONS, POSITION));

		if (PROBABILITY > 0.95)
			PROBABILITY = 0.95;

		POSITION_WEIGHTS[POSITION] = (float)(POSITION_WEIGHTS[POSITION] *
			PROBABILITY / (1.0 - PROBABILITY));
	}

	return (1);
}

void
	LEARN_RECORD_LOSS(WEB *NEURAL_WEB, float BATCH_LOSS)
{
	GROWTH	*GROWTH_STATE = &NEURAL_WEB->GROWTH_STATE;

	if (GROWTH_STATE->LOSS_MOVING_AVERAGE == 0)
		GROWTH_STATE->LOSS_MOVING_AVERAGE = BATCH_LOSS;
	else
		GROWTH_STATE->LOSS_MOVING_AVERAGE =
			(float)0.98 * GROWTH_STATE->LOSS_MOVING_AVERAGE +
			(float)0.02 * BATCH_LOSS;
}
