#ifndef MEMORY_H
#define MEMORY_H
#include <stdint.h>

enum
{
	MEMORY_KIND_FACT = 0,
	MEMORY_KIND_SELF,
	MEMORY_KIND_PERSON,
	MEMORY_KIND_NOTE,
	MEMORY_KIND_TOPIC
};

typedef struct
{
	uint32_t	KIND;
	uint32_t	TIMESTAMP;
	uint32_t	ID_COUNT;
	uint32_t	HIT_COUNT;
	float		WEIGHT;
	int32_t		*IDS;
} MEMORY_RECORD;

typedef struct
{
	MEMORY_RECORD	*RECORDS;
	int				COUNT;
	int				CAPACITY;
	char			PATH[512];
	int				IS_DIRTY;
} MEMORY_FILE;

int		MEMORY_FILE_LOAD(MEMORY_FILE *MEMORY_STORE, const char *PATH);
int		MEMORY_FILE_SAVE(MEMORY_FILE *MEMORY_STORE);
int		MEMORY_FILE_ADD(
	MEMORY_FILE *MEMORY_STORE, uint32_t RECORD_KIND, const int32_t *RECORD_IDS,
	int ID_COUNT, uint32_t TIME_STAMP
);
void	MEMORY_FILE_FREE(MEMORY_FILE *MEMORY_STORE);

#define WORKING_MEMORY_MESSAGES 64
#define WORKING_MEMORY_SAID 3
#define WORKING_MEMORY_IDS 400

typedef struct
{
	int32_t	SPEAKER;
	int32_t	ID_COUNT;
	int32_t	IDS[WORKING_MEMORY_IDS];
} MESSAGE;

typedef struct
{
	MESSAGE		MESSAGES[WORKING_MEMORY_MESSAGES];
	int			MESSAGE_COUNT;
	int32_t		TOPICS[4];
	float		TOPIC_WEIGHTS[4];
	int			TOPIC_COUNT;
	MESSAGE		SAID_MESSAGES[WORKING_MEMORY_SAID];
	int			SAID_COUNT;
	uint32_t	TURN;
	float		SURPRISE_AVERAGE;
	float		LAST_SURPRISE;
	int			IN_MIND_FILES[8];
	int			IN_MIND_RECORDS[8];
	int			IN_MIND_COUNT;
	int			RECALLED_FILE;
	int			RECALLED_RECORD;
} THOUGHT;

void	WORKING_MEMORY_PUSH(
	MESSAGE *MESSAGES, int *MESSAGE_COUNT, int MAXIMUM_MESSAGES,
	const MESSAGE *NEW_MESSAGE
);
int		THOUGHT_SAVE(THOUGHT *WORKING_MEMORY, const char *PATH);
int		THOUGHT_LOAD(THOUGHT *WORKING_MEMORY, const char *PATH);

#endif
