#include "MEMORY.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int
	MEMORY_FILE_LOAD(MEMORY_FILE *MEMORY_STORE, const char *PATH)
{
	memset(MEMORY_STORE, 0, sizeof *MEMORY_STORE);
	snprintf(MEMORY_STORE->PATH, sizeof MEMORY_STORE->PATH, "%s", PATH);

	FILE	*STREAM = fopen(PATH, "rb");

	if (!STREAM)
		return (-1);

	char	MAGIC[8];

	if (fread(MAGIC, 1, 8, STREAM) != 8 || memcmp(MAGIC, "CODEMEM1", 8))
	{
		fclose(STREAM);
		return (-1);
	}

	for (;;)
	{
		uint32_t	HEADER[4];
		float		RECORD_WEIGHT;

		if (
			fread(HEADER, 4, 4, STREAM) != 4 ||
			fread(&RECORD_WEIGHT, 4, 1, STREAM) != 1
		)
			break ;

		if (HEADER[2] > 4096)
			break ;

		int32_t	*RECORD_IDS = malloc((HEADER[2] + 1) * 4);

		if (fread(RECORD_IDS, 4, HEADER[2], STREAM) != HEADER[2])
		{
			free(RECORD_IDS);
			break ;
		}

		MEMORY_FILE_ADD(
			MEMORY_STORE, HEADER[0], RECORD_IDS, (int)HEADER[2], HEADER[1]
		);
		MEMORY_STORE->RECORDS[MEMORY_STORE->COUNT - 1].HIT_COUNT = HEADER[3];
		MEMORY_STORE->RECORDS[MEMORY_STORE->COUNT - 1].WEIGHT = RECORD_WEIGHT;
		free(RECORD_IDS);
	}

	fclose(STREAM);
	MEMORY_STORE->IS_DIRTY = 0;

	return (0);
}

int
	MEMORY_FILE_SAVE(MEMORY_FILE *MEMORY_STORE)
{
	if (!MEMORY_STORE->IS_DIRTY)
		return (0);

	char	TEMPORARY_PATH[600];

	snprintf(
		TEMPORARY_PATH, sizeof TEMPORARY_PATH, "%s.tmp", MEMORY_STORE->PATH
	);

	FILE	*STREAM = fopen(TEMPORARY_PATH, "wb");

	if (!STREAM)
		return (-1);

	fwrite("CODEMEM1", 1, 8, STREAM);

	int	RECORD_INDEX;

	for (RECORD_INDEX = 0; RECORD_INDEX < MEMORY_STORE->COUNT; RECORD_INDEX++)
	{
		MEMORY_RECORD	*RECORD = &MEMORY_STORE->RECORDS[RECORD_INDEX];
		uint32_t		HEADER[4] = {
			RECORD->KIND, RECORD->TIMESTAMP, RECORD->ID_COUNT, RECORD->HIT_COUNT
		};

		fwrite(HEADER, 4, 4, STREAM);
		fwrite(&RECORD->WEIGHT, 4, 1, STREAM);
		fwrite(RECORD->IDS, 4, RECORD->ID_COUNT, STREAM);
	}

	fclose(STREAM);
	remove(MEMORY_STORE->PATH);

	if (rename(TEMPORARY_PATH, MEMORY_STORE->PATH))
		return (-1);

	MEMORY_STORE->IS_DIRTY = 0;

	return (0);
}

int
	MEMORY_FILE_ADD(
		MEMORY_FILE *MEMORY_STORE, uint32_t RECORD_KIND,
		const int32_t *RECORD_IDS, int ID_COUNT, uint32_t TIME_STAMP
	)
{
	if (ID_COUNT <= 0)
		return (-1);

	int	RECORD_INDEX;

	for (RECORD_INDEX = 0; RECORD_INDEX < MEMORY_STORE->COUNT; RECORD_INDEX++)
		if (
			MEMORY_STORE->RECORDS[RECORD_INDEX].KIND == RECORD_KIND &&
			MEMORY_STORE->RECORDS[RECORD_INDEX].ID_COUNT ==
				(uint32_t)ID_COUNT &&
			!memcmp(
				MEMORY_STORE->RECORDS[RECORD_INDEX].IDS, RECORD_IDS,
				ID_COUNT * 4
			)
		)
		{
			MEMORY_STORE->RECORDS[RECORD_INDEX].WEIGHT += 1;
			MEMORY_STORE->RECORDS[RECORD_INDEX].TIMESTAMP = TIME_STAMP;
			MEMORY_STORE->IS_DIRTY = 1;
			return (RECORD_INDEX);
		}

	if (MEMORY_STORE->COUNT >= MEMORY_STORE->CAPACITY)
	{
		if (MEMORY_STORE->CAPACITY)
			MEMORY_STORE->CAPACITY = MEMORY_STORE->CAPACITY * 2;
		else
			MEMORY_STORE->CAPACITY = 32;

		MEMORY_STORE->RECORDS = realloc(
			MEMORY_STORE->RECORDS,
			MEMORY_STORE->CAPACITY * sizeof(MEMORY_RECORD)
		);
	}

	MEMORY_RECORD	*RECORD = &MEMORY_STORE->RECORDS[MEMORY_STORE->COUNT];

	RECORD->KIND = RECORD_KIND;
	RECORD->TIMESTAMP = TIME_STAMP;
	RECORD->ID_COUNT = ID_COUNT;
	RECORD->HIT_COUNT = 0;
	RECORD->WEIGHT = 1;
	RECORD->IDS = malloc(ID_COUNT * 4);
	memcpy(RECORD->IDS, RECORD_IDS, ID_COUNT * 4);
	MEMORY_STORE->IS_DIRTY = 1;

	return (MEMORY_STORE->COUNT++);
}

void
	MEMORY_FILE_FREE(MEMORY_FILE *MEMORY_STORE)
{
	int	RECORD_INDEX;

	for (RECORD_INDEX = 0; RECORD_INDEX < MEMORY_STORE->COUNT; RECORD_INDEX++)
		free(MEMORY_STORE->RECORDS[RECORD_INDEX].IDS);

	free(MEMORY_STORE->RECORDS);
	memset(MEMORY_STORE, 0, sizeof *MEMORY_STORE);
}

void
	WORKING_MEMORY_PUSH(
		MESSAGE *MESSAGES, int *MESSAGE_COUNT, int MAXIMUM_MESSAGES,
		const MESSAGE *NEW_MESSAGE
	)
{
	if (*MESSAGE_COUNT >= MAXIMUM_MESSAGES)
	{
		memmove(
			MESSAGES, MESSAGES + 1, (MAXIMUM_MESSAGES - 1) * sizeof(MESSAGE)
		);
		*MESSAGE_COUNT = MAXIMUM_MESSAGES - 1;
	}

	MESSAGES[(*MESSAGE_COUNT)++] = *NEW_MESSAGE;
}

int
	THOUGHT_SAVE(THOUGHT *WORKING_MEMORY, const char *PATH)
{
	FILE	*STREAM = fopen(PATH, "wb");

	if (!STREAM)
		return (-1);

	fwrite("CODETHT1", 1, 8, STREAM);
	fwrite(&WORKING_MEMORY->TURN, 4, 1, STREAM);
	fwrite(&WORKING_MEMORY->SURPRISE_AVERAGE, 4, 1, STREAM);
	fwrite(&WORKING_MEMORY->MESSAGE_COUNT, 4, 1, STREAM);

	int	ENTRY_INDEX;

	for (
		ENTRY_INDEX = 0;
		ENTRY_INDEX < WORKING_MEMORY->MESSAGE_COUNT;
		ENTRY_INDEX++
	)
	{
		fwrite(&WORKING_MEMORY->MESSAGES[ENTRY_INDEX].SPEAKER, 4, 1, STREAM);
		fwrite(&WORKING_MEMORY->MESSAGES[ENTRY_INDEX].ID_COUNT, 4, 1, STREAM);
		fwrite(
			WORKING_MEMORY->MESSAGES[ENTRY_INDEX].IDS, 4,
			WORKING_MEMORY->MESSAGES[ENTRY_INDEX].ID_COUNT, STREAM
		);
	}

	fwrite(&WORKING_MEMORY->SAID_COUNT, 4, 1, STREAM);

	for (
		ENTRY_INDEX = 0;
		ENTRY_INDEX < WORKING_MEMORY->SAID_COUNT;
		ENTRY_INDEX++
	)
	{
		fwrite(
			&WORKING_MEMORY->SAID_MESSAGES[ENTRY_INDEX].ID_COUNT, 4, 1, STREAM
		);
		fwrite(
			WORKING_MEMORY->SAID_MESSAGES[ENTRY_INDEX].IDS, 4,
			WORKING_MEMORY->SAID_MESSAGES[ENTRY_INDEX].ID_COUNT, STREAM
		);
	}

	fwrite(&WORKING_MEMORY->TOPIC_COUNT, 4, 1, STREAM);
	fwrite(WORKING_MEMORY->TOPICS, 4, WORKING_MEMORY->TOPIC_COUNT, STREAM);
	fwrite(
		WORKING_MEMORY->TOPIC_WEIGHTS, 4, WORKING_MEMORY->TOPIC_COUNT, STREAM
	);
	fclose(STREAM);

	return (0);
}

int
	THOUGHT_LOAD(THOUGHT *WORKING_MEMORY, const char *PATH)
{
	memset(WORKING_MEMORY, 0, sizeof *WORKING_MEMORY);

	FILE	*STREAM = fopen(PATH, "rb");

	if (!STREAM)
		return (-1);

	char	MAGIC[8];
	int		SUCCESS =
		fread(MAGIC, 1, 8, STREAM) == 8 && !memcmp(MAGIC, "CODETHT1", 8);

	SUCCESS = SUCCESS && fread(&WORKING_MEMORY->TURN, 4, 1, STREAM) == 1 &&
		fread(&WORKING_MEMORY->SURPRISE_AVERAGE, 4, 1, STREAM) == 1 &&
		fread(&WORKING_MEMORY->MESSAGE_COUNT, 4, 1, STREAM) == 1 &&
		WORKING_MEMORY->MESSAGE_COUNT >= 0 &&
		WORKING_MEMORY->MESSAGE_COUNT <= WORKING_MEMORY_MESSAGES;

	int	ENTRY_INDEX;

	for (
		ENTRY_INDEX = 0;
		SUCCESS && ENTRY_INDEX < WORKING_MEMORY->MESSAGE_COUNT;
		ENTRY_INDEX++
	)
		SUCCESS =
			fread(
				&WORKING_MEMORY->MESSAGES[ENTRY_INDEX].SPEAKER, 4, 1, STREAM
			) == 1 &&
			fread(
				&WORKING_MEMORY->MESSAGES[ENTRY_INDEX].ID_COUNT, 4, 1, STREAM
			) == 1 &&
			WORKING_MEMORY->MESSAGES[ENTRY_INDEX].ID_COUNT >= 0 &&
			WORKING_MEMORY->MESSAGES[ENTRY_INDEX].ID_COUNT <=
				WORKING_MEMORY_IDS &&
			fread(
				WORKING_MEMORY->MESSAGES[ENTRY_INDEX].IDS, 4,
				WORKING_MEMORY->MESSAGES[ENTRY_INDEX].ID_COUNT, STREAM
			) == (size_t)WORKING_MEMORY->MESSAGES[ENTRY_INDEX].ID_COUNT;

	SUCCESS = SUCCESS &&
		fread(&WORKING_MEMORY->SAID_COUNT, 4, 1, STREAM) == 1 &&
		WORKING_MEMORY->SAID_COUNT >= 0 &&
		WORKING_MEMORY->SAID_COUNT <= WORKING_MEMORY_SAID;

	for (
		ENTRY_INDEX = 0;
		SUCCESS && ENTRY_INDEX < WORKING_MEMORY->SAID_COUNT;
		ENTRY_INDEX++
	)
		SUCCESS = fread(
			&WORKING_MEMORY->SAID_MESSAGES[ENTRY_INDEX].ID_COUNT, 4,
			1, STREAM
			) == 1 &&
			WORKING_MEMORY->SAID_MESSAGES[ENTRY_INDEX].ID_COUNT >= 0 &&
			WORKING_MEMORY->SAID_MESSAGES[ENTRY_INDEX].ID_COUNT <=
				WORKING_MEMORY_IDS &&
			fread(
				WORKING_MEMORY->SAID_MESSAGES[ENTRY_INDEX].IDS, 4,
				WORKING_MEMORY->SAID_MESSAGES[ENTRY_INDEX].ID_COUNT, STREAM
			) == (size_t)WORKING_MEMORY->SAID_MESSAGES[ENTRY_INDEX].ID_COUNT;

	SUCCESS = SUCCESS &&
		fread(&WORKING_MEMORY->TOPIC_COUNT, 4, 1, STREAM) == 1 &&
		WORKING_MEMORY->TOPIC_COUNT >= 0 && WORKING_MEMORY->TOPIC_COUNT <= 4;
	SUCCESS = SUCCESS &&
		fread(WORKING_MEMORY->TOPICS, 4, WORKING_MEMORY->TOPIC_COUNT, STREAM) ==
			(size_t)WORKING_MEMORY->TOPIC_COUNT &&
		fread(
			WORKING_MEMORY->TOPIC_WEIGHTS, 4, WORKING_MEMORY->TOPIC_COUNT,
			STREAM
		) == (size_t)WORKING_MEMORY->TOPIC_COUNT;
	fclose(STREAM);

	if (!SUCCESS)
	{
		memset(WORKING_MEMORY, 0, sizeof *WORKING_MEMORY);
		return (-1);
	}

	return (0);
}
