#ifndef NEAREST_NEIGHBOR_H
#define NEAREST_NEIGHBOR_H
#include "CODE.h"

typedef struct
{
	int			DIMENSION;
	int			COUNT;
	int			CAPACITY;
	int			MESSAGE_COUNT;
	int			MESSAGE_CAPACITY;
	int			MAXIMUM_MESSAGES;
	float		*KEYS;
	int32_t		*VALUES;
	int32_t		*SOURCE_MESSAGES;
	int32_t		**MESSAGES;
	uint8_t		**MASKS;
	int			*MESSAGE_LENGTHS;
	int64_t		TRAINING_STEP;
	uint64_t	VOCABULARY_TAG;
} NEAREST_NEIGHBORS;

void	NEAREST_NEIGHBOR_INITIALIZE(
	NEAREST_NEIGHBORS *NEIGHBOR_INDEX, int KEY_DIMENSION, int MESSAGE_LIMIT
);
void	NEAREST_NEIGHBOR_FREE(NEAREST_NEIGHBORS *NEIGHBOR_INDEX);
void	WEB_HIDDEN_STATE(WEB *NEURAL_WEB, int TOKEN_POSITION, float *OUTPUT);
int		NEAREST_NEIGHBOR_ADD(
	NEAREST_NEIGHBORS *NEIGHBOR_INDEX, WEB *NEURAL_WEB, const int32_t *TOKENS,
	int TOKEN_COUNT, const uint8_t *KEY_MASK
);
void	NEAREST_NEIGHBOR_REBUILD(
	NEAREST_NEIGHBORS *NEIGHBOR_INDEX, WEB *NEURAL_WEB
);
int		NEAREST_NEIGHBOR_QUERY(
	NEAREST_NEIGHBORS *NEIGHBOR_INDEX, const float *QUERY_VECTOR,
	int RESULT_LIMIT, int32_t *RESULT_VALUES, float *RESULT_SIMILARITY
);
int		NEAREST_NEIGHBOR_SAVE(
	NEAREST_NEIGHBORS *NEIGHBOR_INDEX, const char *PATH
);
int		NEAREST_NEIGHBOR_LOAD(
	NEAREST_NEIGHBORS *NEIGHBOR_INDEX, WEB *NEURAL_WEB, const char *PATH,
	uint64_t EXPECTED_TAG
);
void	NEAREST_NEIGHBOR_CLEAR(NEAREST_NEIGHBORS *NEIGHBOR_INDEX);

#endif
