#include "NEAREST_NEIGHBOR.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

void
	NEAREST_NEIGHBOR_INITIALIZE(
		NEAREST_NEIGHBORS *NEIGHBOR_INDEX, int KEY_DIMENSION, int MESSAGE_LIMIT
	)
{
	memset(NEIGHBOR_INDEX, 0, sizeof *NEIGHBOR_INDEX);
	NEIGHBOR_INDEX->DIMENSION = KEY_DIMENSION;
	NEIGHBOR_INDEX->MAXIMUM_MESSAGES = MESSAGE_LIMIT;
}

void
	NEAREST_NEIGHBOR_CLEAR(NEAREST_NEIGHBORS *NEIGHBOR_INDEX)
{
	int	MESSAGE_INDEX;

	for (
		MESSAGE_INDEX = 0;
		MESSAGE_INDEX < NEIGHBOR_INDEX->MESSAGE_COUNT;
		MESSAGE_INDEX++
	)
	{
		free(NEIGHBOR_INDEX->MESSAGES[MESSAGE_INDEX]);
		free(NEIGHBOR_INDEX->MASKS[MESSAGE_INDEX]);
	}

	NEIGHBOR_INDEX->MESSAGE_COUNT = 0;
	NEIGHBOR_INDEX->COUNT = 0;
}

void
	NEAREST_NEIGHBOR_FREE(NEAREST_NEIGHBORS *NEIGHBOR_INDEX)
{
	NEAREST_NEIGHBOR_CLEAR(NEIGHBOR_INDEX);
	free(NEIGHBOR_INDEX->KEYS);
	free(NEIGHBOR_INDEX->VALUES);
	free(NEIGHBOR_INDEX->SOURCE_MESSAGES);
	free(NEIGHBOR_INDEX->MESSAGES);
	free(NEIGHBOR_INDEX->MASKS);
	free(NEIGHBOR_INDEX->MESSAGE_LENGTHS);
	memset(NEIGHBOR_INDEX, 0, sizeof *NEIGHBOR_INDEX);
}

void
	WEB_HIDDEN_STATE(WEB *NEURAL_WEB, int TOKEN_POSITION, float *OUTPUT)
{
	int			MODEL_DIMENSION = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int			FINAL_AREA = 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT;
	const float	*HIDDEN_STATE =
		(const float *)(NEURAL_WEB->ACTIVATIONS +
						LAYER_NORMALIZED(
							NEURAL_WEB,
							NEURAL_WEB->HALF_PRECISION ? (FINAL_AREA & 1)
							: FINAL_AREA
						)) +
		(int64_t)TOKEN_POSITION * MODEL_DIMENSION;
	double		SQUARED_SUM = 0;
	int			COMPONENT_INDEX;

	for (
		COMPONENT_INDEX = 0;
		COMPONENT_INDEX < MODEL_DIMENSION;
		COMPONENT_INDEX++
	)
		SQUARED_SUM += (double)HIDDEN_STATE[COMPONENT_INDEX] *
			HIDDEN_STATE[COMPONENT_INDEX];

	float	INVERSE_NORM;

	if (SQUARED_SUM > 0)
		INVERSE_NORM = (float)(1.0 / sqrt(SQUARED_SUM));
	else
		INVERSE_NORM = 0;

	for (
		COMPONENT_INDEX = 0;
		COMPONENT_INDEX < MODEL_DIMENSION;
		COMPONENT_INDEX++
	)
		OUTPUT[COMPONENT_INDEX] = HIDDEN_STATE[COMPONENT_INDEX] * INVERSE_NORM;
}

static void
	PUSH_KEY(
		NEAREST_NEIGHBORS *NEIGHBOR_INDEX, const float *HIDDEN_KEY,
		int32_t NEXT_TOKEN, int32_t SOURCE_MESSAGE
	)
{
	if (NEIGHBOR_INDEX->COUNT >= NEIGHBOR_INDEX->CAPACITY)
	{
		if (NEIGHBOR_INDEX->CAPACITY)
			NEIGHBOR_INDEX->CAPACITY = NEIGHBOR_INDEX->CAPACITY * 2;
		else
			NEIGHBOR_INDEX->CAPACITY = 1024;

		NEIGHBOR_INDEX->KEYS = realloc(
			NEIGHBOR_INDEX->KEYS,
			(size_t)NEIGHBOR_INDEX->CAPACITY * NEIGHBOR_INDEX->DIMENSION * 4
		);
		NEIGHBOR_INDEX->VALUES = realloc(
			NEIGHBOR_INDEX->VALUES, (size_t)NEIGHBOR_INDEX->CAPACITY * 4
		);
		NEIGHBOR_INDEX->SOURCE_MESSAGES = realloc(
			NEIGHBOR_INDEX->SOURCE_MESSAGES,
			(size_t)NEIGHBOR_INDEX->CAPACITY * 4
		);
	}

	memcpy(
		NEIGHBOR_INDEX->KEYS +
			(size_t)NEIGHBOR_INDEX->COUNT * NEIGHBOR_INDEX->DIMENSION,
		HIDDEN_KEY, NEIGHBOR_INDEX->DIMENSION * 4
	);
	NEIGHBOR_INDEX->VALUES[NEIGHBOR_INDEX->COUNT] = NEXT_TOKEN;
	NEIGHBOR_INDEX->SOURCE_MESSAGES[NEIGHBOR_INDEX->COUNT] = SOURCE_MESSAGE;
	NEIGHBOR_INDEX->COUNT++;
}

static int
	ADD_MESSAGE_KEYS(
		NEAREST_NEIGHBORS *NEIGHBOR_INDEX, WEB *NEURAL_WEB, int MESSAGE_INDEX
	)
{
	int	TOKEN_COUNT = NEIGHBOR_INDEX->MESSAGE_LENGTHS[MESSAGE_INDEX];

	if (TOKEN_COUNT > NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH)
		TOKEN_COUNT = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;

	if (TOKEN_COUNT < 2)
		return (0);

	memcpy(
		NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET,
		NEIGHBOR_INDEX->MESSAGES[MESSAGE_INDEX], TOKEN_COUNT * 4
	);
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	WEB_RUN(NEURAL_WEB, MODE_INFER);

	float	*HIDDEN_BUFFER = malloc(NEIGHBOR_INDEX->DIMENSION * 4);
	int		ADDED_COUNT = 0;
	int		TOKEN_POSITION;

	for (TOKEN_POSITION = 0; TOKEN_POSITION + 1 < TOKEN_COUNT; TOKEN_POSITION++)
	{
		if (!NEIGHBOR_INDEX->MASKS[MESSAGE_INDEX][TOKEN_POSITION + 1])
			continue ;

		WEB_HIDDEN_STATE(NEURAL_WEB, TOKEN_POSITION, HIDDEN_BUFFER);
		PUSH_KEY(
			NEIGHBOR_INDEX, HIDDEN_BUFFER,
			NEIGHBOR_INDEX->MESSAGES[MESSAGE_INDEX][TOKEN_POSITION + 1],
			MESSAGE_INDEX
		);
		ADDED_COUNT++;
	}

	free(HIDDEN_BUFFER);

	return (ADDED_COUNT);
}

static void
	DROP_OLDEST_MESSAGE(NEAREST_NEIGHBORS *NEIGHBOR_INDEX)
{
	free(NEIGHBOR_INDEX->MESSAGES[0]);
	free(NEIGHBOR_INDEX->MASKS[0]);
	memmove(
		NEIGHBOR_INDEX->MESSAGES, NEIGHBOR_INDEX->MESSAGES + 1,
		(NEIGHBOR_INDEX->MESSAGE_COUNT - 1) * sizeof *NEIGHBOR_INDEX->MESSAGES
	);
	memmove(
		NEIGHBOR_INDEX->MASKS, NEIGHBOR_INDEX->MASKS + 1,
		(NEIGHBOR_INDEX->MESSAGE_COUNT - 1) * sizeof *NEIGHBOR_INDEX->MASKS
	);
	memmove(
		NEIGHBOR_INDEX->MESSAGE_LENGTHS, NEIGHBOR_INDEX->MESSAGE_LENGTHS + 1,
		(NEIGHBOR_INDEX->MESSAGE_COUNT - 1) *
			sizeof *NEIGHBOR_INDEX->MESSAGE_LENGTHS
	);
	NEIGHBOR_INDEX->MESSAGE_COUNT--;

	int	WRITE_INDEX = 0;
	int	READ_INDEX;

	for (READ_INDEX = 0; READ_INDEX < NEIGHBOR_INDEX->COUNT; READ_INDEX++)
	{
		if (NEIGHBOR_INDEX->SOURCE_MESSAGES[READ_INDEX] == 0)
			continue ;

		if (WRITE_INDEX != READ_INDEX)
		{
			memcpy(
				NEIGHBOR_INDEX->KEYS +
					(size_t)WRITE_INDEX * NEIGHBOR_INDEX->DIMENSION,
				NEIGHBOR_INDEX->KEYS +
					(size_t)READ_INDEX * NEIGHBOR_INDEX->DIMENSION,
				NEIGHBOR_INDEX->DIMENSION * 4
			);
			NEIGHBOR_INDEX->VALUES[WRITE_INDEX] =
				NEIGHBOR_INDEX->VALUES[READ_INDEX];
		}

		NEIGHBOR_INDEX->SOURCE_MESSAGES[WRITE_INDEX] =
			NEIGHBOR_INDEX->SOURCE_MESSAGES[READ_INDEX] - 1;
		WRITE_INDEX++;
	}

	NEIGHBOR_INDEX->COUNT = WRITE_INDEX;
}

int
	NEAREST_NEIGHBOR_ADD(
		NEAREST_NEIGHBORS *NEIGHBOR_INDEX, WEB *NEURAL_WEB,
		const int32_t *TOKENS, int TOKEN_COUNT, const uint8_t *KEY_MASK
	)
{
	if (
		TOKEN_COUNT < 2 ||
		NEURAL_WEB->CONFIGURATION.DIMENSION != NEIGHBOR_INDEX->DIMENSION
	)
		return (0);

	if (
		NEIGHBOR_INDEX->MAXIMUM_MESSAGES > 0 &&
		NEIGHBOR_INDEX->MESSAGE_COUNT >= NEIGHBOR_INDEX->MAXIMUM_MESSAGES
	)
		DROP_OLDEST_MESSAGE(NEIGHBOR_INDEX);

	if (NEIGHBOR_INDEX->MESSAGE_COUNT >= NEIGHBOR_INDEX->MESSAGE_CAPACITY)
	{
		if (NEIGHBOR_INDEX->MESSAGE_CAPACITY)
			NEIGHBOR_INDEX->MESSAGE_CAPACITY =
				NEIGHBOR_INDEX->MESSAGE_CAPACITY * 2;
		else
			NEIGHBOR_INDEX->MESSAGE_CAPACITY = 64;

		NEIGHBOR_INDEX->MESSAGES = realloc(
			NEIGHBOR_INDEX->MESSAGES,
			NEIGHBOR_INDEX->MESSAGE_CAPACITY * sizeof *NEIGHBOR_INDEX->MESSAGES
		);
		NEIGHBOR_INDEX->MASKS = realloc(
			NEIGHBOR_INDEX->MASKS,
			NEIGHBOR_INDEX->MESSAGE_CAPACITY * sizeof *NEIGHBOR_INDEX->MASKS
		);
		NEIGHBOR_INDEX->MESSAGE_LENGTHS = realloc(
			NEIGHBOR_INDEX->MESSAGE_LENGTHS,
			NEIGHBOR_INDEX->MESSAGE_CAPACITY *
				sizeof *NEIGHBOR_INDEX->MESSAGE_LENGTHS
		);
	}

	int	MESSAGE_INDEX = NEIGHBOR_INDEX->MESSAGE_COUNT++;

	NEIGHBOR_INDEX->MESSAGES[MESSAGE_INDEX] = malloc(TOKEN_COUNT * 4);
	NEIGHBOR_INDEX->MASKS[MESSAGE_INDEX] = malloc(TOKEN_COUNT);
	memcpy(NEIGHBOR_INDEX->MESSAGES[MESSAGE_INDEX], TOKENS, TOKEN_COUNT * 4);
	memcpy(NEIGHBOR_INDEX->MASKS[MESSAGE_INDEX], KEY_MASK, TOKEN_COUNT);
	NEIGHBOR_INDEX->MESSAGE_LENGTHS[MESSAGE_INDEX] = TOKEN_COUNT;
	NEIGHBOR_INDEX->TRAINING_STEP = NEURAL_WEB->STEP;

	return (ADD_MESSAGE_KEYS(NEIGHBOR_INDEX, NEURAL_WEB, MESSAGE_INDEX));
}

void
	NEAREST_NEIGHBOR_REBUILD(NEAREST_NEIGHBORS *NEIGHBOR_INDEX, WEB *NEURAL_WEB)
{
	NEIGHBOR_INDEX->COUNT = 0;
	NEIGHBOR_INDEX->DIMENSION = NEURAL_WEB->CONFIGURATION.DIMENSION;

	int	MESSAGE_INDEX;

	for (
		MESSAGE_INDEX = 0;
		MESSAGE_INDEX < NEIGHBOR_INDEX->MESSAGE_COUNT;
		MESSAGE_INDEX++
	)
		ADD_MESSAGE_KEYS(NEIGHBOR_INDEX, NEURAL_WEB, MESSAGE_INDEX);

	NEIGHBOR_INDEX->TRAINING_STEP = NEURAL_WEB->STEP;
}

int
	NEAREST_NEIGHBOR_QUERY(
		NEAREST_NEIGHBORS *NEIGHBOR_INDEX, const float *QUERY_VECTOR,
		int RESULT_LIMIT, int32_t *RESULT_VALUES, float *RESULT_SIMILARITY
	)
{
	int	FOUND_COUNT = 0;
	int	KEY_INDEX;

	for (KEY_INDEX = 0; KEY_INDEX < NEIGHBOR_INDEX->COUNT; KEY_INDEX++)
	{
		const float	*KEY_VECTOR = NEIGHBOR_INDEX->KEYS +
			(size_t)KEY_INDEX * NEIGHBOR_INDEX->DIMENSION;
		float		SIMILARITY = 0;
		int			COMPONENT_INDEX;

		for (
			COMPONENT_INDEX = 0;
			COMPONENT_INDEX < NEIGHBOR_INDEX->DIMENSION;
			COMPONENT_INDEX++
		)
			SIMILARITY +=
				KEY_VECTOR[COMPONENT_INDEX] * QUERY_VECTOR[COMPONENT_INDEX];

		if (FOUND_COUNT < RESULT_LIMIT)
			FOUND_COUNT++;
		else if (SIMILARITY <= RESULT_SIMILARITY[FOUND_COUNT - 1])
			continue ;

		int	INSERT_POSITION = FOUND_COUNT - 1;

		while (
			INSERT_POSITION > 0 &&
			RESULT_SIMILARITY[INSERT_POSITION - 1] < SIMILARITY
		)
		{
			RESULT_SIMILARITY[INSERT_POSITION] =
				RESULT_SIMILARITY[INSERT_POSITION - 1];
			RESULT_VALUES[INSERT_POSITION] = RESULT_VALUES[INSERT_POSITION - 1];
			INSERT_POSITION--;
		}

		RESULT_SIMILARITY[INSERT_POSITION] = SIMILARITY;
		RESULT_VALUES[INSERT_POSITION] = NEIGHBOR_INDEX->VALUES[KEY_INDEX];
	}

	return (FOUND_COUNT);
}

int
	NEAREST_NEIGHBOR_SAVE(NEAREST_NEIGHBORS *NEIGHBOR_INDEX, const char *PATH)
{
	char	TEMPORARY_PATH[1100];

	snprintf(TEMPORARY_PATH, sizeof TEMPORARY_PATH, "%s.tmp", PATH);

	FILE	*STREAM = fopen(TEMPORARY_PATH, "wb");

	if (!STREAM)
		return (-1);

	fwrite("CODEKNN1", 1, 8, STREAM);
	fwrite(&NEIGHBOR_INDEX->TRAINING_STEP, 8, 1, STREAM);
	fwrite(&NEIGHBOR_INDEX->VOCABULARY_TAG, 8, 1, STREAM);
	fwrite(&NEIGHBOR_INDEX->DIMENSION, 4, 1, STREAM);
	fwrite(&NEIGHBOR_INDEX->MESSAGE_COUNT, 4, 1, STREAM);

	int	MESSAGE_INDEX;

	for (
		MESSAGE_INDEX = 0;
		MESSAGE_INDEX < NEIGHBOR_INDEX->MESSAGE_COUNT;
		MESSAGE_INDEX++
	)
	{
		fwrite(&NEIGHBOR_INDEX->MESSAGE_LENGTHS[MESSAGE_INDEX], 4, 1, STREAM);
		fwrite(
			NEIGHBOR_INDEX->MESSAGES[MESSAGE_INDEX], 4,
			NEIGHBOR_INDEX->MESSAGE_LENGTHS[MESSAGE_INDEX], STREAM
		);
		fwrite(
			NEIGHBOR_INDEX->MASKS[MESSAGE_INDEX], 1,
			NEIGHBOR_INDEX->MESSAGE_LENGTHS[MESSAGE_INDEX], STREAM
		);
	}

	fwrite(&NEIGHBOR_INDEX->COUNT, 4, 1, STREAM);
	fwrite(
		NEIGHBOR_INDEX->KEYS, 4,
		(size_t)NEIGHBOR_INDEX->COUNT * NEIGHBOR_INDEX->DIMENSION, STREAM
	);
	fwrite(NEIGHBOR_INDEX->VALUES, 4, NEIGHBOR_INDEX->COUNT, STREAM);
	fwrite(NEIGHBOR_INDEX->SOURCE_MESSAGES, 4, NEIGHBOR_INDEX->COUNT, STREAM);

	int	SUCCESS = !ferror(STREAM);

	fclose(STREAM);
	remove(PATH);

	if (SUCCESS && !rename(TEMPORARY_PATH, PATH))
		return (0);

	return (-1);
}

int
	NEAREST_NEIGHBOR_LOAD(
		NEAREST_NEIGHBORS *NEIGHBOR_INDEX, WEB *NEURAL_WEB, const char *PATH,
		uint64_t EXPECTED_TAG
	)
{
	FILE	*STREAM = fopen(PATH, "rb");

	if (!STREAM)
		return (-1);

	char		MAGIC[8];
	int64_t		SAVED_STEP;
	uint64_t	SAVED_TAG;
	int			SAVED_DIMENSION;
	int			MESSAGE_COUNT;
	int			KEY_COUNT;

	if (
		fread(MAGIC, 1, 8, STREAM) != 8 ||
		memcmp(MAGIC, "CODEKNN1", 8) ||
		fread(&SAVED_STEP, 8, 1, STREAM) != 1 ||
		fread(&SAVED_TAG, 8, 1, STREAM) != 1 ||
		fread(&SAVED_DIMENSION, 4, 1, STREAM) != 1 ||
		fread(&MESSAGE_COUNT, 4, 1, STREAM) != 1 ||
		MESSAGE_COUNT < 0 ||
		MESSAGE_COUNT > 1000000
	)
	{
		fclose(STREAM);
		return (-1);
	}

	if (
		SAVED_TAG != EXPECTED_TAG ||
		SAVED_DIMENSION != NEURAL_WEB->CONFIGURATION.DIMENSION
	)
	{
		fclose(STREAM);
		return (1);
	}

	NEAREST_NEIGHBOR_CLEAR(NEIGHBOR_INDEX);
	NEIGHBOR_INDEX->DIMENSION = SAVED_DIMENSION;
	NEIGHBOR_INDEX->VOCABULARY_TAG = EXPECTED_TAG;

	int	MESSAGE_INDEX;

	for (MESSAGE_INDEX = 0; MESSAGE_INDEX < MESSAGE_COUNT; MESSAGE_INDEX++)
	{
		int	MESSAGE_LENGTH;

		if (
			fread(&MESSAGE_LENGTH, 4, 1, STREAM) != 1 ||
			MESSAGE_LENGTH < 0 ||
			MESSAGE_LENGTH > 65536
		)
		{
			fclose(STREAM);
			NEAREST_NEIGHBOR_CLEAR(NEIGHBOR_INDEX);
			return (-1);
		}

		int32_t	*MESSAGE_TOKENS = malloc(MESSAGE_LENGTH * 4 + 4);
		uint8_t	*MESSAGE_MASK = malloc(MESSAGE_LENGTH + 1);

		if (
			fread(MESSAGE_TOKENS, 4, MESSAGE_LENGTH, STREAM) !=
				(size_t)MESSAGE_LENGTH ||
			fread(MESSAGE_MASK, 1, MESSAGE_LENGTH, STREAM) !=
				(size_t)MESSAGE_LENGTH
		)
		{
			free(MESSAGE_TOKENS);
			free(MESSAGE_MASK);
			fclose(STREAM);
			NEAREST_NEIGHBOR_CLEAR(NEIGHBOR_INDEX);
			return (-1);
		}

		if (NEIGHBOR_INDEX->MESSAGE_COUNT >= NEIGHBOR_INDEX->MESSAGE_CAPACITY)
		{
			if (NEIGHBOR_INDEX->MESSAGE_CAPACITY)
				NEIGHBOR_INDEX->MESSAGE_CAPACITY =
					NEIGHBOR_INDEX->MESSAGE_CAPACITY * 2;
			else
				NEIGHBOR_INDEX->MESSAGE_CAPACITY = 64;

			NEIGHBOR_INDEX->MESSAGES = realloc(
				NEIGHBOR_INDEX->MESSAGES,
				NEIGHBOR_INDEX->MESSAGE_CAPACITY *
					sizeof *NEIGHBOR_INDEX->MESSAGES
			);
			NEIGHBOR_INDEX->MASKS = realloc(
				NEIGHBOR_INDEX->MASKS,
				NEIGHBOR_INDEX->MESSAGE_CAPACITY * sizeof *NEIGHBOR_INDEX->MASKS
			);
			NEIGHBOR_INDEX->MESSAGE_LENGTHS = realloc(
				NEIGHBOR_INDEX->MESSAGE_LENGTHS,
				NEIGHBOR_INDEX->MESSAGE_CAPACITY *
					sizeof *NEIGHBOR_INDEX->MESSAGE_LENGTHS
			);
		}

		NEIGHBOR_INDEX->MESSAGES[NEIGHBOR_INDEX->MESSAGE_COUNT] =
			MESSAGE_TOKENS;
		NEIGHBOR_INDEX->MASKS[NEIGHBOR_INDEX->MESSAGE_COUNT] = MESSAGE_MASK;
		NEIGHBOR_INDEX->MESSAGE_LENGTHS[NEIGHBOR_INDEX->MESSAGE_COUNT++] =
			MESSAGE_LENGTH;
	}

	int	KEYS_VALID = SAVED_STEP == NEURAL_WEB->STEP &&
		fread(&KEY_COUNT, 4, 1, STREAM) == 1 && KEY_COUNT >= 0 &&
		KEY_COUNT < 100000000;

	if (KEYS_VALID)
	{
		if (KEY_COUNT > NEIGHBOR_INDEX->CAPACITY)
		{
			NEIGHBOR_INDEX->CAPACITY = KEY_COUNT;
			NEIGHBOR_INDEX->KEYS = realloc(
				NEIGHBOR_INDEX->KEYS,
				(size_t)KEY_COUNT * SAVED_DIMENSION * 4 + 4
			);
			NEIGHBOR_INDEX->VALUES =
				realloc(NEIGHBOR_INDEX->VALUES, (size_t)KEY_COUNT * 4 + 4);
			NEIGHBOR_INDEX->SOURCE_MESSAGES = realloc(
				NEIGHBOR_INDEX->SOURCE_MESSAGES, (size_t)KEY_COUNT * 4 + 4
			);
		}

		KEYS_VALID = fread(
			NEIGHBOR_INDEX->KEYS, 4,
			(size_t)KEY_COUNT * SAVED_DIMENSION, STREAM
			) == (size_t)KEY_COUNT * SAVED_DIMENSION &&
			fread(NEIGHBOR_INDEX->VALUES, 4, KEY_COUNT, STREAM) ==
				(size_t)KEY_COUNT &&
			fread(NEIGHBOR_INDEX->SOURCE_MESSAGES, 4, KEY_COUNT, STREAM) ==
				(size_t)KEY_COUNT;

		if (KEYS_VALID)
			NEIGHBOR_INDEX->COUNT = KEY_COUNT;
		else
			NEIGHBOR_INDEX->COUNT = 0;
	}

	fclose(STREAM);

	if (!KEYS_VALID)
		NEAREST_NEIGHBOR_REBUILD(NEIGHBOR_INDEX, NEURAL_WEB);

	return (0);
}
