#ifndef RECIPE_H
#define RECIPE_H
#include <stdint.h>

enum
{
	RECIPE_INPUT,
	RECIPE_MATRIX_VECTOR,
	RECIPE_MATRIX_TRANSPOSED,
	RECIPE_ADD,
	RECIPE_SUBTRACT,
	RECIPE_MULTIPLY,
	RECIPE_ADD_PARAMETER,
	RECIPE_MULTIPLY_PARAMETER,
	RECIPE_RELU,
	RECIPE_SIGMOID,
	RECIPE_SILU,
	RECIPE_TANH,
	RECIPE_GELU,
	RECIPE_DOT_PRODUCT,
	RECIPE_SUM,
	RECIPE_SCALE,
	RECIPE_SOFTMAX,
	RECIPE_OUTPUT,
	RECIPE_OPERATION_COUNT
};

enum
{
	INITIALIZE_READ,
	INITIALIZE_WRITE,
	INITIALIZE_ONE,
	INITIALIZE_ZERO
};

enum
{
	LOCATION_OWN,
	LOCATION_INPUT,
	LOCATION_RESIDUAL
};

#define RECIPE_OPERATION_LIMIT 64
#define RECIPE_PARAMETER_LIMIT 16

typedef struct
{
	int		OPERATION;
	int		FIRST_INPUT;
	int		SECOND_INPUT;
	int		PARAMETER_INDEX;
	int		LENGTH;
	int		LOCATION;
	int		USE_COUNT;
	int64_t	VALUE_OFFSET;
} RECIPE_OPERATION;

typedef struct
{
	char	NAME[32];
	int		ROWS;
	int		COLUMNS;
	int		INITIALIZATION;
	int64_t	OFFSET;
} RECIPE_PARAMETER;

typedef struct
{
	char				NAME[32];
	char				*SOURCE;
	int					OPERATION_COUNT;
	int					PARAMETER_COUNT;
	int					MODEL_DIMENSION;
	RECIPE_OPERATION	OPERATIONS[RECIPE_OPERATION_LIMIT];
	RECIPE_PARAMETER	PARAMETERS[RECIPE_PARAMETER_LIMIT];
	int64_t				PARAMETER_TOTAL;
	int64_t				VALUE_STRIDE;
} RECIPE;

const char	*RECIPE_OPERATION_NAME(int OPERATION_CODE);
int			RECIPE_PARSE(
	RECIPE *PARSED_RECIPE, const char *SOURCE, int MODEL_WIDTH,
	char *ERROR_TEXT, int ERROR_LENGTH
);
void		RECIPE_FREE(RECIPE *ACTIVE_RECIPE);
void		RECIPE_REFERENCE_FORWARD(
	const RECIPE *ACTIVE_RECIPE, const float *PARAMETERS,
	const float *NORMALIZED_INPUT, float *RESIDUAL_OUTPUT, float *VALUE_STORE,
	int FIRST_POSITION, int POSITION_COUNT
);
void		RECIPE_REFERENCE_BACKWARD(
	const RECIPE *ACTIVE_RECIPE, const float *PARAMETERS, float *GRADIENTS,
	const float *NORMALIZED_INPUT, float *INPUT_GRADIENT,
	const float *RESIDUAL_GRADIENT, const float *VALUE_STORE,
	float *VALUE_GRADIENTS, int POSITION_COUNT
);

#endif
