#include "CODE.h"
#include <math.h>
#include <string.h>

static float
	*ACTIVATION_FLOATS(WEB *NEURAL_WEB, int64_t OFFSET)
{
	return ((float *)(NEURAL_WEB->ACTIVATIONS + OFFSET));
}

static int32_t
	*ACTIVATION_INTEGERS(WEB *NEURAL_WEB, int64_t OFFSET)
{
	return ((int32_t *)(NEURAL_WEB->ACTIVATIONS + OFFSET));
}

static float
	FLOAT_DOT(const float *LEFT_VECTOR, const float *RIGHT_VECTOR, int LENGTH)
{
	double	ACCUMULATOR = 0;
	int		INDEX;

	for (INDEX = 0; INDEX < LENGTH; INDEX++)
		ACCUMULATOR += (double)LEFT_VECTOR[INDEX] * RIGHT_VECTOR[INDEX];

	return ((float)ACCUMULATOR);
}

static void
	ROTATE_PAIRS(float *VECTOR, int POSITION, int HEAD_WIDTH, int INVERSE)
{
	int	PAIR_INDEX;

	for (PAIR_INDEX = 0; PAIR_INDEX < HEAD_WIDTH / 2; PAIR_INDEX++)
	{
		double	ANGLE = POSITION * pow(10000.0, -2.0 * PAIR_INDEX / HEAD_WIDTH);
		double	COSINE = cos(ANGLE);
		double	SINE;

		if (INVERSE)
			SINE = -sin(ANGLE);
		else
			SINE = sin(ANGLE);

		double	EVEN_VALUE = VECTOR[2 * PAIR_INDEX];
		double	ODD_VALUE = VECTOR[2 * PAIR_INDEX + 1];

		VECTOR[2 * PAIR_INDEX] =
			(float)(EVEN_VALUE * COSINE - ODD_VALUE * SINE);
		VECTOR[2 * PAIR_INDEX + 1] =
			(float)(EVEN_VALUE * SINE + ODD_VALUE * COSINE);
	}
}

static void
	REFERENCE_HEAD_FORWARD(
		WEB *NEURAL_WEB, NEURON *HEAD_NEURON, int FIRST_POSITION,
		int POSITION_COUNT
	)
{
	int		MODEL_WIDTH = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int		HEAD_WIDTH = NEURAL_WEB->CONFIGURATION.HEAD_DIMENSION;
	int		AREA_INDEX = HEAD_NEURON->AREA_INDEX;
	int		MAX_POSITIONS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;
	float	*PARAMETERS = NEURON_PARAMETERS(NEURAL_WEB, HEAD_NEURON->ID);
	float	*QUERY_WEIGHTS = PARAMETERS;
	float	*KEY_WEIGHTS = PARAMETERS + HEAD_WIDTH * MODEL_WIDTH;
	float	*VALUE_WEIGHTS = PARAMETERS + 2 * HEAD_WIDTH * MODEL_WIDTH;
	float	*OUTPUT_WEIGHTS = PARAMETERS + 3 * HEAD_WIDTH * MODEL_WIDTH;
	float	*QUERIES =
		ACTIVATION_FLOATS(NEURAL_WEB, HEAD_NEURON->ACTIVATION_OFFSET);
	float	*KEYS = QUERIES + MAX_POSITIONS * HEAD_WIDTH;
	float	*VALUES = KEYS + MAX_POSITIONS * HEAD_WIDTH;
	float	*HEAD_OUTPUTS = VALUES + MAX_POSITIONS * HEAD_WIDTH;
	float	*ATTENTION_WEIGHTS = HEAD_OUTPUTS + MAX_POSITIONS * HEAD_WIDTH;
	float	*NORMALIZED_INPUT =
		ACTIVATION_FLOATS(NEURAL_WEB, LAYER_NORMALIZED(NEURAL_WEB, AREA_INDEX));
	float	*RESIDUAL = ACTIVATION_FLOATS(
		NEURAL_WEB, LAYER_RESIDUAL(NEURAL_WEB, AREA_INDEX + 1)
	);
	int		POSITION;

	for (POSITION = FIRST_POSITION; POSITION < POSITION_COUNT; POSITION++)
	{
		int	HEAD_CHANNEL;

		for (HEAD_CHANNEL = 0; HEAD_CHANNEL < HEAD_WIDTH; HEAD_CHANNEL++)
		{
			QUERIES[POSITION * HEAD_WIDTH + HEAD_CHANNEL] = FLOAT_DOT(
				QUERY_WEIGHTS + HEAD_CHANNEL * MODEL_WIDTH,
				NORMALIZED_INPUT + POSITION * MODEL_WIDTH, MODEL_WIDTH
			);
			KEYS[POSITION * HEAD_WIDTH + HEAD_CHANNEL] = FLOAT_DOT(
				KEY_WEIGHTS + HEAD_CHANNEL * MODEL_WIDTH,
				NORMALIZED_INPUT + POSITION * MODEL_WIDTH, MODEL_WIDTH
			);
			VALUES[POSITION * HEAD_WIDTH + HEAD_CHANNEL] = FLOAT_DOT(
				VALUE_WEIGHTS + HEAD_CHANNEL * MODEL_WIDTH,
				NORMALIZED_INPUT + POSITION * MODEL_WIDTH, MODEL_WIDTH
			);
		}

		if (HEAD_NEURON->KIND_DETAIL == 1)
		{
			ROTATE_PAIRS(
				QUERIES + POSITION * HEAD_WIDTH, POSITION, HEAD_WIDTH, 0
			);
			ROTATE_PAIRS(KEYS + POSITION * HEAD_WIDTH, POSITION, HEAD_WIDTH, 0);
		}

		float	MAXIMUM_SCORE = -(float)1e30;
		float	SCORE_SUM = 0;
		int		PAST_POSITION;

		for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
		{
			float	SCORE = FLOAT_DOT(
				QUERIES + POSITION * HEAD_WIDTH,
				KEYS + PAST_POSITION * HEAD_WIDTH, HEAD_WIDTH
				) *
				NEURAL_WEB->KERNEL_STATE->ATTENTION_SCALE;

			ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] = SCORE;

			if (SCORE > MAXIMUM_SCORE)
				MAXIMUM_SCORE = SCORE;
		}

		for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
		{
			ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] = expf(
				ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] -
				MAXIMUM_SCORE
			);
			SCORE_SUM +=
				ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION];
		}

		for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
			ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] /=
				SCORE_SUM;

		for (HEAD_CHANNEL = 0; HEAD_CHANNEL < HEAD_WIDTH; HEAD_CHANNEL++)
		{
			double	OUTPUT_SUM = 0;
			int		PAST_POSITION;

			for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
				OUTPUT_SUM += ATTENTION_WEIGHTS
			[POSITION * MAX_POSITIONS + PAST_POSITION] *
					VALUES[PAST_POSITION * HEAD_WIDTH + HEAD_CHANNEL];

			HEAD_OUTPUTS[POSITION * HEAD_WIDTH + HEAD_CHANNEL] =
				(float)OUTPUT_SUM;
		}

		int	MODEL_CHANNEL;

		for (MODEL_CHANNEL = 0; MODEL_CHANNEL < MODEL_WIDTH; MODEL_CHANNEL++)
		{
			double	RESIDUAL_SUM =
				RESIDUAL[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
			int		HEAD_CHANNEL;

			for (HEAD_CHANNEL = 0; HEAD_CHANNEL < HEAD_WIDTH; HEAD_CHANNEL++)
				RESIDUAL_SUM +=
					HEAD_OUTPUTS[POSITION * HEAD_WIDTH + HEAD_CHANNEL] *
					OUTPUT_WEIGHTS[HEAD_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL];

			RESIDUAL[POSITION * MODEL_WIDTH + MODEL_CHANNEL] =
				(float)RESIDUAL_SUM;
		}
	}
}

static void
	REFERENCE_HEAD_BACKWARD(
		WEB *NEURAL_WEB, NEURON *HEAD_NEURON, int POSITION_COUNT
	)
{
	int				MODEL_WIDTH = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int				HEAD_WIDTH = NEURAL_WEB->CONFIGURATION.HEAD_DIMENSION;
	int				AREA_INDEX = HEAD_NEURON->AREA_INDEX;
	int				MAX_POSITIONS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;
	float			*PARAMETERS =
		NEURON_PARAMETERS(NEURAL_WEB, HEAD_NEURON->ID);
	float			*GRADIENTS = NEURON_GRADIENTS(NEURAL_WEB, HEAD_NEURON->ID);
	float			*QUERY_WEIGHTS = PARAMETERS;
	float			*KEY_WEIGHTS = PARAMETERS + HEAD_WIDTH * MODEL_WIDTH;
	float			*VALUE_WEIGHTS = PARAMETERS + 2 * HEAD_WIDTH * MODEL_WIDTH;
	float			*OUTPUT_WEIGHTS = PARAMETERS + 3 * HEAD_WIDTH * MODEL_WIDTH;
	float			*QUERY_WEIGHT_GRADIENT = GRADIENTS;
	float			*KEY_WEIGHT_GRADIENT = GRADIENTS + HEAD_WIDTH * MODEL_WIDTH;
	float			*VALUE_WEIGHT_GRADIENT =
		GRADIENTS + 2 * HEAD_WIDTH * MODEL_WIDTH;
	float			*OUTPUT_WEIGHT_GRADIENT =
		GRADIENTS + 3 * HEAD_WIDTH * MODEL_WIDTH;
	float			*QUERIES =
		ACTIVATION_FLOATS(NEURAL_WEB, HEAD_NEURON->ACTIVATION_OFFSET);
	float			*KEYS = QUERIES + MAX_POSITIONS * HEAD_WIDTH;
	float			*VALUES = KEYS + MAX_POSITIONS * HEAD_WIDTH;
	float			*HEAD_OUTPUTS = VALUES + MAX_POSITIONS * HEAD_WIDTH;
	float			*ATTENTION_WEIGHTS =
		HEAD_OUTPUTS + MAX_POSITIONS * HEAD_WIDTH;
	float			*NORMALIZED_INPUT =
		ACTIVATION_FLOATS(NEURAL_WEB, LAYER_NORMALIZED(NEURAL_WEB, AREA_INDEX));
	float			*INPUT_GRADIENT = ACTIVATION_FLOATS(
		NEURAL_WEB, LAYER_NORMALIZED_GRADIENT(NEURAL_WEB, AREA_INDEX)
	);
	float			*RESIDUAL_GRADIENT = ACTIVATION_FLOATS(
		NEURAL_WEB, LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, AREA_INDEX + 1)
	);
	static float	QUERY_GRADIENT[1 << 16];
	static float	KEY_GRADIENT[1 << 16];
	static float	VALUE_GRADIENT[1 << 16];
	static float	HEAD_OUTPUT_GRADIENT[1 << 16];
	static float	ATTENTION_GRADIENT[1 << 12];

	memset(KEY_GRADIENT, 0, POSITION_COUNT * HEAD_WIDTH * 4);
	memset(VALUE_GRADIENT, 0, POSITION_COUNT * HEAD_WIDTH * 4);

	int	POSITION;

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
	{
		int	HEAD_CHANNEL;

		for (HEAD_CHANNEL = 0; HEAD_CHANNEL < HEAD_WIDTH; HEAD_CHANNEL++)
		{
			HEAD_OUTPUT_GRADIENT[POSITION * HEAD_WIDTH + HEAD_CHANNEL] =
				FLOAT_DOT(
					RESIDUAL_GRADIENT + POSITION * MODEL_WIDTH,
					OUTPUT_WEIGHTS + HEAD_CHANNEL * MODEL_WIDTH, MODEL_WIDTH
				);

			int	MODEL_CHANNEL;

			for (
				MODEL_CHANNEL = 0;
				MODEL_CHANNEL < MODEL_WIDTH;
				MODEL_CHANNEL++
			)
				OUTPUT_WEIGHT_GRADIENT
					[HEAD_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL] +=
					HEAD_OUTPUTS[POSITION * HEAD_WIDTH + HEAD_CHANNEL] *
					RESIDUAL_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
		}
	}

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
	{
		int	PAST_POSITION;

		for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
		{
			ATTENTION_GRADIENT[PAST_POSITION] = FLOAT_DOT(
				HEAD_OUTPUT_GRADIENT + POSITION * HEAD_WIDTH,
				VALUES + PAST_POSITION * HEAD_WIDTH, HEAD_WIDTH
			);

			int	HEAD_CHANNEL;

			for (HEAD_CHANNEL = 0; HEAD_CHANNEL < HEAD_WIDTH; HEAD_CHANNEL++)
				VALUE_GRADIENT[PAST_POSITION * HEAD_WIDTH + HEAD_CHANNEL] +=
					ATTENTION_WEIGHTS
						[POSITION * MAX_POSITIONS + PAST_POSITION] *
					HEAD_OUTPUT_GRADIENT[POSITION * HEAD_WIDTH + HEAD_CHANNEL];
		}

		double	WEIGHTED_GRADIENT_SUM = 0;

		for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
			WEIGHTED_GRADIENT_SUM +=
				ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] *
				ATTENTION_GRADIENT[PAST_POSITION];

		int	HEAD_CHANNEL;

		for (HEAD_CHANNEL = 0; HEAD_CHANNEL < HEAD_WIDTH; HEAD_CHANNEL++)
			QUERY_GRADIENT[POSITION * HEAD_WIDTH + HEAD_CHANNEL] = 0;

		for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
		{
			float	SCORE_GRADIENT = (ATTENTION_GRADIENT[PAST_POSITION] -
									(float)WEIGHTED_GRADIENT_SUM) *
				ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] *
				NEURAL_WEB->KERNEL_STATE->ATTENTION_SCALE;
			int		HEAD_CHANNEL;

			for (HEAD_CHANNEL = 0; HEAD_CHANNEL < HEAD_WIDTH; HEAD_CHANNEL++)
			{
				QUERY_GRADIENT[POSITION * HEAD_WIDTH + HEAD_CHANNEL] +=
					SCORE_GRADIENT *
					KEYS[PAST_POSITION * HEAD_WIDTH + HEAD_CHANNEL];
				KEY_GRADIENT[PAST_POSITION * HEAD_WIDTH + HEAD_CHANNEL] +=
					SCORE_GRADIENT *
					QUERIES[POSITION * HEAD_WIDTH + HEAD_CHANNEL];
			}
		}
	}

	if (HEAD_NEURON->KIND_DETAIL == 1)
	{
		int	POSITION;

		for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
		{
			ROTATE_PAIRS(
				QUERY_GRADIENT + POSITION * HEAD_WIDTH, POSITION, HEAD_WIDTH, 1
			);
			ROTATE_PAIRS(
				KEY_GRADIENT + POSITION * HEAD_WIDTH, POSITION, HEAD_WIDTH, 1
			);
		}
	}

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
	{
		int	HEAD_CHANNEL;

		for (HEAD_CHANNEL = 0; HEAD_CHANNEL < HEAD_WIDTH; HEAD_CHANNEL++)
		{
			int	MODEL_CHANNEL;

			for (
				MODEL_CHANNEL = 0;
				MODEL_CHANNEL < MODEL_WIDTH;
				MODEL_CHANNEL++
			)
			{
				float	INPUT_VALUE =
					NORMALIZED_INPUT[POSITION * MODEL_WIDTH + MODEL_CHANNEL];

				QUERY_WEIGHT_GRADIENT
					[HEAD_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL] +=
					QUERY_GRADIENT[POSITION * HEAD_WIDTH + HEAD_CHANNEL] *
					INPUT_VALUE;
				KEY_WEIGHT_GRADIENT
					[HEAD_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL] +=
					KEY_GRADIENT[POSITION * HEAD_WIDTH + HEAD_CHANNEL] *
					INPUT_VALUE;
				VALUE_WEIGHT_GRADIENT
					[HEAD_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL] +=
					VALUE_GRADIENT[POSITION * HEAD_WIDTH + HEAD_CHANNEL] *
					INPUT_VALUE;
				INPUT_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL] +=
					QUERY_GRADIENT[POSITION * HEAD_WIDTH + HEAD_CHANNEL] *
						QUERY_WEIGHTS
							[HEAD_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL] +
					KEY_GRADIENT[POSITION * HEAD_WIDTH + HEAD_CHANNEL] *
						KEY_WEIGHTS
							[HEAD_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL] +
					VALUE_GRADIENT[POSITION * HEAD_WIDTH + HEAD_CHANNEL] *
						VALUE_WEIGHTS
							[HEAD_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL];
			}
		}
	}
}

static void
	REFERENCE_COPY_FORWARD(
		WEB *NEURAL_WEB, int FIRST_POSITION, int POSITION_COUNT
	)
{
	NEURON	*COPY_HEAD_NEURON = &NEURAL_WEB->NEURONS[NEURAL_WEB->COPY_ID];
	int		MODEL_WIDTH = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int		COPY_WIDTH = NEURAL_WEB->CONFIGURATION.HEAD_DIMENSION;
	int		MAX_POSITIONS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;
	int64_t	COPY_OFFSETS[10];

	COPY_HEAD_OFFSETS(NEURAL_WEB, COPY_OFFSETS);

	float	*PARAMETERS = NEURON_PARAMETERS(NEURAL_WEB, COPY_HEAD_NEURON->ID);
	float	*QUERY_WEIGHTS = PARAMETERS;
	float	*KEY_WEIGHTS = PARAMETERS + COPY_WIDTH * MODEL_WIDTH;
	float	*GATE_WEIGHTS = PARAMETERS + 2 * COPY_WIDTH * MODEL_WIDTH;
	float	GATE_BIAS = PARAMETERS[2 * COPY_WIDTH * MODEL_WIDTH + MODEL_WIDTH];
	float	*QUERIES = ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[0]);
	float	*KEYS = ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[1]);
	float	*ATTENTION_WEIGHTS = ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[2]);
	float	*GATE_VALUES = ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[3]);
	float	*NORMALIZED_INPUT = ACTIVATION_FLOATS(
		NEURAL_WEB,
		LAYER_NORMALIZED(NEURAL_WEB, 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT)
	);
	int		POSITION;

	for (POSITION = FIRST_POSITION; POSITION < POSITION_COUNT; POSITION++)
	{
		int	COPY_CHANNEL;

		for (COPY_CHANNEL = 0; COPY_CHANNEL < COPY_WIDTH; COPY_CHANNEL++)
		{
			QUERIES[POSITION * COPY_WIDTH + COPY_CHANNEL] = FLOAT_DOT(
				QUERY_WEIGHTS + COPY_CHANNEL * MODEL_WIDTH,
				NORMALIZED_INPUT + POSITION * MODEL_WIDTH, MODEL_WIDTH
			);
			KEYS[POSITION * COPY_WIDTH + COPY_CHANNEL] = FLOAT_DOT(
				KEY_WEIGHTS + COPY_CHANNEL * MODEL_WIDTH,
				NORMALIZED_INPUT + POSITION * MODEL_WIDTH, MODEL_WIDTH
			);
		}

		float	MAXIMUM_SCORE = -(float)1e30;
		float	SCORE_SUM = 0;
		int		PAST_POSITION;

		for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
		{
			float	LOGIT = FLOAT_DOT(
				QUERIES + POSITION * COPY_WIDTH,
				KEYS + PAST_POSITION * COPY_WIDTH, COPY_WIDTH
				) *
				NEURAL_WEB->KERNEL_STATE->ATTENTION_SCALE;

			ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] = LOGIT;

			if (LOGIT > MAXIMUM_SCORE)
				MAXIMUM_SCORE = LOGIT;
		}

		for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
		{
			ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] = expf(
				ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] -
				MAXIMUM_SCORE
			);
			SCORE_SUM +=
				ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION];
		}

		for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
			ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] /=
				SCORE_SUM;

		float	LOGIT = FLOAT_DOT(
			GATE_WEIGHTS,
			NORMALIZED_INPUT + POSITION * MODEL_WIDTH, MODEL_WIDTH
			) +
			GATE_BIAS;

		GATE_VALUES[POSITION] = (float)1.0 / ((float)1.0 + expf(-LOGIT));
	}
}

static void
	REFERENCE_COPY_BACKWARD(WEB *NEURAL_WEB, int POSITION_COUNT)
{
	NEURON	*COPY_HEAD_NEURON = &NEURAL_WEB->NEURONS[NEURAL_WEB->COPY_ID];
	int		MODEL_WIDTH = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int		COPY_WIDTH = NEURAL_WEB->CONFIGURATION.HEAD_DIMENSION;
	int		MAX_POSITIONS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;
	int64_t	COPY_OFFSETS[10];

	COPY_HEAD_OFFSETS(NEURAL_WEB, COPY_OFFSETS);

	float			*PARAMETERS =
		NEURON_PARAMETERS(NEURAL_WEB, COPY_HEAD_NEURON->ID);
	float			*GRADIENTS =
		NEURON_GRADIENTS(NEURAL_WEB, COPY_HEAD_NEURON->ID);
	float			*QUERY_WEIGHTS = PARAMETERS;
	float			*KEY_WEIGHTS = PARAMETERS + COPY_WIDTH * MODEL_WIDTH;
	float			*GATE_WEIGHTS = PARAMETERS + 2 * COPY_WIDTH * MODEL_WIDTH;
	float			*QUERY_WEIGHT_GRADIENT = GRADIENTS;
	float			*KEY_WEIGHT_GRADIENT = GRADIENTS + COPY_WIDTH * MODEL_WIDTH;
	float			*GATE_WEIGHT_GRADIENT =
		GRADIENTS + 2 * COPY_WIDTH * MODEL_WIDTH;
	float			*QUERIES = ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[0]);
	float			*KEYS = ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[1]);
	float			*ATTENTION_WEIGHTS =
		ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[2]);
	float			*COPY_MASS = ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[4]);
	float			*GATE_LOGIT_GRADIENT =
		ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[8]);
	float			*COPY_SCALE =
		ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[9]);
	float			*NORMALIZED_INPUT = ACTIVATION_FLOATS(
		NEURAL_WEB,
		LAYER_NORMALIZED(NEURAL_WEB, 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT)
	);
	float			*INPUT_GRADIENT = ACTIVATION_FLOATS(
		NEURAL_WEB,
		LAYER_NORMALIZED_GRADIENT(
			NEURAL_WEB, 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT
		)
	);
	static float	QUERY_GRADIENT[1 << 16];
	static float	KEY_GRADIENT[1 << 16];
	int32_t			*TOKENS =
		ACTIVATION_INTEGERS(NEURAL_WEB, NEURAL_WEB->TOKENS_OFFSET);
	int32_t			*TARGETS =
		ACTIVATION_INTEGERS(NEURAL_WEB, NEURAL_WEB->TARGETS_OFFSET);

	memset(KEY_GRADIENT, 0, POSITION_COUNT * COPY_WIDTH * 4);

	int	POSITION;

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
	{
		float	EXPECTED_GRADIENT = COPY_SCALE[POSITION] * COPY_MASS[POSITION];
		int		COPY_CHANNEL;

		for (COPY_CHANNEL = 0; COPY_CHANNEL < COPY_WIDTH; COPY_CHANNEL++)
			QUERY_GRADIENT[POSITION * COPY_WIDTH + COPY_CHANNEL] = 0;

		int	PAST_POSITION;

		for (PAST_POSITION = 0; PAST_POSITION <= POSITION; PAST_POSITION++)
		{
			float	ATTENTION_DELTA;

			if (TOKENS[PAST_POSITION] == TARGETS[POSITION])
				ATTENTION_DELTA = COPY_SCALE[POSITION];
			else
				ATTENTION_DELTA = 0;

			float	SCORE_GRADIENT = (ATTENTION_DELTA - EXPECTED_GRADIENT) *
				ATTENTION_WEIGHTS[POSITION * MAX_POSITIONS + PAST_POSITION] *
				NEURAL_WEB->KERNEL_STATE->ATTENTION_SCALE;
			int		COPY_CHANNEL;

			for (COPY_CHANNEL = 0; COPY_CHANNEL < COPY_WIDTH; COPY_CHANNEL++)
			{
				QUERY_GRADIENT[POSITION * COPY_WIDTH + COPY_CHANNEL] +=
					SCORE_GRADIENT *
					KEYS[PAST_POSITION * COPY_WIDTH + COPY_CHANNEL];
				KEY_GRADIENT[PAST_POSITION * COPY_WIDTH + COPY_CHANNEL] +=
					SCORE_GRADIENT *
					QUERIES[POSITION * COPY_WIDTH + COPY_CHANNEL];
			}
		}
	}

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
	{
		int	COPY_CHANNEL;

		for (COPY_CHANNEL = 0; COPY_CHANNEL < COPY_WIDTH; COPY_CHANNEL++)
		{
			int	MODEL_CHANNEL;

			for (
				MODEL_CHANNEL = 0;
				MODEL_CHANNEL < MODEL_WIDTH;
				MODEL_CHANNEL++
			)
			{
				QUERY_WEIGHT_GRADIENT
					[COPY_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL] +=
					QUERY_GRADIENT[POSITION * COPY_WIDTH + COPY_CHANNEL] *
					NORMALIZED_INPUT[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
				KEY_WEIGHT_GRADIENT
					[COPY_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL] +=
					KEY_GRADIENT[POSITION * COPY_WIDTH + COPY_CHANNEL] *
					NORMALIZED_INPUT[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
				INPUT_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL] +=
					QUERY_GRADIENT[POSITION * COPY_WIDTH + COPY_CHANNEL] *
						QUERY_WEIGHTS
							[COPY_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL] +
					KEY_GRADIENT[POSITION * COPY_WIDTH + COPY_CHANNEL] *
						KEY_WEIGHTS[COPY_CHANNEL * MODEL_WIDTH + MODEL_CHANNEL];
			}
		}

		int	MODEL_CHANNEL;

		for (MODEL_CHANNEL = 0; MODEL_CHANNEL < MODEL_WIDTH; MODEL_CHANNEL++)
		{
			GATE_WEIGHT_GRADIENT[MODEL_CHANNEL] +=
				GATE_LOGIT_GRADIENT[POSITION] *
				NORMALIZED_INPUT[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
			INPUT_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL] +=
				GATE_LOGIT_GRADIENT[POSITION] * GATE_WEIGHTS[MODEL_CHANNEL];
		}

		GATE_WEIGHT_GRADIENT[MODEL_WIDTH] += GATE_LOGIT_GRADIENT[POSITION];
	}
}

void
	REFERENCE_FORWARD(WEB *NEURAL_WEB, int IS_TRAINING)
{
	KERNEL_CONTEXT	*KERNEL_STATE = NEURAL_WEB->KERNEL_STATE;
	int				MODEL_WIDTH = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int				LAST_AREA_INDEX = 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT;
	int				POSITION_COUNT = (int)KERNEL_STATE->SEQUENCE_LENGTH;
	int				FIRST_POSITION = (int)KERNEL_STATE->START_POSITION;
	int				MAX_POSITIONS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;
	int				VOCABULARY_SIZE = NEURAL_WEB->WORD_COUNT;
	int32_t			*TOKENS =
		ACTIVATION_INTEGERS(NEURAL_WEB, NEURAL_WEB->TOKENS_OFFSET);
	float			*POSITION_EMBEDDINGS =
		NEURON_PARAMETERS(NEURAL_WEB, NEURAL_WEB->EMBEDDING_ID);
	float			*INPUT_RESIDUAL =
		ACTIVATION_FLOATS(NEURAL_WEB, LAYER_RESIDUAL(NEURAL_WEB, 0));
	int				POSITION;

	for (POSITION = FIRST_POSITION; POSITION < POSITION_COUNT; POSITION++)
	{
		float	*WORD_EMBEDDING = NEURON_PARAMETERS(
			NEURAL_WEB, NEURAL_WEB->WORD_NEURONS[TOKENS[POSITION]]
		);
		int		MODEL_CHANNEL;

		for (MODEL_CHANNEL = 0; MODEL_CHANNEL < MODEL_WIDTH; MODEL_CHANNEL++)
			INPUT_RESIDUAL[POSITION * MODEL_WIDTH + MODEL_CHANNEL] =
				WORD_EMBEDDING[MODEL_CHANNEL] +
				POSITION_EMBEDDINGS[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
	}

	int	AREA_INDEX;

	for (AREA_INDEX = 0; AREA_INDEX <= LAST_AREA_INDEX; AREA_INDEX++)
	{
		float	*RESIDUAL = ACTIVATION_FLOATS(
			NEURAL_WEB, LAYER_RESIDUAL(NEURAL_WEB, AREA_INDEX)
		);
		float	*NORMALIZED_INPUT = ACTIVATION_FLOATS(
			NEURAL_WEB, LAYER_NORMALIZED(NEURAL_WEB, AREA_INDEX)
		);
		float	*INPUT_GRADIENT = ACTIVATION_FLOATS(
			NEURAL_WEB, LAYER_NORMALIZED_GRADIENT(NEURAL_WEB, AREA_INDEX)
		);
		float	*NORM_GAINS =
			NEURON_PARAMETERS(NEURAL_WEB, NEURAL_WEB->NORM_IDS[AREA_INDEX]);
		float	*NEXT_RESIDUAL;

		if (AREA_INDEX < LAST_AREA_INDEX)
			NEXT_RESIDUAL = ACTIVATION_FLOATS(
				NEURAL_WEB, LAYER_RESIDUAL(NEURAL_WEB, AREA_INDEX + 1)
			);
		else
			NEXT_RESIDUAL = NULL;

		float	*INVERSE_NORMS = ACTIVATION_FLOATS(
			NEURAL_WEB,
			NEURAL_WEB->INVERSE_NORM_OFFSET +
				(int64_t)AREA_INDEX * MAX_POSITIONS * 4
		);
		int		POSITION;

		for (POSITION = FIRST_POSITION; POSITION < POSITION_COUNT; POSITION++)
		{
			float	SQUARE_SUM = FLOAT_DOT(
				RESIDUAL + POSITION * MODEL_WIDTH,
				RESIDUAL + POSITION * MODEL_WIDTH, MODEL_WIDTH
			);
			float	INVERSE_NORM = (float)1.0 /
				sqrtf(SQUARE_SUM * KERNEL_STATE->INVERSE_DIMENSION +
					KERNEL_STATE->NORM_EPSILON);

			INVERSE_NORMS[POSITION] = INVERSE_NORM;

			int	MODEL_CHANNEL;

			for (
				MODEL_CHANNEL = 0;
				MODEL_CHANNEL < MODEL_WIDTH;
				MODEL_CHANNEL++
			)
			{
				if (NEXT_RESIDUAL)
					NEXT_RESIDUAL[POSITION * MODEL_WIDTH + MODEL_CHANNEL] =
						RESIDUAL[POSITION * MODEL_WIDTH + MODEL_CHANNEL];

				NORMALIZED_INPUT[POSITION * MODEL_WIDTH + MODEL_CHANNEL] =
					RESIDUAL[POSITION * MODEL_WIDTH + MODEL_CHANNEL] *
					INVERSE_NORM * NORM_GAINS[MODEL_CHANNEL];
				INPUT_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL] = 0;
			}
		}

		AREA	*CURRENT_AREA = &NEURAL_WEB->AREAS[AREA_INDEX];
		int		NEURON_SLOT;

		for (
			NEURON_SLOT = 0;
			NEURON_SLOT < CURRENT_AREA->MEMBER_COUNT;
			NEURON_SLOT++
		)
		{
			NEURON	*CURRENT_NEURON =
				&NEURAL_WEB->NEURONS[CURRENT_AREA->MEMBERS[NEURON_SLOT]];

			if (!CURRENT_NEURON->ALIVE)
				continue ;

			if (CURRENT_NEURON->KIND == KIND_FEED_FORWARD)
			{
				float	*PARAMETERS =
					NEURON_PARAMETERS(NEURAL_WEB, CURRENT_NEURON->ID);
				float	*ACTIVATIONS = ACTIVATION_FLOATS(
					NEURAL_WEB, CURRENT_NEURON->ACTIVATION_OFFSET
				);
				int		POSITION;

				for (
					POSITION = FIRST_POSITION;
					POSITION < POSITION_COUNT;
					POSITION++
				)
				{
					float	ACTIVATION =
						FLOAT_DOT(
							PARAMETERS,
							NORMALIZED_INPUT + POSITION * MODEL_WIDTH,
							MODEL_WIDTH
						) +
						PARAMETERS[2 * MODEL_WIDTH];

					ACTIVATIONS[POSITION] = ACTIVATION;

					if (ACTIVATION > 0)
					{
						int	MODEL_CHANNEL;

						for (
							MODEL_CHANNEL = 0;
							MODEL_CHANNEL < MODEL_WIDTH;
							MODEL_CHANNEL++
						)
							NEXT_RESIDUAL
								[POSITION * MODEL_WIDTH + MODEL_CHANNEL] +=
								ACTIVATION *
								PARAMETERS[MODEL_WIDTH + MODEL_CHANNEL];
					}
				}
			}
			else if (CURRENT_NEURON->KIND == KIND_ATTENTION_HEAD)
				REFERENCE_HEAD_FORWARD(
					NEURAL_WEB, CURRENT_NEURON, FIRST_POSITION, POSITION_COUNT
				);
			else if (CURRENT_NEURON->KIND == KIND_RECIPE)
				RECIPE_REFERENCE_FORWARD(
					&NEURAL_WEB->RECIPES[CURRENT_NEURON->KIND_DETAIL],
					NEURON_PARAMETERS(NEURAL_WEB, CURRENT_NEURON->ID),
					NORMALIZED_INPUT, NEXT_RESIDUAL,
					ACTIVATION_FLOATS(
						NEURAL_WEB, CURRENT_NEURON->ACTIVATION_OFFSET
					),
					FIRST_POSITION, POSITION_COUNT
				);
			else if (CURRENT_NEURON->KIND == KIND_TREE)
			{
				float	*PARAMETERS =
					NEURON_PARAMETERS(NEURAL_WEB, CURRENT_NEURON->ID);
				float	*NODE_ACTIVATIONS = ACTIVATION_FLOATS(
					NEURAL_WEB,
					CURRENT_NEURON->ACTIVATION_OFFSET +
						(int64_t)MAX_POSITIONS *
							(CURRENT_NEURON->KIND_DETAIL + 1) * 4
				);
				int32_t	*NODE_IDS = ACTIVATION_INTEGERS(
					NEURAL_WEB, CURRENT_NEURON->ACTIVATION_OFFSET
				);
				int		LEVEL_COUNT = CURRENT_NEURON->KIND_DETAIL + 1;
				int		NODE_STRIDE = 2 * MODEL_WIDTH + 8;
				int		POSITION;

				for (
					POSITION = FIRST_POSITION;
					POSITION < POSITION_COUNT;
					POSITION++
				)
				{
					int64_t	NODE_INDEX = 0;
					int		LEVEL;

					for (LEVEL = 0; LEVEL < LEVEL_COUNT; LEVEL++)
					{
						float	*NODE_PARAMETERS =
							PARAMETERS + NODE_INDEX * NODE_STRIDE;
						float	ACTIVATION =
							FLOAT_DOT(
								NODE_PARAMETERS,
								NORMALIZED_INPUT + POSITION * MODEL_WIDTH,
								MODEL_WIDTH
							) +
							NODE_PARAMETERS[2 * MODEL_WIDTH];
						float	LEAKY_ACTIVATION;

						if (ACTIVATION > 0)
							LEAKY_ACTIVATION = ACTIVATION;
						else
							LEAKY_ACTIVATION = TREE_LEAK_SLOPE * ACTIVATION;

						if (LEAKY_ACTIVATION < TREE_LEAK_SLOPE * ACTIVATION)
							LEAKY_ACTIVATION = TREE_LEAK_SLOPE * ACTIVATION;

						NODE_IDS[POSITION * LEVEL_COUNT + LEVEL] =
							(int32_t)NODE_INDEX;
						NODE_ACTIVATIONS[POSITION * LEVEL_COUNT + LEVEL] =
							ACTIVATION;

						int	MODEL_CHANNEL;

						for (
							MODEL_CHANNEL = 0;
							MODEL_CHANNEL < MODEL_WIDTH;
							MODEL_CHANNEL++
						)
							NEXT_RESIDUAL
								[POSITION * MODEL_WIDTH + MODEL_CHANNEL] +=
								LEAKY_ACTIVATION *
								NODE_PARAMETERS[MODEL_WIDTH + MODEL_CHANNEL];

						NODE_INDEX = 2 * NODE_INDEX + 1 + (ACTIVATION > 0);
					}
				}
			}
			else if (CURRENT_NEURON->KIND == KIND_WORD)
			{
				float	*PARAMETERS =
					NEURON_PARAMETERS(NEURAL_WEB, CURRENT_NEURON->ID);
				float	*LOGITS = ACTIVATION_FLOATS(
					NEURAL_WEB,
					(int64_t)LOGITS_OFFSET +
						(int64_t)CURRENT_NEURON->KIND_DETAIL * MAX_POSITIONS * 4
				);
				int		POSITION;

				for (
					POSITION = FIRST_POSITION;
					POSITION < POSITION_COUNT;
					POSITION++
				)
					LOGITS[POSITION] =
						FLOAT_DOT(
							PARAMETERS,
							NORMALIZED_INPUT + POSITION * MODEL_WIDTH,
							MODEL_WIDTH
						) +
						PARAMETERS[MODEL_WIDTH];
			}
		}
	}

	if (NEURAL_WEB->COPY_ID >= 0)
		REFERENCE_COPY_FORWARD(NEURAL_WEB, FIRST_POSITION, POSITION_COUNT);

	if (!IS_TRAINING)
		return ;

	int32_t	*TARGETS =
		ACTIVATION_INTEGERS(NEURAL_WEB, NEURAL_WEB->TARGETS_OFFSET);
	float	*LOSS_WEIGHTS =
		ACTIVATION_FLOATS(NEURAL_WEB, NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
	float	*TARGET_LOGITS =
		ACTIVATION_FLOATS(NEURAL_WEB, NEURAL_WEB->TARGET_LOGIT_OFFSET);
	float	*SOFTMAX_STATS =
		ACTIVATION_FLOATS(NEURAL_WEB, NEURAL_WEB->SOFTMAX_STATISTICS_OFFSET);

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
	{
		if (TARGETS[POSITION] >= 0)
			TARGET_LOGITS[POSITION] = ACTIVATION_FLOATS(
				NEURAL_WEB,
				(int64_t)LOGITS_OFFSET +
					(int64_t)TARGETS[POSITION] * MAX_POSITIONS * 4
			)[POSITION];
		else
			TARGET_LOGITS[POSITION] = 0;

		float	MAXIMUM_LOGIT = -(float)1e30;
		double	EXPONENT_SUM = 0;
		int		VOCABULARY_INDEX;

		for (
			VOCABULARY_INDEX = 0;
			VOCABULARY_INDEX < VOCABULARY_SIZE;
			VOCABULARY_INDEX++
		)
		{
			float	LOGIT_VALUE = ACTIVATION_FLOATS(
				NEURAL_WEB,
				(int64_t)LOGITS_OFFSET +
					(int64_t)VOCABULARY_INDEX * MAX_POSITIONS * 4
			)[POSITION];

			if (LOGIT_VALUE > MAXIMUM_LOGIT)
				MAXIMUM_LOGIT = LOGIT_VALUE;
		}

		for (
			VOCABULARY_INDEX = 0;
			VOCABULARY_INDEX < VOCABULARY_SIZE;
			VOCABULARY_INDEX++
		)
		{
			float	*LOGIT_SLOT = &ACTIVATION_FLOATS(
				NEURAL_WEB,
				(int64_t)LOGITS_OFFSET +
					(int64_t)VOCABULARY_INDEX * MAX_POSITIONS * 4
			)[POSITION];

			*LOGIT_SLOT = expf(*LOGIT_SLOT - MAXIMUM_LOGIT);
			EXPONENT_SUM += *LOGIT_SLOT;
		}

		SOFTMAX_STATS[POSITION] = MAXIMUM_LOGIT;
		SOFTMAX_STATS[MAX_POSITIONS + POSITION] = (float)EXPONENT_SUM;

		float	SOFTMAX_SCALE = LOSS_WEIGHTS[POSITION] *
			KERNEL_STATE->GRADIENT_SCALE / (float)EXPONENT_SUM;
		float	TARGET_SCALE =
			LOSS_WEIGHTS[POSITION] * KERNEL_STATE->GRADIENT_SCALE;

		if (NEURAL_WEB->COPY_ID >= 0)
		{
			int64_t	COPY_OFFSETS[10];

			COPY_HEAD_OFFSETS(NEURAL_WEB, COPY_OFFSETS);

			float	*ACTIVATIONS =
				ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[2]);
			float	*GATE_VALUES =
				ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[3]);
			float	*COPY_MASS = ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[4]);
			float	*TARGET_PROBABILITIES =
				ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[5]);
			float	*GATE_LOGIT_GRADIENT =
				ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[8]);
			float	*COPY_SCALE =
				ACTIVATION_FLOATS(NEURAL_WEB, COPY_OFFSETS[9]);
			int32_t	*TOKENS =
				ACTIVATION_INTEGERS(NEURAL_WEB, NEURAL_WEB->TOKENS_OFFSET);

			COPY_MASS[POSITION] = 0;
			TARGET_PROBABILITIES[POSITION] = 1;
			GATE_LOGIT_GRADIENT[POSITION] = 0;
			COPY_SCALE[POSITION] = 0;
			SOFTMAX_SCALE = 0;
			TARGET_SCALE = 0;

			if (TARGETS[POSITION] >= 0)
			{
				float	VOCABULARY_PROBABILITY =
					expf(TARGET_LOGITS[POSITION] - MAXIMUM_LOGIT) /
					(float)EXPONENT_SUM;
				float	STEP_COPY_MASS = 0;
				int		PAST_POSITION;

				for (
					PAST_POSITION = 0;
					PAST_POSITION <= POSITION;
					PAST_POSITION++
				)
					if (TOKENS[PAST_POSITION] == TARGETS[POSITION])
						STEP_COPY_MASS += ACTIVATIONS
							[POSITION * MAX_POSITIONS + PAST_POSITION];

				float	GATE_VALUE = GATE_VALUES[POSITION];
				float	MIXED_PROBABILITY =
					(1 - GATE_VALUE) * VOCABULARY_PROBABILITY +
					GATE_VALUE * STEP_COPY_MASS;

				if (MIXED_PROBABILITY < (float)1e-30)
					MIXED_PROBABILITY = (float)1e-30;

				float	SCALED_WEIGHT =
					LOSS_WEIGHTS[POSITION] * KERNEL_STATE->GRADIENT_SCALE;

				COPY_MASS[POSITION] = STEP_COPY_MASS;
				TARGET_PROBABILITIES[POSITION] = MIXED_PROBABILITY;
				TARGET_SCALE = (1 - GATE_VALUE) * VOCABULARY_PROBABILITY /
					MIXED_PROBABILITY * SCALED_WEIGHT;
				SOFTMAX_SCALE = TARGET_SCALE / (float)EXPONENT_SUM;
				GATE_LOGIT_GRADIENT[POSITION] =
					(VOCABULARY_PROBABILITY - STEP_COPY_MASS) * GATE_VALUE *
					(1 - GATE_VALUE) / MIXED_PROBABILITY * SCALED_WEIGHT;
				COPY_SCALE[POSITION] =
					-(GATE_VALUE / MIXED_PROBABILITY) * SCALED_WEIGHT;
			}
		}

		for (
			VOCABULARY_INDEX = 0;
			VOCABULARY_INDEX < VOCABULARY_SIZE;
			VOCABULARY_INDEX++
		)
			ACTIVATION_FLOATS(
				NEURAL_WEB,
				(int64_t)LOGITS_OFFSET +
					(int64_t)VOCABULARY_INDEX * MAX_POSITIONS * 4
			)
			[POSITION] *= SOFTMAX_SCALE;

		if (TARGETS[POSITION] >= 0)
			ACTIVATION_FLOATS(
				NEURAL_WEB,
				(int64_t)LOGITS_OFFSET +
					(int64_t)TARGETS[POSITION] * MAX_POSITIONS * 4
			)
			[POSITION] -= TARGET_SCALE;
	}
}

void
	REFERENCE_BACKWARD(WEB *NEURAL_WEB)
{
	KERNEL_CONTEXT	*KERNEL_STATE = NEURAL_WEB->KERNEL_STATE;
	int				MODEL_WIDTH = NEURAL_WEB->CONFIGURATION.DIMENSION;
	int				LAST_AREA_INDEX = 2 * NEURAL_WEB->CONFIGURATION.LAYER_COUNT;
	int				POSITION_COUNT = (int)KERNEL_STATE->SEQUENCE_LENGTH;
	int				MAX_POSITIONS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;

	if (NEURAL_WEB->COPY_ID >= 0)
		REFERENCE_COPY_BACKWARD(NEURAL_WEB, POSITION_COUNT);

	int	AREA_INDEX;

	for (AREA_INDEX = LAST_AREA_INDEX; AREA_INDEX >= 0; AREA_INDEX--)
	{
		AREA	*CURRENT_AREA = &NEURAL_WEB->AREAS[AREA_INDEX];
		float	*NORMALIZED_INPUT = ACTIVATION_FLOATS(
			NEURAL_WEB, LAYER_NORMALIZED(NEURAL_WEB, AREA_INDEX)
		);
		float	*INPUT_GRADIENT = ACTIVATION_FLOATS(
			NEURAL_WEB, LAYER_NORMALIZED_GRADIENT(NEURAL_WEB, AREA_INDEX)
		);
		float	*NEXT_RESIDUAL_GRADIENT;

		if (AREA_INDEX < LAST_AREA_INDEX)
			NEXT_RESIDUAL_GRADIENT = ACTIVATION_FLOATS(
				NEURAL_WEB, LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, AREA_INDEX + 1)
			);
		else
			NEXT_RESIDUAL_GRADIENT = NULL;

		int	NEURON_SLOT;

		for (
			NEURON_SLOT = CURRENT_AREA->MEMBER_COUNT - 1;
			NEURON_SLOT >= 0;
			NEURON_SLOT--
		)
		{
			NEURON	*CURRENT_NEURON =
				&NEURAL_WEB->NEURONS[CURRENT_AREA->MEMBERS[NEURON_SLOT]];

			if (!CURRENT_NEURON->ALIVE)
				continue ;

			float	*PARAMETERS =
				NEURON_PARAMETERS(NEURAL_WEB, CURRENT_NEURON->ID);
			float	*GRADIENTS =
				NEURON_GRADIENTS(NEURAL_WEB, CURRENT_NEURON->ID);

			if (CURRENT_NEURON->KIND == KIND_WORD)
			{
				float	*LOGIT_GRADIENTS = ACTIVATION_FLOATS(
					NEURAL_WEB,
					(int64_t)LOGITS_OFFSET +
						(int64_t)CURRENT_NEURON->KIND_DETAIL * MAX_POSITIONS * 4
				);
				double	BIAS_GRADIENT = 0;
				float	*LOSS_WEIGHTS = ACTIVATION_FLOATS(
					NEURAL_WEB, NEURAL_WEB->LOSS_WEIGHTS_OFFSET
				);
				int		POSITION;

				for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
				{
					BIAS_GRADIENT += LOGIT_GRADIENTS[POSITION];

					float	THRESHOLD = LOSS_WEIGHTS[POSITION] *
						KERNEL_STATE->GRADIENT_SCALE *
						KERNEL_STATE->GRADIENT_SKIP_THRESHOLD;

					if (
						LOGIT_GRADIENTS[POSITION] * LOGIT_GRADIENTS[POSITION] <=
							THRESHOLD *THRESHOLD
					)
						continue ;

					int	MODEL_CHANNEL;

					for (
						MODEL_CHANNEL = 0;
						MODEL_CHANNEL < MODEL_WIDTH;
						MODEL_CHANNEL++
					)
						INPUT_GRADIENT
							[POSITION * MODEL_WIDTH + MODEL_CHANNEL] +=
							LOGIT_GRADIENTS[POSITION] *
							PARAMETERS[MODEL_CHANNEL];
				}

				GRADIENTS[MODEL_WIDTH] += (float)BIAS_GRADIENT;

				int	MODEL_CHANNEL;

				for (
					MODEL_CHANNEL = 0;
					MODEL_CHANNEL < MODEL_WIDTH;
					MODEL_CHANNEL++
				)
				{
					double	ACCUMULATOR = 0;
					int		POSITION;

					for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
					{
						float	THRESHOLD = LOSS_WEIGHTS[POSITION] *
							KERNEL_STATE->GRADIENT_SCALE *
							KERNEL_STATE->GRADIENT_SKIP_THRESHOLD;

						if (
							LOGIT_GRADIENTS[POSITION] *
									LOGIT_GRADIENTS[POSITION] >
								THRESHOLD *THRESHOLD
						)
							ACCUMULATOR += LOGIT_GRADIENTS[POSITION] *
								NORMALIZED_INPUT
									[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
					}

					GRADIENTS[MODEL_CHANNEL] += (float)ACCUMULATOR;
				}
			}
			else if (CURRENT_NEURON->KIND == KIND_FEED_FORWARD)
			{
				float	*ACTIVATIONS = ACTIVATION_FLOATS(
					NEURAL_WEB, CURRENT_NEURON->ACTIVATION_OFFSET
				);
				int		POSITION;

				for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
				{
					float	ACTIVATION = ACTIVATIONS[POSITION];

					if (!(ACTIVATION > 0))
						continue ;

					float	ACTIVATION_GRADIENT = FLOAT_DOT(
						NEXT_RESIDUAL_GRADIENT + POSITION * MODEL_WIDTH,
						PARAMETERS + MODEL_WIDTH, MODEL_WIDTH
					);

					GRADIENTS[2 * MODEL_WIDTH] += ACTIVATION_GRADIENT;

					int	MODEL_CHANNEL;

					for (
						MODEL_CHANNEL = 0;
						MODEL_CHANNEL < MODEL_WIDTH;
						MODEL_CHANNEL++
					)
					{
						GRADIENTS[MODEL_WIDTH + MODEL_CHANNEL] += ACTIVATION *
							NEXT_RESIDUAL_GRADIENT[POSITION * MODEL_WIDTH +
								MODEL_CHANNEL];
						GRADIENTS[MODEL_CHANNEL] += ACTIVATION_GRADIENT *
							NORMALIZED_INPUT[POSITION * MODEL_WIDTH +
								MODEL_CHANNEL];
						INPUT_GRADIENT
							[POSITION * MODEL_WIDTH + MODEL_CHANNEL] +=
							ACTIVATION_GRADIENT * PARAMETERS[MODEL_CHANNEL];
					}
				}
			}
			else if (CURRENT_NEURON->KIND == KIND_ATTENTION_HEAD)
				REFERENCE_HEAD_BACKWARD(
					NEURAL_WEB, CURRENT_NEURON, POSITION_COUNT
				);
			else if (CURRENT_NEURON->KIND == KIND_RECIPE)
				RECIPE_REFERENCE_BACKWARD(
					&NEURAL_WEB->RECIPES[CURRENT_NEURON->KIND_DETAIL],
					PARAMETERS, GRADIENTS, NORMALIZED_INPUT, INPUT_GRADIENT,
					NEXT_RESIDUAL_GRADIENT,
					ACTIVATION_FLOATS(
						NEURAL_WEB, CURRENT_NEURON->ACTIVATION_OFFSET
					),
					ACTIVATION_FLOATS(
						NEURAL_WEB,
						ACTIVATION_PLANE + CURRENT_NEURON->ACTIVATION_OFFSET
					),
					POSITION_COUNT
				);
			else if (CURRENT_NEURON->KIND == KIND_TREE)
			{
				float	*NODE_ACTIVATIONS = ACTIVATION_FLOATS(
					NEURAL_WEB,
					CURRENT_NEURON->ACTIVATION_OFFSET +
						(int64_t)MAX_POSITIONS *
							(CURRENT_NEURON->KIND_DETAIL + 1) * 4
				);
				int32_t	*NODE_IDS = ACTIVATION_INTEGERS(
					NEURAL_WEB, CURRENT_NEURON->ACTIVATION_OFFSET
				);
				int		LEVEL_COUNT = CURRENT_NEURON->KIND_DETAIL + 1;
				int		NODE_STRIDE = 2 * MODEL_WIDTH + 8;
				int		POSITION;

				for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
				{
					int	LEVEL;

					for (LEVEL = 0; LEVEL < LEVEL_COUNT; LEVEL++)
					{
						int64_t	NODE_INDEX =
							NODE_IDS[POSITION * LEVEL_COUNT + LEVEL];
						float	*NODE_PARAMETERS =
							PARAMETERS + NODE_INDEX * NODE_STRIDE;
						float	*NODE_GRADIENTS =
							GRADIENTS + NODE_INDEX * NODE_STRIDE;
						float	ACTIVATION =
							NODE_ACTIVATIONS[POSITION * LEVEL_COUNT + LEVEL];
						float	LEAKY_ACTIVATION;

						if (ACTIVATION > 0)
							LEAKY_ACTIVATION = ACTIVATION;
						else
							LEAKY_ACTIVATION = TREE_LEAK_SLOPE * ACTIVATION;

						float	OUTPUT_GRADIENT = FLOAT_DOT(
							NEXT_RESIDUAL_GRADIENT + POSITION * MODEL_WIDTH,
							NODE_PARAMETERS + MODEL_WIDTH, MODEL_WIDTH
						);
						float	ACTIVATION_GRADIENT;

						if (ACTIVATION > 0)
							ACTIVATION_GRADIENT = OUTPUT_GRADIENT;
						else
							ACTIVATION_GRADIENT =
								TREE_LEAK_SLOPE * OUTPUT_GRADIENT;

						NODE_GRADIENTS[2 * MODEL_WIDTH] += ACTIVATION_GRADIENT;

						int	MODEL_CHANNEL;

						for (
							MODEL_CHANNEL = 0;
							MODEL_CHANNEL < MODEL_WIDTH;
							MODEL_CHANNEL++
						)
						{
							NODE_GRADIENTS[MODEL_WIDTH + MODEL_CHANNEL] +=
								LEAKY_ACTIVATION *
								NEXT_RESIDUAL_GRADIENT
									[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
							NODE_GRADIENTS[MODEL_CHANNEL] +=
								ACTIVATION_GRADIENT *
								NORMALIZED_INPUT
									[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
							INPUT_GRADIENT
								[POSITION * MODEL_WIDTH + MODEL_CHANNEL] +=
								ACTIVATION_GRADIENT *
								NODE_PARAMETERS[MODEL_CHANNEL];
						}
					}
				}
			}
		}

		float	*RESIDUAL = ACTIVATION_FLOATS(
			NEURAL_WEB, LAYER_RESIDUAL(NEURAL_WEB, AREA_INDEX)
		);
		float	*RESIDUAL_GRADIENT = ACTIVATION_FLOATS(
			NEURAL_WEB, LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, AREA_INDEX)
		);
		float	*NORM_GAINS =
			NEURON_PARAMETERS(NEURAL_WEB, NEURAL_WEB->NORM_IDS[AREA_INDEX]);
		float	*NORM_GAIN_GRADIENTS =
			NEURON_GRADIENTS(NEURAL_WEB, NEURAL_WEB->NORM_IDS[AREA_INDEX]);
		float	*INVERSE_NORMS = ACTIVATION_FLOATS(
			NEURAL_WEB,
			NEURAL_WEB->INVERSE_NORM_OFFSET +
				(int64_t)AREA_INDEX * MAX_POSITIONS * 4
		);
		int		POSITION;

		for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
		{
			float	INVERSE_NORM = INVERSE_NORMS[POSITION];
			double	PROJECTION_SUM = 0;
			int		MODEL_CHANNEL;

			for (
				MODEL_CHANNEL = 0;
				MODEL_CHANNEL < MODEL_WIDTH;
				MODEL_CHANNEL++
			)
				PROJECTION_SUM +=
					(double
					)INPUT_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL] *
					NORM_GAINS[MODEL_CHANNEL] *
					RESIDUAL[POSITION * MODEL_WIDTH + MODEL_CHANNEL];

			float	CORRECTION_FACTOR = INVERSE_NORM * INVERSE_NORM *
				INVERSE_NORM * (float)PROJECTION_SUM *
				KERNEL_STATE->INVERSE_DIMENSION;

			for (
				MODEL_CHANNEL = 0;
				MODEL_CHANNEL < MODEL_WIDTH;
				MODEL_CHANNEL++
			)
			{
				NORM_GAIN_GRADIENTS[MODEL_CHANNEL] +=
					INPUT_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL] *
					RESIDUAL[POSITION * MODEL_WIDTH + MODEL_CHANNEL] *
					INVERSE_NORM;

				float	RESIDUAL_DELTA =
					INPUT_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL] *
						NORM_GAINS[MODEL_CHANNEL] * INVERSE_NORM -
					RESIDUAL[POSITION * MODEL_WIDTH + MODEL_CHANNEL] *
						CORRECTION_FACTOR;

				if (NEXT_RESIDUAL_GRADIENT)
					RESIDUAL_DELTA += NEXT_RESIDUAL_GRADIENT
						[POSITION * MODEL_WIDTH + MODEL_CHANNEL];

				RESIDUAL_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL] =
					RESIDUAL_DELTA;
			}
		}
	}

	int32_t	*TOKENS =
		ACTIVATION_INTEGERS(NEURAL_WEB, NEURAL_WEB->TOKENS_OFFSET);
	float	*POSITION_GRADIENTS =
		NEURON_GRADIENTS(NEURAL_WEB, NEURAL_WEB->EMBEDDING_ID);
	float	*INPUT_RESIDUAL_GRADIENT =
		ACTIVATION_FLOATS(NEURAL_WEB, LAYER_RESIDUAL_GRADIENT(NEURAL_WEB, 0));
	int		POSITION;

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
	{
		float	*WORD_EMBEDDING_GRADIENT = NEURON_GRADIENTS(
			NEURAL_WEB, NEURAL_WEB->WORD_NEURONS[TOKENS[POSITION]]
		);
		int		MODEL_CHANNEL;

		for (MODEL_CHANNEL = 0; MODEL_CHANNEL < MODEL_WIDTH; MODEL_CHANNEL++)
		{
			WORD_EMBEDDING_GRADIENT[MODEL_CHANNEL] +=
				INPUT_RESIDUAL_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
			POSITION_GRADIENTS[POSITION * MODEL_WIDTH + MODEL_CHANNEL] +=
				INPUT_RESIDUAL_GRADIENT[POSITION * MODEL_WIDTH + MODEL_CHANNEL];
		}
	}
}

static void
	REFERENCE_ADAM(WEB *NEURAL_WEB, NEURON *TARGET_NEURON)
{
	KERNEL_CONTEXT	*KERNEL_STATE = NEURAL_WEB->KERNEL_STATE;
	float			*PARAMETERS =
		NEURON_PARAMETERS(NEURAL_WEB, TARGET_NEURON->ID);
	float			*GRADIENTS =
		NEURON_GRADIENTS(NEURAL_WEB, TARGET_NEURON->ID);
	float			*FIRST_MOMENTS =
		NEURON_MOMENTS(NEURAL_WEB, TARGET_NEURON->ID, 0);
	float			*SECOND_MOMENTS =
		NEURON_MOMENTS(NEURAL_WEB, TARGET_NEURON->ID, 1);
	int64_t			PARAMETER_INDEX;

	for (
		PARAMETER_INDEX = 0;
		PARAMETER_INDEX < TARGET_NEURON->PARAMETER_COUNT;
		PARAMETER_INDEX++
	)
	{
		float	GRADIENT_VALUE = GRADIENTS[PARAMETER_INDEX];
		float	FIRST_MOMENT =
			FIRST_MOMENTS[PARAMETER_INDEX] * KERNEL_STATE->FIRST_MOMENT_DECAY +
			GRADIENT_VALUE * KERNEL_STATE->FIRST_MOMENT_RATE;
		float	SECOND_MOMENT = SECOND_MOMENTS[PARAMETER_INDEX] *
				KERNEL_STATE->SECOND_MOMENT_DECAY +
			GRADIENT_VALUE * GRADIENT_VALUE * KERNEL_STATE->SECOND_MOMENT_RATE;

		FIRST_MOMENTS[PARAMETER_INDEX] = FIRST_MOMENT;
		SECOND_MOMENTS[PARAMETER_INDEX] = SECOND_MOMENT;
		GRADIENTS[PARAMETER_INDEX] = 0;

		float	UPDATE_STEP =
			FIRST_MOMENT * KERNEL_STATE->FIRST_BIAS_CORRECTION /
					(sqrtf(
						SECOND_MOMENT * KERNEL_STATE->SECOND_BIAS_CORRECTION
						) +
						KERNEL_STATE->EPSILON) +
				PARAMETERS[PARAMETER_INDEX] * KERNEL_STATE->WEIGHT_DECAY;

		PARAMETERS[PARAMETER_INDEX] -=
			KERNEL_STATE->LEARNING_RATE * UPDATE_STEP;
	}
}

void
	REFERENCE_UPDATE(WEB *NEURAL_WEB)
{
	int32_t	NEURON_INDEX;

	for (
		NEURON_INDEX = 0;
		NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
		NEURON_INDEX++
	)
	{
		NEURON	*CURRENT_NEURON = &NEURAL_WEB->NEURONS[NEURON_INDEX];

		if (!CURRENT_NEURON->ALIVE || !CURRENT_NEURON->PARAMETER_COUNT)
			continue ;

		REFERENCE_ADAM(NEURAL_WEB, CURRENT_NEURON);
	}
}
