#include "REFLEX.h"
#include "JIT.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

uint64_t
	REFLEX_KEY(const char *KEY_STRING)
{
	uint64_t	HASH_VALUE = (unsigned long long)1469598103934665603;

	for (; *KEY_STRING; KEY_STRING++)
	{
		HASH_VALUE ^= (uint8_t)*KEY_STRING;
		HASH_VALUE *= (unsigned long long)1099511628211;
	}

	if (HASH_VALUE)
		return (HASH_VALUE);

	return (1);
}

void
	REFLEX_NORMALIZE(const char *INPUT_STRING, char *OUTPUT, int OUTPUT_SIZE)
{
	int			OUTPUT_LENGTH = 0;
	int			AFTER_SPACE = 1;
	const char	*CURSOR;

	for (
		CURSOR = INPUT_STRING;
		*CURSOR && OUTPUT_LENGTH < OUTPUT_SIZE - 2;
		CURSOR++
	)
	{
		unsigned char	CURRENT_CHARACTER = (unsigned char)*CURSOR;

		if (
			isalnum(CURRENT_CHARACTER) ||
			CURRENT_CHARACTER == '.' ||
			CURRENT_CHARACTER == '\'' ||
			CURRENT_CHARACTER >= 0X80
		)
		{
			if (
				CURRENT_CHARACTER == '.' &&
				!(
					OUTPUT_LENGTH > 0 &&
					isalnum((unsigned char)OUTPUT[OUTPUT_LENGTH - 1]) &&
					isalnum((unsigned char)CURSOR[1])
				)
			)
			{
				if (!AFTER_SPACE)
				{
					OUTPUT[OUTPUT_LENGTH++] = ' ';
					AFTER_SPACE = 1;
				}

				continue ;
			}

			if (CURRENT_CHARACTER == '\'')
				continue ;

			OUTPUT[OUTPUT_LENGTH++] = (char)tolower(CURRENT_CHARACTER);
			AFTER_SPACE = 0;
		}
		else if (!AFTER_SPACE)
		{
			OUTPUT[OUTPUT_LENGTH++] = ' ';
			AFTER_SPACE = 1;
		}
	}

	while (OUTPUT_LENGTH && OUTPUT[OUTPUT_LENGTH - 1] == ' ')
		OUTPUT_LENGTH--;

	OUTPUT[OUTPUT_LENGTH] = 0;
}

static REFLEX_SET	*SORTING_REFLEX_SET;

static int
	COMPARE_BY_KEY(const void *LEFT_ITEM, const void *RIGHT_ITEM)
{
	uint64_t	LEFT_KEY =
		SORTING_REFLEX_SET->ENTRIES[*(const int *)LEFT_ITEM].KEY;
	uint64_t	RIGHT_KEY =
		SORTING_REFLEX_SET->ENTRIES[*(const int *)RIGHT_ITEM].KEY;

	if (LEFT_KEY < RIGHT_KEY)
		return (-1);

	return (LEFT_KEY > RIGHT_KEY);
}

static void
	EMIT_BINARY_SEARCH(
		ASSEMBLER *ASSEMBLY, REFLEX_SET *REFLEX_TABLE, int *SORTED_ORDER,
		int LOW_INDEX, int HIGH_INDEX, int KEY_REGISTER
	)
{
	if (LOW_INDEX > HIGH_INDEX)
	{
		MOVE_IMMEDIATE(ASSEMBLY, RAX, -1);
		RETURN_INSTRUCTION(ASSEMBLY);
		return ;
	}

	int	MIDDLE_INDEX = (LOW_INDEX + HIGH_INDEX) / 2;
	int	FOUND_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);
	int	BELOW_LABEL = ASSEMBLER_NEW_LABEL(ASSEMBLY);

	MOVE_IMMEDIATE64(
		ASSEMBLY, RDX, REFLEX_TABLE->ENTRIES[SORTED_ORDER[MIDDLE_INDEX]].KEY
	);
	COMPARE_REGISTER(ASSEMBLY, KEY_REGISTER, RDX);
	BRANCH_TO_LABEL(ASSEMBLY, CC_E, FOUND_LABEL);
	BRANCH_TO_LABEL(ASSEMBLY, CC_B, BELOW_LABEL);
	EMIT_BINARY_SEARCH(
		ASSEMBLY, REFLEX_TABLE, SORTED_ORDER, MIDDLE_INDEX + 1, HIGH_INDEX,
		KEY_REGISTER
	);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, BELOW_LABEL);
	EMIT_BINARY_SEARCH(
		ASSEMBLY, REFLEX_TABLE, SORTED_ORDER, LOW_INDEX, MIDDLE_INDEX - 1,
		KEY_REGISTER
	);
	ASSEMBLER_BIND_LABEL(ASSEMBLY, FOUND_LABEL);
	MOVE_IMMEDIATE(ASSEMBLY, RAX, SORTED_ORDER[MIDDLE_INDEX]);
	RETURN_INSTRUCTION(ASSEMBLY);
}

int
	REFLEX_COMPILE(REFLEX_SET *REFLEX_TABLE)
{
	int	COMPILED_COUNT = 0;
	int	*SORTED_ORDER = malloc((REFLEX_TABLE->COUNT + 1) * sizeof(int));
	int	REFLEX_INDEX;

	for (REFLEX_INDEX = 0; REFLEX_INDEX < REFLEX_TABLE->COUNT; REFLEX_INDEX++)
		if (REFLEX_TABLE->ENTRIES[REFLEX_INDEX].IS_COMPILED)
			SORTED_ORDER[COMPILED_COUNT++] = REFLEX_INDEX;

	SORTING_REFLEX_SET = REFLEX_TABLE;
	qsort(SORTED_ORDER, COMPILED_COUNT, sizeof(int), COMPARE_BY_KEY);

	ASSEMBLER	ASSEMBLY;

	ASSEMBLER_INITIALIZE(&ASSEMBLY);
#ifdef _WIN32
	int	KEY_REGISTER = RCX;
#else
	int	KEY_REGISTER = RDI;
#endif
	EMIT_BINARY_SEARCH(
		&ASSEMBLY, REFLEX_TABLE, SORTED_ORDER, 0, COMPILED_COUNT - 1,
		KEY_REGISTER
	);

	if (ASSEMBLER_FINISH(&ASSEMBLY))
	{
		ASSEMBLER_FREE(&ASSEMBLY);
		free(SORTED_ORDER);
		return (-1);
	}

	if (REFLEX_TABLE->MACHINE_CODE)
		EXECUTABLE_FREE(
			REFLEX_TABLE->MACHINE_CODE, REFLEX_TABLE->CODE_CAPACITY
		);

	REFLEX_TABLE->CODE_CAPACITY = (ASSEMBLY.BYTE_COUNT + 4095) & ~4095;
	REFLEX_TABLE->MACHINE_CODE =
		EXECUTABLE_ALLOCATE(REFLEX_TABLE->CODE_CAPACITY);

	if (!REFLEX_TABLE->MACHINE_CODE)
	{
		ASSEMBLER_FREE(&ASSEMBLY);
		free(SORTED_ORDER);
		REFLEX_TABLE->FIND_FUNCTION = NULL;
		return (-1);
	}

	memcpy(REFLEX_TABLE->MACHINE_CODE, ASSEMBLY.BYTES, ASSEMBLY.BYTE_COUNT);
	REFLEX_TABLE->CODE_LENGTH = ASSEMBLY.BYTE_COUNT;
	REFLEX_TABLE->FIND_FUNCTION =
		(int (*)(uint64_t, uint64_t))(void *)REFLEX_TABLE->MACHINE_CODE;
	ASSEMBLER_FREE(&ASSEMBLY);
	free(SORTED_ORDER);

	return (0);
}

int
	REFLEX_FIND(REFLEX_SET *REFLEX_TABLE, uint64_t LOOKUP_KEY)
{
	if (!REFLEX_TABLE->FIND_FUNCTION)
		return (-1);

	return (REFLEX_TABLE->FIND_FUNCTION(LOOKUP_KEY, LOOKUP_KEY));
}

int
	REFLEX_COUNT(REFLEX_SET *REFLEX_TABLE, int COMPILED_STATE)
{
	int	MATCH_COUNT = 0;
	int	REFLEX_INDEX;

	for (REFLEX_INDEX = 0; REFLEX_INDEX < REFLEX_TABLE->COUNT; REFLEX_INDEX++)
		if (REFLEX_TABLE->ENTRIES[REFLEX_INDEX].IS_COMPILED == COMPILED_STATE)
			MATCH_COUNT++;

	return (MATCH_COUNT);
}

void
	REFLEX_DELETE(REFLEX_SET *REFLEX_TABLE, int REFLEX_INDEX)
{
	if (REFLEX_INDEX < 0 || REFLEX_INDEX >= REFLEX_TABLE->COUNT)
		return ;

	REFLEX_TABLE->ENTRIES[REFLEX_INDEX] =
		REFLEX_TABLE->ENTRIES[--REFLEX_TABLE->COUNT];
	REFLEX_TABLE->IS_DIRTY = 1;
}

int
	REFLEX_OBSERVE(
		REFLEX_SET *REFLEX_TABLE, const char *TRIGGER, int REFLEX_KIND,
		const char *RESPONSE, uint32_t CURRENT_TIME
	)
{
	uint64_t	TRIGGER_KEY = REFLEX_KEY(TRIGGER);
	int			REFLEX_INDEX;

	for (REFLEX_INDEX = 0; REFLEX_INDEX < REFLEX_TABLE->COUNT; REFLEX_INDEX++)
		if (REFLEX_TABLE->ENTRIES[REFLEX_INDEX].KEY == TRIGGER_KEY)
		{
			REFLEX	*REFLEX_ENTRY = &REFLEX_TABLE->ENTRIES[REFLEX_INDEX];

			if (
				strcmp(REFLEX_ENTRY->RESPONSE, RESPONSE) ||
				REFLEX_ENTRY->KIND != REFLEX_KIND
			)
			{
				if (!REFLEX_ENTRY->IS_COMPILED)
				{
					snprintf(
						REFLEX_ENTRY->RESPONSE, sizeof REFLEX_ENTRY->RESPONSE,
						"%s", RESPONSE
					);
					REFLEX_ENTRY->KIND = REFLEX_KIND;
					REFLEX_ENTRY->SEEN_COUNT = 1;
					REFLEX_ENTRY->BAD_COUNT = 0;
					REFLEX_TABLE->IS_DIRTY = 1;
				}

				return (REFLEX_INDEX);
			}

			REFLEX_ENTRY->SEEN_COUNT++;
			REFLEX_TABLE->IS_DIRTY = 1;
			return (REFLEX_INDEX);
		}

	if (REFLEX_TABLE->COUNT >= REFLEX_TABLE->CAPACITY)
	{
		if (REFLEX_TABLE->CAPACITY)
			REFLEX_TABLE->CAPACITY = REFLEX_TABLE->CAPACITY * 2;
		else
			REFLEX_TABLE->CAPACITY = 64;

		REFLEX_TABLE->ENTRIES = realloc(
			REFLEX_TABLE->ENTRIES, REFLEX_TABLE->CAPACITY * sizeof(REFLEX)
		);
	}

	REFLEX	*REFLEX_ENTRY = &REFLEX_TABLE->ENTRIES[REFLEX_TABLE->COUNT++];

	memset(REFLEX_ENTRY, 0, sizeof *REFLEX_ENTRY);
	REFLEX_ENTRY->KEY = TRIGGER_KEY;
	REFLEX_ENTRY->KIND = REFLEX_KIND;
	REFLEX_ENTRY->SEEN_COUNT = 1;
	REFLEX_ENTRY->BIRTH_TIME = CURRENT_TIME;
	snprintf(
		REFLEX_ENTRY->TRIGGER, sizeof REFLEX_ENTRY->TRIGGER, "%s", TRIGGER
	);
	snprintf(
		REFLEX_ENTRY->RESPONSE, sizeof REFLEX_ENTRY->RESPONSE, "%s", RESPONSE
	);
	REFLEX_TABLE->IS_DIRTY = 1;

	return (REFLEX_TABLE->COUNT - 1);
}

int
	REFLEX_LOAD(REFLEX_SET *REFLEX_TABLE, const char *PATH)
{
	FILE	*STREAM = fopen(PATH, "rb");

	if (!STREAM)
		return (-1);

	char	LINE_BUFFER[1024];

	while (fgets(LINE_BUFFER, sizeof LINE_BUFFER, STREAM))
	{
		size_t	LINE_LENGTH = strlen(LINE_BUFFER);

		while (
			LINE_LENGTH &&
			(
				LINE_BUFFER[LINE_LENGTH - 1] == '\n' ||
				LINE_BUFFER[LINE_LENGTH - 1] == '\r'
			)
		)
			LINE_BUFFER[--LINE_LENGTH] = 0;

		char	*FIRST_TAB = strchr(LINE_BUFFER, '\t');

		if (!FIRST_TAB)
			continue ;

		*FIRST_TAB = 0;

		char	*SECOND_TAB = strchr(FIRST_TAB + 1, '\t');

		if (!SECOND_TAB)
			continue ;

		*SECOND_TAB = 0;

		char	*THIRD_TAB = strchr(SECOND_TAB + 1, '\t');

		if (THIRD_TAB)
			*THIRD_TAB = 0;

		int	REFLEX_KIND;

		if (!strcmp(LINE_BUFFER, "reply"))
			REFLEX_KIND = REFLEX_REPLY;
		else if (!strcmp(LINE_BUFFER, "action"))
			REFLEX_KIND = REFLEX_ACTION;
		else
			REFLEX_KIND = -1;

		int	COMPILED_STATE = 0;
		int	SEEN_COUNT = 0;
		int	GOOD_COUNT = 0;
		int	USE_COUNT = 0;

		if (THIRD_TAB)
			sscanf(
				THIRD_TAB + 1, "%d %d %d %d", &COMPILED_STATE, &SEEN_COUNT,
				&GOOD_COUNT, &USE_COUNT
			);

		if (REFLEX_KIND < 0 || !*(FIRST_TAB + 1))
			continue ;

		char	NORMALIZED_TRIGGER[200];

		REFLEX_NORMALIZE(
			FIRST_TAB + 1, NORMALIZED_TRIGGER, sizeof NORMALIZED_TRIGGER
		);

		int	REFLEX_INDEX = REFLEX_OBSERVE(
			REFLEX_TABLE, NORMALIZED_TRIGGER, REFLEX_KIND, SECOND_TAB + 1, 0
		);

		if (THIRD_TAB)
			REFLEX_TABLE->ENTRIES[REFLEX_INDEX].IS_COMPILED = COMPILED_STATE;
		else
			REFLEX_TABLE->ENTRIES[REFLEX_INDEX].IS_COMPILED = 1;

		if (SEEN_COUNT)
			REFLEX_TABLE->ENTRIES[REFLEX_INDEX].SEEN_COUNT = SEEN_COUNT;
		else
			REFLEX_TABLE->ENTRIES[REFLEX_INDEX].SEEN_COUNT =
				REFLEX_TABLE->ENTRIES[REFLEX_INDEX].SEEN_COUNT;

		REFLEX_TABLE->ENTRIES[REFLEX_INDEX].GOOD_COUNT = GOOD_COUNT;
		REFLEX_TABLE->ENTRIES[REFLEX_INDEX].USE_COUNT = USE_COUNT;
	}

	fclose(STREAM);
	REFLEX_TABLE->IS_DIRTY = 0;

	return (REFLEX_COMPILE(REFLEX_TABLE));
}

int
	REFLEX_SAVE(REFLEX_SET *REFLEX_TABLE, const char *PATH)
{
	if (!REFLEX_TABLE->IS_DIRTY)
		return (0);

	FILE	*STREAM = fopen(PATH, "wb");

	if (!STREAM)
		return (-1);

	int	REFLEX_INDEX;

	for (REFLEX_INDEX = 0; REFLEX_INDEX < REFLEX_TABLE->COUNT; REFLEX_INDEX++)
	{
		REFLEX	*REFLEX_ENTRY = &REFLEX_TABLE->ENTRIES[REFLEX_INDEX];

		fprintf(
			STREAM, "%s\t%s\t%s\t%d %d %d %d\n",
			REFLEX_ENTRY->KIND == REFLEX_REPLY ? "reply" : "action",
			REFLEX_ENTRY->TRIGGER, REFLEX_ENTRY->RESPONSE,
			REFLEX_ENTRY->IS_COMPILED, REFLEX_ENTRY->SEEN_COUNT,
			REFLEX_ENTRY->GOOD_COUNT, REFLEX_ENTRY->USE_COUNT
		);
	}

	fclose(STREAM);
	REFLEX_TABLE->IS_DIRTY = 0;

	return (0);
}
