#include "CODE.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

void	RANDOMIZE_WEB(WEB *NEURAL_WEB, float SCALE);
int		CHECK_AGAINST_REFERENCE(
	WEB *JIT_WEB, WEB *REFERENCE_WEB, int VOCABULARY_SIZE, int TOKEN_COUNT,
	int WITH_COPY
);

static const char	*GATED_RECIPE_SOURCE =
	"recipe gated\n"
	"param wg 32 d read\nparam wu 32 d read\nparam wd 32 d write\n"
	"x = in\ng = mv wg x\nu = mv wu x\ns = silu g\nh = mul s u\ny = mvt wd "
	"h\nout y\n";
static const char	*GELU_RECIPE_SOURCE =
	"recipe gelu_mlp\n"
	"param w1 48 d read\nparam b1 48 zero\nparam w2 48 d write\nparam b2 d "
	"zero\n"
	"x = in\nh = mv w1 x\nhb = addp h b1\na = gelu hb\ny = mvt w2 a\nyb = addp "
	"y b2\nout yb\n";
static const char	*MIXED_RECIPE_SOURCE =
	"recipe mix\n"
	"param wa 16 d read\nparam wb 16 d read\nparam g 16 one\nparam c 16 "
	"zero\nparam wo 16 d write\nparam wp d d write\n"
	"x = in\na = mv wa x\nb = mv wb x\nt = tanh a\ns = sigmoid b\nm = mulp t "
	"g\nn = sub m s\nq = add n t\nr = relu q\n"
	"k = dot a b\nz = sum s\ne = scale r k\nf = scale e z\np = softmax f\nv = "
	"mul p s\nw2 = addp v c\ny = mvt wo w2\nout y\n"
	"yy = mv wp x\nout yy\n";
static const char	*MEMORY_RECIPE_SOURCE =
	"recipe memory\n"
	"param keys 64 d read\nparam vals 64 d write\n"
	"x = in\ns = mv keys x\np = softmax s\ny = mvt vals p\nout y\n";
static const char	*FEED_FORWARD_RECIPE_SOURCE =
	"recipe ffn16\n"
	"param wi 16 d read\nparam b 16 zero\nparam wo 16 d write\n"
	"x = in\nh = mv wi x\nhb = addp h b\nr = relu hb\ny = mvt wo r\nout y\n";

static WEB
	*BUILD_RECIPE_WEB(
		CONFIG MODEL_CONFIG, uint64_t SEED, int VOCABULARY_SIZE,
		const char **RECIPE_SOURCES, int RECIPE_COUNT, int PER_LAYER
	)
{
	WEB	*NEURAL_WEB = WEB_NEW(MODEL_CONFIG, SEED);
	int	INDEX;

	for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
		WEB_ADD_WORD(NEURAL_WEB);

	for (INDEX = 0; INDEX < RECIPE_COUNT; INDEX++)
	{
		char	ERROR_MESSAGE[200];
		int		RECIPE_ID = WEB_RECIPE_ADD(
			NEURAL_WEB, RECIPE_SOURCES[INDEX], ERROR_MESSAGE,
			sizeof ERROR_MESSAGE
		);

		if (RECIPE_ID < 0)
		{
			printf("  recipe error: %s\n", ERROR_MESSAGE);
			exit(1);
		}

		int	AREA_INDEX;

		for (
			AREA_INDEX = 0;
			AREA_INDEX < 2 * MODEL_CONFIG.LAYER_COUNT;
			AREA_INDEX++
		)
		{
			int	NEURON_INDEX;

			for (NEURON_INDEX = 0; NEURON_INDEX < PER_LAYER; NEURON_INDEX++)
				WEB_ADD_NEURON(
					NEURAL_WEB, KIND_RECIPE, AREA_INDEX, WHY_SEED, RECIPE_ID
				);
		}
	}

	WEB_RELINK(NEURAL_WEB);

	return (NEURAL_WEB);
}

static int
	TEST_RECIPE_PARSE_ERRORS(void)
{
	const char	*BAD_RECIPES[6] = {
		"recipe a\nx = in\ny = foo x\nout y\n",
		"recipe a\nparam w 16 d read\nx = in\ny = mv w x\nout y\n",
		"recipe a\nparam w 20 d read\nx = in\ny = mv w x\nz = mvt w y\nout z\n",
		"recipe a\nx = in\ny = relu x\n",
		"recipe a\nx = in\ny = relu q\nout y\n",
		"recipe a\nx = in\nk = dot x x\nout k\n"
	};
	int			FAIL_COUNT = 0;
	int			INDEX;

	for (INDEX = 0; INDEX < 6; INDEX++)
	{
		RECIPE	PARSED_RECIPE;
		char	ERROR_MESSAGE[200];

		if (
			!RECIPE_PARSE(
				&PARSED_RECIPE, BAD_RECIPES[INDEX], 64, ERROR_MESSAGE,
				sizeof ERROR_MESSAGE
			)
		)
		{
			printf("  bad recipe %d was accepted: FAIL\n", INDEX);
			RECIPE_FREE(&PARSED_RECIPE);
			FAIL_COUNT++;
		}
		else
			printf("  rejected bad recipe %d: %s\n", INDEX, ERROR_MESSAGE);
	}

	return (FAIL_COUNT);
}

static int
	TEST_FEED_FORWARD_RECIPE(void)
{
	int		FAIL_COUNT = 0;
	int		VOCABULARY_SIZE = 30;
	int		POSITION_COUNT = 19;
	CONFIG	MODEL_CONFIG = { 64, 1, 16, 24, 32, 1, 0 };
	WEB		*PLAIN_WEB = WEB_NEW(MODEL_CONFIG, 3);
	WEB		*RECIPE_WEB = WEB_NEW(MODEL_CONFIG, 3);
	int		INDEX;

	for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
	{
		WEB_ADD_WORD(PLAIN_WEB);
		WEB_ADD_WORD(RECIPE_WEB);
	}

	char	ERROR_MESSAGE[200];
	int		RECIPE_ID = WEB_RECIPE_ADD(
		RECIPE_WEB, FEED_FORWARD_RECIPE_SOURCE, ERROR_MESSAGE,
		sizeof ERROR_MESSAGE
	);
	int32_t	NATIVE_NEURONS[16];
	int32_t	RECIPE_NEURON =
		WEB_ADD_NEURON(RECIPE_WEB, KIND_RECIPE, 1, WHY_SEED, RECIPE_ID);
	int		NEURON_INDEX;

	for (NEURON_INDEX = 0; NEURON_INDEX < 16; NEURON_INDEX++)
		NATIVE_NEURONS[NEURON_INDEX] =
			WEB_ADD_NEURON(PLAIN_WEB, KIND_FEED_FORWARD, 1, WHY_SEED, -1);

	WEB_RELINK(PLAIN_WEB);
	WEB_RELINK(RECIPE_WEB);
	RANDOMIZE_WEB(PLAIN_WEB, (float)0.3);
	RANDOMIZE_WEB(RECIPE_WEB, (float)0.3);

	for (INDEX = 0; INDEX < PLAIN_WEB->NEURON_COUNT; INDEX++)
	{
		NEURON	*CURRENT_NEURON = &PLAIN_WEB->NEURONS[INDEX];

		if (
			CURRENT_NEURON->KIND == KIND_FEED_FORWARD ||
			!CURRENT_NEURON->PARAMETER_COUNT ||
			!CURRENT_NEURON->ALIVE
		)
			continue ;

		memcpy(
			NEURON_PARAMETERS(RECIPE_WEB, INDEX),
			NEURON_PARAMETERS(PLAIN_WEB, INDEX),
			CURRENT_NEURON->PARAMETER_COUNT * 4
		);
	}

	RECIPE	*ACTIVE_RECIPE = &RECIPE_WEB->RECIPES[RECIPE_ID];
	float	*RECIPE_PARAMETERS = NEURON_PARAMETERS(RECIPE_WEB, RECIPE_NEURON);
	int		MODEL_WIDTH = MODEL_CONFIG.DIMENSION;

	for (NEURON_INDEX = 0; NEURON_INDEX < 16; NEURON_INDEX++)
	{
		float	*NATIVE_PARAMETERS =
			NEURON_PARAMETERS(PLAIN_WEB, NATIVE_NEURONS[NEURON_INDEX]);

		memcpy(
			RECIPE_PARAMETERS + ACTIVE_RECIPE->PARAMETERS[0].OFFSET +
				NEURON_INDEX * MODEL_WIDTH,
			NATIVE_PARAMETERS, MODEL_WIDTH * 4
		);
		RECIPE_PARAMETERS[ACTIVE_RECIPE->PARAMETERS[1].OFFSET + NEURON_INDEX] =
			NATIVE_PARAMETERS[2 * MODEL_WIDTH];
		memcpy(
			RECIPE_PARAMETERS + ACTIVE_RECIPE->PARAMETERS[2].OFFSET +
				NEURON_INDEX * MODEL_WIDTH,
			NATIVE_PARAMETERS + MODEL_WIDTH, MODEL_WIDTH * 4
		);
	}

	WEB	*WEBS[2] = { PLAIN_WEB, RECIPE_WEB };
	int	WEB_INDEX;

	for (WEB_INDEX = 0; WEB_INDEX < 2; WEB_INDEX++)
	{
		WEB			*NEURAL_WEB = WEBS[WEB_INDEX];
		int32_t		*INPUT_TOKENS =
			(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);
		int32_t		*TARGETS =
			(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TARGETS_OFFSET);
		float		*TOKEN_WEIGHTS = (float *)(NEURAL_WEB->ACTIVATIONS +
			NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
		uint64_t	RANDOM_STATE = 44;
		int			POSITION;

		for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
		{
			INPUT_TOKENS[POSITION] =
				RANDOM_NEXT(&RANDOM_STATE) % VOCABULARY_SIZE;
			TARGETS[POSITION] = RANDOM_NEXT(&RANDOM_STATE) % VOCABULARY_SIZE;
			TOKEN_WEIGHTS[POSITION] = 1;
		}

		NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = POSITION_COUNT;
		NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
		NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE = (float)1.0 / POSITION_COUNT;
		NEURAL_WEB->KERNEL_STATE->GRADIENT_SKIP_THRESHOLD = 0;

		int32_t	INDEX;

		for (INDEX = 0; INDEX < NEURAL_WEB->NEURON_COUNT; INDEX++)
			if (NEURAL_WEB->NEURONS[INDEX].PARAMETER_COUNT)
				memset(
					NEURON_GRADIENTS(NEURAL_WEB, INDEX), 0,
					NEURAL_WEB->NEURONS[INDEX].PARAMETER_COUNT * 4
				);

		WEB_RUN(NEURAL_WEB, MODE_TRAIN);
	}

	double	LOSS_DIFFERENCE = 0;
	double	GRADIENT_DIFFERENCE = 0;
	double	GRADIENT_MAGNITUDE = 0;
	int		POSITION;

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
	{
		double	LOSS_GAP = fabs(
			WEB_LOSS_AT(PLAIN_WEB, PLAIN_WEB->ACTIVATIONS, POSITION) -
			WEB_LOSS_AT(RECIPE_WEB, RECIPE_WEB->ACTIVATIONS, POSITION)
		);

		if (LOSS_GAP > LOSS_DIFFERENCE)
			LOSS_DIFFERENCE = LOSS_GAP;
	}

	float	*RECIPE_GRADIENTS = NEURON_GRADIENTS(RECIPE_WEB, RECIPE_NEURON);

	for (NEURON_INDEX = 0; NEURON_INDEX < 16; NEURON_INDEX++)
	{
		float	*NATIVE_GRADIENTS =
			NEURON_GRADIENTS(PLAIN_WEB, NATIVE_NEURONS[NEURON_INDEX]);
		int		INDEX;

		for (INDEX = 0; INDEX < MODEL_WIDTH; INDEX++)
		{
			GRADIENT_DIFFERENCE = fmax(
				GRADIENT_DIFFERENCE,
				fabs(
					NATIVE_GRADIENTS[INDEX] -
					RECIPE_GRADIENTS
						[ACTIVE_RECIPE->PARAMETERS[0].OFFSET +
							NEURON_INDEX * MODEL_WIDTH + INDEX]
				)
			);
			GRADIENT_DIFFERENCE = fmax(
				GRADIENT_DIFFERENCE,
				fabs(
					NATIVE_GRADIENTS[MODEL_WIDTH + INDEX] -
					RECIPE_GRADIENTS
						[ACTIVE_RECIPE->PARAMETERS[2].OFFSET +
							NEURON_INDEX * MODEL_WIDTH + INDEX]
				)
			);
			GRADIENT_MAGNITUDE =
				fmax(GRADIENT_MAGNITUDE, fabs(NATIVE_GRADIENTS[INDEX]));
		}

		GRADIENT_DIFFERENCE = fmax(
			GRADIENT_DIFFERENCE,
			fabs(
				NATIVE_GRADIENTS[2 * MODEL_WIDTH] -
				RECIPE_GRADIENTS
					[ACTIVE_RECIPE->PARAMETERS[1].OFFSET + NEURON_INDEX]
			)
		);
	}

	double	EMBEDDING_DIFFERENCE = 0;
	float	*PLAIN_EMBEDDING_GRADIENT =
		NEURON_GRADIENTS(PLAIN_WEB, PLAIN_WEB->EMBEDDING_ID);
	float	*RECIPE_EMBEDDING_GRADIENT =
		NEURON_GRADIENTS(RECIPE_WEB, RECIPE_WEB->EMBEDDING_ID);

	for (INDEX = 0; INDEX < POSITION_COUNT * MODEL_WIDTH; INDEX++)
		EMBEDDING_DIFFERENCE = fmax(
			EMBEDDING_DIFFERENCE,
			fabs(
				PLAIN_EMBEDDING_GRADIENT[INDEX] -
				RECIPE_EMBEDDING_GRADIENT[INDEX]
			)
		);

	int	MISMATCH = LOSS_DIFFERENCE > 1e-4 ||
		GRADIENT_DIFFERENCE > 1e-4 * (GRADIENT_MAGNITUDE + 1e-3) + 1e-6 ||
		EMBEDDING_DIFFERENCE > 1e-5;

	printf(
		"  16 hand-written FFN neurons == 1 'ffn16' recipe neuron: loss diff "
		"%.2g, weight-grad diff %.2g (grads up to %.3g), embedding-grad diff "
		"%.2g %s\n",
		LOSS_DIFFERENCE, GRADIENT_DIFFERENCE, GRADIENT_MAGNITUDE,
		EMBEDDING_DIFFERENCE, MISMATCH ? "FAIL" : "ok"
	);
	FAIL_COUNT += MISMATCH;
	WEB_FREE(PLAIN_WEB);
	WEB_FREE(RECIPE_WEB);

	return (FAIL_COUNT);
}

static double
	RECIPE_EVALUATION_LOSS(WEB *NEURAL_WEB, int POSITION_COUNT)
{
	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = POSITION_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_EVALUATE);

	double	LOSS_SUM = 0;
	int		POSITION;

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
		LOSS_SUM += NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE *
			WEB_LOSS_AT(NEURAL_WEB, NEURAL_WEB->ACTIVATIONS, POSITION);

	return (LOSS_SUM);
}

static int
	TEST_RECIPE_GRADIENTS(const char *RECIPE_SOURCE, uint64_t SEED)
{
	CONFIG		MODEL_CONFIG = { 64, 1, 16, 16, 32, 1, 4 };
	const char	*RECIPE_SOURCES[1] = { RECIPE_SOURCE };
	WEB			*NEURAL_WEB =
		BUILD_RECIPE_WEB(MODEL_CONFIG, SEED, 20, RECIPE_SOURCES, 1, 1);

	RANDOMIZE_WEB(NEURAL_WEB, (float)0.3);

	int		POSITION_COUNT = 13;
	int		FAIL_COUNT = 0;
	int32_t	*INPUT_TOKENS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);
	int32_t	*TARGETS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TARGETS_OFFSET);
	float	*TOKEN_WEIGHTS =
		(float *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
	int		POSITION;

	for (POSITION = 0; POSITION < MODEL_CONFIG.MAXIMUM_LENGTH; POSITION++)
	{
		INPUT_TOKENS[POSITION] = RANDOM_NEXT(&NEURAL_WEB->RANDOM_STATE) % 20;
		TARGETS[POSITION] = RANDOM_NEXT(&NEURAL_WEB->RANDOM_STATE) % 20;
		TOKEN_WEIGHTS[POSITION] = 1;
	}

	NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE = (float)1.0 / POSITION_COUNT;
	NEURAL_WEB->KERNEL_STATE->GRADIENT_SKIP_THRESHOLD = 0;

	int32_t	INDEX;

	for (INDEX = 0; INDEX < NEURAL_WEB->NEURON_COUNT; INDEX++)
		if (NEURAL_WEB->NEURONS[INDEX].PARAMETER_COUNT)
			memset(
				NEURON_GRADIENTS(NEURAL_WEB, INDEX), 0,
				NEURAL_WEB->NEURONS[INDEX].PARAMETER_COUNT * 4
			);

	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = POSITION_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_TRAIN);

	int32_t	RECIPE_NEURON = -1;

	for (INDEX = 0; INDEX < NEURAL_WEB->NEURON_COUNT; INDEX++)
		if (NEURAL_WEB->NEURONS[INDEX].KIND == KIND_RECIPE)
		{
			RECIPE_NEURON = INDEX;
			break ;
		}

	RECIPE	*ACTIVE_RECIPE = &NEURAL_WEB->RECIPES[0];
	double	WORST_ERROR = 0;
	int		PARAMETER_INDEX;

	for (
		PARAMETER_INDEX = 0;
		PARAMETER_INDEX < ACTIVE_RECIPE->PARAMETER_COUNT;
		PARAMETER_INDEX++
	)
	{
		int64_t	PARAMETER_SIZE =
			(int64_t)ACTIVE_RECIPE->PARAMETERS[PARAMETER_INDEX].ROWS *
			ACTIVE_RECIPE->PARAMETERS[PARAMETER_INDEX].COLUMNS;
		int		PROBE_INDEX;

		for (PROBE_INDEX = 0; PROBE_INDEX < 3; PROBE_INDEX++)
		{
			int64_t	PROBE_OFFSET =
				ACTIVE_RECIPE->PARAMETERS[PARAMETER_INDEX].OFFSET;
			float	BEST_GRADIENT = -1;
			int		TRY_INDEX;

			for (TRY_INDEX = 0; TRY_INDEX < 64; TRY_INDEX++)
			{
				int64_t	CANDIDATE_OFFSET =
					ACTIVE_RECIPE->PARAMETERS[PARAMETER_INDEX].OFFSET +
					(int64_t)(RANDOM_NEXT(&NEURAL_WEB->RANDOM_STATE) %
						(uint64_t)PARAMETER_SIZE);

				if (
					fabsf(NEURON_GRADIENTS(
						NEURAL_WEB, RECIPE_NEURON
					)[CANDIDATE_OFFSET]) > BEST_GRADIENT
				)
				{
					BEST_GRADIENT = fabsf(NEURON_GRADIENTS(
						NEURAL_WEB, RECIPE_NEURON
					)[CANDIDATE_OFFSET]);
					PROBE_OFFSET = CANDIDATE_OFFSET;
				}
			}

			float	*PARAMETER_POINTER =
				NEURON_PARAMETERS(NEURAL_WEB, RECIPE_NEURON) + PROBE_OFFSET;
			float	ANALYTIC_GRADIENT =
				NEURON_GRADIENTS(NEURAL_WEB, RECIPE_NEURON)[PROBE_OFFSET];
			float	OLD_VALUE = *PARAMETER_POINTER;
			float	STEP_SIZE = (float)4e-3;

			*PARAMETER_POINTER = OLD_VALUE + STEP_SIZE;

			double	LOSS_PLUS =
				RECIPE_EVALUATION_LOSS(NEURAL_WEB, POSITION_COUNT);

			*PARAMETER_POINTER = OLD_VALUE - STEP_SIZE;

			double	LOSS_MINUS =
				RECIPE_EVALUATION_LOSS(NEURAL_WEB, POSITION_COUNT);

			*PARAMETER_POINTER = OLD_VALUE;

			double	NUMERIC_GRADIENT =
				(LOSS_PLUS - LOSS_MINUS) / (2 * STEP_SIZE);
			double	RELATIVE_ERROR =
				fabs(NUMERIC_GRADIENT - ANALYTIC_GRADIENT) /
					(fabs(NUMERIC_GRADIENT) + fabs(ANALYTIC_GRADIENT) + 1e-3);

			if (RELATIVE_ERROR > WORST_ERROR)
				WORST_ERROR = RELATIVE_ERROR;

			if (RELATIVE_ERROR > 0.05)
			{
				printf(
					"    %s param %s[%lld]: analytic %+.6f numeric %+.6f "
					"FAIL\n",
					ACTIVE_RECIPE->NAME,
					ACTIVE_RECIPE->PARAMETERS[PARAMETER_INDEX].NAME,
					(long long)(PROBE_OFFSET -
								ACTIVE_RECIPE->PARAMETERS[PARAMETER_INDEX]
									.OFFSET),
					ANALYTIC_GRADIENT, NUMERIC_GRADIENT
				);
				FAIL_COUNT++;
			}
		}
	}

	printf(
		"  %-10s automatic backward vs finite differences on %d params: worst "
		"relative error %.3g %s\n",
		ACTIVE_RECIPE->NAME, ACTIVE_RECIPE->PARAMETER_COUNT * 3, WORST_ERROR,
		FAIL_COUNT ? "FAIL" : "ok"
	);
	WEB_FREE(NEURAL_WEB);

	return (FAIL_COUNT);
}

static int
	TEST_RECIPE_RELOAD(void)
{
	CONFIG		MODEL_CONFIG = { 64, 2, 16, 24, 32, 2, 8 };
	const char	*RECIPE_SOURCES[2] = {
		GATED_RECIPE_SOURCE, MEMORY_RECIPE_SOURCE
	};
	WEB			*NEURAL_WEB =
		BUILD_RECIPE_WEB(MODEL_CONFIG, 17, 25, RECIPE_SOURCES, 2, 1);

	RANDOMIZE_WEB(NEURAL_WEB, (float)0.3);
	WEB_ROUND_TO_HALF(NEURAL_WEB);

	int		POSITION_COUNT = 17;
	int		FAIL_COUNT = 0;
	int32_t	*INPUT_TOKENS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);
	int		POSITION;

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
		INPUT_TOKENS[POSITION] = (POSITION * 7) % 25;

	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = POSITION_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_INFER);

	float	REFERENCE_LOGITS[64];

	memcpy(REFERENCE_LOGITS, WEB_LAST_LOGITS(NEURAL_WEB), 25 * 4);

	const char	*PATH = "trcp_tmp.web";

	if (WEB_SAVE(NEURAL_WEB, PATH, 0))
	{
		printf("  save failed\n");
		return (1);
	}

	WEB	*LOADED_WEB = WEB_LOAD(PATH);
	WEB	*PLAY_WEB = WEB_LOAD_PLAY(PATH);
	WEB	*RELOADED_WEBS[2] = { LOADED_WEB, PLAY_WEB };
	int	WEB_INDEX;

	for (WEB_INDEX = 0; WEB_INDEX < 2; WEB_INDEX++)
	{
		WEB	*RELOADED_WEB = RELOADED_WEBS[WEB_INDEX];

		if (!RELOADED_WEB)
		{
			printf("  reload failed\n");
			FAIL_COUNT++;
			continue ;
		}

		int32_t	*RELOADED_TOKENS = (int32_t *)(RELOADED_WEB->ACTIVATIONS +
			RELOADED_WEB->TOKENS_OFFSET);
		int		POSITION;

		for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
			RELOADED_TOKENS[POSITION] = (POSITION * 7) % 25;

		RELOADED_WEB->KERNEL_STATE->SEQUENCE_LENGTH = POSITION_COUNT;
		RELOADED_WEB->KERNEL_STATE->START_POSITION = 0;
		WEB_RUN(RELOADED_WEB, MODE_INFER);

		double	MAX_DIFFERENCE = 0;
		int		INDEX;

		for (INDEX = 0; INDEX < 25; INDEX++)
			MAX_DIFFERENCE = fmax(
				MAX_DIFFERENCE,
				fabs(
					REFERENCE_LOGITS[INDEX] -
					WEB_LAST_LOGITS(RELOADED_WEB)[INDEX]
				)
			);

		double	TOLERANCE;

		if (WEB_INDEX)
			TOLERANCE = 1e-4;
		else
			TOLERANCE = 0;

		printf(
			"  %s: recipes travel inside the brain file (%d recipes), max "
			"logit diff %.3g %s\n",
			WEB_INDEX ? "play mode (16-bit)" : "save -> load",
			RELOADED_WEB->RECIPE_COUNT, MAX_DIFFERENCE,
			MAX_DIFFERENCE <= TOLERANCE ? "ok" : "FAIL"
		);
		FAIL_COUNT += MAX_DIFFERENCE > TOLERANCE;
	}

	WEB_FREE(NEURAL_WEB);
	WEB_FREE(LOADED_WEB);
	WEB_FREE(PLAY_WEB);
	remove(PATH);

	return (FAIL_COUNT);
}

int
	TEST_RECIPES(void)
{
	int	FAIL_COUNT = 0;

	printf("recipes: neuron types built from proven blocks\n");
	FAIL_COUNT += TEST_RECIPE_PARSE_ERRORS();
	FAIL_COUNT += TEST_FEED_FORWARD_RECIPE();

	const char	*ALL_RECIPES[5] = {
		GATED_RECIPE_SOURCE, GELU_RECIPE_SOURCE, MIXED_RECIPE_SOURCE,
		MEMORY_RECIPE_SOURCE, FEED_FORWARD_RECIPE_SOURCE
	};
	int			INDEX;

	for (INDEX = 0; INDEX < 5; INDEX++)
		FAIL_COUNT += TEST_RECIPE_GRADIENTS(ALL_RECIPES[INDEX], 50 + INDEX);

	CONFIG	MODEL_CONFIG = { 64, 2, 16, 24, 32, 2, 8 };
	WEB		*FAST_WEB =
		BUILD_RECIPE_WEB(MODEL_CONFIG, 9, 30, ALL_RECIPES, 5, 1);
	WEB		*REFERENCE_WEB =
		BUILD_RECIPE_WEB(MODEL_CONFIG, 9, 30, ALL_RECIPES, 5, 1);

	WEB_ADD_COPY(FAST_WEB);
	WEB_ADD_COPY(REFERENCE_WEB);
	RANDOMIZE_WEB(FAST_WEB, (float)0.3);

	int	KERNEL_FAILURES =
		CHECK_AGAINST_REFERENCE(FAST_WEB, REFERENCE_WEB, 30, 21, 1);

	printf(
		"  machine code vs slow reference, 5 recipes in every area: %s\n",
		KERNEL_FAILURES ? "FAIL" : "ok"
	);
	FAIL_COUNT += KERNEL_FAILURES;
	WEB_FREE(FAST_WEB);
	WEB_FREE(REFERENCE_WEB);
	FAIL_COUNT += TEST_RECIPE_RELOAD();
	printf("recipes: %s\n", FAIL_COUNT ? "FAILED" : "PASSED");

	return (FAIL_COUNT);
}
