#include "DATA.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

static double
	EVALUATE_WINDOWS(
		WEB *NEURAL_WEB, DATASET *TRAINING_DATA, WINDOW *WINDOWS,
		int64_t FIRST_WINDOW, int64_t END_WINDOW
	)
{
	int	MAX_TOKENS = NEURAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;

	WEB_SET_TRAINING(NEURAL_WEB, 1);

	int32_t	*SEQUENCE = malloc((MAX_TOKENS + 1) * 4);
	float	*WEIGHTS = malloc((MAX_TOKENS + 1) * 4);
	double	LOSS_SUM = 0;
	double	WEIGHT_SUM = 0;
	int64_t	WINDOW_INDEX;

	for (WINDOW_INDEX = FIRST_WINDOW; WINDOW_INDEX < END_WINDOW; WINDOW_INDEX++)
	{
		int		SEQUENCE_LENGTH = BUILD_SEQUENCE(
			TRAINING_DATA, &WINDOWS[WINDOW_INDEX], MAX_TOKENS, SEQUENCE, WEIGHTS
		);
		int32_t	*TOKENS =
			(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);
		int32_t	*TARGETS =
			(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TARGETS_OFFSET);
		float	*POSITION_WEIGHTS = (float *)(NEURAL_WEB->ACTIVATIONS +
											NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
		int		POSITION;

		for (POSITION = 0; POSITION < SEQUENCE_LENGTH - 1; POSITION++)
		{
			TOKENS[POSITION] = SEQUENCE[POSITION];
			TARGETS[POSITION] = SEQUENCE[POSITION + 1];
			POSITION_WEIGHTS[POSITION] = WEIGHTS[POSITION + 1];

			if (POSITION_WEIGHTS[POSITION] <= 0)
				TARGETS[POSITION] = -1;
		}

		NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = SEQUENCE_LENGTH - 1;
		NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
		NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE = 0;
		WEB_RUN(NEURAL_WEB, MODE_EVALUATE);

		for (POSITION = 0; POSITION < SEQUENCE_LENGTH - 1; POSITION++)
			if (TARGETS[POSITION] >= 0)
			{
				LOSS_SUM += POSITION_WEIGHTS[POSITION] *
					WEB_LOSS_AT(NEURAL_WEB, NEURAL_WEB->ACTIVATIONS, POSITION);
				WEIGHT_SUM += POSITION_WEIGHTS[POSITION];
			}
	}

	free(SEQUENCE);
	free(WEIGHTS);

	if (WEIGHT_SUM > 0)
		return (LOSS_SUM / WEIGHT_SUM);

	return (0);
}

int
	TEST_TRAIN_SMALL(const char *PATH)
{
	if (!FILE_EXISTS(PATH))
	{
		printf("train: %s not found, skipped\n", PATH);
		return (0);
	}

	printf(
		"train: fresh tiny brain learns from %s (held-out windows measured "
		"before/after)\n",
		PATH
	);

	LANGUAGE	*LEXICON = LANGUAGE_NEW();

	COUNT_FILE_WORDS(LEXICON, PATH);

	int32_t	*WORD_IDS = malloc(LEXICON->COUNT * 4);
	int32_t	WORD_INDEX;

	for (WORD_INDEX = 0; WORD_INDEX < LEXICON->COUNT; WORD_INDEX++)
		WORD_IDS[WORD_INDEX] = WORD_INDEX;

	for (
		WORD_INDEX = 0;
		WORD_INDEX < LEXICON->COUNT && WORD_INDEX < 2000;
		WORD_INDEX++
	)
	{
		int		SELECTED_INDEX = WORD_INDEX;
		int32_t	CANDIDATE_INDEX;

		for (
			CANDIDATE_INDEX = WORD_INDEX + 1;
			CANDIDATE_INDEX < LEXICON->COUNT;
			CANDIDATE_INDEX++
		)
			if (
				LEXICON->USE_COUNTS[WORD_IDS[CANDIDATE_INDEX]] >
					LEXICON->USE_COUNTS[WORD_IDS[SELECTED_INDEX]]
			)
				SELECTED_INDEX = CANDIDATE_INDEX;

		int32_t	SWAP_TEMPORARY = WORD_IDS[WORD_INDEX];

		WORD_IDS[WORD_INDEX] = WORD_IDS[SELECTED_INDEX];
		WORD_IDS[SELECTED_INDEX] = SWAP_TEMPORARY;

		if (LEXICON->USE_COUNTS[WORD_IDS[WORD_INDEX]] >= 3)
			LANGUAGE_VOCABULARY_ADD(LEXICON, WORD_IDS[WORD_INDEX]);
	}

	free(WORD_IDS);

	CONFIG	WEB_CONFIG = { 64, 2, 16, 64, 4096, 4, 128 };
	WEB		*NEURAL_WEB = WEB_NEW(WEB_CONFIG, 7);

	for (WORD_INDEX = 0; WORD_INDEX < LEXICON->TOKEN_COUNT; WORD_INDEX++)
		WEB_ADD_WORD(NEURAL_WEB);

	WEB_RELINK(NEURAL_WEB);

	DATASET	TRAINING_DATA = { 0 };

	LOAD_TRAINING_FILE(
		LEXICON, &TRAINING_DATA, PATH, WEB_CONFIG.MAXIMUM_LENGTH
	);
	DATASET_SET_FIRST_PERSON(&TRAINING_DATA, LEXICON);

	int64_t	WINDOW_COUNT;
	WINDOW	*WINDOWS =
		MAKE_WINDOWS(&TRAINING_DATA, WEB_CONFIG.MAXIMUM_LENGTH, &WINDOW_COUNT);
	int64_t	HELD_OUT_COUNT;

	if (WINDOW_COUNT / 10 > 64)
		HELD_OUT_COUNT = 64;
	else
		HELD_OUT_COUNT = WINDOW_COUNT / 10;

	int64_t		TRAIN_WINDOW_COUNT = WINDOW_COUNT - HELD_OUT_COUNT;
	double		LOSS_BEFORE = EVALUATE_WINDOWS(
		NEURAL_WEB, &TRAINING_DATA, WINDOWS, TRAIN_WINDOW_COUNT, WINDOW_COUNT
	);
	int32_t		*SEQUENCE = malloc((WEB_CONFIG.MAXIMUM_LENGTH + 1) * 4);
	float		*WEIGHTS = malloc((WEB_CONFIG.MAXIMUM_LENGTH + 1) * 4);
	uint64_t	RANDOM_STATE = 99;

	NEURAL_WEB->KERNEL_STATE->LEARNING_RATE = (float)3e-3;

	int	STEP;

	for (STEP = 0; STEP < 400; STEP++)
	{
		int64_t	PICKED_WINDOWS[8];
		double	WEIGHT_SUM = 0;
		int		SELECTED_INDEX;

		for (SELECTED_INDEX = 0; SELECTED_INDEX < 8; SELECTED_INDEX++)
		{
			PICKED_WINDOWS[SELECTED_INDEX] =
				(int64_t)(RANDOM_NEXT(&RANDOM_STATE) % TRAIN_WINDOW_COUNT);

			int	SEQUENCE_LENGTH = BUILD_SEQUENCE(
				&TRAINING_DATA, &WINDOWS[PICKED_WINDOWS[SELECTED_INDEX]],
				WEB_CONFIG.MAXIMUM_LENGTH, SEQUENCE, WEIGHTS
			);
			int	POSITION;

			for (POSITION = 1; POSITION < SEQUENCE_LENGTH; POSITION++)
				WEIGHT_SUM += WEIGHTS[POSITION];
		}

		NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE =
			(float)(1.0 / (WEIGHT_SUM > 0 ? WEIGHT_SUM : 1));

		for (SELECTED_INDEX = 0; SELECTED_INDEX < 8; SELECTED_INDEX++)
		{
			int	SEQUENCE_LENGTH = BUILD_SEQUENCE(
				&TRAINING_DATA, &WINDOWS[PICKED_WINDOWS[SELECTED_INDEX]],
				WEB_CONFIG.MAXIMUM_LENGTH, SEQUENCE, WEIGHTS
			);

			LEARN_WINDOW(NEURAL_WEB, SEQUENCE, SEQUENCE_LENGTH, WEIGHTS, NULL);
		}

		LEARN_UPDATE(NEURAL_WEB);

		if ((STEP + 1) % 100 == 0)
			printf(
				"  step %d: held-out loss %.3f\n", STEP + 1,
				EVALUATE_WINDOWS(
					NEURAL_WEB, &TRAINING_DATA, WINDOWS, TRAIN_WINDOW_COUNT,
					WINDOW_COUNT
				)
			);
	}

	double	LOSS_AFTER = EVALUATE_WINDOWS(
		NEURAL_WEB, &TRAINING_DATA, WINDOWS, TRAIN_WINDOW_COUNT, WINDOW_COUNT
	);
	int		PASSED = LOSS_AFTER < LOSS_BEFORE - 1.0;

	printf(
		"train: held-out loss %.3f -> %.3f : %s\n", LOSS_BEFORE, LOSS_AFTER,
		PASSED ? "PASSED" : "FAILED"
	);
	free(SEQUENCE);
	free(WEIGHTS);
	free(WINDOWS);
	DATASET_FREE(&TRAINING_DATA);
	WEB_FREE(NEURAL_WEB);
	LANGUAGE_FREE(LEXICON);

	if (PASSED)
		return (0);

	return (1);
}

int
	TEST_BRAIN_RELOAD(void)
{
	const char	*PATH = FILE_EXISTS(GLOBAL_WEB_PATH) ? GLOBAL_WEB_PATH
		: FILE_EXISTS(START_WEB_PATH) ? START_WEB_PATH
													: NULL;

	if (!PATH)
	{
		printf("brain reload: no brain yet, skipped\n");
		return (0);
	}

	WEB	*ORIGINAL_WEB = WEB_LOAD(PATH);

	if (!ORIGINAL_WEB)
	{
		printf("brain reload: cannot load %s: FAILED\n", PATH);
		return (1);
	}

	int	TOKEN_COUNT;

	if (ORIGINAL_WEB->CONFIGURATION.MAXIMUM_LENGTH < 64)
		TOKEN_COUNT = ORIGINAL_WEB->CONFIGURATION.MAXIMUM_LENGTH;
	else
		TOKEN_COUNT = 64;

	uint64_t	RANDOM_STATE = 5;
	int32_t		*TOKENS =
		(int32_t *)(ORIGINAL_WEB->ACTIVATIONS + ORIGINAL_WEB->TOKENS_OFFSET);
	int			POSITION;

	for (POSITION = 0; POSITION < TOKEN_COUNT; POSITION++)
		TOKENS[POSITION] =
			(int32_t)(RANDOM_NEXT(&RANDOM_STATE) % ORIGINAL_WEB->WORD_COUNT);

	ORIGINAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	ORIGINAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(ORIGINAL_WEB, MODE_INFER);
	WEB_ROUND_TO_HALF(ORIGINAL_WEB);
	WEB_RUN(ORIGINAL_WEB, MODE_INFER);
	WEB_SAVE(ORIGINAL_WEB, "reload_test.web", 0);

	WEB	*RELOADED_WEB = WEB_LOAD("reload_test.web");
	int	IS_SAME = RELOADED_WEB != NULL;

	if (IS_SAME)
	{
		memcpy(
			RELOADED_WEB->ACTIVATIONS + RELOADED_WEB->TOKENS_OFFSET, TOKENS,
			TOKEN_COUNT * 4
		);
		RELOADED_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
		RELOADED_WEB->KERNEL_STATE->START_POSITION = 0;
		WEB_RUN(RELOADED_WEB, MODE_INFER);
		IS_SAME =
			!memcmp(
				WEB_LAST_LOGITS(ORIGINAL_WEB), WEB_LAST_LOGITS(RELOADED_WEB),
				(size_t)ORIGINAL_WEB->WORD_COUNT * 4
			) &&
			!memcmp(
				ORIGINAL_WEB->ACTIVATIONS +
					LAYER_RESIDUAL(
						ORIGINAL_WEB,
						2 * ORIGINAL_WEB->CONFIGURATION.LAYER_COUNT
					),
				RELOADED_WEB->ACTIVATIONS +
					LAYER_RESIDUAL(
						RELOADED_WEB,
						2 * RELOADED_WEB->CONFIGURATION.LAYER_COUNT
					),
				(size_t)TOKEN_COUNT * ORIGINAL_WEB->CONFIGURATION.DIMENSION * 4
			);
	}

	WEB	*PLAY_WEB = WEB_LOAD_PLAY("reload_test.web");
	int	PLAY_SAME = PLAY_WEB != NULL;

	if (PLAY_SAME)
	{
		memcpy(
			PLAY_WEB->ACTIVATIONS + PLAY_WEB->TOKENS_OFFSET, TOKENS,
			TOKEN_COUNT * 4
		);
		PLAY_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
		PLAY_WEB->KERNEL_STATE->START_POSITION = 0;
		WEB_RUN(PLAY_WEB, MODE_INFER);
		PLAY_SAME = !memcmp(
			WEB_LAST_LOGITS(ORIGINAL_WEB), WEB_LAST_LOGITS(PLAY_WEB),
			(size_t)ORIGINAL_WEB->WORD_COUNT * 4
		);
	}

	printf(
		"brain reload (%s, %d neurons, %lld params): save -> load -> run gives "
		"bit-identical logits: %s\n",
		PATH, ORIGINAL_WEB->NEURON_COUNT,
		(long long)WEB_PARAMETER_COUNT(ORIGINAL_WEB),
		IS_SAME ? "PASSED" : "FAILED"
	);
	printf(
		"play mode (16-bit weights in RAM, JIT recompiled for play) gives "
		"bit-identical logits: %s\n",
		PLAY_SAME ? "PASSED" : "FAILED"
	);
	IS_SAME = IS_SAME && PLAY_SAME;

	if (PLAY_WEB)
		WEB_FREE(PLAY_WEB);

	remove("reload_test.web");
	WEB_FREE(ORIGINAL_WEB);

	if (RELOADED_WEB)
		WEB_FREE(RELOADED_WEB);

	if (IS_SAME)
		return (0);

	return (1);
}
