#include "CODE.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

void	RANDOMIZE_WEB(WEB *NEURAL_WEB, float SCALE);
int		CHECK_AGAINST_REFERENCE(
	WEB *JIT_WEB, WEB *REFERENCE_WEB, int VOCABULARY_SIZE, int TOKEN_COUNT,
	int WITH_COPY
);

static void
	SHAPE_LAST_LOGITS(
		WEB *NEURAL_WEB, const int32_t *SOURCE_TOKENS, int POSITION_COUNT,
		float *OUTPUT
	)
{
	int32_t	*INPUT_TOKENS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);

	memcpy(INPUT_TOKENS, SOURCE_TOKENS, POSITION_COUNT * 4);
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = POSITION_COUNT;
	WEB_RUN(NEURAL_WEB, MODE_INFER);
	memcpy(OUTPUT, WEB_LAST_LOGITS(NEURAL_WEB), NEURAL_WEB->WORD_COUNT * 4);
}

static float
	TRAIN_SHAPE_STEPS(
		WEB *NEURAL_WEB, const int32_t *SOURCE_TOKENS, int POSITION_COUNT,
		int STEP_COUNT
	)
{
	float	LAST_LOSS = 0;
	int		STEP_INDEX;

	for (STEP_INDEX = 0; STEP_INDEX < STEP_COUNT; STEP_INDEX++)
	{
		int32_t	*INPUT_TOKENS =
			(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);
		int32_t	*TARGETS =
			(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TARGETS_OFFSET);
		float	*TOKEN_WEIGHTS = (float *)(NEURAL_WEB->ACTIVATIONS +
			NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
		int		POSITION;

		for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
		{
			INPUT_TOKENS[POSITION] = SOURCE_TOKENS[POSITION];
			TARGETS[POSITION] = SOURCE_TOKENS[POSITION + 1];
			TOKEN_WEIGHTS[POSITION] = 1;
		}

		NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = POSITION_COUNT;
		NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
		NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE = (float)1.0 / POSITION_COUNT;
		NEURAL_WEB->KERNEL_STATE->LEARNING_RATE = (float)3e-3;
		NEURAL_WEB->KERNEL_STATE->GRADIENT_SKIP_THRESHOLD = 0;
		WEB_RUN(NEURAL_WEB, MODE_TRAIN);

		double	LOSS_SUM = 0;

		for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
			LOSS_SUM +=
				WEB_LOSS_AT(NEURAL_WEB, NEURAL_WEB->ACTIVATIONS, POSITION);

		LAST_LOSS = (float)(LOSS_SUM / POSITION_COUNT);
		WEB_RUN(NEURAL_WEB, MODE_UPDATE);
	}

	return (LAST_LOSS);
}

static int
	TEST_ONE_RESHAPE(
		int ADDED_LAYERS, int NEW_WIDTH, int NEW_CONTEXT, uint64_t SEED
	)
{
	int		FAIL_COUNT = 0;
	int		VOCABULARY_SIZE = 40;
	int		POSITION_COUNT = 20;
	CONFIG	MODEL_CONFIG = { 64, 2, 16, 32, 64, 2, 16 };
	WEB		*ORIGINAL_WEB = WEB_NEW(MODEL_CONFIG, SEED);
	int		INDEX;

	for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
		WEB_ADD_WORD(ORIGINAL_WEB);

	WEB_RELINK(ORIGINAL_WEB);
	WEB_ADD_COPY(ORIGINAL_WEB);
	RANDOMIZE_WEB(ORIGINAL_WEB, (float)0.2);

	int	LAYER_INDEX;

	for (
		LAYER_INDEX = 0;
		LAYER_INDEX <= 2 * MODEL_CONFIG.LAYER_COUNT;
		LAYER_INDEX++
	)
	{
		float	*NORM_GAINS = NEURON_PARAMETERS(
			ORIGINAL_WEB, ORIGINAL_WEB->NORM_IDS[LAYER_INDEX]
		);
		int		INDEX;

		for (INDEX = 0; INDEX < MODEL_CONFIG.DIMENSION; INDEX++)
			NORM_GAINS[INDEX] =
				(float)1.0 + (float)0.1 * WEB_GAUSSIAN(ORIGINAL_WEB);
	}

	int32_t	TEST_TOKENS[64];

	for (INDEX = 0; INDEX < 64; INDEX++)
		TEST_TOKENS[INDEX] =
			(int32_t)(RANDOM_NEXT(&ORIGINAL_WEB->RANDOM_STATE) % VOCABULARY_SIZE
			);

	float	*ORIGINAL_LOGITS = malloc(VOCABULARY_SIZE * 4);
	float	*RESHAPED_LOGITS = malloc(VOCABULARY_SIZE * 4);

	SHAPE_LAST_LOGITS(
		ORIGINAL_WEB, TEST_TOKENS, POSITION_COUNT, ORIGINAL_LOGITS
	);

	SHAPE	NEW_SHAPE = {
		NEW_CONTEXT, 0, 3, 1, ADDED_LAYERS, NEW_WIDTH, 12, 2, 0
	};
	WEB		*RESHAPED_WEB = WEB_RESHAPE_SHAPE(ORIGINAL_WEB, NEW_SHAPE);
	WEB		*REFERENCE_WEB = WEB_RESHAPE_SHAPE(ORIGINAL_WEB, NEW_SHAPE);

	if (!RESHAPED_WEB || !REFERENCE_WEB)
	{
		printf("  reshape failed\n");
		return (1);
	}

	SHAPE_LAST_LOGITS(
		RESHAPED_WEB, TEST_TOKENS, POSITION_COUNT, RESHAPED_LOGITS
	);

	double	MAX_DIFFERENCE = 0;
	double	MAX_LOGIT = 0;

	for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
	{
		double	LOGIT_DIFFERENCE =
			fabs(ORIGINAL_LOGITS[INDEX] - RESHAPED_LOGITS[INDEX]);

		if (LOGIT_DIFFERENCE > MAX_DIFFERENCE)
			MAX_DIFFERENCE = LOGIT_DIFFERENCE;

		if (fabs(ORIGINAL_LOGITS[INDEX]) > MAX_LOGIT)
			MAX_LOGIT = fabs(ORIGINAL_LOGITS[INDEX]);
	}

	int	MISMATCH = MAX_DIFFERENCE / (MAX_LOGIT + 1e-9) >
		(NEW_WIDTH > MODEL_CONFIG.DIMENSION ? 2e-6 : 1e-6);

	printf(
		"  layers %d->%d width %d->%d context %d->%d params %lld->%lld: same "
		"answers (max logit diff %.3g of %.3g) %s\n",
		ORIGINAL_WEB->CONFIGURATION.LAYER_COUNT,
		RESHAPED_WEB->CONFIGURATION.LAYER_COUNT,
		ORIGINAL_WEB->CONFIGURATION.DIMENSION,
		RESHAPED_WEB->CONFIGURATION.DIMENSION,
		ORIGINAL_WEB->CONFIGURATION.MAXIMUM_LENGTH,
		RESHAPED_WEB->CONFIGURATION.MAXIMUM_LENGTH,
		(long long)WEB_PARAMETER_COUNT(ORIGINAL_WEB),
		(long long)WEB_PARAMETER_COUNT(RESHAPED_WEB), MAX_DIFFERENCE, MAX_LOGIT,
		MISMATCH ? "FAIL" : "ok"
	);
	FAIL_COUNT += MISMATCH;

	int	KERNEL_FAILURES = CHECK_AGAINST_REFERENCE(
		RESHAPED_WEB, REFERENCE_WEB, VOCABULARY_SIZE, POSITION_COUNT, 1
	);

	printf(
		"  machine code of the grown brain vs slow reference: %s\n",
		KERNEL_FAILURES ? "FAIL" : "ok"
	);
	FAIL_COUNT += KERNEL_FAILURES;
	WEB_FREE(RESHAPED_WEB);
	WEB_FREE(REFERENCE_WEB);
	RESHAPED_WEB = WEB_RESHAPE_SHAPE(ORIGINAL_WEB, NEW_SHAPE);
	WEB_SET_OPTIMIZER(RESHAPED_WEB, 1);

	int	NEW_LAYER = -1;

	for (
		LAYER_INDEX = 0;
		LAYER_INDEX < 2 * RESHAPED_WEB->CONFIGURATION.LAYER_COUNT;
		LAYER_INDEX += 2
	)
		if (
			RESHAPED_WEB->AREAS[LAYER_INDEX].GROWN_COUNT == 2 &&
			WEB_COUNT_NEURONS(
				RESHAPED_WEB, KIND_ATTENTION_HEAD, LAYER_INDEX
			) == 2 &&
			ADDED_LAYERS
		)
		{
			NEW_LAYER = LAYER_INDEX;
			break ;
		}

	float	*EMBEDDINGS =
		NEURON_PARAMETERS(RESHAPED_WEB, RESHAPED_WEB->EMBEDDING_ID);
	double	WIDTH_BEFORE = 0;
	int		POSITION;

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
	{
		int	INDEX;

		for (
			INDEX = MODEL_CONFIG.DIMENSION;
			INDEX < RESHAPED_WEB->CONFIGURATION.DIMENSION;
			INDEX++
		)
			WIDTH_BEFORE += fabs(
				EMBEDDINGS
					[(int64_t)POSITION * RESHAPED_WEB->CONFIGURATION.DIMENSION +
						INDEX]
			);
	}

	float	*HEAD_WEIGHTS;

	if (NEW_LAYER >= 0)
		HEAD_WEIGHTS = NEURON_PARAMETERS(
			RESHAPED_WEB, RESHAPED_WEB->AREAS[NEW_LAYER].MEMBERS[0]
		);
	else
		HEAD_WEIGHTS = NULL;

	double	HEAD_BEFORE = 0;
	int64_t	HEAD_BLOCK_SIZE =
		(int64_t)RESHAPED_WEB->CONFIGURATION.HEAD_DIMENSION *
		RESHAPED_WEB->CONFIGURATION.DIMENSION;

	if (HEAD_WEIGHTS)
	{
		int64_t	INDEX;

		for (INDEX = 0; INDEX < HEAD_BLOCK_SIZE; INDEX++)
			HEAD_BEFORE += fabs(HEAD_WEIGHTS[3 * HEAD_BLOCK_SIZE + INDEX]);
	}

	float	FIRST_LOSS = TRAIN_SHAPE_STEPS(RESHAPED_WEB, TEST_TOKENS, 30, 1);
	float	LAST_LOSS = TRAIN_SHAPE_STEPS(RESHAPED_WEB, TEST_TOKENS, 30, 150);
	double	WIDTH_AFTER = 0;
	double	HEAD_AFTER = 0;

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
	{
		int	INDEX;

		for (
			INDEX = MODEL_CONFIG.DIMENSION;
			INDEX < RESHAPED_WEB->CONFIGURATION.DIMENSION;
			INDEX++
		)
			WIDTH_AFTER += fabs(
				EMBEDDINGS
					[(int64_t)POSITION * RESHAPED_WEB->CONFIGURATION.DIMENSION +
						INDEX]
			);
	}

	if (HEAD_WEIGHTS)
	{
		int64_t	INDEX;

		for (INDEX = 0; INDEX < HEAD_BLOCK_SIZE; INDEX++)
			HEAD_AFTER += fabs(HEAD_WEIGHTS[3 * HEAD_BLOCK_SIZE + INDEX]);
	}

	int	LEARNS = LAST_LOSS < FIRST_LOSS * (float)0.5 &&
		(NEW_WIDTH <= MODEL_CONFIG.DIMENSION ||
			(WIDTH_BEFORE == 0 && WIDTH_AFTER > 0)) &&
		(!HEAD_WEIGHTS || (HEAD_BEFORE == 0 && HEAD_AFTER > 0));

	printf(
		"  grown brain learns: loss %.3f -> %.3f; new width numbers %.3g -> "
		"%.3g; new layer head output %.3g -> %.3g %s\n",
		FIRST_LOSS, LAST_LOSS, WIDTH_BEFORE, WIDTH_AFTER, HEAD_BEFORE,
		HEAD_AFTER, LEARNS ? "ok" : "FAIL"
	);
	FAIL_COUNT += !LEARNS;
	WEB_FREE(RESHAPED_WEB);
	WEB_FREE(ORIGINAL_WEB);
	free(ORIGINAL_LOGITS);
	free(RESHAPED_LOGITS);

	return (FAIL_COUNT);
}

int
	TEST_RESHAPE(void)
{
	printf(
		"reshape: grow a brain in every direction without changing its "
		"answers\n"
	);

	int	FAIL_COUNT = TEST_ONE_RESHAPE(2, 0, 0, 5) +
		TEST_ONE_RESHAPE(0, 96, 0, 6) + TEST_ONE_RESHAPE(3, 128, 48, 7) +
		TEST_ONE_RESHAPE(1, 0, 40, 8);

	printf("reshape: %s\n", FAIL_COUNT ? "FAILED" : "PASSED");

	return (FAIL_COUNT);
}

static double
	ROPE_EVALUATION_LOSS(WEB *NEURAL_WEB, int POSITION_COUNT)
{
	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = POSITION_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_EVALUATE);

	double	LOSS_SUM = 0;
	int		POSITION;

	for (POSITION = 0; POSITION < POSITION_COUNT; POSITION++)
		LOSS_SUM += NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE *
			WEB_LOSS_AT(NEURAL_WEB, NEURAL_WEB->ACTIVATIONS, POSITION);

	return (LOSS_SUM);
}

int
	TEST_ROTARY_POSITIONS(void)
{
	int	FAIL_COUNT = 0;
	int	VOCABULARY_SIZE = 30;
	int	POSITION_COUNT = 23;

	printf("rope: attention heads that see relative positions (rotary)\n");

	CONFIG	MODEL_CONFIG = { 64, 2, 16, 32, 64, 2, 16 };
	WEB		*FAST_WEB = WEB_NEW(MODEL_CONFIG, 91);
	WEB		*REFERENCE_WEB = WEB_NEW(MODEL_CONFIG, 91);
	WEB		*WEBS[2] = { FAST_WEB, REFERENCE_WEB };
	int		CHECK_INDEX;

	for (CHECK_INDEX = 0; CHECK_INDEX < 2; CHECK_INDEX++)
	{
		int	INDEX;

		for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
			WEB_ADD_WORD(WEBS[CHECK_INDEX]);

		int	AREA_INDEX;

		for (
			AREA_INDEX = 0;
			AREA_INDEX < 2 * MODEL_CONFIG.LAYER_COUNT;
			AREA_INDEX += 2
		)
		{
			int	HEAD_INDEX;

			for (HEAD_INDEX = 0; HEAD_INDEX < 2; HEAD_INDEX++)
				WEB_ADD_NEURON(
					WEBS[CHECK_INDEX], KIND_ATTENTION_HEAD, AREA_INDEX,
					WHY_SEED, 1
				);
		}

		WEB_RELINK(WEBS[CHECK_INDEX]);
		WEB_ADD_COPY(WEBS[CHECK_INDEX]);
	}

	RANDOMIZE_WEB(FAST_WEB, (float)0.3);

	int	KERNEL_FAILURES = CHECK_AGAINST_REFERENCE(
		FAST_WEB, REFERENCE_WEB, VOCABULARY_SIZE, POSITION_COUNT, 1
	);

	printf(
		"  machine code vs slow reference with rotary heads: %s\n",
		KERNEL_FAILURES ? "FAIL" : "ok"
	);
	FAIL_COUNT += KERNEL_FAILURES;

	int32_t	*INPUT_TOKENS =
		(int32_t *)(FAST_WEB->ACTIVATIONS + FAST_WEB->TOKENS_OFFSET);
	int32_t	*TARGETS =
		(int32_t *)(FAST_WEB->ACTIVATIONS + FAST_WEB->TARGETS_OFFSET);
	float	*TOKEN_WEIGHTS =
		(float *)(FAST_WEB->ACTIVATIONS + FAST_WEB->LOSS_WEIGHTS_OFFSET);
	int		POSITION;

	for (POSITION = 0; POSITION < MODEL_CONFIG.MAXIMUM_LENGTH; POSITION++)
	{
		INPUT_TOKENS[POSITION] =
			RANDOM_NEXT(&FAST_WEB->RANDOM_STATE) % VOCABULARY_SIZE;
		TARGETS[POSITION] =
			RANDOM_NEXT(&FAST_WEB->RANDOM_STATE) % VOCABULARY_SIZE;
		TOKEN_WEIGHTS[POSITION] = 1;
	}

	FAST_WEB->KERNEL_STATE->GRADIENT_SCALE = (float)1.0 / POSITION_COUNT;
	FAST_WEB->KERNEL_STATE->GRADIENT_SKIP_THRESHOLD = 0;

	int32_t	INDEX;

	for (INDEX = 0; INDEX < FAST_WEB->NEURON_COUNT; INDEX++)
		if (FAST_WEB->NEURONS[INDEX].PARAMETER_COUNT)
			memset(
				NEURON_GRADIENTS(FAST_WEB, INDEX), 0,
				FAST_WEB->NEURONS[INDEX].PARAMETER_COUNT * 4
			);

	FAST_WEB->KERNEL_STATE->SEQUENCE_LENGTH = POSITION_COUNT;
	FAST_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(FAST_WEB, MODE_TRAIN);

	double	WORST_ERROR = 0;
	int		BAD_COUNT = 0;

	for (CHECK_INDEX = 0; CHECK_INDEX < 6; CHECK_INDEX++)
	{
		int32_t	HEAD_NEURON = -1;
		int32_t	INDEX;

		for (INDEX = 0; INDEX < FAST_WEB->NEURON_COUNT; INDEX++)
			if (
				FAST_WEB->NEURONS[INDEX].KIND == KIND_ATTENTION_HEAD &&
				FAST_WEB->NEURONS[INDEX].KIND_DETAIL == 1 &&
				FAST_WEB->NEURONS[INDEX].AREA_INDEX == (CHECK_INDEX % 2) * 2
			)
			{
				HEAD_NEURON = INDEX;
				break ;
			}

		int64_t	HEAD_BLOCK_SIZE =
			(int64_t)MODEL_CONFIG.HEAD_DIMENSION * MODEL_CONFIG.DIMENSION;
		int64_t	PARAMETER_OFFSET =
			(CHECK_INDEX / 2) * HEAD_BLOCK_SIZE + 17 + CHECK_INDEX;
		float	*PARAMETER_POINTER =
			NEURON_PARAMETERS(FAST_WEB, HEAD_NEURON) + PARAMETER_OFFSET;
		float	ANALYTIC_GRADIENT =
			NEURON_GRADIENTS(FAST_WEB, HEAD_NEURON)[PARAMETER_OFFSET];
		float	OLD_VALUE = *PARAMETER_POINTER;
		float	STEP_SIZE = (float)3e-3;

		*PARAMETER_POINTER = OLD_VALUE + STEP_SIZE;

		double	LOSS_PLUS = ROPE_EVALUATION_LOSS(FAST_WEB, POSITION_COUNT);

		*PARAMETER_POINTER = OLD_VALUE - STEP_SIZE;

		double	LOSS_MINUS = ROPE_EVALUATION_LOSS(FAST_WEB, POSITION_COUNT);

		*PARAMETER_POINTER = OLD_VALUE;

		double	NUMERIC_GRADIENT = (LOSS_PLUS - LOSS_MINUS) / (2 * STEP_SIZE);
		double	RELATIVE_ERROR = fabs(NUMERIC_GRADIENT - ANALYTIC_GRADIENT) /
			(fabs(NUMERIC_GRADIENT) + fabs(ANALYTIC_GRADIENT) + 1e-3);

		if (RELATIVE_ERROR > WORST_ERROR)
			WORST_ERROR = RELATIVE_ERROR;

		if (RELATIVE_ERROR > 0.05)
		{
			printf(
				"    rotary head weight %d: analytic %+.6f numeric %+.6f "
				"FAIL\n",
				CHECK_INDEX, ANALYTIC_GRADIENT, NUMERIC_GRADIENT
			);
			BAD_COUNT++;
		}
	}

	printf(
		"  rotary head query/key/value weights vs finite differences: worst "
		"relative error %.3g %s\n",
		WORST_ERROR, BAD_COUNT ? "FAIL" : "ok"
	);
	FAIL_COUNT += BAD_COUNT;
	WEB_FREE(FAST_WEB);
	WEB_FREE(REFERENCE_WEB);

	WEB	*ORIGINAL_WEB = WEB_NEW(MODEL_CONFIG, 92);

	for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
		WEB_ADD_WORD(ORIGINAL_WEB);

	WEB_RELINK(ORIGINAL_WEB);
	WEB_ADD_COPY(ORIGINAL_WEB);
	RANDOMIZE_WEB(ORIGINAL_WEB, (float)0.2);

	int32_t	TEST_TOKENS[32];

	for (INDEX = 0; INDEX < 32; INDEX++)
		TEST_TOKENS[INDEX] =
			(int32_t)(RANDOM_NEXT(&ORIGINAL_WEB->RANDOM_STATE) % VOCABULARY_SIZE
			);

	float	*ORIGINAL_LOGITS = malloc(VOCABULARY_SIZE * 4);
	float	*COMPARED_LOGITS = malloc(VOCABULARY_SIZE * 4);

	SHAPE_LAST_LOGITS(
		ORIGINAL_WEB, TEST_TOKENS, POSITION_COUNT, ORIGINAL_LOGITS
	);

	SHAPE	NEW_SHAPE = { 0, 0, 0, 2, 1, 0, 8, 2, 1 };
	WEB		*GROWN_WEB = WEB_RESHAPE_SHAPE(ORIGINAL_WEB, NEW_SHAPE);

	SHAPE_LAST_LOGITS(GROWN_WEB, TEST_TOKENS, POSITION_COUNT, COMPARED_LOGITS);

	double	MAX_DIFFERENCE = 0;

	for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
		MAX_DIFFERENCE = fmax(
			MAX_DIFFERENCE,
			fabs(ORIGINAL_LOGITS[INDEX] - COMPARED_LOGITS[INDEX])
		);

	int	ROTARY_COUNT = 0;

	for (INDEX = 0; INDEX < GROWN_WEB->NEURON_COUNT; INDEX++)
		ROTARY_COUNT += GROWN_WEB->NEURONS[INDEX].KIND == KIND_ATTENTION_HEAD &&
			GROWN_WEB->NEURONS[INDEX].KIND_DETAIL == 1 &&
			GROWN_WEB->NEURONS[INDEX].ALIVE;

	printf(
		"  growing %d new rotary heads keeps the answers (max logit diff %g) "
		"%s\n",
		ROTARY_COUNT, MAX_DIFFERENCE,
		MAX_DIFFERENCE == 0 && ROTARY_COUNT == 6 ? "ok" : "FAIL"
	);
	FAIL_COUNT += !(MAX_DIFFERENCE == 0 && ROTARY_COUNT == 6);

	const char	*PATH = "trope_tmp.web";

	WEB_ROUND_TO_HALF(GROWN_WEB);
	SHAPE_LAST_LOGITS(GROWN_WEB, TEST_TOKENS, POSITION_COUNT, ORIGINAL_LOGITS);
	WEB_SAVE(GROWN_WEB, PATH, 0);

	WEB	*LOADED_WEB = WEB_LOAD(PATH);
	WEB	*PLAY_WEB = WEB_LOAD_PLAY(PATH);

	SHAPE_LAST_LOGITS(LOADED_WEB, TEST_TOKENS, POSITION_COUNT, COMPARED_LOGITS);

	double	LOADED_DIFFERENCE = 0;
	double	PLAY_DIFFERENCE = 0;

	for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
		LOADED_DIFFERENCE = fmax(
			LOADED_DIFFERENCE,
			fabs(ORIGINAL_LOGITS[INDEX] - COMPARED_LOGITS[INDEX])
		);

	SHAPE_LAST_LOGITS(PLAY_WEB, TEST_TOKENS, POSITION_COUNT, COMPARED_LOGITS);

	for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
		PLAY_DIFFERENCE = fmax(
			PLAY_DIFFERENCE,
			fabs(ORIGINAL_LOGITS[INDEX] - COMPARED_LOGITS[INDEX])
		);

	printf(
		"  rotary heads after save/load %g and in 16-bit play mode %g %s\n",
		LOADED_DIFFERENCE, PLAY_DIFFERENCE,
		LOADED_DIFFERENCE == 0 && PLAY_DIFFERENCE < 1e-4 ? "ok" : "FAIL"
	);
	FAIL_COUNT += !(LOADED_DIFFERENCE == 0 && PLAY_DIFFERENCE < 1e-4);
	remove(PATH);
	WEB_FREE(GROWN_WEB);
	WEB_FREE(LOADED_WEB);
	WEB_FREE(PLAY_WEB);
	WEB_FREE(ORIGINAL_WEB);
	free(ORIGINAL_LOGITS);
	free(COMPARED_LOGITS);
	printf("rope: %s\n", FAIL_COUNT ? "FAILED" : "PASSED");

	return (FAIL_COUNT);
}
