#include "NEAREST_NEIGHBOR.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

void	RANDOMIZE_WEB(WEB *NEURAL_WEB, float SCALE);

static void
	SET_SIGNAL_WEIGHTS(
		WEB *NEURAL_WEB, const int32_t *TOKENS, const float *SIGNAL_WEIGHTS,
		int TOKEN_COUNT
	)
{
	int32_t	*TOKEN_SLOTS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);
	int32_t	*TARGET_SLOTS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TARGETS_OFFSET);
	float	*WEIGHT_SLOTS =
		(float *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
	double	WEIGHT_SUM = 0;
	int		POSITION;

	for (POSITION = 0; POSITION < TOKEN_COUNT; POSITION++)
	{
		TOKEN_SLOTS[POSITION] = TOKENS[POSITION];

		if (SIGNAL_WEIGHTS[POSITION + 1] != 0)
			TARGET_SLOTS[POSITION] = TOKENS[POSITION + 1];
		else
			TARGET_SLOTS[POSITION] = -1;

		WEIGHT_SLOTS[POSITION] = SIGNAL_WEIGHTS[POSITION + 1];
		WEIGHT_SUM += fabs(SIGNAL_WEIGHTS[POSITION + 1]);
	}

	NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE = (float)(1.0 / WEIGHT_SUM);
	NEURAL_WEB->KERNEL_STATE->GRADIENT_SKIP_THRESHOLD = 0;
}

static double
	SIGNAL_OBJECTIVE(
		WEB *NEURAL_WEB, const int32_t *TOKENS, const float *SIGNAL_WEIGHTS,
		int TOKEN_COUNT
	)
{
	SET_SIGNAL_WEIGHTS(NEURAL_WEB, TOKENS, SIGNAL_WEIGHTS, TOKEN_COUNT);
	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_EVALUATE);

	double	TOTAL_LOSS = 0;
	int		POSITION;

	for (POSITION = 0; POSITION < TOKEN_COUNT; POSITION++)
	{
		if (SIGNAL_WEIGHTS[POSITION + 1] == 0)
			continue ;

		double	POSITION_LOSS =
			WEB_LOSS_AT(NEURAL_WEB, NEURAL_WEB->ACTIVATIONS, POSITION);

		if (SIGNAL_WEIGHTS[POSITION + 1] > 0)
			TOTAL_LOSS += SIGNAL_WEIGHTS[POSITION + 1] * POSITION_LOSS;
		else
			TOTAL_LOSS +=
				-SIGNAL_WEIGHTS[POSITION + 1] * -log(1 - exp(-POSITION_LOSS));
	}

	return (TOTAL_LOSS * NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE);
}

static float
	NEXT_WORD_PROBABILITY(
		WEB *NEURAL_WEB, const int32_t *CONTEXT_TOKENS, int TOKEN_COUNT,
		int32_t WANTED_TOKEN
	)
{
	int32_t	*TOKEN_SLOTS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);

	memcpy(TOKEN_SLOTS, CONTEXT_TOKENS, TOKEN_COUNT * 4);
	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_INFER);

	float	*LOGITS = WEB_LAST_LOGITS(NEURAL_WEB);
	float	MAXIMUM_LOGIT = -(float)1e30;
	double	EXPONENT_SUM = 0;
	int		VOCABULARY_INDEX;

	for (
		VOCABULARY_INDEX = 0;
		VOCABULARY_INDEX < NEURAL_WEB->WORD_COUNT;
		VOCABULARY_INDEX++
	)
		if (LOGITS[VOCABULARY_INDEX] > MAXIMUM_LOGIT)
			MAXIMUM_LOGIT = LOGITS[VOCABULARY_INDEX];

	for (
		VOCABULARY_INDEX = 0;
		VOCABULARY_INDEX < NEURAL_WEB->WORD_COUNT;
		VOCABULARY_INDEX++
	)
		EXPONENT_SUM += exp(LOGITS[VOCABULARY_INDEX] - MAXIMUM_LOGIT);

	double	PROBABILITY =
		exp(LOGITS[WANTED_TOKEN] - MAXIMUM_LOGIT) / EXPONENT_SUM;

	if (NEURAL_WEB->COPY_ID >= 0)
	{
		int64_t	COPY_OFFSET_TABLE[10];

		COPY_HEAD_OFFSETS(NEURAL_WEB, COPY_OFFSET_TABLE);

		double	COPY_GATE = ((float *)(NEURAL_WEB->ACTIVATIONS +
			COPY_OFFSET_TABLE[3]))[TOKEN_COUNT - 1];
		double	COPY_PROBABILITY = 0;
		float	*ATTENTION_ROW = WEB_COPY_ATTENTION_ROW(
			NEURAL_WEB, NEURAL_WEB->ACTIVATIONS, TOKEN_COUNT - 1
		);
		int		POSITION;

		for (POSITION = 0; POSITION < TOKEN_COUNT; POSITION++)
			if (TOKEN_SLOTS[POSITION] == WANTED_TOKEN)
				COPY_PROBABILITY += ATTENTION_ROW[POSITION];

		PROBABILITY =
			(1 - COPY_GATE) * PROBABILITY + COPY_GATE * COPY_PROBABILITY;
	}

	return ((float)PROBABILITY);
}

int
	TEST_SIGNALS(void)
{
	int	FAILURE_COUNT = 0;

	printf("signals: learning to avoid an answer (unlikelihood), next to "
		"learning to say one\n");

	CONFIG	WEB_CONFIG = { 64, 2, 16, 24, 32, 2, 16 };
	WEB		*NEURAL_WEB = WEB_NEW(WEB_CONFIG, 71);
	int		INDEX;

	for (INDEX = 0; INDEX < 20; INDEX++)
		WEB_ADD_WORD(NEURAL_WEB);

	WEB_RELINK(NEURAL_WEB);
	WEB_ADD_COPY(NEURAL_WEB);
	RANDOMIZE_WEB(NEURAL_WEB, (float)0.3);

	int		TOKEN_COUNT = 15;
	int32_t	TOKENS[16];
	float	SIGNAL_WEIGHTS[16];
	int		POSITION;

	for (POSITION = 0; POSITION <= TOKEN_COUNT; POSITION++)
	{
		TOKENS[POSITION] =
			(int32_t)(RANDOM_NEXT(&NEURAL_WEB->RANDOM_STATE) % 20);

		if (POSITION < 3)
			SIGNAL_WEIGHTS[POSITION] = 0;
		else if (POSITION % 3 == 0)
			SIGNAL_WEIGHTS[POSITION] = -(float)1.0;
		else
			SIGNAL_WEIGHTS[POSITION] = (float)0.7;
	}

	int32_t	NEURON_INDEX;

	for (
		NEURON_INDEX = 0;
		NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
		NEURON_INDEX++
	)
		if (NEURAL_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT)
			memset(
				NEURON_GRADIENTS(NEURAL_WEB, NEURON_INDEX), 0,
				NEURAL_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT * 4
			);

	SET_SIGNAL_WEIGHTS(NEURAL_WEB, TOKENS, SIGNAL_WEIGHTS, TOKEN_COUNT);
	LEARN_AVOID_WEIGHTS(
		NEURAL_WEB, NEURAL_WEB->KERNEL_STATE, NEURAL_WEB->ACTIVATIONS,
		TOKEN_COUNT
	);
	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_TRAIN);

	int32_t	PROBE_NEURONS[4] = {
		NEURAL_WEB->AREAS[1].MEMBERS[0], NEURAL_WEB->AREAS[0].MEMBERS[1],
		NEURAL_WEB->WORD_NEURONS[5], NEURAL_WEB->COPY_ID
	};
	int64_t	PROBE_PARAMETERS[4] = { 3, 17, 4, 9 };
	double	WORST_ERROR = 0;
	int		PROBE_INDEX;

	for (PROBE_INDEX = 0; PROBE_INDEX < 4; PROBE_INDEX++)
	{
		float	*PARAMETER =
			NEURON_PARAMETERS(NEURAL_WEB, PROBE_NEURONS[PROBE_INDEX]) +
			PROBE_PARAMETERS[PROBE_INDEX];
		float	ANALYTIC_GRADIENT = NEURON_GRADIENTS(
			NEURAL_WEB, PROBE_NEURONS[PROBE_INDEX]
		)[PROBE_PARAMETERS[PROBE_INDEX]];
		float	SAVED_VALUE = *PARAMETER;
		float	EPSILON = (float)3e-3;

		*PARAMETER = SAVED_VALUE + EPSILON;

		double	LOSS_PLUS =
			SIGNAL_OBJECTIVE(NEURAL_WEB, TOKENS, SIGNAL_WEIGHTS, TOKEN_COUNT);

		*PARAMETER = SAVED_VALUE - EPSILON;

		double	LOSS_MINUS =
			SIGNAL_OBJECTIVE(NEURAL_WEB, TOKENS, SIGNAL_WEIGHTS, TOKEN_COUNT);

		*PARAMETER = SAVED_VALUE;

		double	NUMERIC_GRADIENT = (LOSS_PLUS - LOSS_MINUS) / (2 * EPSILON);
		double	RELATIVE_ERROR = fabs(NUMERIC_GRADIENT - ANALYTIC_GRADIENT) /
			(fabs(NUMERIC_GRADIENT) + fabs(ANALYTIC_GRADIENT) + 1e-3);

		if (RELATIVE_ERROR > WORST_ERROR)
			WORST_ERROR = RELATIVE_ERROR;

		if (RELATIVE_ERROR > 0.05)
		{
			printf(
				"  param %d: analytic %+.6f numeric %+.6f FAIL\n", PROBE_INDEX,
				ANALYTIC_GRADIENT, NUMERIC_GRADIENT
			);
			FAILURE_COUNT++;
		}
	}

	printf(
		"  gradient of 'say this' + 'never say that' vs finite differences: "
		"worst relative error %.3g %s\n",
		WORST_ERROR, FAILURE_COUNT ? "FAIL" : "ok"
	);
	WEB_FREE(NEURAL_WEB);
	NEURAL_WEB = WEB_NEW(WEB_CONFIG, 72);

	for (INDEX = 0; INDEX < 20; INDEX++)
		WEB_ADD_WORD(NEURAL_WEB);

	WEB_RELINK(NEURAL_WEB);
	WEB_ADD_COPY(NEURAL_WEB);
	WEB_SET_OPTIMIZER(NEURAL_WEB, 1);

	int32_t	BAD_SENTENCE[6] = { 3, 7, 11, 5, 9, 13 };
	float	SAY_ALL_WEIGHTS[6] = { 0, 1, 1, 1, 1, 1 };
	float	AVOID_END_WEIGHTS[6] = { 0, 0, 0, 0, 0, -1 };
	int		WARMUP_STEP;

	for (WARMUP_STEP = 0; WARMUP_STEP < 80; WARMUP_STEP++)
	{
		SET_SIGNAL_WEIGHTS(NEURAL_WEB, BAD_SENTENCE, SAY_ALL_WEIGHTS, 5);
		NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = 5;
		NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
		NEURAL_WEB->KERNEL_STATE->LEARNING_RATE = (float)3e-3;
		WEB_RUN(NEURAL_WEB, MODE_TRAIN);
		WEB_RUN(NEURAL_WEB, MODE_UPDATE);
	}

	float	BAD_PROBABILITY_BEFORE =
		NEXT_WORD_PROBABILITY(NEURAL_WEB, BAD_SENTENCE, 5, 13);
	float	KEEP_PROBABILITY_BEFORE =
		NEXT_WORD_PROBABILITY(NEURAL_WEB, BAD_SENTENCE, 2, 11);
	int		AVOID_STEPS = 0;

	while (
		AVOID_STEPS < 50 &&
		NEXT_WORD_PROBABILITY(NEURAL_WEB, BAD_SENTENCE, 5, 13) > (float)0.05
	)
	{
		SET_SIGNAL_WEIGHTS(NEURAL_WEB, BAD_SENTENCE, AVOID_END_WEIGHTS, 5);
		LEARN_AVOID_WEIGHTS(
			NEURAL_WEB, NEURAL_WEB->KERNEL_STATE, NEURAL_WEB->ACTIVATIONS, 5
		);
		NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = 5;
		NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
		NEURAL_WEB->KERNEL_STATE->LEARNING_RATE = (float)3e-3;
		WEB_RUN(NEURAL_WEB, MODE_TRAIN);
		WEB_RUN(NEURAL_WEB, MODE_UPDATE);
		AVOID_STEPS++;
	}

	float	BAD_PROBABILITY_AFTER =
		NEXT_WORD_PROBABILITY(NEURAL_WEB, BAD_SENTENCE, 5, 13);
	float	KEEP_PROBABILITY_AFTER =
		NEXT_WORD_PROBABILITY(NEURAL_WEB, BAD_SENTENCE, 2, 11);
	int		SUCCESS = BAD_PROBABILITY_BEFORE > (float)0.5 &&
		BAD_PROBABILITY_AFTER < (float)0.05 &&
		KEEP_PROBABILITY_AFTER > (float)0.5 * KEEP_PROBABILITY_BEFORE;

	printf(
		"  learned a wrong ending (P %.3f); %d 'never say that' steps -> P "
		"%.3f; the rest of the sentence kept (P %.3f -> %.3f) %s\n",
		BAD_PROBABILITY_BEFORE, AVOID_STEPS, BAD_PROBABILITY_AFTER,
		KEEP_PROBABILITY_BEFORE, KEEP_PROBABILITY_AFTER, SUCCESS ? "ok" : "FAIL"
	);
	FAILURE_COUNT += !SUCCESS;
	WEB_FREE(NEURAL_WEB);

	{
		CONFIG	MEMORY_CONFIG = { 64, 2, 16, 24, 32, 2, 16 };
		WEB		*TEST_WEB = WEB_NEW(MEMORY_CONFIG, 81);
		int		INDEX;

		for (INDEX = 0; INDEX < 30; INDEX++)
			WEB_ADD_WORD(TEST_WEB);

		WEB_RELINK(TEST_WEB);
		RANDOMIZE_WEB(TEST_WEB, (float)0.3);

		NEAREST_NEIGHBORS	NEIGHBOR_INDEX;

		NEAREST_NEIGHBOR_INITIALIZE(
			&NEIGHBOR_INDEX, TEST_WEB->CONFIGURATION.DIMENSION, 3
		);

		int32_t	FIRST_SENTENCE[8] = { 2, 9, 14, 21, 7, 11, 5, 3 };
		int32_t	SECOND_SENTENCE[6] = { 2, 4, 17, 25, 8, 6 };
		uint8_t	FIRST_MASK[8] = { 0, 0, 0, 1, 0, 1, 0, 0 };
		uint8_t	SECOND_MASK[6] = { 0, 0, 0, 1, 1, 0 };
		int		FIRST_KEY_COUNT = NEAREST_NEIGHBOR_ADD(
			&NEIGHBOR_INDEX, TEST_WEB, FIRST_SENTENCE, 8, FIRST_MASK
		);
		int		SECOND_KEY_COUNT = NEAREST_NEIGHBOR_ADD(
			&NEIGHBOR_INDEX, TEST_WEB, SECOND_SENTENCE, 6, SECOND_MASK
		);
		int32_t	*TOKEN_SLOTS =
			(int32_t *)(TEST_WEB->ACTIVATIONS + TEST_WEB->TOKENS_OFFSET);

		memcpy(TOKEN_SLOTS, FIRST_SENTENCE, 5 * 4);
		TEST_WEB->KERNEL_STATE->START_POSITION = 0;
		TEST_WEB->KERNEL_STATE->SEQUENCE_LENGTH = 5;
		WEB_RUN(TEST_WEB, MODE_INFER);

		float	HIDDEN_STATE[64];
		float	SIMILARITIES[4];
		int32_t	RECALLED_WORDS[4];

		WEB_HIDDEN_STATE(TEST_WEB, 4, HIDDEN_STATE);

		int	RECALL_COUNT = NEAREST_NEIGHBOR_QUERY(
			&NEIGHBOR_INDEX, HIDDEN_STATE, 4, RECALLED_WORDS, SIMILARITIES
		);
		int	RECALL_SUCCESS = FIRST_KEY_COUNT == 2 && SECOND_KEY_COUNT == 2 &&
			RECALL_COUNT == 4 && RECALLED_WORDS[0] == 11 &&
			SIMILARITIES[0] > (float)0.999 && SIMILARITIES[1] < SIMILARITIES[0];

		printf(
			"  instant memory: stored 2 sentences (%d keys), same context "
			"recalls the stored next word %d (similarity %.4f) %s\n",
			NEIGHBOR_INDEX.COUNT, RECALL_COUNT ? RECALLED_WORDS[0] : -1,
			RECALL_COUNT ? SIMILARITIES[0] : 0, RECALL_SUCCESS ? "ok" : "FAIL"
		);
		FAILURE_COUNT += !RECALL_SUCCESS;
		NEIGHBOR_INDEX.VOCABULARY_TAG = 42;
		NEAREST_NEIGHBOR_SAVE(&NEIGHBOR_INDEX, "tknn_tmp.bin");

		NEAREST_NEIGHBORS	RELOADED_INDEX;

		NEAREST_NEIGHBOR_INITIALIZE(
			&RELOADED_INDEX, TEST_WEB->CONFIGURATION.DIMENSION, 3
		);

		int		RELOAD_RESULT = NEAREST_NEIGHBOR_LOAD(
			&RELOADED_INDEX, TEST_WEB, "tknn_tmp.bin", 42
		);
		double	MAXIMUM_DIFFERENCE = 0;

		for (
			INDEX = 0;
			INDEX < NEIGHBOR_INDEX.COUNT * NEIGHBOR_INDEX.DIMENSION;
			INDEX++
		)
			MAXIMUM_DIFFERENCE = fmax(
				MAXIMUM_DIFFERENCE,
				fabs(NEIGHBOR_INDEX.KEYS[INDEX] - RELOADED_INDEX.KEYS[INDEX])
			);

		TEST_WEB->STEP = 7;

		NEAREST_NEIGHBORS	REBUILT_INDEX;

		NEAREST_NEIGHBOR_INITIALIZE(
			&REBUILT_INDEX, TEST_WEB->CONFIGURATION.DIMENSION, 3
		);

		int	REBUILD_RESULT =
			NEAREST_NEIGHBOR_LOAD(&REBUILT_INDEX, TEST_WEB, "tknn_tmp.bin", 42);
		int	REFUSE_RESULT =
			NEAREST_NEIGHBOR_LOAD(&REBUILT_INDEX, TEST_WEB, "tknn_tmp.bin", 43);
		int	FILE_SUCCESS = RELOAD_RESULT == 0 &&
			RELOADED_INDEX.COUNT == NEIGHBOR_INDEX.COUNT &&
			MAXIMUM_DIFFERENCE == 0 && REBUILD_RESULT == 0 &&
			REBUILT_INDEX.COUNT == NEIGHBOR_INDEX.COUNT && REFUSE_RESULT == 1;

		printf(
			"  instant memory file: reload %s, rebuilt after the brain changed "
			"%s, refused with another vocabulary %s\n",
			RELOAD_RESULT == 0 && MAXIMUM_DIFFERENCE == 0 ? "exact" : "WRONG",
			REBUILD_RESULT == 0 && REBUILT_INDEX.COUNT == NEIGHBOR_INDEX.COUNT
				? "ok"
				: "WRONG",
			REFUSE_RESULT == 1 ? "ok" : "WRONG"
		);
		FAILURE_COUNT += !FILE_SUCCESS;
		NEAREST_NEIGHBOR_ADD(
			&NEIGHBOR_INDEX, TEST_WEB, FIRST_SENTENCE, 8, FIRST_MASK
		);
		NEAREST_NEIGHBOR_ADD(
			&NEIGHBOR_INDEX, TEST_WEB, SECOND_SENTENCE, 6, SECOND_MASK
		);

		int	EVICTION_SUCCESS =
			NEIGHBOR_INDEX.MESSAGE_COUNT == 3 && NEIGHBOR_INDEX.COUNT == 6;

		printf(
			"  instant memory keeps the newest %d sentences (%d keys) %s\n",
			NEIGHBOR_INDEX.MESSAGE_COUNT, NEIGHBOR_INDEX.COUNT,
			EVICTION_SUCCESS ? "ok" : "FAIL"
		);
		FAILURE_COUNT += !EVICTION_SUCCESS;
		remove("tknn_tmp.bin");
		NEAREST_NEIGHBOR_FREE(&NEIGHBOR_INDEX);
		NEAREST_NEIGHBOR_FREE(&RELOADED_INDEX);
		NEAREST_NEIGHBOR_FREE(&REBUILT_INDEX);
		WEB_FREE(TEST_WEB);
	}

	{
		CONFIG	PERSONAL_CONFIG = { 64, 2, 16, 24, 32, 2, 16 };
		WEB		*TEST_WEB = WEB_NEW(PERSONAL_CONFIG, 83);
		int		INDEX;

		for (INDEX = 0; INDEX < 20; INDEX++)
			WEB_ADD_WORD(TEST_WEB);

		WEB_RELINK(TEST_WEB);
		WEB_ADD_COPY(TEST_WEB);
		WEB_SET_OPTIMIZER(TEST_WEB, 1);
		RANDOMIZE_WEB(TEST_WEB, (float)0.2);
		TEST_WEB->KERNEL_STATE->WEIGHT_DECAY = (float)0.01;

		int	PERSONAL_COUNT = LEARN_PERSONAL(TEST_WEB, 8, 0);

		LEARN_FREEZE(TEST_WEB, 1);

		int	NEW_WORD_ID = WEB_ADD_WORD(TEST_WEB);

		WEB_RELINK(TEST_WEB);

		int64_t	PARAMETER_TOTAL = 0;
		int32_t	NEURON_INDEX;

		for (
			NEURON_INDEX = 0;
			NEURON_INDEX < TEST_WEB->NEURON_COUNT;
			NEURON_INDEX++
		)
			if (TEST_WEB->NEURONS[NEURON_INDEX].ALIVE)
				PARAMETER_TOTAL +=
					TEST_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT;

		float	*SNAPSHOT = malloc(PARAMETER_TOTAL * 4);
		int64_t	SNAPSHOT_OFFSET = 0;

		for (
			NEURON_INDEX = 0;
			NEURON_INDEX < TEST_WEB->NEURON_COUNT;
			NEURON_INDEX++
		)
			if (
				TEST_WEB->NEURONS[NEURON_INDEX].ALIVE &&
				TEST_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT
			)
			{
				memcpy(
					SNAPSHOT + SNAPSHOT_OFFSET,
					NEURON_PARAMETERS(TEST_WEB, NEURON_INDEX),
					TEST_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT * 4
				);
				SNAPSHOT_OFFSET +=
					TEST_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT;
			}

		int32_t	TRAINING_SEQUENCE[9] = {
			3, 7, 11, 5, 9, 12, 4, NEW_WORD_ID, 6
		};
		float	SAY_ALL_WEIGHTS[9] = { 0, 1, 1, 1, 1, 1, 1, 1, 1 };
		float	FIRST_LOSS = 0;
		float	LAST_LOSS = 0;
		int		PERSONAL_STEP;

		for (PERSONAL_STEP = 0; PERSONAL_STEP < 60; PERSONAL_STEP++)
		{
			SET_SIGNAL_WEIGHTS(TEST_WEB, TRAINING_SEQUENCE, SAY_ALL_WEIGHTS, 8);
			TEST_WEB->KERNEL_STATE->SEQUENCE_LENGTH = 8;
			TEST_WEB->KERNEL_STATE->START_POSITION = 0;
			TEST_WEB->KERNEL_STATE->LEARNING_RATE = (float)3e-3;
			WEB_RUN(TEST_WEB, MODE_TRAIN);

			double	TOTAL_LOSS = 0;
			int		POSITION;

			for (POSITION = 0; POSITION < 8; POSITION++)
				TOTAL_LOSS +=
					WEB_LOSS_AT(TEST_WEB, TEST_WEB->ACTIVATIONS, POSITION);

			if (PERSONAL_STEP == 0)
				FIRST_LOSS = (float)(TOTAL_LOSS / 8);

			LAST_LOSS = (float)(TOTAL_LOSS / 8);
			LEARN_UPDATE(TEST_WEB);
		}

		int	CHANGED_BASE = 0;
		int	CHANGED_PERSONAL = 0;
		int	CHANGED_NEW_WORD = 0;

		SNAPSHOT_OFFSET = 0;

		for (
			NEURON_INDEX = 0;
			NEURON_INDEX < TEST_WEB->NEURON_COUNT;
			NEURON_INDEX++
		)
		{
			NEURON	*CURRENT_NEURON = &TEST_WEB->NEURONS[NEURON_INDEX];

			if (!CURRENT_NEURON->ALIVE || !CURRENT_NEURON->PARAMETER_COUNT)
				continue ;

			int	DIFFERS = memcmp(
				SNAPSHOT + SNAPSHOT_OFFSET,
				NEURON_PARAMETERS(TEST_WEB, NEURON_INDEX),
				CURRENT_NEURON->PARAMETER_COUNT * 4
				) != 0;

			if (CURRENT_NEURON->BIRTH_REASON == WHY_PERSONAL)
				CHANGED_PERSONAL += DIFFERS;
			else if (
				CURRENT_NEURON->KIND == KIND_WORD &&
				CURRENT_NEURON->KIND_DETAIL == NEW_WORD_ID
			)
				CHANGED_NEW_WORD += DIFFERS;
			else
			{
				CHANGED_BASE += DIFFERS;

				if (DIFFERS && getenv("DBGF"))
					printf(
						"    changed: id %d kind %d why %d word %d\n",
						NEURON_INDEX, CURRENT_NEURON->KIND,
						CURRENT_NEURON->BIRTH_REASON,
						CURRENT_NEURON->KIND_DETAIL
					);
			}

			SNAPSHOT_OFFSET += CURRENT_NEURON->PARAMETER_COUNT;
		}

		int	SUCCESS = CHANGED_BASE == 0 && CHANGED_PERSONAL > 0 &&
			CHANGED_NEW_WORD == 1 && LAST_LOSS < FIRST_LOSS * (float)0.7;

		printf(
			"  safe chat learning: main brain bit-identical after 60 steps (%d "
			"neurons changed), %d/%d personal neurons and the new word "
			"learned, loss %.3f -> %.3f %s\n",
			CHANGED_BASE, CHANGED_PERSONAL, PERSONAL_COUNT, FIRST_LOSS,
			LAST_LOSS, SUCCESS ? "ok" : "FAIL"
		);
		FAILURE_COUNT += !SUCCESS;
		LEARN_PERSONAL(TEST_WEB, 8, 1);
		SET_SIGNAL_WEIGHTS(TEST_WEB, TRAINING_SEQUENCE, SAY_ALL_WEIGHTS, 8);
		TEST_WEB->KERNEL_STATE->SEQUENCE_LENGTH = 8;
		TEST_WEB->KERNEL_STATE->START_POSITION = 0;
		WEB_RUN(TEST_WEB, MODE_EVALUATE);

		double	TOTAL_LOSS = 0;
		int		POSITION;

		for (POSITION = 0; POSITION < 8; POSITION++)
			TOTAL_LOSS +=
				WEB_LOSS_AT(TEST_WEB, TEST_WEB->ACTIVATIONS, POSITION);

		printf(
			"  reset personal neurons: loss back to %.3f (new word still "
			"known) %s\n",
			TOTAL_LOSS / 8, TOTAL_LOSS / 8 > LAST_LOSS ? "ok" : "FAIL"
		);
		FAILURE_COUNT += !(TOTAL_LOSS / 8 > LAST_LOSS);
		free(SNAPSHOT);
		WEB_FREE(TEST_WEB);
	}

	printf("signals: %s\n", FAILURE_COUNT ? "FAILED" : "PASSED");

	return (FAILURE_COUNT);
}
