#include "CODE.h"
#include "THREAD.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

void	RANDOMIZE_WEB(WEB *NEURAL_WEB, float SCALE);
int		CHECK_AGAINST_REFERENCE(
	WEB *JIT_WEB, WEB *REFERENCE_WEB, int VOCABULARY_SIZE, int TOKEN_COUNT,
	int WITH_COPY
);

static WEB
	*BUILD_TREE_WEB(
		CONFIG WEB_CONFIG, uint64_t SEED, int VOCABULARY_SIZE, int TREE_DEPTH,
		int TREES_PER_LAYER, int GROWTH_REASON, int ADD_COPY_HEAD
	)
{
	WEB	*NEURAL_WEB = WEB_NEW(WEB_CONFIG, SEED);
	int	WORD_INDEX;

	for (WORD_INDEX = 0; WORD_INDEX < VOCABULARY_SIZE; WORD_INDEX++)
		WEB_ADD_WORD(NEURAL_WEB);

	int	LAYER;

	for (LAYER = 1; LAYER < 2 * WEB_CONFIG.LAYER_COUNT; LAYER += 2)
	{
		int	TREE_INDEX;

		for (TREE_INDEX = 0; TREE_INDEX < TREES_PER_LAYER; TREE_INDEX++)
			WEB_ADD_NEURON(
				NEURAL_WEB, KIND_TREE, LAYER, GROWTH_REASON, TREE_DEPTH
			);
	}

	WEB_RELINK(NEURAL_WEB);

	if (ADD_COPY_HEAD)
		WEB_ADD_COPY(NEURAL_WEB);

	return (NEURAL_WEB);
}

static void
	TREE_LAST_LOGITS(
		WEB *NEURAL_WEB, const int32_t *TOKENS, int TOKEN_COUNT,
		float *OUTPUT_LOGITS
	)
{
	int32_t	*TOKEN_SLOTS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);

	memcpy(TOKEN_SLOTS, TOKENS, TOKEN_COUNT * 4);
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	WEB_RUN(NEURAL_WEB, MODE_INFER);
	memcpy(
		OUTPUT_LOGITS, WEB_LAST_LOGITS(NEURAL_WEB), NEURAL_WEB->WORD_COUNT * 4
	);
}

static double
	TREE_EVALUATION_LOSS(WEB *NEURAL_WEB, int TOKEN_COUNT)
{
	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_EVALUATE);

	double	TOTAL_LOSS = 0;
	int		POSITION;

	for (POSITION = 0; POSITION < TOKEN_COUNT; POSITION++)
		TOTAL_LOSS += NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE *
			WEB_LOSS_AT(NEURAL_WEB, NEURAL_WEB->ACTIVATIONS, POSITION);

	return (TOTAL_LOSS);
}

static int32_t
	FIRST_TREE_NEURON(WEB *NEURAL_WEB, int AREA_INDEX)
{
	int32_t	NEURON_INDEX;

	for (
		NEURON_INDEX = 0;
		NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
		NEURON_INDEX++
	)
		if (
			NEURAL_WEB->NEURONS[NEURON_INDEX].KIND == KIND_TREE &&
			NEURAL_WEB->NEURONS[NEURON_INDEX].ALIVE &&
			NEURAL_WEB->NEURONS[NEURON_INDEX].AREA_INDEX == AREA_INDEX
		)
			return (NEURON_INDEX);

	return (-1);
}

static float
	TRAIN_TREE_STEPS(
		WEB *NEURAL_WEB, const int32_t *TOKENS, int TOKEN_COUNT, int STEP_COUNT,
		float LEARNING_RATE
	)
{
	float	LAST_LOSS = 0;
	int		STEP;

	for (STEP = 0; STEP < STEP_COUNT; STEP++)
	{
		int32_t	*TOKEN_SLOTS =
			(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);
		int32_t	*TARGET_SLOTS =
			(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TARGETS_OFFSET);
		float	*WEIGHT_SLOTS = (float *)(NEURAL_WEB->ACTIVATIONS +
										NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
		int		POSITION;

		for (POSITION = 0; POSITION < TOKEN_COUNT; POSITION++)
		{
			TOKEN_SLOTS[POSITION] = TOKENS[POSITION];
			TARGET_SLOTS[POSITION] = TOKENS[POSITION + 1];
			WEIGHT_SLOTS[POSITION] = 1;
		}

		NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
		NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
		NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE = (float)1.0 / TOKEN_COUNT;
		NEURAL_WEB->KERNEL_STATE->LEARNING_RATE = LEARNING_RATE;
		NEURAL_WEB->KERNEL_STATE->GRADIENT_SKIP_THRESHOLD = 0;
		WEB_RUN(NEURAL_WEB, MODE_TRAIN);

		double	TOTAL_LOSS = 0;

		for (POSITION = 0; POSITION < TOKEN_COUNT; POSITION++)
			TOTAL_LOSS +=
				WEB_LOSS_AT(NEURAL_WEB, NEURAL_WEB->ACTIVATIONS, POSITION);

		LAST_LOSS = (float)(TOTAL_LOSS / TOKEN_COUNT);
		WEB_RUN(NEURAL_WEB, MODE_UPDATE);
	}

	return (LAST_LOSS);
}

int
	TEST_TREES(void)
{
	int	FAILURE_COUNT = 0;

	printf("trees: tree neurons (each word walks one path through a tree of "
		"neurons)\n");

	{
		CONFIG	WEB_CONFIG = { 64, 2, 16, 32, 64, 2, 16 };
		WEB		*TEST_WEB =
			BUILD_TREE_WEB(WEB_CONFIG, 31, 30, 4, 2, WHY_SEED, 1);
		WEB		*REFERENCE_WEB =
			BUILD_TREE_WEB(WEB_CONFIG, 31, 30, 4, 2, WHY_SEED, 1);

		RANDOMIZE_WEB(TEST_WEB, (float)0.3);

		int	KERNEL_FAILURES =
			CHECK_AGAINST_REFERENCE(TEST_WEB, REFERENCE_WEB, 30, 23, 1);

		printf(
			"  machine code vs slow reference, 2 trees of depth 4 in every FFN "
			"layer: %s\n",
			KERNEL_FAILURES ? "FAIL" : "ok"
		);
		FAILURE_COUNT += KERNEL_FAILURES;
		WEB_FREE(TEST_WEB);
		WEB_FREE(REFERENCE_WEB);
	}

	{
		CONFIG	WEB_CONFIG = { 64, 2, 16, 32, 64, 2, 16 };
		int		VOCABULARY_SIZE = 30;
		int		TOKEN_COUNT = 21;
		WEB		*TEST_WEB =
			BUILD_TREE_WEB(WEB_CONFIG, 41, VOCABULARY_SIZE, 3, 1, WHY_SEED, 0);

		RANDOMIZE_WEB(TEST_WEB, (float)0.3);

		int32_t	*TOKEN_SLOTS =
			(int32_t *)(TEST_WEB->ACTIVATIONS + TEST_WEB->TOKENS_OFFSET);
		int32_t	*TARGET_SLOTS =
			(int32_t *)(TEST_WEB->ACTIVATIONS + TEST_WEB->TARGETS_OFFSET);
		float	*WEIGHT_SLOTS =
			(float *)(TEST_WEB->ACTIVATIONS + TEST_WEB->LOSS_WEIGHTS_OFFSET);
		int		POSITION;

		for (POSITION = 0; POSITION < WEB_CONFIG.MAXIMUM_LENGTH; POSITION++)
		{
			TOKEN_SLOTS[POSITION] =
				RANDOM_NEXT(&TEST_WEB->RANDOM_STATE) % VOCABULARY_SIZE;
			TARGET_SLOTS[POSITION] =
				RANDOM_NEXT(&TEST_WEB->RANDOM_STATE) % VOCABULARY_SIZE;
			WEIGHT_SLOTS[POSITION] = 1;
		}

		TEST_WEB->KERNEL_STATE->GRADIENT_SCALE = (float)1.0 / TOKEN_COUNT;
		TEST_WEB->KERNEL_STATE->GRADIENT_SKIP_THRESHOLD = 0;

		int32_t	NEURON_INDEX;

		for (
			NEURON_INDEX = 0;
			NEURON_INDEX < TEST_WEB->NEURON_COUNT;
			NEURON_INDEX++
		)
			if (TEST_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT)
				memset(
					NEURON_GRADIENTS(TEST_WEB, NEURON_INDEX), 0,
					TEST_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT * 4
				);

		TEST_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
		TEST_WEB->KERNEL_STATE->START_POSITION = 0;
		WEB_RUN(TEST_WEB, MODE_TRAIN);

		double	WORST_ERROR = 0;
		int		BAD_COUNT = 0;
		int		CHECKED_COUNT = 0;
		int32_t	TREE_ID = FIRST_TREE_NEURON(TEST_WEB, 1);
		int		NODE_STRIDE = 2 * WEB_CONFIG.DIMENSION + 8;
		int64_t	PICKED_PARAMETERS[7][2] = {
			{ 0, 3 }, { 0, WEB_CONFIG.DIMENSION + 5 },
			{ 0, 2 * WEB_CONFIG.DIMENSION }, { 1, 7 },
			{ 2, WEB_CONFIG.DIMENSION + 9 }, { 4, 11 },
			{ 5, WEB_CONFIG.DIMENSION + 2 }
		};
		size_t	PICK_INDEX;

		for (
			PICK_INDEX = 0;
			PICK_INDEX < sizeof PICKED_PARAMETERS / sizeof PICKED_PARAMETERS[0];
			PICK_INDEX++
		)
		{
			int64_t	PARAMETER_OFFSET =
				PICKED_PARAMETERS[PICK_INDEX][0] * NODE_STRIDE +
				PICKED_PARAMETERS[PICK_INDEX][1];
			float	*PARAMETER =
				NEURON_PARAMETERS(TEST_WEB, TREE_ID) + PARAMETER_OFFSET;
			float	ANALYTIC_GRADIENT =
				NEURON_GRADIENTS(TEST_WEB, TREE_ID)[PARAMETER_OFFSET];
			float	SAVED_VALUE = *PARAMETER;
			float	EPSILON = (float)2e-3;

			*PARAMETER = SAVED_VALUE + EPSILON;

			double	LOSS_PLUS = TREE_EVALUATION_LOSS(TEST_WEB, TOKEN_COUNT);

			*PARAMETER = SAVED_VALUE - EPSILON;

			double	LOSS_MINUS = TREE_EVALUATION_LOSS(TEST_WEB, TOKEN_COUNT);

			*PARAMETER = SAVED_VALUE;

			double	NUMERIC_GRADIENT = (LOSS_PLUS - LOSS_MINUS) / (2 * EPSILON);

			if (fabs(NUMERIC_GRADIENT) < 1e-6 && fabs(ANALYTIC_GRADIENT) < 1e-6)
				continue ;

			double	RELATIVE_ERROR =
				fabs(NUMERIC_GRADIENT - ANALYTIC_GRADIENT) /
					(fabs(NUMERIC_GRADIENT) + fabs(ANALYTIC_GRADIENT) + 1e-3);

			CHECKED_COUNT++;

			if (RELATIVE_ERROR > WORST_ERROR)
				WORST_ERROR = RELATIVE_ERROR;

			if (RELATIVE_ERROR > 0.05)
			{
				printf(
					"    tree node %lld param %lld: analytic %+.6f numeric "
					"%+.6f\n",
					(long long)PICKED_PARAMETERS[PICK_INDEX][0],
					(long long)PICKED_PARAMETERS[PICK_INDEX][1],
					ANALYTIC_GRADIENT, NUMERIC_GRADIENT
				);
				BAD_COUNT++;
			}
		}

		printf(
			"  tree weights vs finite differences (%d checked): worst relative "
			"error %.3g %s\n",
			CHECKED_COUNT, WORST_ERROR,
			BAD_COUNT || CHECKED_COUNT < 4 ? "FAIL" : "ok"
		);
		FAILURE_COUNT += BAD_COUNT || CHECKED_COUNT < 4;
		WEB_FREE(TEST_WEB);
	}

	{
		CONFIG	WEB_CONFIG = { 64, 2, 16, 32, 64, 2, 16 };
		int		VOCABULARY_SIZE = 30;
		int		TOKEN_COUNT = 23;
		WEB		*ORIGINAL_WEB = WEB_NEW(WEB_CONFIG, 51);
		int		INDEX;

		for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
			WEB_ADD_WORD(ORIGINAL_WEB);

		WEB_RELINK(ORIGINAL_WEB);
		WEB_ADD_COPY(ORIGINAL_WEB);
		RANDOMIZE_WEB(ORIGINAL_WEB, (float)0.2);

		int32_t	TOKENS[64];

		for (INDEX = 0; INDEX < 64; INDEX++)
			TOKENS[INDEX] = (int32_t)(RANDOM_NEXT(&ORIGINAL_WEB->RANDOM_STATE) %
				VOCABULARY_SIZE);

		float	*LOGITS_BEFORE = malloc(VOCABULARY_SIZE * 4);
		float	*LOGITS_AFTER = malloc(VOCABULARY_SIZE * 4);

		TREE_LAST_LOGITS(ORIGINAL_WEB, TOKENS, TOKEN_COUNT, LOGITS_BEFORE);

		int	LAYER;

		for (LAYER = 1; LAYER < 2 * WEB_CONFIG.LAYER_COUNT; LAYER += 2)
			WEB_ADD_NEURON(ORIGINAL_WEB, KIND_TREE, LAYER, WHY_GROWTH, 6);

		WEB_RELINK(ORIGINAL_WEB);
		TREE_LAST_LOGITS(ORIGINAL_WEB, TOKENS, TOKEN_COUNT, LOGITS_AFTER);

		double	MAXIMUM_DIFFERENCE = 0;

		for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
			MAXIMUM_DIFFERENCE = fmax(
				MAXIMUM_DIFFERENCE,
				fabs(LOGITS_BEFORE[INDEX] - LOGITS_AFTER[INDEX])
			);

		printf(
			"  adding silent trees (depth 6, %lld parameters each) keeps the "
			"answers: max logit diff %g %s\n",
			(long long)ORIGINAL_WEB->NEURONS[FIRST_TREE_NEURON(ORIGINAL_WEB, 1)]
				.PARAMETER_COUNT,
			MAXIMUM_DIFFERENCE, MAXIMUM_DIFFERENCE == 0 ? "ok" : "FAIL"
		);
		FAILURE_COUNT += MAXIMUM_DIFFERENCE != 0;
		RANDOMIZE_WEB(ORIGINAL_WEB, (float)0.2);

		const char	*PATH = "ttree_tmp.web";

		WEB_ROUND_TO_HALF(ORIGINAL_WEB);
		TREE_LAST_LOGITS(ORIGINAL_WEB, TOKENS, TOKEN_COUNT, LOGITS_BEFORE);
		WEB_SAVE(ORIGINAL_WEB, PATH, 0);

		WEB		*LOADED_WEB = WEB_LOAD(PATH);
		WEB		*PLAY_WEB = WEB_LOAD_PLAY(PATH);
		double	LOADED_DIFFERENCE = 0;
		double	PLAY_DIFFERENCE = 0;

		if (LOADED_WEB && PLAY_WEB)
		{
			TREE_LAST_LOGITS(LOADED_WEB, TOKENS, TOKEN_COUNT, LOGITS_AFTER);

			int	INDEX;

			for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
				LOADED_DIFFERENCE = fmax(
					LOADED_DIFFERENCE,
					fabs(LOGITS_BEFORE[INDEX] - LOGITS_AFTER[INDEX])
				);

			TREE_LAST_LOGITS(PLAY_WEB, TOKENS, TOKEN_COUNT, LOGITS_AFTER);

			for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
				PLAY_DIFFERENCE = fmax(
					PLAY_DIFFERENCE,
					fabs(LOGITS_BEFORE[INDEX] - LOGITS_AFTER[INDEX])
				);
		}

		int	SUCCESS = LOADED_WEB && PLAY_WEB && LOADED_DIFFERENCE == 0 &&
			PLAY_DIFFERENCE < 1e-4;

		printf(
			"  trees after save/load %g and in 16-bit play mode %g %s\n",
			LOADED_DIFFERENCE, PLAY_DIFFERENCE, SUCCESS ? "ok" : "FAIL"
		);
		FAILURE_COUNT += !SUCCESS;
		remove(PATH);

		if (LOADED_WEB)
			WEB_FREE(LOADED_WEB);

		if (PLAY_WEB)
			WEB_FREE(PLAY_WEB);

		WEB_FREE(ORIGINAL_WEB);
		free(LOGITS_BEFORE);
		free(LOGITS_AFTER);
	}

	{
		CONFIG	WEB_CONFIG = { 64, 2, 16, 48, 64, 2, 16 };
		int		VOCABULARY_SIZE = 40;
		int		TOKEN_COUNT = 40;
		WEB		*NEURAL_WEB = BUILD_TREE_WEB(
			WEB_CONFIG, 61, VOCABULARY_SIZE, 5, 1, WHY_GROWTH, 1
		);

		WEB_SET_OPTIMIZER(NEURAL_WEB, 1);

		int32_t	TOKENS[64];
		int		INDEX;

		for (INDEX = 0; INDEX < 64; INDEX++)
			TOKENS[INDEX] =
				(int32_t)((INDEX * 7 + INDEX / 5) % VOCABULARY_SIZE);

		int32_t	TREE_ID = FIRST_TREE_NEURON(NEURAL_WEB, 1);
		double	WEIGHT_SUM_BEFORE = 0;
		int64_t	WEIGHT_INDEX;

		for (
			WEIGHT_INDEX = 0;
			WEIGHT_INDEX < NEURAL_WEB->NEURONS[TREE_ID].PARAMETER_COUNT;
			WEIGHT_INDEX++
		)
			WEIGHT_SUM_BEFORE +=
				fabs(NEURON_PARAMETERS(NEURAL_WEB, TREE_ID)[WEIGHT_INDEX]);

		float	FIRST_LOSS =
			TRAIN_TREE_STEPS(NEURAL_WEB, TOKENS, TOKEN_COUNT, 1, (float)3e-3);
		float	LAST_LOSS =
			TRAIN_TREE_STEPS(NEURAL_WEB, TOKENS, TOKEN_COUNT, 200, (float)3e-3);
		double	WEIGHT_SUM_AFTER = 0;

		for (
			WEIGHT_INDEX = 0;
			WEIGHT_INDEX < NEURAL_WEB->NEURONS[TREE_ID].PARAMETER_COUNT;
			WEIGHT_INDEX++
		)
			WEIGHT_SUM_AFTER +=
				fabs(NEURON_PARAMETERS(NEURAL_WEB, TREE_ID)[WEIGHT_INDEX]);

		int	SUCCESS = LAST_LOSS < FIRST_LOSS * (float)0.5 &&
			WEIGHT_SUM_AFTER != WEIGHT_SUM_BEFORE;

		printf(
			"  a brain with silent trees learns: loss %.3f -> %.3f, tree "
			"weights changed %s\n",
			FIRST_LOSS, LAST_LOSS, SUCCESS ? "ok" : "FAIL"
		);
		FAILURE_COUNT += !SUCCESS;
		WEB_FREE(NEURAL_WEB);
	}

	{
		CONFIG	WEB_CONFIG = { 256, 1, 32, 128, 64, 2, 16 };
		int		VOCABULARY_SIZE = 50;
		int		TOKEN_COUNT = 128;
		int		TREE_DEPTH = 10;
		int64_t	NODE_COUNT = ((int64_t)1 << (TREE_DEPTH + 1)) - 1;
		WEB		*DENSE_WEB = WEB_NEW(WEB_CONFIG, 71);
		WEB		*TREE_WEB = WEB_NEW(WEB_CONFIG, 71);
		int		INDEX;

		for (INDEX = 0; INDEX < VOCABULARY_SIZE; INDEX++)
		{
			WEB_ADD_WORD(DENSE_WEB);
			WEB_ADD_WORD(TREE_WEB);
		}

		int64_t	NODE_INDEX;

		for (NODE_INDEX = 0; NODE_INDEX < NODE_COUNT; NODE_INDEX++)
			WEB_ADD_NEURON(DENSE_WEB, KIND_FEED_FORWARD, 1, WHY_SEED, -1);

		WEB_ADD_NEURON(TREE_WEB, KIND_TREE, 1, WHY_SEED, TREE_DEPTH);
		WEB_RELINK(DENSE_WEB);
		WEB_RELINK(TREE_WEB);

		int32_t	TOKENS[128];

		for (INDEX = 0; INDEX < 128; INDEX++)
			TOKENS[INDEX] = INDEX % VOCABULARY_SIZE;

		float	*LOGITS = malloc(VOCABULARY_SIZE * 4);
		double	RUN_SECONDS[2];
		WEB		*TIMED_WEBS[2] = { DENSE_WEB, TREE_WEB };
		int		WEB_INDEX;

		for (WEB_INDEX = 0; WEB_INDEX < 2; WEB_INDEX++)
		{
			TREE_LAST_LOGITS(
				TIMED_WEBS[WEB_INDEX], TOKENS, TOKEN_COUNT, LOGITS
			);

			double	START_TIME = THREAD_NOW_SECONDS();
			int		REPEAT;

			for (REPEAT = 0; REPEAT < 5; REPEAT++)
				TREE_LAST_LOGITS(
					TIMED_WEBS[WEB_INDEX], TOKENS, TOKEN_COUNT, LOGITS
				);

			RUN_SECONDS[WEB_INDEX] = (THREAD_NOW_SECONDS() - START_TIME) / 5;
		}

		printf(
			"  speed, %lld neurons in one layer, %d words: dense %.1f ms, tree "
			"%.1f ms (%.0fx faster) %s\n",
			(long long)NODE_COUNT, TOKEN_COUNT, 1000 * RUN_SECONDS[0],
			1000 * RUN_SECONDS[1], RUN_SECONDS[0] / RUN_SECONDS[1],
			RUN_SECONDS[1] < RUN_SECONDS[0] ? "ok" : "FAIL"
		);
		FAILURE_COUNT += !(RUN_SECONDS[1] < RUN_SECONDS[0]);
		free(LOGITS);
		WEB_FREE(DENSE_WEB);
		WEB_FREE(TREE_WEB);
	}

	printf("trees: %s\n", FAILURE_COUNT ? "FAILED" : "PASSED");

	return (FAILURE_COUNT);
}
