#include "CODE.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

static double
	COMPARE_ARRAYS(
		const char *LABEL, const float *REFERENCE, const float *CANDIDATE,
		int64_t VALUE_COUNT, int *FAILURE_COUNT
	)
{
	double	MAX_MAGNITUDE = 1e-6;
	double	MAX_DIFFERENCE = 0;
	int64_t	VALUE_INDEX;

	for (VALUE_INDEX = 0; VALUE_INDEX < VALUE_COUNT; VALUE_INDEX++)
	{
		double	REFERENCE_MAGNITUDE = fabs(REFERENCE[VALUE_INDEX]);
		double	CANDIDATE_MAGNITUDE = fabs(CANDIDATE[VALUE_INDEX]);

		if (REFERENCE_MAGNITUDE > MAX_MAGNITUDE)
			MAX_MAGNITUDE = REFERENCE_MAGNITUDE;

		if (CANDIDATE_MAGNITUDE > MAX_MAGNITUDE)
			MAX_MAGNITUDE = CANDIDATE_MAGNITUDE;

		double	ABSOLUTE_DIFFERENCE =
			fabs((double)REFERENCE[VALUE_INDEX] - CANDIDATE[VALUE_INDEX]);

		if (
			ABSOLUTE_DIFFERENCE > MAX_DIFFERENCE ||
			ABSOLUTE_DIFFERENCE != ABSOLUTE_DIFFERENCE
		)
		{
			if (ABSOLUTE_DIFFERENCE != ABSOLUTE_DIFFERENCE)
				MAX_DIFFERENCE = 1e30;
			else
				MAX_DIFFERENCE = ABSOLUTE_DIFFERENCE;
		}
	}

	double	RELATIVE_ERROR = MAX_DIFFERENCE / MAX_MAGNITUDE;
	int		IS_BAD = RELATIVE_ERROR > 2e-4;

	printf(
		"  %-28s max|ref|=%-10.4g maxdiff=%-10.3g rel=%-9.2g %s\n", LABEL,
		MAX_MAGNITUDE, MAX_DIFFERENCE, RELATIVE_ERROR, IS_BAD ? "FAIL" : "ok"
	);

	if (IS_BAD)
		(*FAILURE_COUNT)++;

	return (RELATIVE_ERROR);
}

void
	RANDOMIZE_WEB(WEB *NEURAL_WEB, float SCALE)
{
	WEB_SET_OPTIMIZER(NEURAL_WEB, 1);

	int32_t	NEURON_INDEX;

	for (
		NEURON_INDEX = 0;
		NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
		NEURON_INDEX++
	)
	{
		NEURON	*CURRENT_NEURON = &NEURAL_WEB->NEURONS[NEURON_INDEX];

		if (!CURRENT_NEURON->PARAMETER_COUNT || !CURRENT_NEURON->ALIVE)
			continue ;

		float	*PARAMETERS = NEURON_PARAMETERS(NEURAL_WEB, NEURON_INDEX);
		float	*FIRST_MOMENT = NEURON_MOMENTS(NEURAL_WEB, NEURON_INDEX, 0);
		float	*SECOND_MOMENT = NEURON_MOMENTS(NEURAL_WEB, NEURON_INDEX, 1);
		int64_t	PARAMETER_INDEX;

		for (
			PARAMETER_INDEX = 0;
			PARAMETER_INDEX < CURRENT_NEURON->PARAMETER_COUNT;
			PARAMETER_INDEX++
		)
			PARAMETERS[PARAMETER_INDEX] =
				(CURRENT_NEURON->KIND == KIND_NORMALIZATION ? (float)1.0
															: (float)0.0) +
				SCALE * WEB_GAUSSIAN(NEURAL_WEB);

		for (
			PARAMETER_INDEX = 0;
			PARAMETER_INDEX < CURRENT_NEURON->PARAMETER_COUNT;
			PARAMETER_INDEX++
		)
		{
			FIRST_MOMENT[PARAMETER_INDEX] =
				(float)0.01 * WEB_GAUSSIAN(NEURAL_WEB);
			SECOND_MOMENT[PARAMETER_INDEX] =
				(float)0.01 * WEB_RANDOM(NEURAL_WEB);
		}
	}
}

static int
	COMPARE_GRADIENTS(
		WEB *REFERENCE_WEB, WEB *CANDIDATE_WEB, const char *COMPARE_TAG,
		int *FAILURE_COUNT
	)
{
	int			NEURON_KINDS[8] = {
		KIND_EMBEDDING, KIND_NORMALIZATION, KIND_FEED_FORWARD,
		KIND_ATTENTION_HEAD, KIND_WORD, KIND_COPY, KIND_RECIPE, KIND_TREE
	};
	const char	*KIND_NAMES[8] = {
		"embed", "norm", "ffn", "head", "word", "copy", "recipe", "tree"
	};
	int			KIND_INDEX;

	for (KIND_INDEX = 0; KIND_INDEX < 8; KIND_INDEX++)
	{
		int64_t	TOTAL_PARAMETERS = 0;
		int32_t	NEURON_INDEX;

		for (
			NEURON_INDEX = 0;
			NEURON_INDEX < REFERENCE_WEB->NEURON_COUNT;
			NEURON_INDEX++
		)
			if (
				REFERENCE_WEB->NEURONS[NEURON_INDEX].KIND ==
					NEURON_KINDS[KIND_INDEX] &&
				REFERENCE_WEB->NEURONS[NEURON_INDEX].ALIVE
			)
				TOTAL_PARAMETERS +=
					REFERENCE_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT;

		if (!TOTAL_PARAMETERS)
			continue ;

		float	*REFERENCE_VALUES = malloc(TOTAL_PARAMETERS * 4);
		float	*CANDIDATE_VALUES = malloc(TOTAL_PARAMETERS * 4);
		int64_t	VALUE_OFFSET = 0;

		for (
			NEURON_INDEX = 0;
			NEURON_INDEX < REFERENCE_WEB->NEURON_COUNT;
			NEURON_INDEX++
		)
			if (
				REFERENCE_WEB->NEURONS[NEURON_INDEX].KIND ==
					NEURON_KINDS[KIND_INDEX] &&
				REFERENCE_WEB->NEURONS[NEURON_INDEX].ALIVE
			)
			{
				int64_t	PARAMETER_COUNT =
					REFERENCE_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT;

				memcpy(
					REFERENCE_VALUES + VALUE_OFFSET,
					strcmp(COMPARE_TAG, "grad")
						? NEURON_PARAMETERS(REFERENCE_WEB, NEURON_INDEX)
						: NEURON_GRADIENTS(REFERENCE_WEB, NEURON_INDEX),
					PARAMETER_COUNT * 4
				);
				memcpy(
					CANDIDATE_VALUES + VALUE_OFFSET,
					strcmp(COMPARE_TAG, "grad")
						? NEURON_PARAMETERS(CANDIDATE_WEB, NEURON_INDEX)
						: NEURON_GRADIENTS(CANDIDATE_WEB, NEURON_INDEX),
					PARAMETER_COUNT * 4
				);
				VALUE_OFFSET += PARAMETER_COUNT;
			}

		char	LABEL[64];

		snprintf(
			LABEL, sizeof LABEL, "%s %s", COMPARE_TAG, KIND_NAMES[KIND_INDEX]
		);
		COMPARE_ARRAYS(
			LABEL, REFERENCE_VALUES, CANDIDATE_VALUES, TOTAL_PARAMETERS,
			FAILURE_COUNT
		);
		free(REFERENCE_VALUES);
		free(CANDIDATE_VALUES);
	}

	return (0);
}

static void
	COPY_WEB_STATE(WEB *DESTINATION, WEB *SOURCE)
{
	WEB_SET_OPTIMIZER(DESTINATION, 1);

	int64_t	WORD_BYTES = (int64_t)SOURCE->WORD_COUNT * SOURCE->WORD_STRIDE;
	int		PLANE_INDEX;

	for (PLANE_INDEX = 0; PLANE_INDEX < 4; PLANE_INDEX++)
	{
		memcpy(
			(uint8_t *)DESTINATION->PARAMETERS + PLANE_INDEX * PARAMETER_PLANE,
			(uint8_t *)SOURCE->PARAMETERS + PLANE_INDEX * PARAMETER_PLANE,
			SOURCE->PARAMETER_BYTES_USED
		);
		memcpy(
			(uint8_t *)DESTINATION->PARAMETERS + PLANE_INDEX * PARAMETER_PLANE +
				WORD_PLANE_OFFSET,
			(uint8_t *)SOURCE->PARAMETERS + PLANE_INDEX * PARAMETER_PLANE +
				WORD_PLANE_OFFSET,
			WORD_BYTES
		);
	}

	memcpy(
		DESTINATION->ACTIVATIONS, SOURCE->ACTIVATIONS,
		SOURCE->ACTIVATION_BYTES_USED
	);
	memcpy(
		DESTINATION->ACTIVATIONS + ACTIVATION_PLANE,
		SOURCE->ACTIVATIONS + ACTIVATION_PLANE, SOURCE->ACTIVATION_BYTES_USED
	);
	memcpy(
		DESTINATION->ACTIVATIONS + ACTIVATION_PLANE + TRAINING_REGION_OFFSET,
		SOURCE->ACTIVATIONS + ACTIVATION_PLANE + TRAINING_REGION_OFFSET,
		SOURCE->TRAINING_BYTES_USED
	);
	memcpy(
		DESTINATION->ACTIVATIONS + LOGITS_OFFSET,
		SOURCE->ACTIVATIONS + LOGITS_OFFSET,
		(int64_t)SOURCE->WORD_COUNT * SOURCE->CONFIGURATION.MAXIMUM_LENGTH * 4
	);
	memcpy(
		DESTINATION->ACTIVATIONS + LAST_LOGITS_OFFSET,
		SOURCE->ACTIVATIONS + LAST_LOGITS_OFFSET,
		(int64_t)SOURCE->CONFIGURATION.MAXIMUM_WORDS * 4
	);

	KERNEL_CONTEXT	KEPT_STATE = *DESTINATION->KERNEL_STATE;

	*DESTINATION->KERNEL_STATE = *SOURCE->KERNEL_STATE;
	DESTINATION->KERNEL_STATE->ACTIVATIONS = KEPT_STATE.ACTIVATIONS;
	DESTINATION->KERNEL_STATE->PARAMETERS = KEPT_STATE.PARAMETERS;
	DESTINATION->KERNEL_STATE->OWNER = KEPT_STATE.OWNER;
	DESTINATION->KERNEL_STATE->SERVICE_TABLE = KEPT_STATE.SERVICE_TABLE;
	DESTINATION->STEP = SOURCE->STEP;
}

static float	GRADIENT_SKIP_EPSILON;

int	CHECK_AGAINST_REFERENCE(
	WEB *JIT_WEB, WEB *REFERENCE_WEB, int VOCABULARY_SIZE, int TOKEN_COUNT,
	int WITH_COPY
);

int
	TEST_KERNELS_ONCE(
		CONFIG WEB_CONFIG, int VOCABULARY_SIZE, int TOKEN_COUNT, uint64_t SEED,
		int WITH_COPY
	)
{
	int	FAILURE_COUNT = 0;

	printf(
		"kernels: d=%d layers=%d dh=%d heads=%d ffn=%d Tmax=%d V=%d T=%d\n",
		WEB_CONFIG.DIMENSION, WEB_CONFIG.LAYER_COUNT, WEB_CONFIG.HEAD_DIMENSION,
		WEB_CONFIG.INITIAL_HEADS, WEB_CONFIG.INITIAL_FEED_FORWARD,
		WEB_CONFIG.MAXIMUM_LENGTH, VOCABULARY_SIZE, TOKEN_COUNT
	);

	WEB	*JIT_WEB = WEB_NEW(WEB_CONFIG, SEED);
	WEB	*REFERENCE_WEB = WEB_NEW(WEB_CONFIG, SEED);
	int	WORD_INDEX;

	for (WORD_INDEX = 0; WORD_INDEX < VOCABULARY_SIZE; WORD_INDEX++)
	{
		WEB_ADD_WORD(JIT_WEB);
		WEB_ADD_WORD(REFERENCE_WEB);
	}

	WEB_RELINK(JIT_WEB);
	WEB_RELINK(REFERENCE_WEB);

	if (WITH_COPY)
	{
		WEB_ADD_COPY(JIT_WEB);
		WEB_ADD_COPY(REFERENCE_WEB);
		printf("  (with copy neuron)\n");
	}

	RANDOMIZE_WEB(JIT_WEB, (float)0.3);

	if (WITH_COPY)
		NEURON_PARAMETERS(JIT_WEB, JIT_WEB->COPY_ID)
		[2 * WEB_CONFIG.HEAD_DIMENSION * WEB_CONFIG.DIMENSION +
			WEB_CONFIG.DIMENSION] = (float)0.3;

	FAILURE_COUNT = CHECK_AGAINST_REFERENCE(
		JIT_WEB, REFERENCE_WEB, VOCABULARY_SIZE, TOKEN_COUNT, WITH_COPY
	);
	WEB_FREE(JIT_WEB);
	WEB_FREE(REFERENCE_WEB);
	printf(
		"kernels: %s (%d failures)\n", FAILURE_COUNT ? "FAILED" : "PASSED",
		FAILURE_COUNT
	);

	return (FAILURE_COUNT);
}

int
	CHECK_AGAINST_REFERENCE(
		WEB *JIT_WEB, WEB *REFERENCE_WEB, int VOCABULARY_SIZE, int TOKEN_COUNT,
		int WITH_COPY
	)
{
	int		FAILURE_COUNT = 0;
	CONFIG	WEB_CONFIG = JIT_WEB->CONFIGURATION;
	int32_t	*TOKENS =
		(int32_t *)(JIT_WEB->ACTIVATIONS + JIT_WEB->TOKENS_OFFSET);
	int32_t	*TARGETS =
		(int32_t *)(JIT_WEB->ACTIVATIONS + JIT_WEB->TARGETS_OFFSET);
	float	*WEIGHTS =
		(float *)(JIT_WEB->ACTIVATIONS + JIT_WEB->LOSS_WEIGHTS_OFFSET);
	int		POSITION;

	for (POSITION = 0; POSITION < WEB_CONFIG.MAXIMUM_LENGTH; POSITION++)
	{
		TOKENS[POSITION] =
			RANDOM_NEXT(&JIT_WEB->RANDOM_STATE) % VOCABULARY_SIZE;

		if (POSITION % 7 == 3)
			TARGETS[POSITION] = -1;
		else
			TARGETS[POSITION] = (int32_t)(RANDOM_NEXT(&JIT_WEB->RANDOM_STATE) %
				VOCABULARY_SIZE);

		WEIGHTS[POSITION] = (float)0.5 + WEB_RANDOM(JIT_WEB);
	}

	JIT_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	JIT_WEB->KERNEL_STATE->START_POSITION = 0;
	JIT_WEB->KERNEL_STATE->GRADIENT_SCALE = (float)1.0 / TOKEN_COUNT;
	JIT_WEB->KERNEL_STATE->WEIGHT_DECAY = (float)0.05;
	JIT_WEB->KERNEL_STATE->GRADIENT_SKIP_THRESHOLD = GRADIENT_SKIP_EPSILON;

	if (GRADIENT_SKIP_EPSILON > 0)
		printf(
			"  (skipping output-gradient terms below %g)\n",
			GRADIENT_SKIP_EPSILON
		);

	COPY_WEB_STATE(REFERENCE_WEB, JIT_WEB);
	WEB_RUN(JIT_WEB, MODE_TRAIN);
	WEB_PREPARE(REFERENCE_WEB, MODE_TRAIN);
	REFERENCE_FORWARD(REFERENCE_WEB, 1);
	REFERENCE_BACKWARD(REFERENCE_WEB);

	int	LAST_RESIDUAL = 2 * WEB_CONFIG.LAYER_COUNT;
	int	RESIDUAL_INDEX;

	for (RESIDUAL_INDEX = 0; RESIDUAL_INDEX <= LAST_RESIDUAL; RESIDUAL_INDEX++)
	{
		char	LABEL[64];

		snprintf(LABEL, sizeof LABEL, "fwd residual R%d", RESIDUAL_INDEX);
		COMPARE_ARRAYS(
			LABEL,
			(float *)(REFERENCE_WEB->ACTIVATIONS +
				LAYER_RESIDUAL(REFERENCE_WEB, RESIDUAL_INDEX)),
			(float *)(JIT_WEB->ACTIVATIONS +
				LAYER_RESIDUAL(JIT_WEB, RESIDUAL_INDEX)),
			(int64_t)TOKEN_COUNT * WEB_CONFIG.DIMENSION, &FAILURE_COUNT
		);
	}

	COMPARE_ARRAYS(
		"fwd final norm N",
		(float *)(REFERENCE_WEB->ACTIVATIONS +
			LAYER_NORMALIZED(REFERENCE_WEB, LAST_RESIDUAL)),
		(float *)(JIT_WEB->ACTIVATIONS +
			LAYER_NORMALIZED(JIT_WEB, LAST_RESIDUAL)),
		(int64_t)TOKEN_COUNT * WEB_CONFIG.DIMENSION, &FAILURE_COUNT
	);

	{
		float	*REFERENCE_LOGITS =
			malloc((size_t)VOCABULARY_SIZE * TOKEN_COUNT * 4);
		float	*JIT_LOGITS = malloc((size_t)VOCABULARY_SIZE * TOKEN_COUNT * 4);
		int		VOCABULARY_INDEX;

		for (
			VOCABULARY_INDEX = 0;
			VOCABULARY_INDEX < VOCABULARY_SIZE;
			VOCABULARY_INDEX++
		)
		{
			int	POSITION;

			for (POSITION = 0; POSITION < TOKEN_COUNT; POSITION++)
			{
				REFERENCE_LOGITS[VOCABULARY_INDEX * TOKEN_COUNT + POSITION] =
					((float *)(REFERENCE_WEB->ACTIVATIONS + LOGITS_OFFSET)
					)[(int64_t)VOCABULARY_INDEX * WEB_CONFIG.MAXIMUM_LENGTH +
						POSITION];
				JIT_LOGITS[VOCABULARY_INDEX * TOKEN_COUNT + POSITION] =
					((float *)(JIT_WEB->ACTIVATIONS + LOGITS_OFFSET)
					)[(int64_t)VOCABULARY_INDEX * WEB_CONFIG.MAXIMUM_LENGTH +
						POSITION];
			}
		}

		COMPARE_ARRAYS(
			"loss grad dlogits", REFERENCE_LOGITS, JIT_LOGITS,
			(int64_t)VOCABULARY_SIZE * TOKEN_COUNT, &FAILURE_COUNT
		);
		free(REFERENCE_LOGITS);
		free(JIT_LOGITS);
	}

	for (RESIDUAL_INDEX = LAST_RESIDUAL; RESIDUAL_INDEX >= 0; RESIDUAL_INDEX--)
	{
		char	LABEL[64];

		snprintf(LABEL, sizeof LABEL, "bwd dR%d", RESIDUAL_INDEX);
		COMPARE_ARRAYS(
			LABEL,
			(float *)(REFERENCE_WEB->ACTIVATIONS +
				LAYER_RESIDUAL_GRADIENT(REFERENCE_WEB, RESIDUAL_INDEX)),
			(float *)(JIT_WEB->ACTIVATIONS +
				LAYER_RESIDUAL_GRADIENT(JIT_WEB, RESIDUAL_INDEX)),
			(int64_t)TOKEN_COUNT * WEB_CONFIG.DIMENSION, &FAILURE_COUNT
		);
	}

	if (WITH_COPY && JIT_WEB->COPY_ID >= 0 && REFERENCE_WEB->COPY_ID >= 0)
	{
		int64_t	COPY_OFFSETS[10];

		COPY_HEAD_OFFSETS(JIT_WEB, COPY_OFFSETS);
		COMPARE_ARRAYS(
			"copy mix probability P",
			(float *)(REFERENCE_WEB->ACTIVATIONS + COPY_OFFSETS[5]),
			(float *)(JIT_WEB->ACTIVATIONS + COPY_OFFSETS[5]), TOKEN_COUNT,
			&FAILURE_COUNT
		);
		COMPARE_ARRAYS(
			"copy gate",
			(float *)(REFERENCE_WEB->ACTIVATIONS + COPY_OFFSETS[3]),
			(float *)(JIT_WEB->ACTIVATIONS + COPY_OFFSETS[3]), TOKEN_COUNT,
			&FAILURE_COUNT
		);
	}

	COMPARE_GRADIENTS(REFERENCE_WEB, JIT_WEB, "grad", &FAILURE_COUNT);
	COPY_WEB_STATE(REFERENCE_WEB, JIT_WEB);
	WEB_RUN(JIT_WEB, MODE_UPDATE);
	REFERENCE_WEB->STEP++;
	WEB_PREPARE(REFERENCE_WEB, MODE_UPDATE);
	REFERENCE_WEB->KERNEL_STATE->WEIGHT_DECAY =
		JIT_WEB->KERNEL_STATE->WEIGHT_DECAY;
	REFERENCE_UPDATE(REFERENCE_WEB);
	COMPARE_GRADIENTS(REFERENCE_WEB, JIT_WEB, "adam", &FAILURE_COUNT);
	JIT_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	JIT_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(JIT_WEB, MODE_INFER);

	float	*FULL_LOGITS = malloc((size_t)VOCABULARY_SIZE * 4);

	memcpy(FULL_LOGITS, WEB_LAST_LOGITS(JIT_WEB), VOCABULARY_SIZE * 4);
	JIT_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT - 5;
	JIT_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(JIT_WEB, MODE_INFER);

	int	STEP_POSITION;

	for (
		STEP_POSITION = TOKEN_COUNT - 5;
		STEP_POSITION < TOKEN_COUNT;
		STEP_POSITION++
	)
	{
		JIT_WEB->KERNEL_STATE->START_POSITION = STEP_POSITION;
		JIT_WEB->KERNEL_STATE->SEQUENCE_LENGTH = STEP_POSITION + 1;
		WEB_RUN(JIT_WEB, MODE_INFER);
	}

	float	*INCREMENTAL_LOGITS = malloc((size_t)VOCABULARY_SIZE * 4);

	memcpy(INCREMENTAL_LOGITS, WEB_LAST_LOGITS(JIT_WEB), VOCABULARY_SIZE * 4);
	COMPARE_ARRAYS(
		"incremental == full infer", FULL_LOGITS, INCREMENTAL_LOGITS,
		VOCABULARY_SIZE, &FAILURE_COUNT
	);
	free(FULL_LOGITS);
	free(INCREMENTAL_LOGITS);

	return (FAILURE_COUNT);
}

int
	TEST_KERNELS(
		CONFIG WEB_CONFIG, int VOCABULARY_SIZE, int TOKEN_COUNT, uint64_t SEED
	)
{
	int	FAILURE_COUNT =
		TEST_KERNELS_ONCE(WEB_CONFIG, VOCABULARY_SIZE, TOKEN_COUNT, SEED, 0) +
		TEST_KERNELS_ONCE(
			WEB_CONFIG, VOCABULARY_SIZE, TOKEN_COUNT, SEED + 100, 1
		);

	GRADIENT_SKIP_EPSILON = (float)0.02;
	FAILURE_COUNT += TEST_KERNELS_ONCE(
		WEB_CONFIG, VOCABULARY_SIZE, TOKEN_COUNT, SEED + 200, 1
	);
	GRADIENT_SKIP_EPSILON = 0;

	return (FAILURE_COUNT);
}

static double
	WEIGHTED_EVALUATION_LOSS(WEB *NEURAL_WEB, int TOKEN_COUNT)
{
	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_EVALUATE);

	float	*POSITION_WEIGHTS =
		(float *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
	int32_t	*TARGETS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TARGETS_OFFSET);
	double	LOSS_SUM = 0;
	int		POSITION;

	for (POSITION = 0; POSITION < TOKEN_COUNT; POSITION++)
		if (TARGETS[POSITION] >= 0)
			LOSS_SUM += POSITION_WEIGHTS[POSITION] *
				NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE *
				WEB_LOSS_AT(NEURAL_WEB, NEURAL_WEB->ACTIVATIONS, POSITION);

	return (LOSS_SUM);
}

int
	TEST_GRADIENT_CHECK(void)
{
	CONFIG	WEB_CONFIG = { 64, 1, 16, 16, 32, 2, 16 };
	WEB		*NEURAL_WEB = WEB_NEW(WEB_CONFIG, 31);
	int		WORD_INDEX;

	for (WORD_INDEX = 0; WORD_INDEX < 20; WORD_INDEX++)
		WEB_ADD_WORD(NEURAL_WEB);

	WEB_RELINK(NEURAL_WEB);
	WEB_ADD_COPY(NEURAL_WEB);
	RANDOMIZE_WEB(NEURAL_WEB, (float)0.3);
	NEURON_PARAMETERS(NEURAL_WEB, NEURAL_WEB->COPY_ID)
	[2 * WEB_CONFIG.HEAD_DIMENSION * WEB_CONFIG.DIMENSION +
		WEB_CONFIG.DIMENSION] = (float)0.0;

	int		TOKEN_COUNT = 15;
	int32_t	*TOKENS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TOKENS_OFFSET);
	int32_t	*TARGETS =
		(int32_t *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->TARGETS_OFFSET);
	float	*WEIGHTS =
		(float *)(NEURAL_WEB->ACTIVATIONS + NEURAL_WEB->LOSS_WEIGHTS_OFFSET);
	int		POSITION;

	for (POSITION = 0; POSITION < WEB_CONFIG.MAXIMUM_LENGTH; POSITION++)
	{
		TOKENS[POSITION] = RANDOM_NEXT(&NEURAL_WEB->RANDOM_STATE) % 20;
		WEIGHTS[POSITION] = 1;
	}

	for (POSITION = 0; POSITION < TOKEN_COUNT; POSITION++)
	{
		if (POSITION > 3)
			TARGETS[POSITION] =
				TOKENS[RANDOM_NEXT(&NEURAL_WEB->RANDOM_STATE) % POSITION];
		else
			TARGETS[POSITION] =
				(int32_t)(RANDOM_NEXT(&NEURAL_WEB->RANDOM_STATE) % 20);
	}

	NEURAL_WEB->KERNEL_STATE->GRADIENT_SCALE = (float)1.0 / TOKEN_COUNT;

	int32_t	NEURON_INDEX;

	for (
		NEURON_INDEX = 0;
		NEURON_INDEX < NEURAL_WEB->NEURON_COUNT;
		NEURON_INDEX++
	)
		if (NEURAL_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT)
			memset(
				NEURON_GRADIENTS(NEURAL_WEB, NEURON_INDEX), 0,
				NEURAL_WEB->NEURONS[NEURON_INDEX].PARAMETER_COUNT * 4
			);

	NEURAL_WEB->KERNEL_STATE->SEQUENCE_LENGTH = TOKEN_COUNT;
	NEURAL_WEB->KERNEL_STATE->START_POSITION = 0;
	WEB_RUN(NEURAL_WEB, MODE_TRAIN);

	int32_t	COPY_NEURON_ID = NEURAL_WEB->COPY_ID;
	int64_t	HEAD_MATRIX_SIZE =
		(int64_t)WEB_CONFIG.HEAD_DIMENSION * WEB_CONFIG.DIMENSION;
	struct
	{
		int32_t		NEURON_ID;
		int64_t		PARAMETER_INDEX;
		const char	*LABEL;
	} PROBES[7] = {
		{
			COPY_NEURON_ID, 2 * HEAD_MATRIX_SIZE + WEB_CONFIG.DIMENSION,
			"copy gate bias"
		},
		{ COPY_NEURON_ID, 3, "copy query weight" },
		{ COPY_NEURON_ID, HEAD_MATRIX_SIZE + 7, "copy key weight" },
		{ COPY_NEURON_ID, 2 * HEAD_MATRIX_SIZE + 5, "copy gate weight" },
		{ NEURAL_WEB->WORD_NEURONS[3], 2, "word embedding" },
		{ NEURAL_WEB->AREAS[1].MEMBERS[0], 4, "ffn weight" },
		{ NEURAL_WEB->AREAS[0].MEMBERS[0], 9, "attention weight" }
	};
	int	FAILURE_COUNT = 0;

	printf("gradcheck: analytic gradient (JIT backward) vs finite differences "
		"of the JIT loss (with copy neuron)\n");

	int	PROBE_INDEX;

	for (PROBE_INDEX = 0; PROBE_INDEX < 7; PROBE_INDEX++)
	{
		float	*PARAMETER =
			NEURON_PARAMETERS(NEURAL_WEB, PROBES[PROBE_INDEX].NEURON_ID) +
			PROBES[PROBE_INDEX].PARAMETER_INDEX;
		float	ANALYTIC_GRADIENT = NEURON_GRADIENTS(
			NEURAL_WEB, PROBES[PROBE_INDEX].NEURON_ID
		)[PROBES[PROBE_INDEX].PARAMETER_INDEX];
		float	ORIGINAL_VALUE = *PARAMETER;
		float	EPSILON = (float)2e-3;

		*PARAMETER = ORIGINAL_VALUE + EPSILON;

		double	LOSS_PLUS = WEIGHTED_EVALUATION_LOSS(NEURAL_WEB, TOKEN_COUNT);

		*PARAMETER = ORIGINAL_VALUE - EPSILON;

		double	LOSS_MINUS = WEIGHTED_EVALUATION_LOSS(NEURAL_WEB, TOKEN_COUNT);

		*PARAMETER = ORIGINAL_VALUE;

		double	NUMERIC_GRADIENT = (LOSS_PLUS - LOSS_MINUS) / (2 * EPSILON);
		double	RELATIVE_ERROR = fabs(NUMERIC_GRADIENT - ANALYTIC_GRADIENT) /
			(fabs(NUMERIC_GRADIENT) + fabs(ANALYTIC_GRADIENT) + 1e-4);
		int		IS_BAD = RELATIVE_ERROR > 0.05;

		printf(
			"  %-20s analytic %+.6f numeric %+.6f  %s\n",
			PROBES[PROBE_INDEX].LABEL, ANALYTIC_GRADIENT, NUMERIC_GRADIENT,
			IS_BAD ? "FAIL" : "ok"
		);
		FAILURE_COUNT += IS_BAD;
	}

	WEB_FREE(NEURAL_WEB);
	printf("gradcheck: %s\n", FAILURE_COUNT ? "FAILED" : "PASSED");

	return (FAILURE_COUNT);
}
