#include "THREAD.h"
#include <stdlib.h>
#ifdef _WIN32
#include <windows.h>

typedef struct
{
	THREAD_FUNCTION	ENTRY_FUNCTION;
	void			*ENTRY_ARGUMENT;
} THREAD_START_PACK;

static DWORD WINAPI
	THREAD_TRAMPOLINE(LPVOID THREAD_ARGUMENT)
{
	THREAD_START_PACK	*START_PACK = THREAD_ARGUMENT;

	START_PACK->ENTRY_FUNCTION(START_PACK->ENTRY_ARGUMENT);

	return (0);
}

void
	THREAD_RUN(
		THREAD_FUNCTION WORKER_FUNCTION, void **ARGUMENTS, int THREAD_COUNT
	)
{
	HANDLE				*THREAD_HANDLES = malloc(THREAD_COUNT * sizeof(HANDLE));
	THREAD_START_PACK	*START_PACKS =
		malloc(THREAD_COUNT * sizeof(THREAD_START_PACK));
	int					THREAD_INDEX;

	for (THREAD_INDEX = 1; THREAD_INDEX < THREAD_COUNT; THREAD_INDEX++)
	{
		START_PACKS[THREAD_INDEX].ENTRY_FUNCTION = WORKER_FUNCTION;
		START_PACKS[THREAD_INDEX].ENTRY_ARGUMENT = ARGUMENTS[THREAD_INDEX];
		THREAD_HANDLES[THREAD_INDEX] = CreateThread(
			NULL, 1 << 20, THREAD_TRAMPOLINE, &START_PACKS[THREAD_INDEX], 0,
			NULL
		);
	}

	WORKER_FUNCTION(ARGUMENTS[0]);

	for (THREAD_INDEX = 1; THREAD_INDEX < THREAD_COUNT; THREAD_INDEX++)
	{
		WaitForSingleObject(THREAD_HANDLES[THREAD_INDEX], INFINITE);
		CloseHandle(THREAD_HANDLES[THREAD_INDEX]);
	}

	free(THREAD_HANDLES);
	free(START_PACKS);
}

int
	THREAD_CORE_COUNT(void)
{
	SYSTEM_INFO	SYSTEM_DETAILS;

	GetSystemInfo(&SYSTEM_DETAILS);

	return ((int)SYSTEM_DETAILS.dwNumberOfProcessors);
}

void
	THREAD_SPAWN(THREAD_FUNCTION WORKER_FUNCTION, void *ARGUMENT)
{
	THREAD_START_PACK	*START_PACK = malloc(sizeof(THREAD_START_PACK));

	START_PACK->ENTRY_FUNCTION = WORKER_FUNCTION;
	START_PACK->ENTRY_ARGUMENT = ARGUMENT;

	HANDLE	THREAD_HANDLE =
		CreateThread(NULL, 1 << 23, THREAD_TRAMPOLINE, START_PACK, 0, NULL);

	if (THREAD_HANDLE)
		CloseHandle(THREAD_HANDLE);
}

void
	*THREAD_NEW_MUTEX(void)
{
	CRITICAL_SECTION	*MUTEX = malloc(sizeof(CRITICAL_SECTION));

	InitializeCriticalSection(MUTEX);

	return (MUTEX);
}

void
	THREAD_LOCK(void *MUTEX)
{
	EnterCriticalSection((CRITICAL_SECTION *)MUTEX);
}

void
	THREAD_UNLOCK(void *MUTEX)
{
	LeaveCriticalSection((CRITICAL_SECTION *)MUTEX);
}

void
	THREAD_SLEEP_MILLISECONDS(int MILLISECONDS)
{
	Sleep(MILLISECONDS);
}

double
	THREAD_NOW_SECONDS(void)
{
	LARGE_INTEGER	FREQUENCY;
	LARGE_INTEGER	COUNTER;

	QueryPerformanceFrequency(&FREQUENCY);
	QueryPerformanceCounter(&COUNTER);

	return ((double)COUNTER.QuadPart / (double)FREQUENCY.QuadPart);
}
#else
#include <pthread.h>
#include <unistd.h>
#include <time.h>

typedef struct
{
	THREAD_FUNCTION	ENTRY_FUNCTION;
	void			*ENTRY_ARGUMENT;
} THREAD_START_PACK;

static void
	*THREAD_TRAMPOLINE(void *THREAD_ARGUMENT)
{
	THREAD_START_PACK	*START_PACK = THREAD_ARGUMENT;

	START_PACK->ENTRY_FUNCTION(START_PACK->ENTRY_ARGUMENT);

	return (NULL);
}

void
	THREAD_RUN(
		THREAD_FUNCTION WORKER_FUNCTION, void **ARGUMENTS, int THREAD_COUNT
	)
{
	pthread_t			*THREAD_HANDLES =
		malloc(THREAD_COUNT * sizeof(pthread_t));
	THREAD_START_PACK	*START_PACKS =
		malloc(THREAD_COUNT * sizeof(THREAD_START_PACK));
	int					THREAD_INDEX;

	for (THREAD_INDEX = 1; THREAD_INDEX < THREAD_COUNT; THREAD_INDEX++)
	{
		START_PACKS[THREAD_INDEX].ENTRY_FUNCTION = WORKER_FUNCTION;
		START_PACKS[THREAD_INDEX].ENTRY_ARGUMENT = ARGUMENTS[THREAD_INDEX];
		pthread_create(
			&THREAD_HANDLES[THREAD_INDEX], NULL, THREAD_TRAMPOLINE,
			&START_PACKS[THREAD_INDEX]
		);
	}

	WORKER_FUNCTION(ARGUMENTS[0]);

	for (THREAD_INDEX = 1; THREAD_INDEX < THREAD_COUNT; THREAD_INDEX++)
		pthread_join(THREAD_HANDLES[THREAD_INDEX], NULL);

	free(THREAD_HANDLES);
	free(START_PACKS);
}

int
	THREAD_CORE_COUNT(void)
{
	long	PROCESSOR_COUNT = sysconf(_SC_NPROCESSORS_ONLN);

	if (PROCESSOR_COUNT > 0)
		return ((int)PROCESSOR_COUNT);

	return (1);
}

void
	THREAD_SPAWN(THREAD_FUNCTION WORKER_FUNCTION, void *ARGUMENT)
{
	THREAD_START_PACK	*START_PACK = malloc(sizeof(THREAD_START_PACK));

	START_PACK->ENTRY_FUNCTION = WORKER_FUNCTION;
	START_PACK->ENTRY_ARGUMENT = ARGUMENT;

	pthread_t	THREAD_HANDLE;

	if (!pthread_create(&THREAD_HANDLE, NULL, THREAD_TRAMPOLINE, START_PACK))
		pthread_detach(THREAD_HANDLE);
}

void
	*THREAD_NEW_MUTEX(void)
{
	pthread_mutex_t	*MUTEX = malloc(sizeof(pthread_mutex_t));

	pthread_mutex_init(MUTEX, NULL);

	return (MUTEX);
}

void
	THREAD_LOCK(void *MUTEX)
{
	pthread_mutex_lock((pthread_mutex_t *)MUTEX);
}

void
	THREAD_UNLOCK(void *MUTEX)
{
	pthread_mutex_unlock((pthread_mutex_t *)MUTEX);
}

void
	THREAD_SLEEP_MILLISECONDS(int MILLISECONDS)
{
	struct timespec	DURATION = {
		MILLISECONDS / 1000, (long)(MILLISECONDS % 1000) * (long)1000000
	};

	nanosleep(&DURATION, NULL);
}

double
	THREAD_NOW_SECONDS(void)
{
	struct timespec	CURRENT_TIME;

	clock_gettime(CLOCK_MONOTONIC, &CURRENT_TIME);

	return (CURRENT_TIME.tv_sec + CURRENT_TIME.tv_nsec * 1e-9);
}
#endif
