#ifndef THREAD_H
#define THREAD_H
typedef void (*THREAD_FUNCTION)(void *);
void	THREAD_RUN(
	THREAD_FUNCTION WORKER_FUNCTION, void **ARGUMENTS, int THREAD_COUNT
);
int		THREAD_CORE_COUNT(void);
double	THREAD_NOW_SECONDS(void);
void	THREAD_SPAWN(THREAD_FUNCTION WORKER_FUNCTION, void *ARGUMENT);
void	*THREAD_NEW_MUTEX(void);
void	THREAD_LOCK(void *MUTEX);
void	THREAD_UNLOCK(void *MUTEX);
void	THREAD_SLEEP_MILLISECONDS(int MILLISECONDS);
#endif
